<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PerforatedInvoice.name'] = "Berlubang";
$lang['PerforatedInvoice.page_of'] = "Halaman %1\$s dari %2\$s"; // %1$s is the current page number, %2$s is the total number of pages
$lang['PerforatedInvoice.terms_heading'] = "Syarat";
$lang['PerforatedInvoice.type_active'] = "FAKTUR";
$lang['PerforatedInvoice.type_draft'] = "FAKTUR - DRAFT";
$lang['PerforatedInvoice.type_void'] = "FAKTUR - TIDAK BERLAKU";
$lang['PerforatedInvoice.type_proforma'] = "INVOICE PROFORMA";
$lang['PerforatedInvoice.invoice_id_code'] = "Nomor faktur:";
$lang['PerforatedInvoice.client_id_code'] = "Nomor pelanggan:";
$lang['PerforatedInvoice.client_name'] = "Nama Pelanggan:";
$lang['PerforatedInvoice.tax_id'] = "Nomor Pajak/PPN:";
$lang['PerforatedInvoice.client_tax_id'] = "Nomor Pajak/PPN Pelanggan:";
$lang['PerforatedInvoice.date_billed'] = "Tanggal faktur:";
$lang['PerforatedInvoice.date_due'] = "Batas tanggal terakhir:";
$lang['PerforatedInvoice.notes_heading'] = "Catatan";
$lang['PerforatedInvoice.subtotal_heading'] = "Subtotal";
$lang['PerforatedInvoice.total_heading'] = "Total";
$lang['PerforatedInvoice.lines_description'] = "Deskripsi";
$lang['PerforatedInvoice.lines_quantity'] = "Kuantitas";
$lang['PerforatedInvoice.lines_unit_price'] = "Patokan harga";
$lang['PerforatedInvoice.lines_cost'] = "Biaya";
$lang['PerforatedInvoice.watermark_paid'] = "DIBAYAR";
$lang['PerforatedInvoice.payments_heading'] = "Pembayaran";
$lang['PerforatedInvoice.payments_applied_date'] = "Tanggal Berlaku";
$lang['PerforatedInvoice.payments_type_name'] = "Jenis";
$lang['PerforatedInvoice.payments_transaction_id'] = "Nomor transaksi";
$lang['PerforatedInvoice.payments_applied_amount'] = "Jumlah yang Diterapkan";
$lang['PerforatedInvoice.balance_heading'] = "Saldo";
$lang['PerforatedInvoice.detach_heading'] = "LEPAS DAN KEMBALI DENGAN PEMBAYARAN";
$lang['PerforatedInvoice.detach_remit_to'] = "Kirim ke:";
$lang['PerforatedInvoice.detach_total_due'] = "Jumlah total jatuh tempo :";
$lang['PerforatedInvoice.detach_total_payment'] = "Jumlah Pembayaran Total:";
$lang['PerforatedInvoice.proforma_id_code'] = "Nomor Proforma:";
$lang['PerforatedInvoice.draft_id_code'] = "Nomor Draf:";
?>