<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Vesta.name'] = "Vesta";
$lang['Vesta.module_row'] = "Server";
$lang['Vesta.module_row_plural'] = "Server";
$lang['Vesta.module_group'] = "Grup Server";
$lang['Vesta.tab_stats'] = "Statistik";
$lang['Vesta.tab_client_actions'] = "Aksi";
$lang['Vesta.submit'] = "Kirimkan";
$lang['Vesta.tab_stats.info.WEB_DOMAINS'] = "Domain";
$lang['Vesta.tab_stats.info.WEB_ALIASES'] = "Alias";
$lang['Vesta.tab_stats.info.DNS_DOMAINS'] = "DNS Domain";
$lang['Vesta.tab_stats.info.DNS_RECORDS'] = "Catatan DNS";
$lang['Vesta.tab_stats.info.MAIL_DOMAINS'] = "Domain Surat";
$lang['Vesta.tab_stats.info.MAIL_ACCOUNTS'] = "Akun Email";
$lang['Vesta.tab_stats.info.DATABASES'] = "Database";
$lang['Vesta.tab_stats.info.CRON_JOBS'] = "Pekerjaan Cron";
$lang['Vesta.tab_stats.info.DISK_QUOTA'] = "Penggunaan Disk";
$lang['Vesta.tab_stats.info.BANDWIDTH'] = "Penggunaan Bandwidth";
$lang['Vesta.tab_stats.info.BACKUPS'] = "Cadangan";
$lang['Vesta.add_module_row'] = "Tambahkan server";
$lang['Vesta.add_module_group'] = "Tambahkan Grup Server";
$lang['Vesta.manage.module_rows_title'] = "Server";
$lang['Vesta.manage.module_groups_title'] = "Grup Server";
$lang['Vesta.manage.module_rows_heading.name'] = "Label Server";
$lang['Vesta.manage.module_rows_heading.hostname'] = "Nama host";
$lang['Vesta.manage.module_rows_heading.port'] = "Port";
$lang['Vesta.manage.module_rows_heading.accounts'] = "Akun";
$lang['Vesta.manage.module_rows_heading.options'] = "Pilihan";
$lang['Vesta.manage.module_groups_heading.name'] = "Nama grup";
$lang['Vesta.manage.module_groups_heading.servers'] = "Jumlah Server";
$lang['Vesta.manage.module_groups_heading.options'] = "Pilihan";
$lang['Vesta.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Vesta.manage.module_rows.edit'] = "Edit";
$lang['Vesta.manage.module_groups.edit'] = "Sunting";
$lang['Vesta.manage.module_rows.delete'] = "Hapus";
$lang['Vesta.manage.module_groups.delete'] = "Menghapus";
$lang['Vesta.manage.module_rows.confirm_delete'] = "Anda yakin ingin menghapus server ini?";
$lang['Vesta.manage.module_groups.confirm_delete'] = "Anda yakin ingin menghapus grup server ini?";
$lang['Vesta.manage.module_rows_no_results'] = "Tidak ada server.";
$lang['Vesta.manage.module_groups_no_results'] = "Tidak ada grup server.";
$lang['Vesta.order_options.first'] = "Server tidak penuh pertama";
$lang['Vesta.add_row.box_title'] = "Tambahkan Server Vesta";
$lang['Vesta.add_row.basic_title'] = "Pengaturan dasar";
$lang['Vesta.add_row.remove_name_server'] = "Menghapus";
$lang['Vesta.add_row.add_btn'] = "Tambahkan server";
$lang['Vesta.edit_row.box_title'] = "Sunting Server Vesta";
$lang['Vesta.edit_row.basic_title'] = "Pengaturan Dasar";
$lang['Vesta.edit_row.remove_name_server'] = "Menghapus";
$lang['Vesta.edit_row.add_btn'] = "Sunting Server";
$lang['Vesta.row_meta.server_name'] = "Server Label";
$lang['Vesta.row_meta.host_name'] = "Hostname";
$lang['Vesta.row_meta.user_name'] = "Nama pengguna";
$lang['Vesta.row_meta.password'] = "Kata sandi";
$lang['Vesta.row_meta.port'] = "Port";
$lang['Vesta.row_meta.use_ssl'] = "Gunakan SSL saat menghubungkan ke API (disarankan)";
$lang['Vesta.package_fields.package_name'] = "Nama Paket Vesta";
$lang['Vesta.package_fields.package_name_how_to'] = "Anda bisa mendapatkan nama paket dengan masuk ke Panel Kontrol Vesta > Paket";
$lang['Vesta.service_field.domain'] = "Nama domain";
$lang['Vesta.service_field.username'] = "Username";
$lang['Vesta.service_field.password'] = "Kata sandi";
$lang['Vesta.stored_locally_only'] = "Bidang ini hanya akan diperbarui secara lokal";
$lang['Vesta.service_info.hostname'] = "Nama host";
$lang['Vesta.service_info.username'] = "Nama pengguna";
$lang['Vesta.service_info.password'] = "Kata sandi";
$lang['Vesta.service_info.server'] = "Server";
$lang['Vesta.service_info.options'] = "Pilihan";
$lang['Vesta.service_info.option_login'] = "Gabung";
$lang['Vesta.tab_client_actions.change_password'] = "Ganti kata sandi";
$lang['Vesta.tab_client_actions.password'] = "Password";
$lang['Vesta.tab_client_actions.confirm_password'] = "setujui password";
$lang['Vesta.tab_stats.info_heading.field'] = "Bidang";
$lang['Vesta.tab_stats.info_heading.value'] = "Nilai";
$lang['Vesta.!error.server_name_valid'] = "Anda harus memasukkan Label Server.";
$lang['Vesta.!error.host_name_valid'] = "Nama Host tampaknya tidak valid.";
$lang['Vesta.!error.user_name_valid'] = "User Name tidak valid.";
$lang['Vesta.!error.port_valid'] = "Port tampaknya tidak valid.";
$lang['Vesta.!error.password_valid'] = "Kata sandi tampaknya tidak valid.";
$lang['Vesta.!error.meta[package_name].empty'] = "Silakan masukkan nama paket Vesta.";
$lang['Vesta.!error.api.internal'] = "Terjadi kesalahan internal, atau server tidak menanggapi permintaan.";
$lang['Vesta.!error.module_row.missing'] = "Terjadi kesalahan internal. Baris modul tidak tersedia.";
$lang['Vesta.!error.domain.format'] = "Silahkan masukkan domain dengan benar, Contoh : domain.com ";
$lang['Vesta.!error.domain.test'] = "Nama domain tidak boleh diawali dengan 'test'.";
$lang['Vesta.!error.user_name.empty'] = "Nama pengguna wajib diisi.";
$lang['Vesta.!error.password.valid'] = "Kata sandi harus minimal 8 karakter.";
$lang['Vesta.!error.actions_password.valid'] = "Bidang Sandi & Konfirmasi Sandi wajib diisi.";
$lang['Vesta.description'] = "Vesta, atau VestaCP, adalah panel kontrol web sumber terbuka yang dianggap sebagai alternatif yang bagus untuk cPanel. Tidak hanya keamanan dan pembaruannya yang sering sesuai kualitasnya dengan cPanel, itu juga sepenuhnya gratis.";
?>