<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['IpUnblockerPlugin.name'] = "Pembuka IP";
$lang['IpUnblockerPlugin.description'] = "Plugin untuk Blesta yang terintegrasi dengan cPanel dan DirectAdmin untuk membuka blokir IP yang masuk daftar hitam";
$lang['IpUnblockerPlugin.unblock_ip'] = "Buka blokir IP";
$lang['IpUnblockerPlugin.!success.unblock_ip'] = "Buka blokir permintaan yang dikirim.";
$lang['IpUnblockerPlugin.!error.remote_curl'] = "Tidak dapat terhubung ke server jauh. Kesalahan cURL: %1\$s"; // %1$s is the curl error
?>
