<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminMain.!error.export_found'] = "Ekspor tidak dapat ditemukan di sistem file.";
$lang['AdminMain.index.page_title'] = "Mailer Massal";
$lang['AdminMain.index.boxtitle'] = "Pekerjaan Mailer Massal";
$lang['AdminMain.index.categorylink_compose'] = "Buat Surat Baru";
$lang['AdminMain.index.job_task_total'] = "%1\$s / %2\$s"; // %1$s is the number of mailing tasks completed, %2$s is the total number of mailing tasks
$lang['AdminMain.index.heading_date'] = "Tanggal Ditambahkan";
$lang['AdminMain.index.heading_type'] = "Jenis";
$lang['AdminMain.index.heading_status'] = "Status";
$lang['AdminMain.index.heading_complete'] = "Lengkap";
$lang['AdminMain.index.heading_options'] = "Pilihan";
$lang['AdminMain.index.option_export'] = "Ekspor";
$lang['AdminMain.index.type.email'] = "Email";
$lang['AdminMain.index.type.export'] = "Ekspor";
$lang['AdminMain.index.email_to'] = "Untuk";
$lang['AdminMain.index.email_from'] = "Dari";
$lang['AdminMain.index.email_subject'] = "Subjek";
$lang['AdminMain.index.email_to_recipients'] = "%1\$s Penerima"; // %1$s is the number of email recipients
$lang['AdminMain.index.no_export_details'] = "Tidak ada rincian yang tersedia tentang ekspor.";
$lang['AdminMain.index.no_results'] = "Saat ini tidak ada lowongan pengiriman surat.";
?>
