<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['MassMailerEmails.!error.job_id.valid'] = "ID pekerjaan tidak valid.";
$lang['MassMailerEmails.!error.job_id.unique'] = "Pekerjaan sudah diberi email.";
$lang['MassMailerEmails.!error.from_name.empty'] = "Harap masukkan dari nama.";
$lang['MassMailerEmails.!error.from_address.valid'] = "Silahkan masukkan email yang valid.";
$lang['MassMailerEmails.!error.subject.empty'] = "Silakan masukkan subjek.";
$lang['MassMailerEmails.!error.html.empty'] = "Silakan masukkan konten email HTML.";
$lang['MassMailerEmails.!error.log.valid'] = "Opsi log harus disetel ke 0 atau 1.";
?>
