<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['MassMailerJobs.!error.company_id.valid'] = "Harap tetapkan ID perusahaan.";
$lang['MassMailerJobs.!error.status.format'] = "Silahkan pilih status yang valid.";
$lang['MassMailerJobs.!error.task_count.format'] = "Jumlah tugas harus berupa bilangan bulat positif.";
$lang['MassMailerJobs.!error.data.empty'] = "Harap sertakan informasi pekerjaan tambahan.";
$lang['MassMailerJobs.!error.date_added.format'] = "Harap tetapkan tanggal ditambahkan.";
$lang['MassMailerJobs.!error.job_id.exists'] = "ID pekerjaan tidak valid.";
$lang['MassMailerJobs.status.pending'] = "Tertunda";
$lang['MassMailerJobs.status.in_progress'] = "Sedang berlangsung";
$lang['MassMailerJobs.status.complete'] = "Lengkap";
?>
