<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderTypeDomain.name'] = "Domain dan Lainnya";
$lang['OrderTypeDomain.!error.domain.invalid'] = "Nama domain tersebut tidak didukung.";
$lang['OrderTypeDomain.!error.domain.empty'] = "Harap masukkan nama domain.";
$lang['OrderTypeDomain.!error.template.valid'] = "Template yang dipilih memerlukan setidaknya satu grup paket.";
$lang['OrderTypeDomain.settings.domain_group_title'] = "Grup Paket Domain";
$lang['Main.steps.step_1_description'] = "Pilih domain";
$lang['OrderTypeDomain.!error.meta[domain_group].exists'] = "Harap pilih grup paket domain yang valid.";
$lang['OrderTypeDomain.!error.meta[domain_group].groups'] = "Grup paket domain juga tidak dapat menjadi grup paket yang ditetapkan.";
?>