<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Whmcs8_0.!error.host.invalid'] = "Host Basis Data diperlukan.";
$lang['Whmcs8_0.!error.database.invalid'] = "Nama Basis Data wajib diisi.";
$lang['Whmcs8_0.!error.user.invalid'] = "Pengguna Basis Data diperlukan.";
$lang['Whmcs8_0.!error.pass.invalid'] = "Kata Sandi Basis Data diperlukan.";
$lang['Whmcs8_0.!error.key.invalid'] = "Diperlukan AESKEY yang valid.";
$lang['Whmcs8_0.!error.import'] = "Impor selesai tetapi terjadi kesalahan berikut:";
$lang['Whmcs8_0.!notice.gmp'] = "Ekstensi 'gmp' tidak ditemukan. Ekstensi ini direkomendasikan untuk meningkatkan kinerja dan akan meningkatkan proses impor. Anda dapat melanjutkan tanpa ekstensi ini tetapi proses impor mungkin jauh lebih lambat.";
$lang['Whmcs8_0.settings.host'] = "Tuan Rumah Basis Data";
$lang['Whmcs8_0.settings.database'] = "Nama Basis Data";
$lang['Whmcs8_0.settings.user'] = "Pengguna Basis Data";
$lang['Whmcs8_0.settings.pass'] = "Kata Sandi Basis Data";
$lang['Whmcs8_0.settings.key'] = "Enkripsi CC Hash";
$lang['Whmcs8_0.settings.key.info'] = "Ini adalah kunci enkripsi yang digunakan oleh WHMCS untuk mengenkripsi berbagai bit data. Itu dapat ditemukan di file configuration.php WHMCS Anda.";
$lang['Whmcs8_0.settings.balance_credit'] = "Transaksi saldo otomatis untuk mencocokkan kredit klien di WHMCS";
$lang['Whmcs8_0.settings.balance_credit.info'] = "Jika dicentang, akan menghasilkan transaksi atau faktur untuk memastikan bahwa kredit klien di Blesta cocok dengan yang ditetapkan untuk klien di WHMCS. Ini diperlukan karena WHMCS tidak memperhitungkan kredit klien dengan benar.";
$lang['Whmcs8_0.settings.enable_debug'] = "Aktifkan Debug";
$lang['Whmcs8_0.configuration.create_packages_true'] = "Secara otomatis membuat paket yang diperlukan selama impor";
$lang['Whmcs8_0.configuration.create_packages_false'] = "Memetakan paket secara manual";
$lang['Whmcs8_0.configuration.local_package'] = "Paket Lokal";
$lang['Whmcs8_0.configuration.remote_package'] = "Paket Jarak Jauh";
$lang['Whmcs8_0.configuration.no_local_packages'] = "Anda harus membuat paket sebelum dapat memetakannya.";
?>
