<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Kassacompleet.!error.api_key.empty'] = "Silakan masukkan kunci API";
$lang['Kassacompleet.!error.api_key.valid'] = "Kunci API tidak valid";
$lang['Kassacompleet.name'] = "Kartu Kredit/Debit (Kassa Compleet)";
$lang['Kassacompleet.api_key'] = "kunci API";
$lang['Kassacompleet.tooltip.api_key'] = "Untuk menggunakan mode pengujian, cukup masukkan kunci API dari akun pengujian";
$lang['Kassacompleet.buildprocess.submit'] = "Bayar dengan Kassa Compleet";
$lang['Kassacompleet.description'] = "Integrasi Kassa Compleet untuk jenis pembayaran Kartu Kredit.";
?>
