<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Checkout.index.header_checkout'] = "Hampir sampai!";
$lang['Checkout.index.checkout_note'] = "Silahkan lakukan pembayaran untuk menyelesaikan pesanan Anda.";
$lang['Checkout.index.field_useaccount'] = "Gunakan Akun Pembayaran";
$lang['Checkout.index.field_newdetails'] = "Detail Pembayaran Baru";
$lang['Checkout.index.heading_other_payment_options'] = "Opsi Pembayaran Lainnya";
$lang['Checkout.index.heading_payment_options'] = "Opsi pembayaran";
$lang['Checkout.index.pay_btn'] = "Bayar & Selesaikan Pesanan";
$lang['Checkout.index.no_options'] = "Tidak ada opsi pembayaran yang tersedia.";
$lang['Checkout.contact_info.heading_contact'] = "Kontak informasi";
$lang['Checkout.contact_info.field_contact_id'] = "Salin Informasi Kontak Dari";
$lang['Checkout.contact_info.text_select_contact'] = "Anda dapat memilih kontak yang ada untuk mengisi formulir ini sebelumnya.";
$lang['Checkout.cc_info.heading_cc'] = "Informasi Kartu Kredit";
$lang['Checkout.ach_info.heading_ach'] = "Informasi Rekening Bank";
$lang['Checkout.complete.order_more_btn'] = "Tempatkan pesanan lain";
$lang['Checkout.complete.invoice_paid'] = "DIBAYAR";
?>
