<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['ReassignPricingServices.!error.pricing_id.exists'] = "ID harga tidak valid.";
$lang['ReassignPricingServices.!error.pricing_id.company'] = "ID harga bukan milik perusahaan yang sama dengan layanan.";
$lang['ReassignPricingServices.!error.module_row_id.exists'] = "ID baris modul tidak valid dari ID harga yang diberikan.";
$lang['ReassignPricingServices.!error.module_row_id.company'] = "ID baris modul bukan milik perusahaan yang sama dengan layanan.";
$lang['ReassignPricingServices.!error.service_id.exists'] = "ID layanan tidak valid.";
$lang['ReassignPricingServices.!error.package_group_id.exists'] = "ID grup paket tidak valid.";
$lang['ReassignPricingServices.!error.package_group_id.company'] = "ID grup paket bukan milik perusahaan yang sama dengan layanan.";
?>
