<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['ReassignPricingPlugin.action_staff_client.index'] = "Pengaturan Ulang Harga";
$lang['ReassignPricingPlugin.name'] = "Tetapkan Ulang Harga";
$lang['ReassignPricingPlugin.description'] = "Memungkinkan harga layanan diperbarui ke harga dari paket lain yang menggunakan modul yang sama.";
?>
