<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['OrderTypeRegistration.name'] = "Pendaftaran Klien";
$lang['OrderTypeRegistration.!success.signup'] = "Terima kasih telah mendaftarkan akun bersama kami.";
$lang['OrderTypeRegistration.!error.template.valid'] = "Pendaftaran Klien hanya mendukung template Standar.";
?>
