<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Main.steps.step_1_name'] = "Langkah 1";
$lang['Main.steps.step_1_description'] = "Pilih paket Anda";
$lang['Main.steps.step_2_name'] = "Langkah 2";
$lang['Main.steps.step_2_description'] = "Konfigurasi";
$lang['Main.steps.step_3_name'] = "Langkah 3";
$lang['Main.steps.step_3_description'] = "Tinjau Pesanan";
$lang['Main.steps.step_4_name'] = "Langkah 4";
$lang['Main.steps.step_4_description'] = "Periksa";
$lang['Main.index.select_btn'] = "Masukkan ke keranjang";
$lang['Main.index.sold_out'] = "Kehabisan persediaan";
$lang['Main.index.client_limit'] = "Batas Tercapai";
$lang['Main.index.field_currency'] = "Mata uang:";
?>
