<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Summary.index.box_heading'] = "Keranjang Anda";
$lang['Summary.index.login_customer'] = "Pelanggan yang (telah) Ada?";
$lang['Summary.index.login_link'] = "Gabung";
$lang['Summary.index.link_resetpassword'] = "Setel ulang kata sandi saya";
$lang['Summary.index.field_username'] = "Nama pengguna";
$lang['Summary.index.field_password'] = "Kata sandi";
$lang['Summary.index.login_btn'] = "Gabung";
$lang['Summary.index.checkout_btn'] = "Periksa";
$lang['Summary.index.have_coupon'] = "Punya kupon?";
$lang['Summary.index.coupon'] = "Kupon";
$lang['Summary.index.coupon_btn'] = "Menebus";
$lang['Summary.index.cart_empty'] = "Tidak ada item di keranjang Anda.";
?>
