<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['CustomReport.name'] = "Laporan Kustom";
$lang['CustomReports.options.field_report'] = "Melaporkan";
$lang['CustomReports.options.field_report_select'] = "-- Silahkan pilih --";
$lang['CustomReport.!error.field'] = "%1\$s tidak valid."; // %1$s is the field label
?>
