<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['InvoiceCreation.name'] = "Pembuatan Faktur";
$lang['InvoiceCreation.options.field_start_date'] = "Mulai tanggal";
$lang['InvoiceCreation.options.field_end_date'] = "Tanggal Akhir";
$lang['InvoiceCreation.options.field_status'] = "Status";
$lang['InvoiceCreation.option.any'] = "Apa saja";
$lang['InvoiceCreation.heading.id_code'] = "Invoice #";
$lang['InvoiceCreation.heading.client_id_code'] = "Klien #";
$lang['InvoiceCreation.heading.subtotal'] = "Subtotal";
$lang['InvoiceCreation.heading.total'] = "Total";
$lang['InvoiceCreation.heading.paid'] = "Dibayar";
$lang['InvoiceCreation.heading.currency'] = "Mata uang";
$lang['InvoiceCreation.heading.status'] = "Status";
$lang['InvoiceCreation.heading.date_billed'] = "Tanggal Ditagih";
$lang['InvoiceCreation.heading.date_due'] = "Tanggal jatuh tempo";
$lang['InvoiceCreation.heading.date_closed'] = "Tanggal Ditutup";
?>
