<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.Phpids.email_alert_name'] = "Peringatan Intrusi PHPIDS";
$lang['AdminCompanyEmails.templates.Phpids.email_alert_desc'] = "Email peringatan intrusi PHPIDS, dikirim ke alamat yang dikonfigurasi di bawah plugin PHPIDS.";
?>