<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PhpidsManagePlugin.!success.settings_updated'] = "Pengaturan berhasil diperbarui.";
$lang['PhpidsManagePlugin.index.page_title'] = "PHPIDS> Pengaturan";
$lang['PhpidsManagePlugin.logs.page_title'] = "PHPID> Log";
$lang['PhpidsManagePlugin.index.boxtitle_phpids'] = "PHPIDS";
$lang['PhpidsManagePlugin.index.tab_settings'] = "Pengaturan";
$lang['PhpidsManagePlugin.index.tab_logs'] = "Logs";
$lang['PhpidsManagePlugin.index.heading_general'] = "Pilihan Dasar ";
$lang['PhpidsManagePlugin.index.field.compound_impact'] = "Peringkat Dampak Majemuk dalam Sesi";
$lang['PhpidsManagePlugin.index.field.rotate_impact'] = "Putar Interval Peringkat Dampak Sesi";
$lang['PhpidsManagePlugin.index.heading_logging'] = "Pencatatan";
$lang['PhpidsManagePlugin.index.field.log_min_score'] = "Peringkat Dampak Minimum untuk Masuk";
$lang['PhpidsManagePlugin.index.field.log_rotate_freq'] = "Putar Frekuensi Log";
$lang['PhpidsManagePlugin.index.heading_email'] = "Email Alert";
$lang['PhpidsManagePlugin.index.field.email_min_score'] = "Dampak Minimum Penilaian ke Email";
$lang['PhpidsManagePlugin.index.field.email_addresses'] = "Alamat ke Email peringatan (dipisahkan koma)";
$lang['PhpidsManagePlugin.index.text.edit_template'] = "Edit Template Email";
$lang['PhpidsManagePlugin.index.heading_redirect'] = "Pengalihan";
$lang['PhpidsManagePlugin.index.field.redirect_min_score'] = "Peringkat Dampak Minimum untuk Dialihkan";
$lang['PhpidsManagePlugin.index.field.redirect_url'] = "URL untuk Dialihkan ke";
$lang['PhpidsManagePlugin.index.field.submit'] = "Pembaruan Pengaturan";
$lang['PhpidsManagePlugin.getIntervals.mins_singular'] = "%1\$s Menit"; // %1$s is the number of minutes
$lang['PhpidsManagePlugin.getIntervals.mins_plural'] = "%1\$s Menit"; // %1$s is the number of minutes
$lang['PhpidsManagePlugin.getDays.days_singular'] = "%1\$s hari"; // %1$s is the number of days
$lang['PhpidsManagePlugin.getDays.days_plural'] = "%1\$s Hari"; // %1$s is the number of days
$lang['PhpidsManagePlugin.getDays.days_never'] = "Jangan pernah memutar";
$lang['PhpidsManagePlugin.logs.heading.name'] = "Nama";
$lang['PhpidsManagePlugin.logs.heading.value'] = "Nilai";
$lang['PhpidsManagePlugin.logs.heading.uri'] = "URI";
$lang['PhpidsManagePlugin.logs.heading.ip'] = "IP";
$lang['PhpidsManagePlugin.logs.heading.user_id'] = "Identitas pengguna";
$lang['PhpidsManagePlugin.logs.heading.tags'] = "Tag";
$lang['PhpidsManagePlugin.logs.heading.impact'] = "Dampak";
$lang['PhpidsManagePlugin.logs.heading.date_added'] = "Tanggal Ditambahkan";
$lang['PhpidsManagePlugin.logs.no_results'] = "Tidak ada hasil.";
?>