<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CmsPlugin.name'] = "Portal";
$lang['CmsPlugin.index.title'] = "Klien Portal";
$lang['CmsPlugin.description'] = "Portal memungkinkan Anda untuk mengatur konten halaman untuk ditampilkan di URL beranda Blesta.";
?>