<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.options_updated'] = "pengaturan Sistem Ikhtisar berhasil diperbarui!";
$lang['AdminMain.index.boxtitle_overview'] = "Ikhtisar Sistem";
$lang['AdminMain.overview.statistic.clients_active'] = "Klien aktif";
$lang['AdminMain.overview.statistic.services_active'] = "Layanan Aktif";
$lang['AdminMain.overview.statistic.active_users_today'] = "Pengguna Aktif Hari Ini";
$lang['AdminMain.overview.statistic.recurring_invoices'] = "Faktur Berulang";
$lang['AdminMain.overview.statistic.pending_orders'] = "pesanan tertunda";
$lang['AdminMain.overview.statistic.open_tickets'] = "Buka Tiket";
$lang['AdminMain.overview.heading_users'] = "Pengguna Terbaru";
$lang['AdminMain.overview.tab_all'] = "Grafik";
$lang['AdminMain.overview.tab_clients'] = "klien";
$lang['AdminMain.overview.tab_services'] = "Layanan";
$lang['AdminMain.overview.tooltip_activity'] = "Aktivitas terakhir";
$lang['AdminMain.overview.tooltip_location'] = "Lokasi";
$lang['AdminMain.overview.tooltip_last_activity_now'] = "Baru saja";
$lang['AdminMain.overview.tooltip_last_activity_minute'] = "1 menit yang lalu";
$lang['AdminMain.date_range.days'] = "%1\$s Hari"; // %1$s is the number of days (more than 1)
$lang['AdminMain.settings.heading_statistics'] = "Statistika";
$lang['AdminMain.settings.text_options'] = "Periksa opsi yang akan muncul pada sitem overview.";
$lang['AdminMain.settings.clients_active'] = "Klien aktif";
$lang['AdminMain.settings.services_active'] = "Layanan Aktif";
$lang['AdminMain.settings.active_users_today'] = "Pengguna Aktif Hari Ini";
$lang['AdminMain.settings.recurring_invoices'] = "Faktur Berulang";
$lang['AdminMain.settings.open_tickets'] = "Tiket Terbuka";
$lang['AdminMain.settings.pending_orders'] = "Pesanan Tertunda";
$lang['AdminMain.settings.heading_clients'] = "Klien Tab";
$lang['AdminMain.settings.text_graphs_clients'] = "Memeriksa grafik akan muncul pada Tab Klien.";
$lang['AdminMain.settings.graph_clients'] = "Grafik Klien";
$lang['AdminMain.settings.heading_services'] = "Tab Layanan";
$lang['AdminMain.settings.text_graphs_services'] = "Periksa grafik mana yang akan muncul di Tab Layanan.";
$lang['AdminMain.settings.graph_services'] = " Grafik Layanan ";
$lang['AdminMain.settings.heading_settings'] = "Pengaturan";
$lang['AdminMain.settings.show_one_tab'] = "Tampilkan Hanya Satu Tab";
$lang['AdminMain.settings.tooltip_show_one_tab'] = "Tidak lagi memisahkan grafik di tab, melainkan menampilkan semua dalam satu tab.";
$lang['AdminMain.settings.show_legend'] = "Tampilkan Legenda";
$lang['AdminMain.settings.date_range'] = "Grafik Tanggal Rentang";
$lang['AdminMain.settings.submit_cancel'] = "Kembali ke Ikhtisar";
$lang['AdminMain.settings.submit_settings'] = "Perbarui Pengaturan";
$lang['AdminMain.graph_name.graph_services'] = "Layanan";
$lang['AdminMain.graph_name.graph_clients'] = "Pelanggan";
$lang['AdminMain.graph_line_name.active'] = "Aktif";
$lang['AdminMain.graph_line_name.canceled'] = "Dibatalkan";
$lang['AdminMain.graph_line_name.new'] = "Baru";
$lang['AdminMain.overview.statistic.services_scheduled_cancellation'] = "Layanan Pembatalan Dijadwalkan ";
$lang['AdminMain.settings.services_scheduled_cancellation'] = "Dijadwalkan, Pembatalan Layanan ";
$lang['AdminMain.overview.tooltip_last_activity_minutes'] = "%1\$s menit yang lalu"; // %1$s is the number of minutes since the user's last activity
$lang['AdminMain.graph_line_name.suspended'] = "Ditangguhkan";
?>