<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FeedReaderFeeds.!error.url.valid'] = "URL yang diberikan tidak valid.";
$lang['FeedReaderFeeds.!error.company_id.exists'] = "Perusahaan yang ditentukan tidak ada.";
$lang['FeedReaderFeeds.!error.updated.valid'] = "Anda harus menentukan tanggal pembaruan yang valid.";
$lang['FeedReaderFeeds.!error.feed_id.exists'] = "Feed yang diberikan tidak ada.";
$lang['FeedReaderFeeds.!error.staff_id.exists'] = "Anggota staf yang ditentukan tidak ada.";
$lang['FeedReaderFeeds.!error.date.valid'] = "Data yang ditentukan tidak valid.";
?>