<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_updated_name'] = "Tiket Staf Diperbarui";
$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_updated_desc'] = "Pemberitahuan dikirim ke anggota staf saat tiket diperbarui.";
$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_updated_mobile_name'] = "Tiket Staff Diperbaharui (Seluler)";
$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_updated_mobile_desc'] = "Pemberitahuan via ponsel dikirim ke anggota staf ketika tiket diperbarui.";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_received_name'] = "Tiket Diterima";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_received_desc'] = "Pemberitahuan dikirim ke pengguna saat tiket diterima.";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_updated_name'] = "Tiket Diperbarui";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_updated_desc'] = "Pemberitahuan dikirim saat tiket diperbarui.";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_bounce_name'] = "Bounce Tiket";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_bounce_desc'] = "Pemberitahuan dikirim ketika tiket gagal dibuka melalui email.";
$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_assigned_name'] = "Tiket Staf Ditugaskan";
$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_assigned_desc'] = "Pemberitahuan dikirim ke anggota staf ketika tiket telah diberikan kepada mereka.";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_reminder_name'] = "Pengingat Tiket";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_reminder_desc'] = "Pemberitahuan dikirim ketika tiket tidak menerima balasan untuk jangka waktu tertentu.";
$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_reminder_name'] = "Pengingat Tiket Staf";
$lang['AdminCompanyEmails.templates.SupportManager.staff_ticket_reminder_desc'] = "Pemberitahuan dikirim ketika tiket tidak menerima balasan untuk jangka waktu tertentu.";
?>