<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminDepartments.!success.department_created'] = "Departemen %1\$s berhasil dibuat."; // %1$s is the name of the department
$lang['AdminDepartments.!success.department_updated'] = "department %1\$s berhasil diperbarui."; // %1$s is the name of the department
$lang['AdminDepartments.!success.department_deleted'] = "The %1\$s departemen berhasil dihapus."; // %1$s is the name of the department
$lang['AdminDepartments.index.page_title'] = "Support Manager> Departemen";
$lang['AdminDepartments.add.page_title'] = "Support Manager > Departemen> Tambah Department";
$lang['AdminDepartments.edit.page_title'] = "Dukungan Manager> Departemen> Edit Departemen";
$lang['AdminDepartments.index.categorylink_adddepartment'] = "Tambahkan Departemen";
$lang['AdminDepartments.index.boxtitle_departments'] = "Departemen";
$lang['AdminDepartments.index.heading_name'] = "Nama";
$lang['AdminDepartments.index.heading_description'] = "Deskripsi";
$lang['AdminDepartments.index.heading_email'] = "Email";
$lang['AdminDepartments.index.heading_assigned_staff'] = "Staf yang ditugaskan";
$lang['AdminDepartments.index.heading_default_priority'] = "Prioritas Bawaan";
$lang['AdminDepartments.index.heading_options'] = "Pilihan";
$lang['AdminDepartments.index.option_edit'] = "Sunting";
$lang['AdminDepartments.index.option_delete'] = "Hapus";
$lang['AdminDepartments.index.confirm_delete'] = "Departemen dengan tiket yang ditetapkan kepada mereka tidak dapat dihapus sampai semua tiket telah kembali ditetapkan ke departemen alternatif. Apakah Anda yakin ingin menghapus departemen ini?";
$lang['AdminDepartments.index.no_results'] = "Tidak ada departemen.";
$lang['AdminDepartments.assigned_staff.heading_staff'] = "Staf";
$lang['AdminDepartments.assigned_staff.no_results'] = "Tidak ada staf yang ditugaskan untuk departemen ini.";
$lang['AdminDepartments.!tooltip.piping_config'] = "Atur jalur perpipaan Anda seperti yang ditunjukkan, tetapi pastikan untuk menggunakan jalur yang benar ke PHP di server Anda. Pastikan pipe.php dapat dieksekusi. Anda mungkin juga perlu mengedit pipe.php untuk menyertakan hashbang pada baris 1 yang akan terlihat seperti: #!/usr/bin/php";
$lang['AdminDepartments.add.boxtitle_adddepartment'] = "Tambahkan Departemen";
$lang['AdminDepartments.add.field_name'] = "Nama";
$lang['AdminDepartments.add.field_description'] = "Deskripsi";
$lang['AdminDepartments.add.field_clients_only'] = "hanya klien yang bisa membuka atau membalas tiket";
$lang['AdminDepartments.add.field_email'] = "Email";
$lang['AdminDepartments.add.field_method'] = "Penanganan Email";
$lang['AdminDepartments.add.field_piping_config'] = "Konfigurasi Piping";
$lang['AdminDepartments.add.field_default_priority'] = "Standar Prioritas";
$lang['AdminDepartments.add.field_security'] = "Keamanan";
$lang['AdminDepartments.add.field_box_name'] = "Nama Kotak";
$lang['AdminDepartments.add.field_mark_messages'] = "Tandai Pesan sebagai";
$lang['AdminDepartments.add.field_host'] = "Host";
$lang['AdminDepartments.add.field_user'] = "Pengguna";
$lang['AdminDepartments.add.field_pass'] = "Pass";
$lang['AdminDepartments.add.field_port'] = "Port";
$lang['AdminDepartments.add.field_status'] = "Status";
$lang['AdminDepartments.add.field_addsubmit'] = "Tambahkan Department";
$lang['AdminDepartments.edit.boxtitle_adddepartment'] = "Sunting Department";
$lang['AdminDepartments.edit.field_name'] = "Nama";
$lang['AdminDepartments.edit.field_description'] = "Deskripsi";
$lang['AdminDepartments.edit.field_clients_only'] = "Izinkan hanya klien untuk membuka atau membalas tiket";
$lang['AdminDepartments.edit.field_email'] = "Email";
$lang['AdminDepartments.edit.field_method'] = "Email Penanganan";
$lang['AdminDepartments.edit.field_piping_config'] = "Konfigurasi Perpipaan";
$lang['AdminDepartments.edit.field_default_priority'] = "Standar Prioritas";
$lang['AdminDepartments.edit.field_security'] = "Keamanan";
$lang['AdminDepartments.edit.field_box_name'] = "Nama Kotak";
$lang['AdminDepartments.edit.field_mark_messages'] = "Tandai  Pesan sebagai";
$lang['AdminDepartments.edit.field_host'] = "Host";
$lang['AdminDepartments.edit.field_user'] = "Pemakai";
$lang['AdminDepartments.edit.field_pass'] = "Lulus";
$lang['AdminDepartments.edit.field_port'] = "Port";
$lang['AdminDepartments.edit.field_status'] = "Status";
$lang['AdminDepartments.edit.field_addsubmit'] = "Edit Departemen";
$lang['AdminDepartments.assigned_staff.heading_assigned_staff'] = "Staf yang Ditugaskan";
$lang['AdminDepartments.add.field_override_from_email'] = "Timpa alamat email yang ditetapkan dalam template dengan alamat email yang ditetapkan untuk departemen ini";
$lang['AdminDepartments.edit.field_override_from_email'] = "Menimpa alamat yang ditetapkan dalam template email dengan alamat email yang ditetapkan untuk departemen ini";
$lang['AdminDepartments.!tooltip.close_ticket_interval'] = "Semua tiket dengan status selain %1\$s yang terakhir adalah jawaban dari anggota staf akan ditutup secara otomatis jika tidak ada balasan telah dibuat dalam jumlah waktu yang ditentukan"; // %1$s is the ticket status In Progress
$lang['AdminDepartments.!text.add_response'] = "Setel Respons yang Sudah Ditentukan Tutup Otomatis";
$lang['AdminDepartments.!text.no_selected_response'] = "Tidak ada respon penutupan otomatis yang dipilih.";
$lang['AdminDepartments.!text.remove_response'] = "hapus";
$lang['AdminDepartments.add.field_close_ticket_interval'] = "Menutup Tiket Secara Otomatis";
$lang['AdminDepartments.add.field_response_id'] = "Respons Penutupan Tiket Otomatis";
$lang['AdminDepartments.edit.field_response_id'] = "Otomatis-Tutup (Respons Tiket)";
$lang['AdminDepartments.!tooltip.send_ticket_received'] = "Tidak mencentang kotak ini menunjukkan bahwa tiket baru yang dibuat untuk departemen ini (melalui email atau klien) tidak akan mengirim pemberitahuan balasan kepada klien atau staf melalui email Menerima Tiket atau email Diperbarui Tiket Staf.";
$lang['AdminDepartments.add.field_send_ticket_received'] = "Kirim Email Respons Otomatis untuk Tiket Baru";
$lang['AdminDepartments.edit.field_send_ticket_received'] = "Kirim Email Respons Otomatis untuk Tiket Baru";
$lang['AdminDepartments.!tooltip.delete_ticket_interval'] = "Semua tiket dengan status %1\$s akan dihapus secara otomatis setelah tetap dalam status tersebut selama jangka waktu yang dipilih."; // %1$s is the ticket status (e.g. Trash)
$lang['AdminDepartments.add.field_delete_ticket_interval'] = "Hapus Tiket Secara Otomatis";
$lang['AdminDepartments.edit.field_close_ticket_interval'] = "Menutup Tiket Secara Otomatis";
$lang['AdminDepartments.edit.field_delete_ticket_interval'] = "Hapus Tiket Secara Otomatis";
$lang['AdminDepartments.!tooltip.automatic_transition'] = "Mengubah status menjadi %1\$s saat anggota staf membalas."; // %1$s is the 'Awaiting Client Reply' status
$lang['AdminDepartments.add.field_automatic_transition'] = "Transisi status tiket secara otomatis pada balasan admin";
$lang['AdminDepartments.edit.field_automatic_transition'] = "Transisi status tiket secara otomatis pada balasan admin";
$lang['AdminDepartments.add.field_require_captcha'] = "Memerlukan Verifikasi Manusia untuk pengguna yang tidak diautentikasi";
$lang['AdminDepartments.edit.field_require_captcha'] = "Memerlukan Verifikasi Manusia untuk pengguna yang tidak diautentikasi";
$lang['AdminDepartments.!tooltip.reminder_ticket_interval'] = "Untuk semua tiket dengan status selain %1\$s, pengingat akan dikirimkan ke bagian lain jika tidak ada balasan yang dibuat dalam jangka waktu yang dipilih."; // %1$s is the ticket status Closed
$lang['AdminDepartments.!tooltip.include_attachments'] = "Server email memiliki batasan pada ukuran lampiran dan jenis file. Untuk mengurangi risiko email ditolak, harap sertakan jenis lampiran dan batasan ukuran. Untuk memastikan klien mengetahui lampiran yang tidak disertakan, gunakan tag {ticket.reply_has_attachments} di pemberitahuan tiket.";
$lang['AdminDepartments.!tooltip.attachment_types'] = "Daftar ekstensi yang didukung dipisahkan dengan koma (mis. zip,jpg,png).";
$lang['AdminDepartments.!tooltip.max_attachment_size'] = "Ukuran maksimum lampiran untuk disertakan dalam MB.";
$lang['AdminDepartments.add.field_include_attachments'] = "Sertakan lampiran yang didukung dalam pemberitahuan tiket";
$lang['AdminDepartments.add.field_attachment_types'] = "Jenis Lampiran yang Didukung";
$lang['AdminDepartments.add.field_max_attachment_size'] = "Maksimum Ukuran Lampiran";
$lang['AdminDepartments.add.field_reminder_ticket_interval'] = "Kirim Pengingat Tiket Secara Otomatis";
$lang['AdminDepartments.add.field_reminder_ticket_status'] = "Kirim Pengingat ke Tiket dengan Status";
$lang['AdminDepartments.add.field_reminder_ticket_priority'] = "Kirim Pengingat ke Tiket dengan Prioritas";
$lang['AdminDepartments.edit.field_include_attachments'] = "Sertakan lampiran yang didukung dalam pemberitahuan tiket";
$lang['AdminDepartments.edit.field_attachment_types'] = "Jenis Lampiran yang Didukung";
$lang['AdminDepartments.edit.field_max_attachment_size'] = "Maksimum Ukuran Lampiran";
$lang['AdminDepartments.edit.field_reminder_ticket_interval'] = "Kirim Pengingat Tiket Secara Otomatis";
$lang['AdminDepartments.edit.field_reminder_ticket_status'] = "Kirim Pengingat ke Tiket dengan Status";
$lang['AdminDepartments.edit.field_reminder_ticket_priority'] = "Kirim Pengingat ke Tiket dengan Prioritas";
?>