<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyMessengers.templates.SupportManager.staff_ticket_updated_name'] = "Tiket Staf Diperbarui";
$lang['AdminCompanyMessengers.templates.SupportManager.staff_ticket_updated_desc'] = "Pemberitahuan dikirim ke anggota staf saat tiket diperbarui.";
$lang['AdminCompanyMessengers.templates.SupportManager.staff_ticket_assigned_name'] = "Tiket Staf Ditugaskan";
$lang['AdminCompanyMessengers.templates.SupportManager.staff_ticket_assigned_desc'] = "Pemberitahuan dikirim ke anggota staf ketika tiket telah diberikan kepada mereka.";
?>