<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminTickets.!success.ticket_created'] = "Tiket #%1\$s telah berhasil dibuka."; // %1$s is the ticket number
$lang['AdminTickets.!success.ticket_updated'] = "Tiket #%1\$s telah berhasil diperbarui."; // %1$s is the ticket number
$lang['AdminTickets.!notice.no_departments_staff'] = "Belum ada staf dan/atau departemen yang dibentuk. Klik %1\$s di atas untuk membuat departemen, atau %2\$s untuk menetapkan anggota staf."; // %1$s is the language definition for the Departments navigation item, %2$s is the language definition for the Staff navigation item
$lang['AdminTickets.index.page_title'] = "Manajer Dukungan > Tiket";
$lang['AdminTickets.add.page_title'] = "Manajer Dukungan > Buka Tiket";
$lang['AdminTickets.reply.page_title'] = "Support Manager > Ticket #%1\$s"; // %1$s is the ticket number
$lang['AdminTickets.search.page_title'] = "Hasil pencarian untuk \"%1\$s\""; // %1$s is the search keywords
$lang['AdminTickets.text.unassigned'] = "Tidak Ditugaskan";
$lang['AdminTickets.index.category_open'] = "Menunggu jawaban staf";
$lang['AdminTickets.index.category_awaiting_reply'] = "Menunggu Balasan Klien";
$lang['AdminTickets.index.category_in_progress'] = "Sedang berlangsung";
$lang['AdminTickets.index.category_closed'] = "Tutup";
$lang['AdminTickets.index.categorylink_createticket'] = "Buka Tiket";
$lang['AdminTickets.index.boxtitle_tickets'] = "Tiket";
$lang['AdminTickets.index.heading_code'] = "Nomor tiket";
$lang['AdminTickets.index.heading_priority'] = "Prioritas";
$lang['AdminTickets.index.heading_department_name'] = "Departemen";
$lang['AdminTickets.index.heading_summary'] = "Ringkasan";
$lang['AdminTickets.index.heading_last_reply_date'] = "Balasan Terakhir";
$lang['AdminTickets.index.no_results'] = "Tidak ada ticket dengan status ini";
$lang['AdminTickets.add.boxtitle_add'] = "Buka Tiket";
$lang['AdminTickets.add.heading_search_client'] = "Mencari Klien";
$lang['AdminTickets.add.text_no_clients'] = "Tidak ada klien ditemukan. Silahkan dicoba lagi.";
$lang['AdminTickets.add.heading_summary'] = "Ringkasan";
$lang['AdminTickets.add.heading_client'] = "Klien";
$lang['AdminTickets.add.heading_department'] = "Departemen";
$lang['AdminTickets.add.heading_staff_id'] = "Ditugaskan untuk";
$lang['AdminTickets.add.heading_priority'] = "Prioritas";
$lang['AdminTickets.add.heading_status'] = "Status";
$lang['AdminTickets.add.field_attachments'] = "lampiran";
$lang['AdminTickets.add.field_details'] = "rincian";
$lang['AdminTickets.add.text_add_attachment'] = "Tambahkan Lampiran";
$lang['AdminTickets.add.field_addsubmit'] = "Buka Tiket";
$lang['AdminTickets.add.text_add_response'] = "Masukkan Respons yang Telah Ditentukan";
$lang['AdminTickets.reply.boxtitle_reply'] = "Tiket #%1\$s"; // %1$s is the ticket number
$lang['AdminTickets.reply.heading_summary'] = "Ringkasan";
$lang['AdminTickets.reply.heading_client'] = "Klien";
$lang['AdminTickets.reply.heading_department'] = "Departemen";
$lang['AdminTickets.reply.heading_staff_id'] = "Ditugaskan Untuk";
$lang['AdminTickets.reply.heading_priority'] = "Prioritas";
$lang['AdminTickets.reply.heading_status'] = "Status";
$lang['AdminTickets.reply.heading_date_added'] = "Tanggal Dibuka";
$lang['AdminTickets.reply.text_add_response'] = "Masukkan Respons yang Telah Ditentukan";
$lang['AdminTickets.reply.heading_reply'] = "Tambahkan Balasan";
$lang['AdminTickets.reply.field_reply'] = "Balas";
$lang['AdminTickets.reply.field_note'] = "Catatan";
$lang['AdminTickets.reply.field_attachments'] = "Lampiran";
$lang['AdminTickets.reply.text_add_attachment'] = "Tambahkan Lampiran";
$lang['AdminTickets.reply.field_replysubmit'] = "Perbarui Tiket";
$lang['AdminTickets.reply.reply_date'] = "Pada %1\$s %2\$s %3\$s menjawab"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['AdminTickets.reply.log_date'] = "%1\$s oleh %2\$s %3\$s"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['AdminTickets.reply.system'] = "Sistem";
$lang['AdminTickets.reply.staff_title'] = "Staf pendukung";
$lang['AdminTickets.client.category_open'] = "Menunggu Balasan Staf";
$lang['AdminTickets.client.category_awaiting_reply'] = "Menunggu Balasan Klien";
$lang['AdminTickets.client.category_in_progress'] = "Sedang berlangsung";
$lang['AdminTickets.client.category_closed'] = "Tertutup";
$lang['AdminTickets.client.categorylink_createticket'] = "Buka Tiket";
$lang['AdminTickets.client.boxtitle_tickets'] = "Tiket";
$lang['AdminTickets.client.heading_code'] = "Nomor tiket";
$lang['AdminTickets.client.heading_priority'] = "Prioritas";
$lang['AdminTickets.client.heading_department_name'] = "Departemen";
$lang['AdminTickets.client.heading_summary'] = "Ringkasan";
$lang['AdminTickets.client.heading_last_reply_date'] = "Balasan Terakhir";
$lang['AdminTickets.client.no_results'] = "Saat ini tidak ada tiket dengan status ini.";
$lang['AdminTickets.search.boxtitle_tickets'] = "Cari Tiket untuk \"%1\$s\""; // %1$s is the search criteria
$lang['AdminTickets.search.heading_code'] = "Nomor Tiket";
$lang['AdminTickets.search.heading_priority'] = "Prioritas";
$lang['AdminTickets.search.heading_status'] = "Status";
$lang['AdminTickets.search.heading_department_name'] = "Departemen";
$lang['AdminTickets.search.heading_summary'] = "Ringkasan";
$lang['AdminTickets.search.heading_last_reply_date'] = "Balasan Terakhir";
$lang['AdminTickets.search.no_results'] = "Tidak ada tiket yang cocok dengan kriteria pencarian.";
$lang['AdminTickets.index.last_reply_by'] = "oleh";
$lang['Admintickets.add.client_placeholder'] = "ID atau Nama Klien";
$lang['AdminTickets.!success.ticket_split'] = "Tiket #%1\$s telah berhasil dipecah menjadi tiket #%2\$s."; // %1$s is the ticket number of the ticket being split, %2$s is the ticket number of the split ticket
$lang['AdminTickets.!success.ticket_merge'] = "Tiket yang dipilih telah berhasil digabungkan ke dalam tiket #%1\$s."; // %1$s is the ticket number
$lang['AdminTickets.!success.ticket_update_status'] = "Tiket yang dipilih telah berhasil diperbarui.";
$lang['AdminTickets.index.heading_assigned_staff'] = "Ditugaskan Untuk";
$lang['AdminTickets.index.unassigned'] = "tidak dialokasikan";
$lang['AdminTickets.index.text_with_selected'] = "Dengan tiket yang dipilih, lakukan:";
$lang['AdminTickets.index.text_into_ticket'] = "Ke tiket:";
$lang['AdminTickets.index.text_to_status'] = "Ubah :";
$lang['AdminTickets.index.ticket_number_placeholder'] = "Nomor Tiket";
$lang['AdminTickets.index.text_no_tickets'] = "Tidak ada tiket terbuka ditemukan. Coba cari lagi.";
$lang['AdminTickets.index.field_actionsubmit'] = "Kirim";
$lang['AdminTickets.index.ticket_name'] = "#%1\$s %2\$s %3\$s"; // %1$s is the ticket number, %2$s is the client's first name, %3$s is the client's last name
$lang['AdminTickets.index.ticket_email'] = "#%1\$s %2\$s"; // %1$s is the ticket number, %2$s is the client's email address
$lang['AdminTickets.reply.text_with_selected'] = "Dengan balasan yang dipilih, lakukan:";
$lang['AdminTickets.reply.field_actionsubmit'] = "Pergi";
$lang['AdminTickets.index.heading_client'] = "Klien";
$lang['AdminTickets.!success.ticket_delete'] = "Tiket yang dipilih telah berhasil dihapus.";
$lang['AdminTickets.index.category_on_hold'] = "Tertahan";
$lang['AdminTickets.index.category_trash'] = "Sampah";
$lang['AdminTickets.client.category_on_hold'] = "Tertahan";
$lang['AdminTickets.client.category_trash'] = "Sampah";
$lang['AdminTickets.reply.refresh'] = "Ada balasan baru atau perubahan status.";
$lang['AdminTickets.reply.refresh_link'] = "Klik untuk menampilkan.";
$lang['AdminTickets.!success.ticket_reassign'] = "Tiket yang dipilih telah berhasil dipindahkan.";
$lang['AdminTickets.index.text_to_client'] = "Untuk klien:";
$lang['AdminTickets.index.any'] = "Apa saja";
$lang['AdminTickets.index.minutes'] = "%1\$s menit"; // %1$s is the elapsed minutes
$lang['AdminTickets.index.hour'] = "1 jam";
$lang['AdminTickets.index.hours'] = "%1\$s jam"; // %1$s is the elapsed hours
$lang['AdminTickets.index.field_ticket_number'] = "Nomor tiket";
$lang['AdminTickets.index.field_priority'] = "Prioritas";
$lang['AdminTickets.index.field_department_id'] = "Departemen";
$lang['AdminTickets.index.field_summary'] = "Ringkasan";
$lang['AdminTickets.index.field_assigned_staff'] = "Ditugaskan untuk";
$lang['AdminTickets.index.field_last_reply'] = "Balasan Terakhir";
$lang['AdminTickets.add.dropzone_drop_files_here'] = "Letakkan file di sini untuk mengupload atau Klik untuk memilih file";
$lang['AdminTickets.add.dropzone_remove_file'] = "Hapus Berkas";
$lang['AdminTickets.reply.dropzone_drop_files_here'] = "Letakkan file di sini untuk mengunggah atau Klik untuk memilih file";
$lang['AdminTickets.reply.dropzone_remove_file'] = "Hapus Berkas";
?>