<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerDepartments.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['SupportManagerDepartments.!error.name.empty'] = "Harap masukkan nama untuk departemen ini.";
$lang['SupportManagerDepartments.!error.description.empty'] = "Harap masukkan deskripsi.";
$lang['SupportManagerDepartments.!error.email.format'] = "Silakan masukkan alamat email yang valid.";
$lang['SupportManagerDepartments.!error.method.format'] = "Jenis metode tidak valid.";
$lang['SupportManagerDepartments.!error.method.imap'] = "ekstensi PHP IMAP diperlukan untuk men-download pesan melalui POP3 atau IMAP.";
$lang['SupportManagerDepartments.!error.method.mailparse'] = "Ekstensi PHP Mailparse PECL diperlukan untuk mengurai tiket email.";
$lang['SupportManagerDepartments.!error.default_priority.format'] = "Jenis prioritas bawaan tidak valid.";
$lang['SupportManagerDepartments.!error.host.format'] = "Masukkan nama host yang valid.";
$lang['SupportManagerDepartments.!error.host.length'] = "Nama host tidak boleh melebihi 128 karakter.";
$lang['SupportManagerDepartments.!error.user.format'] = "Harap masukkan nama pengguna.";
$lang['SupportManagerDepartments.!error.user.length'] = "Nama pengguna tidak boleh melebihi 64 karakter.";
$lang['SupportManagerDepartments.!error.password.format'] = "Silakan masukkan password.";
$lang['SupportManagerDepartments.!error.port.format'] = "Harap masukkan nomor port.";
$lang['SupportManagerDepartments.!error.port.length'] = "port tidak dapat melebihi 6 digit.";
$lang['SupportManagerDepartments.!error.service.format'] = "Silahkan memilih tipe layanan yang valid.";
$lang['SupportManagerDepartments.!error.security.format'] = "Silakan memilih jenis keamanan yang valid.";
$lang['SupportManagerDepartments.!error.mark_messages.format'] = "Harap pilih jenis pesan yang valid untuk menandai pesan.";
$lang['SupportManagerDepartments.!error.mark_messages.valid'] = "Pesan menggunakan POP3 hanya dapat ditandai sebagai dihapus.";
$lang['SupportManagerDepartments.!error.status.format'] = "Jenis Status keliru";
$lang['SupportManagerDepartments.!error.department_id.exists'] = "ID departemen tidak valid.";
$lang['SupportManagerDepartments.!error.department_id.has_tickets'] = "Departemen tidak dapat dihapus karena saat ini memiliki tiket yang ditetapkan untuk departemen tersebut.";
$lang['SupportManagerDepartments.methods.none'] = "Tidak Ada";
$lang['SupportManagerDepartments.methods.pipe'] = "Piping";
$lang['SupportManagerDepartments.methods.pop3'] = "POP3";
$lang['SupportManagerDepartments.methods.imap'] = "IMAP";
$lang['SupportManagerDepartments.statuses.hidden'] = "Tersembunyi";
$lang['SupportManagerDepartments.statuses.visible'] = "Bisa dilihat";
$lang['SupportManagerDepartments.priorities.emergency'] = "Keadaan darurat";
$lang['SupportManagerDepartments.priorities.critical'] = "Kritis";
$lang['SupportManagerDepartments.priorities.high'] = "Tinggi";
$lang['SupportManagerDepartments.priorities.medium'] = "Medium";
$lang['SupportManagerDepartments.priorities.low'] = "Rendah";
$lang['SupportManagerDepartments.security_types.none'] = "Tak satupun";
$lang['SupportManagerDepartments.security_types.ssl'] = "SSL";
$lang['SupportManagerDepartments.security_types.tls'] = "TLS";
$lang['SupportManagerDepartments.message_types.read'] = "Baca ";
$lang['SupportManagerDepartments.message_types.deleted'] = "Dihapus";
$lang['SupportManagerDepartments.!error.clients_only.format'] = "Apakah mengizinkan klien untuk membuka atau membalas tiket harus disetel ke 0 atau 1.";
$lang['SupportManagerDepartments.!error.override_from_email.format'] = "Apakah mengizinkan alamat email departemen ini yang akan digunakan sebagai dari alamat email template, harus diatur ke 0 atau 1.";
$lang['SupportManagerDepartments.!error.close_ticket_interval.format'] = "Silakan pilih interval tiket terdekat yang valid.";
$lang['SupportManagerDepartments.!error.response_id.format'] = "Silakan pilih respons penutupan otomatis yang valid.";
$lang['SupportManagerDepartments.ticket_intervals.day'] = "1 hari";
$lang['SupportManagerDepartments.ticket_intervals.days'] = "%1\$s hari"; // %1$s is the number of days
$lang['SupportManagerDepartments.!error.send_ticket_received.format'] = "Apakah mengirim email konfirmasi tiket untuk departemen ini harus diatur ke 0 atau 1.";
$lang['SupportManagerDepartments.!error.delete_ticket_interval.format'] = "Harap pilih interval penghapusan tiket yang valid.";
$lang['SupportManagerDepartments.!error.require_captcha.format'] = "Apakah memerlukan verifikasi manusia harus disetel ke 0 atau 1.";
$lang['SupportManagerDepartments.!error.reminder_ticket_interval.format'] = "Harap pilih interval tiket pengingat yang valid.";
$lang['SupportManagerDepartments.!error.reminder_ticket_status.format'] = "Silakan pilih status pengingat tiket yang valid.";
$lang['SupportManagerDepartments.!error.reminder_ticket_priority.format'] = "Harap pilih prioritas pengingat tiket yang valid.";
$lang['SupportManagerDepartments.!error.include_attachments.format'] = "Apakah akan menyertakan lampiran tiket harus disetel ke 0 atau 1.";
$lang['SupportManagerDepartments.!error.attachment_types.length'] = "Daftar jenis lampiran tidak boleh melebihi 255 karakter.";
$lang['SupportManagerDepartments.!error.max_attachment_size.format'] = "Ukuran lampiran maksimum harus berupa nilai numerik.";
$lang['SupportManagerDepartments.reminder_intervals.hour'] = "1 jam";
$lang['SupportManagerDepartments.reminder_intervals.hours'] = "%1\$s Jam"; // %1$s is the number of hours
$lang['SupportManagerDepartments.reminder_intervals.minutes'] = "%1\$s Menit"; // %1$s is the number of minutes
?>