<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Package.!error.meta[pricing_id].format'] = "Pilih lisensi yang valid.";
$lang['BlestaLicense.module_row.name'] = "Eceran";
$lang['BlestaLicense.module_rows.name'] = "Resellers";
$lang['BlestaLicense.add_module_row'] = "Tambahkan Pengecer";
$lang['BlestaLicense.manage.module_rows_title'] = "Reseller";
$lang['BlestaLicense.manage.module_rows_heading.username'] = "Nama pengguna";
$lang['BlestaLicense.manage.module_rows_heading.options'] = "Pilihan";
$lang['BlestaLicense.manage.module_rows.edit'] = "Sunting";
$lang['BlestaLicense.manage.module_rows.delete'] = "Menghapus";
$lang['BlestaLicense.manage.module_rows.confirm_delete'] = "Yakin ingin menghapus pengecer ini?";
$lang['BlestaLicense.manage.module_rows_no_results'] = "Tidak ada reseller.";
$lang['BlestaLicense.!tooltip.username'] = "Masukkan nama pengguna akun Blesta Anda.";
$lang['BlestaLicense.!tooltip.password'] = "Masukkan kata sandi akun Blesta Anda.";
$lang['BlestaLicense.row_meta.username'] = "Nama pengguna";
$lang['BlestaLicense.row_meta.password'] = "Kata sandi";
$lang['BlestaLicense.row_meta.test_mode'] = "Modus Uji";
$lang['BlestaLicense.add_row.box_title'] = "Tambahkan Reseller";
$lang['BlestaLicense.add_row.basic_title'] = "Pengaturan dasar";
$lang['BlestaLicense.add_row.add_btn'] = "Tambahkan Pengecer";
$lang['BlestaLicense.edit_row.box_title'] = "Edit Reseller";
$lang['BlestaLicense.edit_row.basic_title'] = "Pengaturan dasar";
$lang['BlestaLicense.edit_row.edit_btn'] = "Perbarui Pengecer";
$lang['Package.getpricings.pricing_id'] = "%1\$s (ID %2\$s)"; // %1$s is the package name, %2$s is the package pricing ID
$lang['Package.package_fields.pricing_id'] = "Lisensi";
$lang['BlestaLicense.tab_reissue'] = "Lisensi Penerbitan Ulang";
$lang['BlestaLicense.tab_reissue.heading_reissue'] = "Penerbitan ulang";
$lang['BlestaLicense.tab_reissue.description'] = "Menerbitkan kembali lisensi akan memungkinkan lisensi untuk dipasang atau dipindahkan ke lokasi lain yang akan dikunci.";
$lang['BlestaLicense.tab_reissue.field_submit'] = "Penerbitan ulang";
?>