<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Twilio.name'] = "Twilio";
$lang['Twilio.description'] = "Kirim notifikasi SMS menggunakan Twilio.";
$lang['Twilio.configuration_fields.phone_number'] = "Nomor Telepon";
$lang['Twilio.configuration_fields.sid'] = "SID akun";
$lang['Twilio.configuration_fields.token'] = "Token";
?>