<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TransactionsApplied.name'] = "Transaksi Diterapkan";
$lang['TransactionsApplied.option.any'] = "Apa saja";
$lang['TransactionsApplied.options.field_start_date'] = "Tangga lMulai ";
$lang['TransactionsApplied.options.field_end_date'] = "Tanggal Akhir";
$lang['TransactionsApplied.options.field_gateway'] = "Gateway";
$lang['TransactionsApplied.options.field_status'] = "Status";
$lang['TransactionsApplied.options.field_payment_type'] = "Jenis Pembayaran";
$lang['TransactionsApplied.heading.id'] = "Transaksi #";
$lang['TransactionsApplied.heading.transaction_id'] = "ID transaksi";
$lang['TransactionsApplied.heading.reference_id'] = "ID Referensi";
$lang['TransactionsApplied.heading.client_id_code'] = "Klien #";
$lang['TransactionsApplied.heading.invoice_id_code'] = "Faktur #";
$lang['TransactionsApplied.heading.gateway_name'] = "Gateway Pembayaran";
$lang['TransactionsApplied.heading.type_name'] = "Tipe Pembayaran";
$lang['TransactionsApplied.heading.applied_amount'] = "Jumlah yang diterapkan";
$lang['TransactionsApplied.heading.amount'] = "Jumlah pembayaran";
$lang['TransactionsApplied.heading.currency'] = "Mata uang";
$lang['TransactionsApplied.heading.status'] = "Status";
$lang['TransactionsApplied.heading.applied_date'] = "Tanggal Diterapkan";
$lang['TransactionsApplied.heading.income_type'] = "tipe transaksi";
?>