<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Stripe_gateway.!error.auth'] = "ateway tidak bisa mengotentikasi.";
$lang['Stripe_gateway.!error.api_key.empty'] = "Silahkan masukkan kunci API";
$lang['Stripe_gateway.!error.json_required'] = "JSON ekstensi diperlukan untuk gateway ini.";
$lang['Stripe_gateway.name'] = "Garis";
$lang['Stripe_gateway.api_key'] = "API Secret Key";
$lang['Stripe_gateway.tooltip_api'] = "Kunci Rahasia API Anda khusus untuk mode langsung atau uji coba. Pastikan Anda menggunakan kunci yang benar.";
$lang['Stripe_gateway.stored'] = "Simpan Informasi Kartu di Luar Situs";
$lang['Stripe_gateway.tooltip_stored'] = "Centang kotak ini untuk menyimpan informasi kartu akun pembayaran dengan Stripe daripada di dalam Blesta.";
$lang['Stripe_gateway.charge_description'] = "Tagihan untuk %1\$s"; // Where %1$s is a comma seperated list of invoice ID display codes
$lang['Stripe_gateway.description'] = "Ini adalah gerbang Stripe lama yang menggunakan Stripe Checkout. Ini mengharuskan akun Stripe Anda diperbarui menjadi \"Proses pembayaran dengan tidak aman\". Sebaiknya gunakan gateway Pembayaran Stripe di Blesta sebagai gantinya";
?>
