<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['GenericDomains.name'] = "Domain Umum";
$lang['GenericDomains.description'] = "Modul generik untuk pendaftaran domain.";
$lang['GenericDomains.module_row'] = "Baris Modul";
$lang['GenericDomains.module_row_plural'] = "Baris Modul";
$lang['GenericDomains.domain.domain'] = "Domain";
$lang['GenericDomains.transfer.domain'] = "Domain";
$lang['GenericDomains.transfer.transfer_key'] = "Kode EPP";
$lang['GenericDomains.manage.text'] = "Staf dapat menerima salinan BCC dari pembuatan layanan, penangguhan, dan email pembatalan jika grup staf mereka telah menetapkan pemberitahuan BCC ini, dan anggota staf berlangganan ke mereka di bawah bagian [Info Saya] -> [Pemberitahuan].";
$lang['GenericDomains.package_fields.tld_options'] = "TLD";
?>
