<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Widepay.name'] = "Wide Pay";
$lang['Widepay.wallet_id'] = "ID dompet";
$lang['Widepay.wallet_token'] = "Token Dompet";
$lang['Widepay.allow_card_payment'] = "Izinkan Pembayaran Kartu";
$lang['Widepay.!error.wallet_id.format'] = "Silakan masukkan ID dompet
";
$lang['Widepay.!error.wallet_token.format'] = "Silakan masukkan token API dompet";
$lang['Widepay.buildprocess.submit_card'] = "Bayar dengan Kartu Kredit Bayar Lebar";
$lang['Widepay.buildprocess.submit_ticket'] = "Bayar dengan Tiket Bayar Lebar";
$lang['Widepay.charge_types.ticket'] = "Tiket";
$lang['Widepay.charge_types.card'] = "Kartu kredit";
?>
