<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Payumoney.name'] = "Payumoney";
$lang['Payumoney.merchant_key'] = "Kunci Pedagang";
$lang['Payumoney.merchant_salt'] = "Merchant Salt";
$lang['Payumoney.auth_header'] = "Judul Otorisasi";
$lang['Payumoney.auth_header_note'] = "Header otorisasi dapat ditemukan di dashboard Payumoney di bawah Kelola Akun -> Akun Saya -> Merchant Key-Salt.";
$lang['Payumoney.merchant_key_note'] = "kunci pedagang dapat ditemukan di dasbor Payumoney di bawah Kelola Akun -> Akun Saya -> Merchant Key-Salt.";
$lang['Payumoney.merchant_salt_note'] = "merchant salt dapat ditemukan di dasbor Payumoney di bawah Kelola Akun -> Akun Saya -> Merchant Key-Salt.";
$lang['Payumoney.test_mode'] = "Mode Sandbox";
$lang['Payumoney.test_mode_note'] = "Mengaktifkan opsi ini akan menggunakan kotak pasir Payumoney. Hanya aktifkan opsi ini jika Anda menguji dengan akun kotak pasir Payumoney.";
$lang['Payumoney.buildprocess.submit'] = "Bayar melalui Payumoney";
$lang['Payumoney.!error.merchant_key.valid'] = "Harap masukkan kunci pedagang yang valid.";
$lang['Payumoney.!error.merchant_salt.valid'] = "Harap masukkan Salt yang valid.";
$lang['Payumoney.!error.auth_header.valid'] = "Harap masukkan header otorisasi yang valid.";
$lang['Payumoney.!error.key.valid'] = "Kunci pedagang tidak valid.";
$lang['Payumoney.!error.invalid_token.response'] = "Payumoney merespons dengan token yang tidak valid.";
$lang['Payumoney.description'] = "Di India, PayU melayani lebih dari 4.50.000+ pedagang dengan lebih dari 100+ metode pembayaran dan merupakan mitra pembayaran pilihan untuk hampir 60% pedagang e-niaga";
?>
