<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Blesta2_5.!error.host.invalid'] = "Host Basis Data diperlukan.";
$lang['Blesta2_5.!error.database.invalid'] = "Nama Basis Data wajib diisi.";
$lang['Blesta2_5.!error.user.invalid'] = "Pengguna Basis Data diperlukan.";
$lang['Blesta2_5.!error.pass.invalid'] = "Password Database diperlukan.";
$lang['Blesta2_5.!error.key.invalid'] = "Diperlukan AESKEY yang valid.";
$lang['Blesta2_5.settings.host'] = "Tuan Rumah Basis Data";
$lang['Blesta2_5.settings.database'] = "Nama Basis Data";
$lang['Blesta2_5.settings.user'] = "Pengguna Basis Data";
$lang['Blesta2_5.settings.pass'] = "Kata Sandi Basis Data";
$lang['Blesta2_5.settings.key'] = "AESKEY";
$lang['Blesta2_5.settings.key.info'] = "Masukkan nilai definisi AESKEY di /inc/config.php. Panjangnya harus 32 karakter.";
$lang['Blesta2_5.configuration.create_packages_true'] = "Secara otomatis membuat paket yang diperlukan selama impor";
$lang['Blesta2_5.configuration.create_packages_false'] = "Memetakan paket secara manual";
$lang['Blesta2_5.configuration.local_package'] = "Paket Lokal";
$lang['Blesta2_5.configuration.remote_package'] = "Paket Remote";
$lang['Blesta2_5.configuration.no_local_packages'] = "Anda harus membuat paket sebelum dapat memetakannya.";
?>
