<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Coingate.name'] = "CoinGate.com";
$lang['Coingate.app_id'] = "ID Aplikasi";
$lang['Coingate.api_key'] = "kunci API";
$lang['Coingate.api_secret'] = "Rahasia API";
$lang['Coingate.coingate_environment'] = "CoinGate Environment";
$lang['Coingate.environment.sandbox'] = "sandbox";
$lang['Coingate.environment.live'] = "hidup";
$lang['Coingate.receive_currency'] = "Mata uang Pembayaran";
$lang['Coingate.receive_currency_note'] = "Mata uang yang ingin Anda terima saat melakukan penarikan di CoinGate. Harap dicatat bahwa jika Anda memilih EUR atau USD, Anda akan diminta untuk memverifikasi bisnis Anda sebelum melakukan penarikan di CoinGate.";
$lang['Coingate.environment_note'] = "Aktifkan \"kotak pasir\" untuk menguji di sandbox.coingate.com. Harap dicatat, bahwa untuk mode sandbox Anda harus membuat kredensial API terpisah di sandbox.coingate.com. Kredensial API yang dibuat di coingate.com tidak akan berfungsi untuk mode kotak pasir.";
$lang['Coingate.buildprocess.submit'] = "CoinGate.com";
$lang['Coingate.receive_currency.usd'] = "standardkan";
$lang['Coingate.receive_currency.btc'] = "Bitcoin ฿";
$lang['Coingate.receive_currency.eur'] = "Euros €";
$lang['Coingate.!error.app_id.empty'] = "ID APP tidak boleh kosong.";
$lang['Coingate.!error.api_key.empty'] = "Kunci API tidak boleh kosong";
$lang['Coingate.!error.api_secret.empty'] = "Rahasia API tidak boleh kosong";
$lang['Coingate.!error.payment.invalid'] = "Transaksi tidak valid dan tidak dapat diproses.";
$lang['Coingate.!error.payment.canceled'] = "Transaksi dibatalkan dan tidak dapat diproses.";
$lang['Coingate.!error.payment.expired'] = "Transaksi telah kedaluwarsa dan tidak dapat diproses.";
$lang['Coingate.!error.failed.response'] = "Transaksi tidak dapat diproses.";
?>
