<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['ClientDataPortability.name'] = "Portabilitas Data Klien";
$lang['ClientDataPortability.options.field_client_id'] = "ID Klien";
$lang['ClientDataPortability.!error.client_id'] = "ID Klien tidak valid.";
$lang['ClientDataPortability.!tooltip.client_id'] = "Ini adalah ID klien internal yang ditampilkan di URL saat Anda melihat profil klien.";
?>
