<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminCompanyEmails.templates.Thesslstore.expiration_reminder_name'] = "Pengingat Sertifikat SSL Kadaluarsa";
$lang['AdminCompanyEmails.templates.Thesslstore.expiration_reminder_desc'] = "Pemberitahuan dikirim sebelum 30 hari dari Tanggal kedaluwarsa sertifikat.";
?>
