<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PayJunction.name'] = "PayJunction";
$lang['PayJunction.api_key'] = "API Key";
$lang['PayJunction.user_name'] = "Nama pengguna";
$lang['PayJunction.password'] = "Kata sandi";
$lang['PayJunction.test_mode'] = "Mode pengembang";
$lang['PayJunction.api_key_note'] = "Masukkan kunci API dari akun PayJunction Anda.";
$lang['PayJunction.user_name_note'] = "Ketik username PayJunction anda. ";
$lang['PayJunction.password_note'] = "Masukkan kata sandi akun PayJunction Anda.";
$lang['PayJunction.test_mode_note'] = "Mengaktifkan Mode Pengembang maka akan memposting transaksi ke PayJunction Labs mode demo. Anda harus menggunakan username dan password demo, serta Labs API Key anda, untuk menggunakan mode Developer.";
$lang['PayJunction.!error.api_key.empty'] = "Harap masukkan Kunci API yang valid.";
$lang['PayJunction.!error.user_name.empty'] = "Silakan masukkan nama pengguna akun Anda.";
$lang['PayJunction.!error.password.empty'] = "Masukkan password akun Anda.";
$lang['PayJunction.!error.test_mode.valid'] = "Mode Pengembang harus disetel ke 'benar' jika diberikan.";
$lang['PayJunction.description'] = "PayJunction memproses \$4 miliar per tahun dan berkembang pesat. Teknologinya sangat cocok untuk bisnis multi-lokasi dan multi-departemen yang memproses \$10.000 atau lebih dalam volume kartu kredit bulanan";
?>