<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PaypalPaymentsStandard.name'] = "PayPal (Pembayaran Standar)";
$lang['PaypalPaymentsStandard.account_id'] = " Akun Email PayPal";
$lang['PaypalPaymentsStandard.page_style'] = "Nama Gaya Halaman";
$lang['PaypalPaymentsStandard.page_style_note'] = "Nama Gaya Halaman dari tema halaman pembayaran khusus yang Anda buat di PayPal. Biarkan kosong untuk gaya halaman default.";
$lang['PaypalPaymentsStandard.dev_mode'] = "Mode pengembang";
$lang['PaypalPaymentsStandard.dev_mode_note'] = "Mengaktifkan opsi ini akan mengeposkan transaksi ke lingkungan PayPal Sandbox. Hanya aktifkan opsi ini jika Anda menguji dengan akun PayPal Sandbox.";
$lang['PaypalPaymentsStandard.api_username'] = "Nama Pengguna API";
$lang['PaypalPaymentsStandard.api_username_note'] = "Ini, serta API Password dan API Signature, diperlukan untuk memproses pengembalian uang melalui PayPal.";
$lang['PaypalPaymentsStandard.api_password'] = "API Sandi";
$lang['PaypalPaymentsStandard.api_signature'] = "API Signature";
$lang['PaypalPaymentsStandard.pay_type'] = "Opsi Pembayaran";
$lang['PaypalPaymentsStandard.pay_type_onetime'] = "Hanya satu kali pembayaran";
$lang['PaypalPaymentsStandard.pay_type_subscribe'] = "Hanya Pembayaran Berlangganan";
$lang['PaypalPaymentsStandard.pay_type_both'] = "Pembayaran satu kali dan berlangganan bila memungkinkan";
$lang['PaypalPaymentsStandard.buildprocess.submit'] = "Membayar dengan PayPal";
$lang['PaypalPaymentsStandard.!error.account_id.valid'] = "Anda harus memasukan alamat email yang valid.";
$lang['PaypalPaymentsStandard.!error.dev_mode.valid'] = "Mode pengembang harus diatur ke \"true\" jika diberikan.";
$lang['PaypalPaymentsStandard.description'] = "Standar Pembayaran PayPal adalah salah satu cara termudah untuk menerima pembayaran kartu kredit dan PayPal secara online dengan aman";
?>