<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Apnscp.module_row.name'] = "Server";
$lang['Apnscp.module_row_plural.name'] = "Server";
$lang['Apnscp.module_group.name'] = "Grup Server";
$lang['Apnscp.tab_stats'] = "Statistik";
$lang['Apnscp.tab_client_stats'] = "Statistik";
$lang['Apnscp.tab_client_actions'] = "Tindakan";
$lang['Apnscp.add_module_row'] = "Tambahkan server";
$lang['Apnscp.add_module_group'] = "Tambahkan Grup Server";
$lang['Apnscp.manage.module_rows_title'] = "Server";
$lang['Apnscp.manage.module_groups_title'] = "Grup Server";
$lang['Apnscp.manage.module_rows_heading.name'] = "Label Server";
$lang['Apnscp.manage.module_rows_heading.hostname'] = "Nama host";
$lang['Apnscp.manage.module_rows_heading.accounts'] = "Akun";
$lang['Apnscp.manage.module_rows_heading.options'] = "Pilihan";
$lang['Apnscp.manage.module_groups_heading.name'] = "Nama grup";
$lang['Apnscp.manage.module_groups_heading.servers'] = "Jumlah Server";
$lang['Apnscp.manage.module_groups_heading.options'] = "Pilihan";
$lang['Apnscp.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Apnscp.manage.module_rows.edit'] = "Sunting";
$lang['Apnscp.manage.module_groups.edit'] = "Sunting";
$lang['Apnscp.manage.module_rows.delete'] = "Hapus";
$lang['Apnscp.manage.module_groups.delete'] = "Hapus";
$lang['Apnscp.manage.module_rows.confirm_delete'] = "Anda yakin ingin menghapus server ini?";
$lang['Apnscp.manage.module_groups.confirm_delete'] = "Anda yakin ingin menghapus grup server ini?";
$lang['Apnscp.manage.module_rows_no_results'] = "Tidak ada server.";
$lang['Apnscp.manage.module_groups_no_results'] = "Tidak ada grup server.";
$lang['Apnscp.order_options.first'] = "Server Tidak Penuh Pertama";
$lang['Apnscp.order_options.roundrobin'] = "Distribusikan Secara Merata Antar Server";
$lang['Apnscp.add_row.basic_title'] = "Pengaturan dasar";
$lang['Apnscp.add_row.name_servers_title'] = "Nama Server";
$lang['Apnscp.add_row.notes_title'] = "Catatan";
$lang['Apnscp.add_row.name_server_btn'] = "Tambahkan Server Nama Tambahan";
$lang['Apnscp.add_row.name_server_col'] = "Nama Server";
$lang['Apnscp.add_row.name_server_host_col'] = "Nama host";
$lang['Apnscp.add_row.name_server'] = "Nama server %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Apnscp.add_row.remove_name_server'] = "Hapus";
$lang['Apnscp.add_row.add_btn'] = "Tambahkan server";
$lang['Apnscp.edit_row.basic_title'] = "Pengaturan dasar";
$lang['Apnscp.edit_row.name_servers_title'] = "Nama Server";
$lang['Apnscp.edit_row.notes_title'] = "Catatan";
$lang['Apnscp.edit_row.name_server_btn'] = "Tambahkan Server Nama Tambahan";
$lang['Apnscp.edit_row.name_server_col'] = "Nama Server";
$lang['Apnscp.edit_row.name_server_host_col'] = "Nama host";
$lang['Apnscp.edit_row.name_server'] = "Nama server %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Apnscp.edit_row.remove_name_server'] = "Menghapus";
$lang['Apnscp.edit_row.add_btn'] = "Sunting Server";
$lang['Apnscp.row_meta.server_name'] = "Label Server";
$lang['Apnscp.row_meta.host_name'] = "Nama host";
$lang['Apnscp.row_meta.port'] = "Port";
$lang['Apnscp.row_meta.default_port'] = "2083";
$lang['Apnscp.row_meta.api_key'] = "kunci API";
$lang['Apnscp.row_meta.use_ssl'] = "Gunakan SSL saat menghubungkan ke API (disarankan)";
$lang['Apnscp.row_meta.account_limit'] = "Batas Akun";
$lang['Apnscp.service_field.domain'] = "Domain";
$lang['Apnscp.service_field.username'] = "Nama pengguna";
$lang['Apnscp.service_field.password'] = "Kata sandi";
$lang['Apnscp.tab_stats.info_title'] = "Informasi";
$lang['Apnscp.tab_stats.info_heading.field'] = "Bidang";
$lang['Apnscp.tab_stats.info_heading.value'] = "Nilai";
$lang['Apnscp.tab_stats.info.disk'] = "Kuota Disk";
$lang['Apnscp.tab_stats.info.bandwidth'] = "Kuota Bandwidth";
$lang['Apnscp.tab_client_actions.change_password'] = "Ganti kata sandi";
$lang['Apnscp.tab_client_actions.field_apnscp_password'] = "Kata sandi";
$lang['Apnscp.tab_client_actions.field_password_submit'] = "Perbarui Kata Sandi";
$lang['Apnscp.tab_client_stats.info_title'] = "Informasi";
$lang['Apnscp.tab_client_stats.bandwidth_title'] = "Penggunaan Bandwidth (Bulan Hingga Tanggal)";
$lang['Apnscp.tab_client_stats.disk_title'] = "Penggunaan Disk";
$lang['Apnscp.tab_client_stats.usage'] = "(%1\$s MB/%2\$s MB)"; // %1$s is the amount of resource usage, %2$s is the resource usage limit
$lang['Apnscp.tab_client_stats.usage_unlimited'] = "(%1\$s MB/∞)"; // %1$s is the amount of resource usage
$lang['Apnscp.service_info.username'] = "Nama pengguna";
$lang['Apnscp.service_info.password'] = "Kata sandi";
$lang['Apnscp.service_info.server'] = "Server";
$lang['Apnscp.service_info.options'] = "Pilihan";
$lang['Apnscp.service_info.option_login'] = "Masuk";
$lang['Apnscp.service_field.tooltip.username'] = "Anda dapat mengosongkan nama pengguna untuk membuatnya secara otomatis.";
$lang['Apnscp.service_field.tooltip.password'] = "Anda dapat membiarkan kata sandi kosong untuk membuatnya secara otomatis.";
$lang['Apnscp.!error.server_name_valid'] = "Anda harus memasukkan Label Server.";
$lang['Apnscp.!error.host_name_valid'] = "Nama Host tampaknya tidak valid.";
$lang['Apnscp.!error.port_format'] = "Port harus berupa angka.";
$lang['Apnscp.!error.api_key_valid'] = "Kunci API tampaknya tidak valid.";
$lang['Apnscp.!error.api_key_valid_connection'] = "Sambungan ke server tidak dapat dibuat. Harap periksa untuk memastikan bahwa Hostname, API Key, dan Port sudah benar.";
$lang['Apnscp.!error.account_limit_valid'] = "Batas Akun harus dikosongkan (untuk akun tidak terbatas) atau disetel ke beberapa nilai bilangan bulat.";
$lang['Apnscp.!error.name_servers_valid'] = "Satu atau lebih dari nama server yang dimasukkan tidak valid.";
$lang['Apnscp.!error.name_servers_count'] = "Anda harus menentukan setidaknya 2 server nama.";
$lang['Apnscp.!error.api.internal'] = "Terjadi kesalahan internal, atau server tidak menanggapi permintaan.";
$lang['Apnscp.!error.module_row.missing'] = "Terjadi kesalahan internal. Baris modul tidak tersedia.";
$lang['Apnscp.!error.apnscp_domain.format'] = "Harap masukkan nama domain yang valid, mis. domain.com.";
$lang['Apnscp.!error.apnscp_domain.test'] = "Nama domain tidak boleh diawali dengan 'test'.";
$lang['Apnscp.!error.apnscp_username.format'] = "Nama pengguna hanya boleh berisi huruf atau angka, tetapi tidak boleh dimulai dengan angka.";
$lang['Apnscp.!error.apnscp_username.test'] = "Nama pengguna tidak boleh dimulai dengan 'test'.";
$lang['Apnscp.!error.apnscp_username.length'] = "Nama pengguna harus antara 1 dan 16 karakter.";
$lang['Apnscp.!error.apnscp_password.valid'] = "Kata sandi harus minimal 8 karakter.";
$lang['Apnscp.!error.apnscp_password.matches'] = "Kata Sandi dan Konfirmasi Kata Sandi tidak cocok.";
$lang['Apnscp.description'] = "Sebelumnya disebut APNSCP.";
$lang['Apnscp.name'] = "ApisCP";
$lang['Apnscp.add_row.box_title'] = "Tambahkan Server ApisCP";
$lang['Apnscp.edit_row.box_title'] = "Sunting Server ApisCP";
$lang['Apnscp.package_fields.package'] = "Paket ApisCP";
$lang['Apnscp.!error.meta[package].empty'] = "Paket ApisCP diperlukan.";
?>
