<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Alipay.name'] = "Alipay";
$lang['Alipay.merchant_email'] = "Email pedagang";
$lang['Alipay.merchant_uid'] = "UID/PID pedagang";
$lang['Alipay.signature_key'] = "Kunci Tanda Tangan";
$lang['Alipay.dev_mode'] = "Mode pengembang";
$lang['Alipay.dev_mode_note'] = "Mengaktifkan opsi ini akan memposting transaksi ke lingkungan Alipay Sandbox. Hanya aktifkan opsi ini jika Anda menguji dengan akun Alipay Sandbox.";
$lang['Alipay.buildprocess.submit'] = "Bayar dengan Alipay";
$lang['Alipay.!error.merchant_email.valid'] = "Anda harus memasukan alamat email yang valid.";
$lang['Alipay.!error.merchant_uid.valid'] = "Anda harus memasukkan Merchant UID/PID yang valid.";
$lang['Alipay.!error.signature_key.valid'] = "Anda harus memasukkan kunci tanda tangan yang valid.";
$lang['Alipay.description'] = "Salah satu platform pembayaran seluler dan online pihak ketiga terbesar di dunia. Pasar utama adalah Cina daratan";
?>