<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Centoswebpanel.name'] = "CentOS WebPanel";
$lang['Centoswebpanel.module_row'] = "Server";
$lang['Centoswebpanel.module_row_plural'] = "Server";
$lang['Centoswebpanel.module_group'] = "Grup Server";
$lang['Centoswebpanel.add_module_row'] = "Tambahkan server";
$lang['Centoswebpanel.add_module_group'] = "Tambahkan Grup Server";
$lang['Centoswebpanel.manage.module_rows_title'] = "Server";
$lang['Centoswebpanel.manage.module_groups_title'] = "Grup Server";
$lang['Centoswebpanel.manage.module_rows_heading.name'] = "Label Server";
$lang['Centoswebpanel.manage.module_rows_heading.hostname'] = "Nama host";
$lang['Centoswebpanel.manage.module_rows_heading.accounts'] = "Akun";
$lang['Centoswebpanel.manage.module_rows_heading.options'] = "Pilihan";
$lang['Centoswebpanel.manage.module_groups_heading.name'] = "Nama grup";
$lang['Centoswebpanel.manage.module_groups_heading.servers'] = "Jumlah Server";
$lang['Centoswebpanel.manage.module_groups_heading.options'] = "Pilihan";
$lang['Centoswebpanel.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Centoswebpanel.manage.module_rows.edit'] = "Sunting";
$lang['Centoswebpanel.manage.module_groups.edit'] = "Sunting";
$lang['Centoswebpanel.manage.module_rows.delete'] = "Hapus";
$lang['Centoswebpanel.manage.module_groups.delete'] = "Menghapus";
$lang['Centoswebpanel.manage.module_rows.confirm_delete'] = "Anda yakin ingin menghapus server ini?";
$lang['Centoswebpanel.manage.module_groups.confirm_delete'] = "Anda yakin ingin menghapus grup server ini?";
$lang['Centoswebpanel.manage.module_rows_no_results'] = "Tidak ada server.";
$lang['Centoswebpanel.manage.module_groups_no_results'] = "Tidak ada grup server.";
$lang['Centoswebpanel.order_options.first'] = "Server Tidak Penuh Pertama";
$lang['Centoswebpanel.order_options.roundrobin'] = "Distribusikan Secara Merata Antar Server";
$lang['Centoswebpanel.add_row.box_title'] = "Tambahkan Server CentOS WebPanel";
$lang['Centoswebpanel.add_row.basic_title'] = "Pengaturan dasar";
$lang['Centoswebpanel.add_row.name_servers_title'] = "Nama Server";
$lang['Centoswebpanel.add_row.notes_title'] = "Catatan";
$lang['Centoswebpanel.add_row.name_server_btn'] = "Tambahkan Name Server Tambahan";
$lang['Centoswebpanel.add_row.name_server_col'] = "Nama Server";
$lang['Centoswebpanel.add_row.name_server_host_col'] = "Hostname";
$lang['Centoswebpanel.add_row.name_server'] = "Nama server %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Centoswebpanel.add_row.remove_name_server'] = "Menghapus";
$lang['Centoswebpanel.add_row.add_btn'] = "Tambahkan server";
$lang['Centoswebpanel.edit_row.box_title'] = "Sunting Server CentOS WebPanel";
$lang['Centoswebpanel.edit_row.basic_title'] = "Pengaturan dasar";
$lang['Centoswebpanel.edit_row.name_servers_title'] = "Nama Server";
$lang['Centoswebpanel.edit_row.notes_title'] = "Catatan";
$lang['Centoswebpanel.edit_row.name_server_btn'] = "Tambahkan Server Nama Tambahan";
$lang['Centoswebpanel.edit_row.name_server_col'] = "Nama Server";
$lang['Centoswebpanel.edit_row.name_server_host_col'] = "Nama host";
$lang['Centoswebpanel.edit_row.name_server'] = "Nama server %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Centoswebpanel.edit_row.remove_name_server'] = "Menghapus";
$lang['Centoswebpanel.edit_row.add_btn'] = "Sunting Server";
$lang['Centoswebpanel.row_meta.server_name'] = "Label Server";
$lang['Centoswebpanel.row_meta.host_name'] = "Nama host";
$lang['Centoswebpanel.row_meta.api_key'] = "kunci API";
$lang['Centoswebpanel.row_meta.use_ssl'] = "Gunakan SSL saat menghubungkan ke API (disarankan)";
$lang['Centoswebpanel.row_meta.account_limit'] = "Batas Akun";
$lang['Centoswebpanel.package_fields.package'] = "ID Paket";
$lang['Centoswebpanel.package_fields.inode'] = "Inode Maksimum";
$lang['Centoswebpanel.package_fields.nofile'] = "File Maksimum";
$lang['Centoswebpanel.package_fields.nproc'] = "Proses Maksimum";
$lang['Centoswebpanel.service_field.domain'] = "Domain";
$lang['Centoswebpanel.service_field.username'] = "Nama pengguna";
$lang['Centoswebpanel.service_field.password'] = "Kata sandi";
$lang['Centoswebpanel.service_info.username'] = "Nama pengguna";
$lang['Centoswebpanel.service_info.password'] = "Kata sandi";
$lang['Centoswebpanel.service_info.server'] = "Server";
$lang['Centoswebpanel.service_info.options'] = "Pilihan";
$lang['Centoswebpanel.service_info.option_login'] = "Gabung";
$lang['Centoswebpanel.service_field.tooltip.username'] = "Anda dapat membiarkan nama pengguna kosong untuk diisi secara otomatis.";
$lang['Centoswebpanel.service_field.tooltip.password'] = "Anda dapat membiarkan kata sandi kosong untuk membuatnya secara otomatis.";
$lang['Centoswebpanel.!error.server_name_valid'] = "Anda harus memasukkan Label Server.";
$lang['Centoswebpanel.!error.host_name_valid'] = "Nama Host tampaknya tidak valid.";
$lang['Centoswebpanel.!error.user_name_valid'] = "Nama Pengguna tampaknya tidak valid.";
$lang['Centoswebpanel.!error.remote_api_key_valid'] = "Kunci API tampaknya tidak valid.";
$lang['Centoswebpanel.!error.remote_api_key_valid_connection'] = "Sambungan ke server tidak dapat dibuat. Harap periksa untuk memastikan bahwa Hostname dan API Key sudah benar.";
$lang['Centoswebpanel.!error.account_limit_valid'] = "Batas Akun harus dikosongkan (untuk akun tidak terbatas) atau disetel ke beberapa nilai bilangan bulat.";
$lang['Centoswebpanel.!error.name_servers_valid'] = "Satu atau lebih dari nama server yang dimasukkan tidak berlaku.";
$lang['Centoswebpanel.!error.name_servers_count'] = "Anda harus menentukan setidaknya 2 server nama.";
$lang['Centoswebpanel.!error.meta[package].empty'] = "Paket CentOS WebPanel diperlukan.";
$lang['Centoswebpanel.!error.meta[inode].valid'] = "Inode Maksimum harus berupa nilai numerik.";
$lang['Centoswebpanel.!error.meta[nofile].valid'] = "File Maksimum harus berupa nilai numerik.";
$lang['Centoswebpanel.!error.meta[nproc].valid'] = "Proses Maksimum harus berupa nilai numerik.";
$lang['Centoswebpanel.!error.api.internal'] = "Terjadi kesalahan internal, atau server tidak menanggapi permintaan.";
$lang['Centoswebpanel.!error.module_row.missing'] = "Terjadi kesalahan internal. Baris modul tidak tersedia.";
$lang['Centoswebpanel.!error.centoswebpanel_domain.format'] = "Harap masukkan nama domain yang valid, mis. domain.com.";
$lang['Centoswebpanel.!error.centoswebpanel_domain.test'] = "Nama domain tidak boleh diawali dengan 'test'.";
$lang['Centoswebpanel.!error.centoswebpanel_username.format'] = "Nama pengguna hanya boleh berisi huruf dan angka dan tidak boleh dimulai dengan angka.";
$lang['Centoswebpanel.!error.centoswebpanel_username.test'] = "Nama pengguna tidak boleh dimulai dengan 'test'.";
$lang['Centoswebpanel.!error.centoswebpanel_username.length'] = "Nama pengguna harus antara 1 dan 16 karakter.";
$lang['Centoswebpanel.!error.centoswebpanel_password.valid'] = "Kata sandi harus minimal 8 karakter.";
$lang['Centoswebpanel.!error.centoswebpanel_password.matches'] = "Kata Sandi dan Konfirmasi Kata Sandi tidak cocok.";
$lang['Centoswebpanel.row_meta.login_port'] = "Login Port";
$lang['Centoswebpanel.row_meta.default_login_port'] = "2031";
$lang['Centoswebpanel.row_meta.port'] = "API Port";
$lang['Centoswebpanel.row_meta.default_port'] = "2304";
$lang['Centoswebpanel.service_field.tooltip.domain_edit'] = "Perubahan ini tidak akan mempengaruhi CentOS Web Panel, tetapi hanya mengubah catatan lokal di Blesta.";
$lang['Centoswebpanel.service_field.tooltip.username_edit'] = "Perubahan ini tidak akan mempengaruhi CentOS Web Panel, tetapi hanya mengubah catatan lokal di Blesta.";
$lang['Centoswebpanel.!error.login_port_valid'] = "Anda harus memasukkan port login.";
$lang['Centoswebpanel.!error.port_valid'] = "Anda harus memasukkan port API.";
$lang['Centoswebpanel.!error.api'] = "Terjadi kesalahan internal, atau server tidak menanggapi permintaan.";
$lang['Centoswebpanel.description'] = "Panel kontrol Hosting Web Gratis yang dirancang untuk pengelolaan server (Dedicated & VPS) yang cepat dan mudah";
?>