<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['MaxmindV2.!error.reject.private_ip'] = "Pesanan dari IP pribadi tidak diterima.";
$lang['MaxmindV2.!error.review.private_ip'] = "Pesanan dari IP pribadi sedang ditinjau.";
$lang['MaxmindV2.!error.reject.reject_score'] = "Pesanan Anda tidak dapat diproses saat ini.";
$lang['MaxmindV2.!error.review.review_score'] = "Pesanan Anda harus ditinjau secara manual.";
$lang['MaxmindV2.!error.reject.free_email'] = "Pesanan dengan akun email gratis tidak diterima.";
$lang['MaxmindV2.!error.review.free_email'] = "Pesanan dengan akun email gratis sedang ditinjau.";
$lang['MaxmindV2.!error.reject.country_mismatch'] = "Pesanan dengan ketidakcocokan negara tidak diterima.";
$lang['MaxmindV2.!error.review.country_mismatch'] = "Pesanan dengan ketidakcocokan negara sedang ditinjau.";
$lang['MaxmindV2.!error.reject.risky_country'] = "Pesanan dari negara berisiko tidak diterima.";
$lang['MaxmindV2.!error.review.risky_country'] = "Pesanan dari negara-negara berisiko sedang ditinjau.";
$lang['MaxmindV2.!error.reject.anon_proxy'] = "Pesanan dari proxy anonim tidak diterima.";
$lang['MaxmindV2.!error.review.anon_proxy'] = "Pesanan dari proxy anonim sedang ditinjau.";
$lang['MaxmindV2.settings.tooltip.enable_js'] = "Opsi ini memasukkan kode JavaScript ke dalam semua formulir pemesanan, yang memungkinkan informasi tambahan dari pengguna dikumpulkan dan dilacak oleh MaxMind. Mengaktifkan opsi ini meningkatkan akurasi hasil.";
$lang['MaxmindV2.settings.field_server'] = "Server";
$lang['MaxmindV2.settings.field_account_id'] = "ID Akun";
$lang['MaxmindV2.settings.field_key'] = "Kunci lisensi";
$lang['MaxmindV2.settings.field_minfraud_api'] = "minFraud API";
$lang['MaxmindV2.settings.field_reject_score'] = "Skor Minimum untuk Ditolak";
$lang['MaxmindV2.settings.field_review_score'] = "Skor Minimum untuk Ditinjau";
$lang['MaxmindV2.settings.field_free_email'] = "Email Gratis";
$lang['MaxmindV2.settings.field_country_mismatch'] = "Negara Tidak Cocok Country";
$lang['MaxmindV2.settings.field_risky_country'] = "Negara Berisiko";
$lang['MaxmindV2.settings.field_anon_proxy'] = "Proksi Anonim";
$lang['MaxmindV2.settings.field_private_ip'] = "IP pribadi";
$lang['MaxmindV2.settings.field_enable_js'] = "Aktifkan Pengaya Pelacakan JavaScript";
$lang['MaxmindV2.settings.option_score'] = "minFraud Score";
$lang['MaxmindV2.settings.option_insights'] = "minFraud Insights";
$lang['MaxmindV2.settings.option_factors'] = "minFraud Factors";
$lang['MaxmindV2.settings.option_allow'] = "Mengizinkan";
$lang['MaxmindV2.settings.option_review'] = "Ulasan";
$lang['MaxmindV2.settings.option_reject'] = "Menolak";
$lang['MaxmindV2.settings.option_enable'] = "Memungkinkan";
$lang['MaxmindV2.settings.option_disable'] = "Nonaktifkan";
?>
