<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FraudLabsPro.!error.reject.reject_score'] = "Pesanan Anda tidak dapat diproses saat ini.";
$lang['FraudLabsPro.!error.review.review_score'] = "Pesanan Anda harus ditinjau secara manual.";
$lang['FraudLabsPro.!error.reject.fraudlabspro'] = "Pesanan Anda telah ditandai sebagai penipuan oleh FraudLabs Pro.";
$lang['FraudLabsPro.!error.review.fraudlabspro'] = "Pesanan Anda telah ditandai sebagai \"berpotensi penipuan\" oleh FraudLabs Pro. Ini akan ditinjau secara manual.";
$lang['FraudLabsPro.settings.field_api_key'] = "kunci API";
$lang['FraudLabsPro.settings.label_description'] = "Dapatkan FraudLabs Pro Micro Plan gratis (500 kueri/bulan) dari http://www.fraudlabspro.com/plan";
$lang['FraudLabsPro.settings.field_reject_score'] = "Skor Minimum untuk Ditolak";
$lang['FraudLabsPro.settings.field_review_score'] = "Minimal Skor untuk Review";
$lang['FraudLabsPro.settings.field_follow_flp_result'] = "Secara Otomatis Tolak/Tinjau berdasarkan rekomendasi dari FraudLabs Pro";
$lang['FraudLabsPro.settings.option_yes'] = "Ya";
$lang['FraudLabsPro.settings.option_no'] = "Tidak";
?>