<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MulticraftModule.!error.json.unavailable'] = "JSON extension diperlukan oleh modul ini.";
$lang['MulticraftModule.!error.server_name.empty'] = "Masukkan label untuk server ini.";
$lang['MulticraftModule.!error.panel_url.empty'] = "Cukup masukkan URL ke panel Multicraft Anda.";
$lang['MulticraftModule.!error.panel_api_url.empty'] = "Silahkan masukkan URL untuk Multicraft panel API Anda.";
$lang['MulticraftModule.!error.username.empty'] = "Silakan masukkan nama pengguna Multicraft Anda";
$lang['MulticraftModule.!error.key.empty'] = "Masukkan API key Anda";
$lang['MulticraftModule.!error.log_all.format'] = "Apakah akan mencatat semua permintaan API harus disetel ke 1 atau 0.";
$lang['MulticraftModule.!error.ips.match'] = "Silahkan tetapkan sebuah alamat IP untuk setiap Daemon set.";
$lang['MulticraftModule.!error.daemons.match'] = "Harap setel ID Daemon untuk setiap set alamat IP.";
$lang['MulticraftModule.!error.ips_in_use.match'] = "Silahkan tetapkan alamat IP yang digunakan 1 atau 0";
?>