<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MulticraftService.!error.internal'] = "Terjadi kesalahan internal, atau server tidak menanggapi permintaan.";
$lang['MulticraftService.!error.client'] = "Tidak ada klien ditemukan untuk membuat user Multicraft.";
$lang['MulticraftService.!error.server_id.format'] = "Server ID harus berupa angka, atau biarkan kosong.";
$lang['MulticraftService.!error.user_id.format'] = "ID pengguna harus berupa bilangan bulat, atau dibiarkan kosong.";
$lang['MulticraftService.!error.daemon_id.format'] = "Daemon ID harus integer, atau biarkan kosong.";
$lang['MulticraftService.!error.ip.format'] = "Harap masukkan alamat IP yang valid, atau biarkan kosong.";
$lang['MulticraftService.!error.port.format'] = "Harap isikan nomor port yang benar, atau biarkan kosong";
$lang['MulticraftService.service_fields.server_id'] = "Server ID";
$lang['MulticraftService.service_fields.tooltip.server_id'] = "Tetapkan ID unik Server Multicraft yang akan ditetapkan layanan ini. Biarkan kosong jika tidak.";
$lang['MulticraftService.service_fields.user_id'] = "identitas pengguna";
$lang['MulticraftService.service_fields.tooltip.user_id'] = "Atur ID unik dari Pengguna Multicraft yang mana layanan ini akan ditetapkan. atau Biarkan kosong untuk sebaliknya sebaliknya.";
$lang['MulticraftService.service_fields.daemon_id'] = "ID Daemon";
$lang['MulticraftService.service_fields.tooltip.daemon_id'] = "Tentukan ID pada Multicraft daemon yang akan ditugaskan, atau biarkan kosong";
$lang['MulticraftService.service_fields.ip'] = "Alamat IP";
$lang['MulticraftService.service_fields.tooltip.ip'] = "Nama";
$lang['MulticraftService.service_fields.port'] = "Port";
$lang['MulticraftService.service_fields.tooltip.port'] = "Atur port server Multicraft yang akan ditetapkan layanan ini. Biarkan kosong jika tidak.";
$lang['MulticraftService.service_fields.yes'] = "Ya";
$lang['MulticraftService.service_fields.no'] = "Tidak";
$lang['MulticraftService.!error.configoptions[user_players].format'] = "Apakah pemilik server dapat mengatur jumlah pemain harus diatur ke 1 atau 0.";
$lang['MulticraftService.!error.configoptions[players].format'] = "Silakan atur jumlah pemain.";
$lang['MulticraftService.!error.configoptions[memory].format'] = "Harap setel jumlah memori yang valid.";
$lang['MulticraftService.!error.configoptions[daemon_id].format'] = "Harap tetapkan daemon yang valid.";
$lang['MulticraftService.!error.configoptions[dedicated_ip].format'] = "Jika menggunakan IP dedicated harus di set ke 1 atau 0.";
?>