<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MulticraftPackage.!error.meta[server_name].format'] = "Harap menetapkan nama untuk server.";
$lang['MulticraftPackage.!error.meta[players].format'] = "Harap atur jumlah maksimum slot pemain yang diizinkan.";
$lang['MulticraftPackage.!error.meta[memory].format'] = "Silakan tetapkan jumlah maksimum memori sebagai integer dalam MB.";
$lang['MulticraftPackage.!error.meta[jardir].format'] = "Silakan pilih direktori JAR yang valid.";
$lang['MulticraftPackage.!error.meta[user_jar].format'] = "Apakah pemilik dapat memilih JAR harus diatur ke 1 atau 0.";
$lang['MulticraftPackage.!error.meta[user_name].format'] = "Apakah pemilik dapat menetapkan nama harus disetel ke 1 atau 0.";
$lang['MulticraftPackage.!error.meta[user_schedule].format'] = "Apakah pemilik dapat menjadwalkan tugas-tugas? harus diatur ke 1 atau 0.";
$lang['MulticraftPackage.!error.meta[user_ftp].format'] = "Apakah pemilik dapat memberikan akses FTP kepada orang lain harus disetel ke 1 atau 0.";
$lang['MulticraftPackage.!error.meta[user_visibility].format'] = "Apakah pemilik dapat mengubah visibilitas server harus disetel ke 1 atau 0.";
$lang['MulticraftPackage.!error.meta[default_level].format'] = "Silakan pilih peran Default yang valid.";
$lang['MulticraftPackage.!error.meta[autostart].format'] = "Apakah server secara otomatis mulai. Harus diatur ke 1 atau 0.";
$lang['MulticraftPackage.!error.meta[create_ftp].format'] = "Apakah akan membuat akun FTP harus diset 1 atau 0.";
$lang['MulticraftPackage.!error.meta[server_visibility].format'] = "Harap pilih Visibilitas Server yang valid.";
$lang['MulticraftPackage.package_fields.server_name'] = "Nama Server";
$lang['MulticraftPackage.package_fields.players'] = "Slots Pemain";
$lang['MulticraftPackage.package_fields.memory'] = "RAM server";
$lang['MulticraftPackage.package_fields.tooltip.memory'] = "Setel memori dalam MB, atau biarkan kosong untuk menggunakan jumlah default.";
$lang['MulticraftPackage.package_fields.jarfile'] = "JAR File";
$lang['MulticraftPackage.package_fields.tooltip.jarfile'] = "Biarkan kosong untuk menggunakan file JAR default.";
$lang['MulticraftPackage.package_fields.jardir'] = "Carilah guci (JARs ) di direktori berikut";
$lang['MulticraftPackage.package_fields.tooltip.jardir'] = "Jika tidak menggunakan daemon direktori JAR, Multicraft harus dijalankan pada multi-user mode.";
$lang['MulticraftPackage.package_fields.jardir_daemon'] = "Direktori Daemon JAR";
$lang['MulticraftPackage.package_fields.jardir_server'] = "direktori Server JAR";
$lang['MulticraftPackage.package_fields.jardir_server_base'] = "Direktori basis server";
$lang['MulticraftPackage.package_fields.user_jar'] = "Pemilik JAR yang Dapat Dipilih";
$lang['MulticraftPackage.package_fields.user_name'] = "Pemilik Dapat Mengatur Nama";
$lang['MulticraftPackage.package_fields.tooltip.user_name'] = "Atur apakah pemilik dapat menentukan atau mengubah nama server.";
$lang['MulticraftPackage.package_fields.user_schedule'] = "Pemilik Bisa menjadwalkan Tugas";
$lang['MulticraftPackage.package_fields.tooltip.user_schedule'] = "Menentukan apakah pemilik bisa membuat tugas terjadwal dan mengubah pengaturan penyimpanan otomatis.";
$lang['MulticraftPackage.package_fields.user_ftp'] = "Pemilik Bisa Kelola FTP";
$lang['MulticraftPackage.package_fields.tooltip.user_ftp'] = "Menentukan apakah pemilik dapat memberikan akses FTP untuk pengguna lain.";
$lang['MulticraftPackage.package_fields.user_visibility'] = "Pemilik Bisa Mengatur Visibilitas";
$lang['MulticraftPackage.package_fields.tooltip.user_visibility'] = "Menentukan apakah pemilik dapat mengubah visibilitas server dan Peran Default";
$lang['MulticraftPackage.package_fields.default_level'] = "Peran Default";
$lang['MulticraftPackage.package_fields.tooltip.default_level'] = "Pilih pemain peran mana yang akan ditetapkan saat mereka pertama kali terhubung. Gunakan Tidak Ada Akses untuk daftar putih.";
$lang['MulticraftPackage.package_fields.default_level_0'] = "Tidak ada akses";
$lang['MulticraftPackage.package_fields.default_level_10'] = "Tamu";
$lang['MulticraftPackage.package_fields.default_level_20'] = "Pengguna";
$lang['MulticraftPackage.package_fields.default_level_30'] = "moderator";
$lang['MulticraftPackage.package_fields.autostart'] = "Mulai Server";
$lang['MulticraftPackage.package_fields.tooltip.autostart'] = "Secara otomatis menyalakan server ketika Multicraft memulai ulang.";
$lang['MulticraftPackage.package_fields.create_ftp'] = "Buat Akun FTP";
$lang['MulticraftPackage.package_fields.tooltip.create_ftp'] = "Secara otomatis membuat sebuah account FTP.";
$lang['MulticraftPackage.package_fields.server_visibility'] = "Visibilitas Server";
$lang['MulticraftPackage.package_fields.tooltip.server_visibility'] = "Menetapkan visibilitas server dalam daftar server Multicraft.";
$lang['MulticraftPackage.package_fields.server_visibility_0'] = "Hanya Pemilik";
$lang['MulticraftPackage.package_fields.server_visibility_1'] = "Dengan Peran Standar";
$lang['MulticraftPackage.package_fields.server_visibility_2'] = "Pengguna dengan Peran saja";
?>