<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemGeneral.!success.basic_updated'] = "Pengaturan Dasar berhasil diperbarui!";
$lang['AdminSystemGeneral.!success.geoip_updated'] = "Pengaturan GeoIP berhasil diperbarui!";
$lang['AdminSystemGeneral.!success.maintenance_updated'] = "Pengaturan Pemeliharaan berhasil diperbarui!";
$lang['AdminSystemGeneral.!success.license_updated'] = "Kode Lisensi anda elah berhasil di update!";
$lang['AdminSystemGeneral.!success.addtype_created'] = "Jenis pembayaran \"%1\$s\" telah berhasil dibuat!"; // %1$s is the name of the payment type
$lang['AdminSystemGeneral.!success.edittype_updated'] = "Jenis pembayaran  \"%1\$s\" telah berhasil diperbarui!"; // %1$s is the name of the payment type
$lang['AdminSystemGeneral.!success.deletetype_deleted'] = "The jenis pembayaran \"%1\$s\" telah terhapus dengan sukses!"; // %1$s is the name of the payment type
$lang['AdminSystemGeneral.basic.boxtitle_basic'] = "Dasar Pengaturan";
$lang['AdminSystemGeneral.basic.text_writable'] = "Dapat ditulis";
$lang['AdminSystemGeneral.basic.text_unwritable'] = "Tidak bisa ditulisi";
$lang['AdminSystemGeneral.basic.text_day'] = "Hari";
$lang['AdminSystemGeneral.basic.text_days'] = "Hari";
$lang['AdminSystemGeneral.geoip.boxtitle_geoip'] = "GeoIP";
$lang['AdminSystemGeneral.geoip.text_setup'] = "GeoIP dapat diaktifkan di sini, memberikan fungsi layanan lokasi GeoIP untuk Blesta. Mengaktifkan itu akan memungkinkan fitur tertentu untuk mengambil manfaat dari layanan lokasi.";
$lang['AdminSystemGeneral.geoip.text_database_exists'] = "%1\$s ada."; // %1$s is a file system path to the GeoIP database file
$lang['AdminSystemGeneral.geoip.text_database_not_exists'] = "%1\$s tidak ada."; // %1$s is a file system path to the GeoIP database file
$lang['AdminSystemGeneral.geoip.field_geoip_enabled'] = "Aktifkan GeoIP";
$lang['AdminSystemGeneral.geoip.field_geoipsubmit'] = "Pembaruan Pengaturan";
$lang['AdminSystemGeneral.maintenance.boxtitle_maintenance'] = "Pemeliharaan";
$lang['AdminSystemGeneral.license.boxtitle_license'] = "Kunci lisensi";
$lang['AdminSystemGeneral.paymenttypes.categorylink_addtype'] = "Buat Jenis Pembayaran";
$lang['AdminSystemGeneral.paymenttypes.boxtitle_types'] = "Jenis Pembayaran";
$lang['AdminSystemGeneral.paymenttypes.heading_name'] = "Nama";
$lang['AdminSystemGeneral.paymenttypes.heading_is_lang'] = "Gunakan Definisi Bahasa";
$lang['AdminSystemGeneral.paymenttypes.heading_options'] = "Pilihan";
$lang['AdminSystemGeneral.paymenttypes.option_edit'] = "Edit";
$lang['AdminSystemGeneral.paymenttypes.option_delete'] = "Hapus";
$lang['AdminSystemGeneral.paymenttypes.modal_delete'] = "Menghapus jenis pembayaran ini akan menyebabkan semua transaksi yang menggunakan jenis pembayaran ini disetel ke \"lainnya\". Yakin ingin menghapus jenis pembayaran ini?";
$lang['AdminSystemGeneral.paymenttypes.text_yes'] = "Ya";
$lang['AdminSystemGeneral.paymenttypes.text_no'] = "Tidak";
$lang['AdminSystemGeneral.paymenttypes.no_results'] = "Tidak ada jenis pembayaran.";
$lang['AdminSystemGeneral.addtype.boxtitle_addtype'] = "Buat Jenis Pembayaran";
$lang['AdminSystemGeneral.addtype.field_name'] = "Nama";
$lang['AdminSystemGeneral.addtype.field_is_lang'] = "Gunakan Definisi Bahasa";
$lang['AdminSystemGeneral.addtype.field_typesubmit'] = "Buat Jenis Pembayaran";
$lang['AdminSystemGeneral.edittype.boxtitle_edittype'] = "Sunting Jenis Pembayaran";
$lang['AdminSystemGeneral.edittype.field_name'] = "Nama";
$lang['AdminSystemGeneral.edittype.field_is_lang'] = "Gunakan Definisi Bahasa";
$lang['AdminSystemGeneral.edittype.field_typesubmit'] = "Sunting Jenis Pembayaran";
$lang['AdminSystemGeneral.basic.page_title'] = "Pengaturan > Sistem > Umum > Pengaturan Dasar";
$lang['AdminSystemGeneral.geoip.page_title'] = "Pengaturan > Sistem > Umum > Pengaturan GeoIP";
$lang['AdminSystemGeneral.maintenance.page_title'] = "Settings> System> General> Pemeliharaan";
$lang['AdminSystemGeneral.license.page_title'] = "Pengaturan > Sistem>  Umum > License Key";
$lang['AdminSystemGeneral.paymenttypes.page_title'] = "Pengaturan > Sistem> Umum > Jenis Pembayaran";
$lang['AdminSystemGeneral.addtype.page_title'] = "Pengaturan > System> General/Umum > Buat Jenis Pembayaran";
$lang['AdminSystemGeneral.edittype.page_title'] = "Pengaturan > Sistem > Umum > Edit Jenis Pembayaran";
$lang['AdminSystemGeneral.basic.text_no_log'] = "Tidak pernah memutar Log";
$lang['AdminSystemGeneral.!paymenttypes.is_lang'] = "Hanya centang kotak ini jika Anda telah menambahkan definisi bahasa untuk jenis pembayaran ini dalam file bahasa kustom.";
$lang['AdminSystemGeneral.!error.geoip_mbstring_required'] = "mbstring extension diperlukan untuk fitur ini.";
$lang['AdminSystemGeneral.paymenttypes.heading_type'] = "Jenis";
$lang['AdminSystemGeneral.!paymenttypes.type'] = "Jika diatur ke debit, transaksi yang menggunakan jenis pembayaran ini dianggap berbasis pendapatan sedangkan kredit tidak berbasis pendapatan.";
$lang['AdminSystemGeneral.addtype.field_type'] = "Jenis";
$lang['AdminSystemGeneral.edittype.field_type'] = "Tipe";
$lang['AdminSystemGeneral.!tooltip.behind_proxy'] = "Saat dicentang, Blesta akan menganggapnya berada di belakang proxy dan akan menentukan alamat IP dari header x-forwarded-for yang disediakan oleh proxy. Anda hanya boleh memeriksa pengaturan ini jika header x-forwarded-for dapat dipercaya.";
$lang['AdminSystemGeneral.basic.text_docroot'] = "Mengharapkan \"%1\$s\""; // %1$s is the absolute path to the document root directory
$lang['AdminSystemGeneral.!tooltip.license_key'] = "Ini adalah kunci lisensi Blesta Anda. Jika Anda menerima kunci lisensi baru, masukkan di sini.";
$lang['AdminSystemGeneral.!tooltip.root_web_dir'] = "Nilai ini mewakili path server lengkap ke direktori root dokumen server web (mis. /home/user/public_html/). Ini belum tentu jalur ke direktori tempat Blesta diinstal.";
$lang['AdminSystemGeneral.!tooltip.temp_dir'] = "Nilai ini mewakili jalur server lengkap ke tempat Blesta harus menulis file sementara. Direktori ini harus dapat ditulis oleh pengguna web server dan pengguna cron.";
$lang['AdminSystemGeneral.!tooltip.uploads_dir'] = "Nilai ini mewakili jalur server lengkap ke tempat Blesta harus menulis file yang diunggah. Direktori ini harus dapat ditulis oleh pengguna web server dan pengguna cron.";
$lang['AdminSystemGeneral.!tooltip.log_dir'] = "Nilai ini mewakili jalur server lengkap ke tempat Blesta harus menulis file log. Direktori ini harus dapat ditulis oleh pengguna web server dan pengguna cron.";
$lang['AdminSystemGeneral.!tooltip.log_days'] = "Kebijakan Rotasi menetapkan lama waktu untuk menyimpan sebagian besar data log perusahaan. File konfigurasi sistem dapat mengatur pengaturan penyimpanan log tambahan.";
$lang['AdminSystemGeneral.!tooltip.maintenance_mode'] = "Saat dalam mode pemeliharaan, hanya pengguna staf yang dapat menggunakan sistem. Semua pengguna lain akan diarahkan ke halaman login dan ditampilkan Alasan Pemeliharaan.";
$lang['AdminSystemGeneral.!tooltip.maintenance_reason'] = "Alasan pemeliharaan ini akan ditampilkan kepada pengguna non-staf yang mengakses sistem saat mode pemeliharaan diaktifkan.";
$lang['AdminSystemGeneral.basic.field.root_web_dir'] = "Direktori Web Root";
$lang['AdminSystemGeneral.basic.field.temp_dir'] = "Direktori Temp";
$lang['AdminSystemGeneral.basic.field.uploads_dir'] = "Direktori Unggah";
$lang['AdminSystemGeneral.basic.field.log_dir'] = "Direktori Log";
$lang['AdminSystemGeneral.basic.field.log_days'] = "Kebijakan Rotasi";
$lang['AdminSystemGeneral.basic.field.behind_proxy'] = "Instalasi saya berada di belakang proxy atau load balancer";
$lang['AdminSystemGeneral.basic.field.basicsubmit'] = "Perbarui Pengaturan";
$lang['AdminSystemGeneral.maintenance.field.maintenance_mode'] = "Aktifkan Mode Pemeliharaan";
$lang['AdminSystemGeneral.maintenance.field.maintenance_reason'] = "Alasan Pemeliharaan";
$lang['AdminSystemGeneral.maintenance.field.maintenancesubmit'] = "Perbarui Pengaturan";
$lang['AdminSystemGeneral.license.field.license_key'] = "Kunci lisensi";
$lang['AdminSystemGeneral.license.field.licensesubmit'] = "Perbarui Pengaturan";
$lang['AdminSystemGeneral.geoip.text_geolite_step_1'] = "Mendaftar untuk akun MaxMind";
$lang['AdminSystemGeneral.geoip.text_geolite_step_2'] = "Gunakan email selamat datang untuk mengatur kata sandi Anda";
$lang['AdminSystemGeneral.geoip.text_geolite_step_3'] = "Masuk ke akun Anda";
$lang['AdminSystemGeneral.geoip.text_geolite_step_4'] = "Di bawah \"GeoIP2 / GeoLite2 > Unduh File\" unduh file biner GeoLite2-City";
$lang['AdminSystemGeneral.geoip.text_geolite_step_5'] = "Unggah file itu ke instalasi Blesta Anda di jalur yang disebutkan di bawah ini";
$lang['AdminSystemGeneral.geoip.text_geolite'] = "GeoIP memerlukan database biner GeoLite City, yang dapat diunduh dari akun Anda di <a target=\"_blank\" href=\"%1\$s\">%1\$s</a>. File harus dibuka ritsletingnya dan diunggah ke:"; // %1$s is the URL to maxmind
?>