<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSettings.company.category_company'] = "Perusahaan";
$lang['AdminSettings.company.category_system'] = "Sistem";
$lang['AdminSettings.company.boxtitle_settings'] = "Pengaturan";
$lang['AdminSettings.company.heading_general'] = "Umum";
$lang['AdminSettings.company.heading_billing'] = "Penagihan/Pembayaran";
$lang['AdminSettings.company.text_billing'] = "Konfigurasikan opsi faktur dan kustomisasi, pembayaran otomatis, pemberitahuan pembayaran, dan kupon.";
$lang['AdminSettings.company.heading_emails'] = "Email";
$lang['AdminSettings.company.text_emails'] = "Konfigurasikan pengaturan email, edit templat email, dan buat dan kelola tanda tangan email.";
$lang['AdminSettings.company.heading_currencies'] = "mata uang";
$lang['AdminSettings.company.heading_clientgroups'] = "Grup Klien";
$lang['AdminSettings.company.text_clientgroups'] = "Semua klien termasuk dalam grup, yang menentukan kapan klien tersebut ditagih, ditagih, dan lainnya. Buat dan kelola grup dan pengaturan klien.";
$lang['AdminSettings.company.heading_automation'] = "Otomatisasi";
$lang['AdminSettings.company.text_automation'] = "Akses dan kontrol tugas otomatis di Blesta.";
$lang['AdminSettings.company.heading_modules'] = "Modul";
$lang['AdminSettings.company.text_modules'] = "Instal dan kelola modul, yang digunakan untuk penyediaan dan pengelolaan layanan.";
$lang['AdminSettings.company.heading_gateways'] = "Gateway Pembayaran";
$lang['AdminSettings.company.text_gateways'] = "Enable and disable merchant and non-merchant payment processors untuk penerimaan pembayaran.";
$lang['AdminSettings.company.heading_taxes'] = "Pajak";
$lang['AdminSettings.company.text_taxes'] = "Aktifkan atau nonaktifkan pajak, tetapkan Nomor Pajak/PPN, dan buat aturan pajak tunggal atau bertingkat.";
$lang['AdminSettings.company.heading_plugins'] = "Plugins";
$lang['AdminSettings.company.text_plugins'] = "Instal, hapus instalan, dan kelola plugin, yang memperluas dan menyesuaikan fungsionalitas inti Blesta.";
$lang['AdminSettings.system.category_company'] = "Perusahaan";
$lang['AdminSettings.system.category_system'] = "Sistem";
$lang['AdminSettings.system.boxtitle_settings'] = "Pengaturan";
$lang['AdminSettings.system.heading_general'] = "Umum";
$lang['AdminSettings.system.text_general'] = "Konfigurasikan pengaturan di seluruh sistem, termasuk mengaktifkan Mode Pemeliharaan, database GeoIP, atau memperbarui Kunci Lisensi Anda.";
$lang['AdminSettings.system.heading_companies'] = "Perusahaan
";
$lang['AdminSettings.system.text_companies'] = "Menambah atau memperbarui perusahaan.";
$lang['AdminSettings.system.heading_backup'] = "Cadangan";
$lang['AdminSettings.system.heading_api'] = "Akses API";
$lang['AdminSettings.system.text_api'] = "Mengontrol akses ke API instalasi ini.";
$lang['AdminSettings.system.heading_marketplace'] = "pasar";
$lang['AdminSettings.system.text_marketplace'] = "Jelajahi dan unduh plugin, modul, gateway, dan lainnya dari Blesta Marketplace.";
$lang['AdminSettings.system.heading_automation'] = "Otomatisasi";
$lang['AdminSettings.system.text_automation'] = "Tentukan informasi Cron atau Scheduled Task";
$lang['AdminSettings.system.heading_staff'] = "Staff";
$lang['AdminSettings.system.text_staff'] = "Buat atau ubah akun dan izin Staf. Staf memiliki akses ke area Admin Blesta.";
$lang['AdminSettings.system.heading_upgrade'] = "Pilihan Upgrade";
$lang['AdminSettings.system.text_upgrade'] = "Lihat upgrade informasi dan download.";
$lang['AdminSettings.system.heading_help'] = "Bantu";
$lang['AdminSettings.system.text_help'] = "Lihat bantuan untuk instalasi Blesta.";
$lang['AdminSettings.company.page_title'] = "Pengaturan";
$lang['AdminSettings.system.page_title'] = "Pengaturan";
$lang['AdminSettings.company.text_currencies'] = "Perbarui dan tambahkan mata uang, atur mata uang default, konfigurasikan multi-mata uang, dan konfigurasikan nilai tukar.";
$lang['AdminSettings.system.text_backup'] = "Konfigurasi backup otomatis menggunakan SFTP, atau Amazon S3, atau men-download backup ke komputer lokal Anda.";
$lang['AdminSettings.company.heading_lookandfeel'] = "Lihat dan rasakan";
$lang['AdminSettings.company.text_lookandfeel'] = "Sesuaikan tampilan dan nuansa dari Blesta dengan mengelola tema warna, atau memperbarui template antarmuka klien.";
$lang['AdminSettings.company.text_general'] = "Konfigurasikan pelokalan, opsi internasionalisasi, dan jenis kontak klien.";
$lang['AdminSettings.company.heading_clientoptions'] = "Opsi Klien";
$lang['AdminSettings.company.text_clientoptions'] = "Buat dan kelola bidang klien khusus dan pilih bidang klien yang diperlukan.";
$lang['AdminSettings.company.heading_messengers'] = "Messenger";
$lang['AdminSettings.company.text_messengers'] = "Instal dan kelola messenger, yang digunakan untuk notifikasi dan komunikasi.";
?>