<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemCompanies.!success.company_added'] = "Perusahaan %1\$s berhasil dibuat"; // %1$s is the name of the company
$lang['AdminSystemCompanies.!success.company_edited'] = "Perusahaan %1\$s telah berhasil diperbarui!"; // %1$s is the name of the company
$lang['AdminSystemCompanies.index.boxtitle_companies'] = "Perusahaan";
$lang['AdminSystemCompanies.index.categorylink_addcompany'] = "Tambahkan Perusahaan";
$lang['AdminSystemCompanies.index.no_results'] = "Tidak ada perusahaan.";
$lang['AdminSystemCompanies.index.text_name'] = "Nama";
$lang['AdminSystemCompanies.index.text_address'] = "Alamat";
$lang['AdminSystemCompanies.index.text_phone'] = "Telepon";
$lang['AdminSystemCompanies.index.text_options'] = "Pilihan";
$lang['AdminSystemCompanies.index.option_edit'] = "Sunting";
$lang['AdminSystemCompanies.add.boxtitle_addcompany'] = "Tambahkan Perusahaan";
$lang['AdminSystemCompanies.add.field_company'] = "Impor Pengaturan Perusahaan Dari";
$lang['AdminSystemCompanies.add.field_name'] = "Nama";
$lang['AdminSystemCompanies.add.field_hostname'] = "Nama host";
$lang['AdminSystemCompanies.add.field_address'] = "Alamat";
$lang['AdminSystemCompanies.add.field_phone'] = "Telepon";
$lang['AdminSystemCompanies.add.field_fax'] = "Fax";
$lang['AddSystemCompanies.add.field_companysubmit'] = "Buat Perusahaan";
$lang['AdminSystemCompanies.edit.boxtitle_editcompany'] = "Edit Perusahaan";
$lang['AdminSystemCompanies.edit.field_name'] = "Nama";
$lang['AdminSystemCompanies.edit.field_hostname'] = "Hostname";
$lang['AdminSystemCompanies.edit.field_address'] = "Alamat";
$lang['AdminSystemCompanies.edit.field_phone'] = "Phone";
$lang['AdminSystemCompanies.edit.field_fax'] = "Fax";
$lang['AddSystemCompanies.edit.field_companysubmit'] = "Sunting Perusahaan";
$lang['AdminSystemCompanies.index.page_title'] = "Settings> System> perusahaan";
$lang['AdminSystemCompanies.index.text_hostname'] = "Hostname";
$lang['AdminSystemCompanies.add.page_title'] = "Settings> System> perusahaan> tambah Perusahaan";
$lang['AdminSystemCompanies.edit.page_title'] = "Pengaturan > Sistem > Perusahaan > Edit Perusahaan";
$lang['AdminSystemCompanies.!success.company_deleted'] = "Perusahaan %1\$s telah berhasil dihapus!"; // %1$s is the name of the company
$lang['AdminSystemCompanies.index.option_delete'] = "Hapus";
$lang['AdminSystemCompanies.index.confirm_delete'] = "Benar-benar menghapus perusahaan ini? Segala sesuatu yang berkaitan dengan perusahaan ini akan hilang.";
$lang['AdminSystemCompanies.!tooltip.hostname'] = "Hostname harus berisi hanya nama domain, TLD, dan nomor port opsional. Misalnya, 'domain.com' atau 'subdomain.domain.com:8080'.";
?>