<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyModules.!success.installed'] = "Modul berhasil diinstal.";
$lang['AdminCompanyModules.!success.module_updated'] = "Modul berhasil diperbarui.";
$lang['AdminCompanyModules.!success.group_added'] = "Kelompok telah ditambahkan.";
$lang['AdminCompanyModules.!success.group_updated'] = "Kelompok ini berhasil diperbarui.";
$lang['AdminCompanyModules.!success.group_deleted'] = "Kelompok ini berhasil dihapus.";
$lang['AdminCompanyModules.!success.row_added'] = "%1\$s berhasil ditambahkan."; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.!success.row_updated'] = "%1\$s berhasil diperbarui."; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.!success.row_deleted'] = "%1\$s berhasil dihapus."; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.available.text_author'] = "Penulis:";
$lang['AdminCompanyModules.available.text_author_url'] = "URL penulis";
$lang['AdminCompanyModules.available.text_none'] = "Tidak ada modul yang tersedia.";
$lang['AdminCompanyModules.available.btn_install'] = "Install";
$lang['AdminCompanyModules.installed.text_author'] = "Penulis:";
$lang['AdminCompanyModules.installed.text_author_url'] = "URL penulis";
$lang['AdminCompanyModules.installed.text_none'] = "Tidak ada modul yang diinstal.";
$lang['AdminCompanyModules.installed.btn_uninstall'] = "Uninstall";
$lang['AdminCompanyModules.installed.btn_manage'] = "Mengelola";
$lang['AdminCompanyModules.installed.btn_upgrade'] = "tingkatkan";
$lang['AdminCompanyModules.installed.confirm_uninstall'] = "Apakah Anda yakin ingin menghapus modul ini?";
$lang['AdminCompanyModules.manage.boxtitle_manage'] = "Mengelola %1\$s"; // %1$s is the name of the module
$lang['AdminCompanyModules.addgroup.boxtitle_add'] = "Tambahkan %1\$s %2\$s Group"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.addgroup.btn_add'] = "Tambahkan Grup";
$lang['AdminCompanyModules.addgroup.assigned'] = "Ditugaskan %1\$s"; // %1$s is the module row noun in plural form (e.g. Servers)
$lang['AdminCompanyModules.addgroup.available'] = "Tersedia %1\$s"; // %1$s is the module row noun in plural form (e.g. Servers)
$lang['AdminCompanyModules.addgroup.text_name'] = "Nama grup";
$lang['AdminCompanyModules.addgroup.text_order'] = "Tambahkan pesanan";
$lang['AdminCompanyModules.editgroup.boxtitle_edit'] = "Edit Grup %1\$s %2\$s"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.editgroup.btn_edit'] = "Pembaruan Grup";
$lang['AdminCompanyModules.editgroup.assigned'] = "Ditugaskan %1\$s"; // %1$s is the module row noun in plural form (e.g. Servers)
$lang['AdminCompanyModules.editgroup.available'] = "Tersedia %1\$s"; // %1$s is the module row noun in plural form (e.g. Servers)
$lang['AdminCompanyModules.editgroup.text_name'] = "Nama grup";
$lang['AdminCompanyModules.editgroup.text_order'] = "Tambahkan Pesanan";
$lang['AdminCompanyModules.available.page_title'] = "Pengaturan> Perusahaan> Modul> Tersedia";
$lang['AdminCompanyModules.installed.page_title'] = "Pengaturan > Perusahaan > Modul > Terpasang";
$lang['AdminCompanyModules.manage.page_title'] = "Setelan > Perusahaan > Modul > Kelola %1\$s"; // %1$s is the name of the module
$lang['AdminCompanyModules.addgroup.page_title'] = "Settings > Perusahaan > Modul > Tambah %1\$s %2\$s Group"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.editgroup.page_title'] = "Setelan > Perusahaan > Modul > Edit Grup %1\$s %2\$s"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.addrow.page_title'] = "Pengaturan > Perusahaan > Modul > tambah %1\$s %2\$s"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.editrow.page_title'] = "Pengaturan> Perusahaan> Modul> Edit %1\$s %2\$s"; // %1$s is the module name, %2$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.available.text_version'] = "(ver %1\$s)"; // %1$s is the module's version number
$lang['AdminCompanyModules.installed.text_version'] = "(ver %1\$s)"; // %1$s is the module's version number
$lang['AdminCompanyModules.!tab.installed'] = "Terpasang";
$lang['AdminCompanyModules.!tab.available'] = "Tersedia";
$lang['AdminCompanyModules.available.boxtitle_module'] = "Modul";
$lang['AdminCompanyModules.installed.boxtitle_installed'] = "Modul";
$lang['AdminCompanyModules.addgroup.force_limits'] = "Paksa %1\$s Batas"; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.addgroup.tooltip_force_limits'] = "Menerapkan batas keras sehingga jumlah %1\$s tidak pernah melebihi batasnya."; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.editgroup.force_limits'] = "Paksa %1\$s Batas"; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.editgroup.tooltip_force_limits'] = "Menerapkan batas keras sehingga jumlah %1\$s tidak pernah melebihi batasnya."; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.!success.upgraded'] = "Modul berhasil ditingkatkan.";
$lang['AdminCompanyModules.!success.uninstalled'] = "Modul berhasil dicopot pemasangannya.";
?>