<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyGeneral.!success.localization_updated'] = "Pengaturan lokalisasi telah berhasil diperbarui.";
$lang['AdminCompanyGeneral.!success.encryption_updated'] = "Pengaturan enkripsi telah berhasil diperbarui.";
$lang['AdminCompanyGeneral.!success.contact_type_added'] = "Kontak jenis \"%1\$s\" telah berhasil ditambahkan."; // %1$s is the name of the contact type
$lang['AdminCompanyGeneral.!success.contact_type_updated'] = "Jenis kontak \"%1\$s\" telah berhasil diperbarui."; // %1$s is the name of the contact type
$lang['AdminCompanyGeneral.!success.contact_type_deleted'] = "Tipe kontak \"%1\$s\" telah berhasil dihapus."; // %1$s is the name of the contact type
$lang['AdminCompanyGeneral.localization.tz_format'] = "(UTC %1\$s) %2\$s"; // %1$s is the UTC offset, %2$s is the timezone name
$lang['AdminCompanyGeneral.international.boxtitle_international'] = "Internasionalisasi";
$lang['AdminCompanyGeneral.international.text_language'] = "Bahasa";
$lang['AdminCompanyGeneral.international.text_iso'] = "ISO 639-1, 3166-1";
$lang['AdminCompanyGeneral.international.text_options'] = "Pilihan";
$lang['AdminCompanyGeneral.international.option_install'] = "Memasang";
$lang['AdminCompanyGeneral.international.option_uninstall'] = "Uninstall";
$lang['AdminCompanyGeneral.!notice.passphrase_set'] = "PERINGATAN: passphrase telah ditetapkan. Anda diminta untuk pembayaran batch passphras secara manual. Mengubah kata sandi untuk passphrase / kosong akan menghapus persyaratan ini.";
$lang['AdminCompanyGeneral.encryption.boxtitle_encryption'] = "Enkripsi";
$lang['AdminCompanyGeneral.encryption.field_current_passphrase'] = "Private Key Passphrase Saat ini";
$lang['AdminCompanyGeneral.encryption.field_private_key_passphrase'] = "Passphrase Private Key Baru";
$lang['AdminCompanyGeneral.encryption.field_confirm_new_passphrase'] = "Konfirmasikan Kombinasi Sandi Rahasia";
$lang['AdminCompanyGeneral.encryption.field_agree'] = "Saya telah menyimpan kata sandi ini ke lokasi yang aman";
$lang['AdminCompanyGeneral.encryption.field_encryptionsubmit'] = "Perbarui Frasa Sandi";
$lang['AdminCompanyGeneral.contacttypes.categorylink_addtype'] = "Buat Jenis Kontak";
$lang['AdminCompanyGeneral.contacttypes.boxtitle_types'] = "Jenis Kontak";
$lang['AdminCompanyGeneral.contacttypes.heading_name'] = "Nama";
$lang['AdminCompanyGeneral.contacttypes.heading_define'] = "Menggunakan definisi bahasa";
$lang['AdminCompanyGeneral.contacttypes.heading_options'] = "Pilihan";
$lang['AdminCompanyGeneral.contacttypes.text_yes'] = "Ya";
$lang['AdminCompanyGeneral.contacttypes.text_no'] = "No";
$lang['AdminCompanyGeneral.contacttypes.option_edit'] = "Edit";
$lang['AdminCompanyGeneral.contacttypes.option_delete'] = "Hapus";
$lang['AdminCompanyGeneral.contacttypes.modal_delete'] = "Menghapus jenis kontak ini akan menyebabkan semua kontak yang ditetapkan untuk jenis ini ditempatkan ke dalam jenis \"Penagihan\" default. Anda yakin ingin menghapus jenis kontak ini?";
$lang['AdminCompanyGeneral.addcontacttype.boxtitle_addcontacttype'] = "Buat Jenis Kontak";
$lang['AdminCompanyGeneral.addcontacttype.field_name'] = "Nama";
$lang['AdminCompanyGeneral.addcontacttype.field_is_lang'] = "Gunakan Bahasa Definisi";
$lang['AdminCompanyGeneral.addcontacttype.field_contacttypesubmit'] = "Buat Jenis Kontak";
$lang['AdminCompanyGeneral.editcontacttype.boxtitle_editcontacttype'] = "Sunting Jenis Kontak";
$lang['AdminCompanyGeneral.editcontacttype.field_name'] = "Nama";
$lang['AdminCompanyGeneral.editcontacttype.field_is_lang'] = "Gunakan Bahasa Definisi";
$lang['AdminCompanyGeneral.editcontacttype.field_contacttypesubmit'] = "Sunting Jenis Kontak";
$lang['AdminCompanyGeneral.localization.page_title'] = "Pengaturan> Perusahaan> General> Lokalisasi";
$lang['AdminCompanyGeneral.international.page_title'] = "Pengaturan> Perusahaan> Umum> Internasionalisasi";
$lang['AdminCompanyGeneral.encryption.page_title'] = "Pengaturan > Perusahaan > Umum > Enkripsi";
$lang['AdminCompanyGeneral.contacttypes.page_title'] = "Pengaturan > Perusahaan > Umum > Jenis Kontak";
$lang['AdminCompanyGeneral.addcontacttype.page_title'] = "Pengaturan > Perusahaan > Umum > Buat Jenis Kontak";
$lang['AdminCompanyGeneral.editcontacttype.page_title'] = "Settings > Company > General > Edit Contact Type";
$lang['AdminCompanyGeneral.!contacttypes.is_lang'] = "Hanya centang kotak ini jika Anda telah menambahkan definisi bahasa untuk jenis kontak ini dalam file bahasa kustom.";
$lang['AdminCompanyGeneral.!success.language_installed'] = "Bahasa %1\$s telah berhasil diinstal."; // %1$s is the name of the language
$lang['AdminCompanyGeneral.!success.language_uninstalled'] = "Bahasa %1\$s telah berhasil dihapus."; // %1$s is the name of the language
$lang['AdminCompanyGeneral.!notice.international_languages'] = "Sebuah proyek terjemahan crowdsourced ada di translate.blesta.com. Anda dapat berkontribusi dan download terjemahan bahasa ada. Untuk menginstal, unzip isi file ke direktori instalasi Blesta Anda. Kemudian, refresh halaman ini, dan klik Install Link.";
$lang['AdminCompanyGeneral.international.confirm_install'] = "Apakah Anda yakin ingin menginstal bahasa %1\$s?"; // %1$s is the name of the language
$lang['AdminCompanyGeneral.international.confirm_uninstall'] = "Apakah Anda yakin ingin menghapus bahasa  %1\$s? Bahasa ini akan dihapus dan semua template email dalam bahasa ini akan dihapus secara permanen."; // %1$s is the name of the language
$lang['AdminCompanyGeneral.contacttypes.no_results'] = "Tidak ada Jenis Kontak.";
$lang['AdminCompanyGeneral.!notice.passphrase'] = "PERINGATAN: Menetapkan passphrase akan mencegah rekening pembayaran disimpan secara lokal dari yang otomatis diproses. Anda akan diminta secara manual untuk pembayaran batch dengan memasukkan passphrase Anda. Untuk informasi lebih lanjut mengenai fitur ini, silakan berkonsultasi panduan manual.";
$lang['AdminCompanyGeneral.localization.boxtitle_localization'] = "Lokalisasi";
$lang['AdminCompanyGeneral.!success.marketing_updated'] = "Pengaturan untuk marketing berhasil diubah.";
$lang['AdminCompanyGeneral.marketing.boxtitle_marketing'] = "Pemasaran";
$lang['AdminCompanyGeneral.marketing.field_show_receive_email_marketing'] = "Hadirkan klien dengan opsi untuk ikut serta/tidak ikut pemasaran email";
$lang['AdminCompanyGeneral.marketing.field_submit'] = "Perbarui Pengaturan";
$lang['AdminCompanyGeneral.!tooltip.language'] = "Bahasa default yang digunakan oleh sistem. Untuk menambahkan lebih banyak bahasa, lihat Pengaturan internasionalisasi.";
$lang['AdminCompanyGeneral.!tooltip.client_set_lang'] = "Saat dicentang, klien dapat memilih bahasa mereka sendiri untuk digunakan dari yang tersedia di sistem.";
$lang['AdminCompanyGeneral.!tooltip.calendar_begins'] = "Setel hari mulai mingguan kalender.";
$lang['AdminCompanyGeneral.!tooltip.timezone'] = "Ini adalah zona waktu sistem tempat konversi tanggal dan waktu akan diformat.";
$lang['AdminCompanyGeneral.!tooltip.date_format'] = "Mengatur format tanggal. Format ini digunakan saat menampilkan tanggal. Silakan merujuk ke manual php untuk opsi yang tersedia.";
$lang['AdminCompanyGeneral.!tooltip.datetime_format'] = "Mengatur format tanggal dan waktu. Format ini digunakan saat menampilkan tanggal dan waktu. Silakan merujuk ke manual php untuk opsi yang tersedia.";
$lang['AdminCompanyGeneral.!tooltip.country'] = "Ini adalah negara yang dipilih secara default pada formulir yang relevan.";
$lang['AdminCompanyGeneral.localization.field.language'] = "Bahasa Bawaan";
$lang['AdminCompanyGeneral.localization.field.setlanguage'] = "Klien dapat mengatur Bahasa";
$lang['AdminCompanyGeneral.localization.field.calendar'] = "Hari Mulai Kalender";
$lang['AdminCompanyGeneral.localization.field.sunday'] = "Minggu";
$lang['AdminCompanyGeneral.localization.field.monday'] = "Senin";
$lang['AdminCompanyGeneral.localization.field.timezone'] = "Zona waktu";
$lang['AdminCompanyGeneral.localization.field.dateformat'] = "Format tanggal";
$lang['AdminCompanyGeneral.localization.field.datetimeformat'] = "Format Tanggal Waktu";
$lang['AdminCompanyGeneral.localization.field.country'] = "Negara Default";
$lang['AdminCompanyGeneral.localization.field.localizationsubmit'] = "Perbarui Pengaturan";
$lang['AdminCompanyGeneral.!error.captcha_gd'] = "Ekstensi GD diperlukan untuk menghasilkan captcha internal.";
$lang['AdminCompanyGeneral.!success.smartsearch_updated'] = "Pengaturan Pencarian Cerdas telah berhasil diperbarui.";
$lang['AdminCompanyGeneral.!success.humanverification_updated'] = "Pengaturan verifikasi manusia telah berhasil diperbarui.";
$lang['AdminCompanyGeneral.!tooltip.captcha'] = "Ini adalah captcha yang digunakan secara default, Captcha Internal memerlukan ekstensi GD.";
$lang['AdminCompanyGeneral.smartsearch.boxtitle_smartsearch'] = "Pencarian cerdas";
$lang['AdminCompanyGeneral.smartsearch.field_client_search'] = "Pencarian Klien";
$lang['AdminCompanyGeneral.smartsearch.field_invoice_search'] = "Pencarian Faktur";
$lang['AdminCompanyGeneral.smartsearch.field_transaction_search'] = "Pencarian Transaksi";
$lang['AdminCompanyGeneral.smartsearch.field_service_search'] = "Pencarian Layanan";
$lang['AdminCompanyGeneral.smartsearch.field_package_search'] = "Pencarian Paket";
$lang['AdminCompanyGeneral.smartsearch.field_submit'] = "Perbarui Pengaturan";
$lang['AdminCompanyGeneral.humanverification.boxtitle_humanverification'] = "Verifikasi Manusia";
$lang['AdminCompanyGeneral.humanverification.field_captcha'] = "Captcha";
$lang['AdminCompanyGeneral.humanverification.field_captcha_none'] = "Tidak ada";
$lang['AdminCompanyGeneral.humanverification.field_captcha_recaptcha'] = "reCaptcha";
$lang['AdminCompanyGeneral.humanverification.field_captcha_internalcaptcha'] = "Captcha Internal";
$lang['AdminCompanyGeneral.humanverification.field_recaptcha_pub_key'] = "Kunci Situs reCaptcha";
$lang['AdminCompanyGeneral.humanverification.field_recaptcha_shared_key'] = "Kunci Bersama reCaptcha";
$lang['AdminCompanyGeneral.humanverification.field_submit'] = "Perbarui Pengaturan";
$lang['AdminCompanyGeneral.humanverification.heading_captcha_provider'] = "Penyedia Captcha";
$lang['AdminCompanyGeneral.humanverification.heading_enabled_forms'] = "Formulir yang Diaktifkan";
$lang['AdminCompanyGeneral.humanverification.field_captcha_enabled_forms_admin_login'] = "Admin Login";
$lang['AdminCompanyGeneral.humanverification.field_captcha_enabled_forms_client_login'] = "Login Klien";
$lang['AdminCompanyGeneral.humanverification.field_captcha_enabled_forms_admin_login_reset'] = "Admin Setel Ulang Kata Sandi Saya";
$lang['AdminCompanyGeneral.humanverification.field_captcha_enabled_forms_client_login_reset'] = "Klien Atur Ulang Kata Sandi Saya";
$lang['AdminCompanyGeneral.humanverification.field_captcha_enabled_forms_client_login_forgot'] = "Klien Lupa Nama Pengguna Saya";
?>