<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyAutomation.!success.automation_updated'] = "Pengaturan Otomasi berhasil diperbarui!";
$lang['AdminCompanyAutomation.index.boxtitle_automation'] = "Otomatisasi";
$lang['AdminCompanyAutomation.index.field_automationsubmit'] = "Perbaharui Pengaturan";
$lang['AdminCompanyAutomation.index.field_enabled'] = "Diaktifkan";
$lang['AdminCompanyAutomation.index.text_interval'] = "Selang";
$lang['AdminCompanyAutomation.index.text_starttime'] = "Waktu mulai";
$lang['AdminCompanyAutomation.index.text_task_lastran'] = "Tugas Terakhir Berlari:";
$lang['AdminCompanyAutomation.index.no_results'] = "Tidak ada tugas cron.";
$lang['AdminCompanyAutomation.index.no_cron_lastran'] = "Tak pernah";
$lang['AdminCompanyAutomation.index.text_cron_last_ran'] = "Cron terakhir berlari pada %1\$s."; // %1$s is the date that the cron last ran
$lang['AdminCompanyAutomation.index.text_cron_never_ran'] = "Cron tidak pernah berjalan.";
$lang['AdminCompanyAutomation.getintervals.text_minutes'] = "menit";
$lang['AdminCompanyAutomation.getintervals.text_hour'] = "jam";
$lang['AdminCompanyAutomation.getintervals.text_hours'] = "jam";
$lang['AdminCompanyAutomation.index.page_title'] = "Pengaturan > Perusahaan > Otomatisasi";
$lang['AdminCompanyAutomation.!success.task_cleared'] = "Tugas cron telah dihapus.";
$lang['AdminCompanyAutomation.index.option_clear_task'] = "Hapus Kunci Tugas";
$lang['AdminCompanyAutomation.index.confirm_clear_task'] = "Anda yakin ingin menghapus kunci tugas cron ini? Jika tugas ini terus menerus terhenti, mungkin ada masalah yang lebih serius. Coba jalankan cron secara manual, atau periksa kesalahan log cron untuk menentukan penyebabnya.";
?>