<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientPay.!success.payment_processed'] = "Pembayaran berhasil diproses untuk %1\$s. Nomor Transaksi: %2\$s"; // %1$s is the payment amount, %2$s is the transaction number
$lang['ClientPay.!error.invalid_amount'] = "Jumlah pembayaran lainnya mungkin tidak negatif.";
$lang['ClientPay.!error.payment_amounts'] = "Silakan pilih faktur untuk membayar atau masukkan jumlah pembayaran yang lain.";
$lang['ClientPay.index.page_title'] = "Klien %1\$s Membayar"; // %1$s is the client ID
$lang['ClientPay.index.boxtitle_pay'] = "Melakukan Pembayaran";
$lang['ClientPay.index.field_submit'] = "Terus";
$lang['ClientPay.multipleinvoices.text_amount'] = "Jumlah Bayar";
$lang['ClientPay.multipleinvoices.text_due'] = "Jumlah yang harus dibayar";
$lang['ClientPay.multipleinvoices.text_invoice'] = "Faktur #";
$lang['ClientPay.multipleinvoices.text_datedue'] = "Tanggal jatuh tempo";
$lang['ClientPay.multipleinvoices.no_results'] = "Tidak ada faktur dalam mata uang ini.";
$lang['ClientPay.received.page_title'] = "Klien %1\$s Pembayaran Diterima"; // %1$s is the client ID
$lang['ClientPay.received.boxtitle_received'] = "Terima Kasih!";
$lang['ClientPay.received.statement'] = "Pembayaran Anda sedang diproses.";
$lang['ClientPay.setcontactview.text_none'] = "Tak satupun";
$lang['ClientPay.index.field_credit'] = "Jumlah Pembayaran Lainnya";
$lang['ClientPay.method.page_title'] = "Cara Pembayaran Klien %1\$s"; // %1$s is the client ID
$lang['ClientPay.method.boxtitle_method'] = "Melakukan pembayaran";
$lang['ClientPay.method.field_useaccount'] = "Gunakan Rekening Pembayaran";
$lang['ClientPay.method.field_newdetails'] = "Detail Pembayaran Baru";
$lang['ClientPay.method.field_paymentaccount'] = "%1\$s %2\$s - %3\$s x%4\$s"; // %1$s is the account first name, %2$s is the account last name, %3$s is the account type (card type or bank account type), %4$s is the last 4 of the account
$lang['ClientPay.method.field_paymentaccount_cc'] = "Akun Kartu Kredit";
$lang['ClientPay.method.field_paymentaccount_autodebit'] = "(Auto Debit) %1\$s %2\$s - %3\$s x%4\$s"; // %1$s is the account first name, %2$s is the account last name, %3$s is the account type (card type or bank account type), %4$s is the last 4 of the account
$lang['ClientPay.method.field_paymentaccount_ach'] = "Akun ACH";
$lang['ClientPay.method.field_submit'] = "Tinjau dan Konfirmasi";
$lang['ClientPay.confirm.page_title'] = "Klien %1\$s Mengkonfirmasi Pembayaran"; // %1$s is the client ID
$lang['ClientPay.confirm.boxtitle_confirm'] = "Konfirmasi Pembayaran";
$lang['ClientPay.confirm.payment_details'] = "Detil Pembayaran";
$lang['ClientPay.confirm.account_exp'] = "berakhir pada %1\$s"; // %1$s is the date the credit card expires
$lang['ClientPay.confirm.total'] = "Total:";
$lang['ClientPay.confirm.field_submit'] = "Kirim Pembayaran";
$lang['ClientPay.confirm.field_edit'] = "Mengedit Pembayaran";
$lang['ClientPay.confirm.description_invoice'] = "Faktur #%1\$s"; // %1$s is the invoice number
$lang['ClientPay.confirm.description_invoice_separator'] = ",";
$lang['ClientPay.confirm.description_invoice_number'] = "#%1\$s"; // %1$s is the invoice number
$lang['ClientPay.confirm.description_credit'] = "Kredit Pembayaran";
$lang['ClientPay.!error.invalid_details'] = "Silakan pilih opsi pembayaran.";
$lang['ClientPay.method.heading_other_payment_options'] = "Opsi Pembayaran Lainnya";
$lang['ClientPay.method.heading_payment_options'] = "Opsi pembayaran";
$lang['ClientPay.method.no_options'] = "Tidak ada opsi pembayaran yang tersedia.";
$lang['ClientPay.!success.credit_full_processed'] = "Kredit yang tersedia telah diterapkan.";
$lang['ClientPay.!success.credit_partial_processed'] = "Kredit yang tersedia telah diterapkan, tetapi saldo masih ada. Silakan lengkapi transaksi ini dengan membayar sisanya di bawah ini.";
$lang['ClientPay.method.field_apply_credit'] = "Terapkan Kredit (%1\$s Available)"; // %1$s is the amount of available credit that may be used
$lang['ClientPay.method.field_credit_submit'] = "Terapkan Kredit dan Lanjutkan";
$lang['ClientPay.multipleinvoices.text_edit_amounts'] = "Lakukan Pembayaran Sebagian Sebagai gantinya";
$lang['ClientPay.method.heading_invoice'] = "Faktur #%1\$s"; // %1$s is the invoice ID code
$lang['ClientPay.method.invoice_description'] = "Deskripsi";
$lang['ClientPay.method.invoice_quantity'] = "Kuantitas";
$lang['ClientPay.method.invoice_amount'] = "Jumlah";
$lang['ClientPay.!error.invoice_voided'] = "Faktur ini telah dibatalkan dan tidak dapat dibayar.";
$lang['ClientPay.received.transaction_id'] = "ID transaksi";
$lang['ClientPay.received.amount'] = "Jumlah";
$lang['ClientPay.received.invoices'] = "Faktur #";
$lang['ClientPay.!success.invoice_paid'] = "Faktur ini sebelumnya telah dibayar.";
$lang['ClientPay.confirm.account_info_type'] = "%1\$s"; // %1$s is the account type (Credit Card or ACH)
$lang['ClientPay.confirm.account_info'] = "%1\$s (%2\$s) berakhir dengan %3\$s"; // %1$s is the account type (Credit Card or ACH), %2$s is the type (Savings, Checking, MasterCard, etc.) and %3$s is the last 4 digits of the account
$lang['ClientPay.!info.unverified_email'] = "Tautan telah dikirim ke alamat email yang Anda berikan. Silakan klik link di email untuk memverifikasi alamat email Anda sebelum melanjutkan untuk melakukan pembayaran.";
$lang['ClientPay.!info.unverified_email_button'] = "Mengirim ulang email verifikasi";
$lang['ClientPay.received.text_try_again'] = "Coba lagi";
?>