<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientGroups.!error.name.empty'] = "Harap tentukan nama grup.";
$lang['ClientGroups.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['ClientGroups.!error.color.length'] = "Panjang warna tidak boleh melebihi 16 karakter.";
$lang['ClientGroups.!error.group_id.exists'] = "ID grup klien tidak valid.";
?>