<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientDialog.confirm.text_yes'] = "Ya";
$lang['ClientDialog.confirm.text_no'] = "Tidak";
$lang['ClientDialog.password.title'] = "Buat Kata Sandi";
$lang['ClientDialog.password.field_modal_password'] = "Password";
$lang['ClientDialog.password.field_modal_password_copied'] = "Saya telah menyalin kata sandi ini ke tempat yang aman";
$lang['ClientDialog.password.btn_generate'] = "Menghasilkan";
$lang['ClientDialog.password.btn_cancel'] = "Batalkan";
$lang['ClientDialog.password.btn_use_password'] = "Gunakan Kata Sandi";
?>