<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Companies.!error.company_id.in_use'] = "Perusahaan sedang dalam digunakan sehingga tidak dapat dihapus.";
$lang['Companies.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['Companies.!error.name.empty'] = "Harap masukkan nama.";
$lang['Companies.!error.name.length'] = "panjang Nama tidak boleh melebihi 64 karakter.";
$lang['Companies.!error.hostname.unique'] = "Hostname telah diambil oleh perusahaan lain.";
$lang['Companies.!error.phone.length'] = "Panjang telepon tidak boleh melebihi 64 karakter.";
$lang['Companies.!error.fax.length'] = "Panjang faks tidak boleh melebihi 64 karakter.";
$lang['Companies.!error.private_key_passphrase.valid'] = "Frasa sandi yang Anda masukkan tidak valid.";
$lang['Companies.!error.inv_format.format'] = "Format Faktur tidak boleh bertentangan dengan Format Konsep Faktur.";
$lang['Companies.!error.inv_format.contains'] = "Format Faktur harus berisi {num}.";
$lang['Companies.!error.inv_draft_format.format'] = "Format Draft Faktur tidak dapat bertentangan dengan Format Faktur.";
$lang['Companies.!error.inv_draft_format.contains'] = "Format Draft Faktur harus berisi {num}.";
$lang['Companies.!error.inv_start.number'] = "Nilai Awal Faktur harus berupa angka.";
$lang['Companies.!error.inv_increment.number'] = "Faktur Kenaikan Nilai harus berupa angka.";
$lang['Companies.!error.inv_pad_size.number'] = "Ukuran Padding Faktur harus berupa angka.";
$lang['Companies.!error.inv_pad_str.length'] = "Karakter Padding Faktur harus satu karakter.";
$lang['Companies.!error.hostname.valid'] = "Masukkan hostname yang valid.";
$lang['Companies.!error.hostname.length'] = "Hostname tidak boleh lebih dari 255 karakter";
$lang['Companies.!error.quota.allowed'] = "Tidak ada lisensi perusahaan addon yang tersedia. Silakan masuk ke akun Anda di account.blesta.com atau hubungi bagian penjualan untuk membeli lisensi perusahaan tambahan.";
$lang['Companies.!error.inv_proforma_format.format'] = "Format Faktur Pro Forma tidak boleh bertentangan dengan Format Faktur Draft.";
$lang['Companies.!error.inv_proforma_format.contains'] = "Format Faktur Pro Forma harus berisi {num}.";
$lang['Companies.!error.inv_proforma_start.number'] = "Nilai permulaan faktur pro forma harus berupa angka.";
?>