<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Contacts.!error.client_id.exists'] = "ID klien tidak valid.";
$lang['Contacts.!error.user_id.exists'] = "ID pengguna tidak valid.";
$lang['Contacts.!error.contact_type.format'] = "Jenis kontak tidak valid.";
$lang['Contacts.!error.contact_type_id.format'] = "ID jenis kontak tidak valid.";
$lang['Contacts.!error.first_name.empty'] = "Masukkan nama pertama.";
$lang['Contacts.!error.last_name.empty'] = "Masukkan nama terakhir.";
$lang['Contacts.!error.title.length'] = "Panjang judul tidak boleh melebihi 64 karakter.";
$lang['Contacts.!error.company.length'] = "Panjang perusahaan tidak boleh melebihi 128 karakter.";
$lang['Contacts.!error.email.format'] = "Alamat email salah.";
$lang['Contacts.!error.state.length'] = "Panjang negara tidak boleh melebihi 3 karakter.";
$lang['Contacts.!error.state.country_exists'] = "Silakan pilih negara yang sesuai dengan negara yang dipilih.";
$lang['Contacts.!error.country.length'] = "Panjang negara tidak boleh lebih dari 3 karakter.";
$lang['Contacts.!error.contact_id.exists'] = "ID kontak tidak valid.";
$lang['Contacts.!error.number.empty'] = "Silakan masukkan nomor kontak.";
$lang['Contacts.!error.type.format'] = "Jenis tidak valid.";
$lang['Contacts.!error.location.format'] = "Lokasi tidak valid";
$lang['Contacts.!error.id.exists'] = "Nomor ID kontak tidak valid.";
$lang['Contacts.!error.company_id.format'] = "ID perusahaan tidak valid.";
$lang['Contacts.!error.name.empty'] = "Silakan masukkan nama.";
$lang['Contacts.!error.is_lang.format'] = "is_lang harus berupa angka.";
$lang['Contacts.!error.is_lang.length'] = "panjang is_lang tidak boleh lebih dari 1 karakter.";
$lang['Contacts.!error.contact_type_id.exists'] = "ID jenis kontak tidak valid.";
$lang['Contacts.getcontacttypes.primary'] = "Utama";
$lang['Contacts.getcontacttypes.billing'] = "Penagihan";
$lang['Contacts.getcontacttypes.other'] = "Lain";
$lang['Contacts.getnumbertypes.phone'] = "Telepon";
$lang['Contacts.getnumbertypes.fax'] = "Fax";
$lang['Contacts.getnumberlocations.home'] = "Home";
$lang['Contacts.getnumberlocations.work'] = "Jalan";
$lang['Contacts.getnumberlocations.mobile'] = "Mobil";
$lang['Contacts.!error.contact_type.inv_address_to'] = "Faktur sudah ditetapkan untuk ditujukan kepada kontak ini dan harus diubah sebelum memperbarui kontak ini.";
$lang['Contacts.!error.contact_id.primary'] = "Kontak klien utama tidak boleh dihapus.";
$lang['Contacts.getPermissionOptions.client_invoices'] = "Faktur";
$lang['Contacts.getPermissionOptions.client_services'] = "Jasa";
$lang['Contacts.getPermissionOptions.client_transactions'] = "Transaksi";
$lang['Contacts.getPermissionOptions.client_contacts'] = "Kontak";
$lang['Contacts.getPermissionOptions.client_accounts'] = "Akun Pembayaran";
$lang['Contacts.getPermissionOptions._invoice_delivery'] = "Pengiriman Faktur";
$lang['Contacts.getPermissionOptions._credits'] = "Kredit";
$lang['Contacts.!error.title.empty'] = "Harap masukkan judul.";
$lang['Contacts.!error.company.empty'] = "Harap masukkan perusahaan.";
$lang['Contacts.!error.city.empty'] = "Silakan masukkan kota.";
$lang['Contacts.!error.state.empty'] = "Silahkan pilih provinsi";
$lang['Contacts.!error.country.empty'] = "Silakan pilih negara.";
$lang['Contacts.!error.address1.empty'] = "Silakan masukkan baris pertama alamat Anda.";
$lang['Contacts.!error.address2.empty'] = "Silakan masukkan baris kedua alamat Anda.";
$lang['Contacts.!error.zip.empty'] = "Silakan masukkan kode pos/pos.";
$lang['Contacts.!error.email.unique'] = "Alamat email sudah diambil.";
$lang['Contacts.getPermissionOptions.client_emails'] = "Riwayat Email";
?>