<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CouponTerms.!error.coupon_id.exists'] = "Kupon yang diberikan tidak ada.";
$lang['CouponTerms.!error.term.format'] = "Harap masukkan istilah yang valid untuk setiap periode.";
$lang['CouponTerms.!error.period.valid'] = "Harap masukkan periode yang valid.";
$lang['CouponTerms.!error.term_id.exists'] = "Kode kupon yang diberikan tidak ada.";
$lang['CouponTerms.getperiods.day'] = "Hari";
$lang['CouponTerms.getperiods.week'] = "Minggu";
$lang['CouponTerms.getperiods.month'] = "Bulan";
$lang['CouponTerms.getperiods.year'] = "Tahun";
$lang['CouponTerms.getperiods.onetime'] = "Satu kali";
?>