<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['GatewayManager.!error.company_id.valid'] = "ID Perusahaan tidak valid.";
$lang['GatewayManager.!error.class.valid'] = "Kelas tidak valid.";
$lang['GatewayManager.!error.name.valid'] = "Nama tidak valid.";
$lang['GatewayManager.!error.version.valid'] = "Versi tidak valid.";
$lang['GatewayManager.!error.currencies[].exists'] = "Setidaknya satu mata uang tidak diterima oleh gateway ini.";
$lang['GatewayManager.!error.currencies[].in_use'] = "Setidaknya satu mata uang sedang digunakan oleh gateway lain.";
?>