<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MerchantGateway.!error.card_number_invalid'] = "Nomor kartu tidak valid.";
$lang['MerchantGateway.!error.card_expired'] = "Kartu telah kedaluwarsa.";
$lang['MerchantGateway.!error.routing_number_invalid'] = "Jumlah routing tidak valid.";
$lang['MerchantGateway.!error.account_number_invalid'] = "Nomor rekening tidak valid.";
$lang['MerchantGateway.!error.duplicate_transaction'] = "Sebuah transaksia ganda telah terdeteksi.";
$lang['MerchantGateway.!error.card_not_accepted'] = " Jenis Kartu yang tidak diterima.";
$lang['MerchantGateway.!error.invalid_security_code'] = "Kode keamanan tampaknya tidak valid.";
$lang['MerchantGateway.!error.address_verification_failed'] = "Alamatnya tampaknya tidak valid.";
$lang['MerchantGateway.!error.transaction_not_found'] = "Transaksi tidak valid atau tidak lagi tersedia untuk memproses tindakan itu.";
$lang['MerchantGateway.!error.general'] = "Terjadi kesalahan saat memproses permintaan dengan gateway.";
$lang['MerchantGateway.!error.unsupported'] = "Gateway tidak mendukung tindakan itu.";
?>