<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Messages.!error.message_group_id.valid'] = "ID grup pesan tidak valid.";
$lang['Messages.!error.company_id.valid'] = "ID perusahaan tidak valid.";
$lang['Messages.!error.type.valid'] = "Jenis pesan harus disetel ke \"sms\".";
$lang['Messages.!error.status.valid'] = "Status pesan harus disetel ke \"aktif\" atau \"tidak aktif\".";
$lang['Messages.!error.content.format'] = "Isi pesan harus berupa array.";
$lang['Messages.getTypes.sms'] = "SMS";
$lang['Messages.getStatusTypes.active'] = "Aktif";
$lang['Messages.getStatusTypes.inactive'] = "Tidak aktif";
?>