<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ModuleManager.!error.company_id.valid'] = "ID Perusahaan tidak valid.";
$lang['ModuleManager.!error.class.valid'] = "Kelas tidak valid.";
$lang['ModuleManager.!error.name.valid'] = "Nama tidak valid.";
$lang['ModuleManager.!error.version.valid'] = "Versi tidak valid.";
$lang['ModuleManager.!error.name.empty'] = "Anda harus menentukan nama untuk grup.";
$lang['ModuleManager.!error.module_rows[].valid'] = "Satu atau lebih dari baris yang ditentukan tidak termasuk modul ini.";
$lang['ModuleManager.!error.module_row_id.assigned_package'] = "Baris tidak dapat dihapus karena itu milik satu atau lebih paket.";
$lang['ModuleManager.!error.module_group_id.assigned_package'] = "Grup tidak dapat dihapus karena dimiliki oleh satu atau lebih paket.";
$lang['ModuleManager.!error.module_row_id.assigned_service'] = "Baris itu tidak dapat dihapus karena itu milik satu atau beberapa layanan.";
$lang['ModuleManager.!error.module_id.assigned_package'] = "Modul ini tidak dapat dihapus karena digunakan oleh satu atau lebih paket aktif";
$lang['ModuleManager.!error.module_id.assigned_service'] = "Modul tidak dapat dihapus instalasinya karena digunakan oleh satu atau lebih layanan yang tidak dibatalkan.";
$lang['ModuleManager.!error.force_limits.valid'] = "Apakah akan menerapkan batas yang ketat harus disetel ke 0 atau 1.";
$lang['ModuleManager.!error.type_id.valid'] = "Jenis ID tidak valid.";
?>