<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PackageOptionConditionSets.!error.id.exists'] = "ID kondisi opsi yang diberikan tidak ada";
$lang['PackageOptionConditionSets.!error.option_group_id.exists'] = "ID grup opsi yang diberikan tidak ada";
$lang['PackageOptionConditionSets.!error.option_id.exists'] = "ID opsi yang diberikan tidak ada";
$lang['PackageOptionConditionSets.!error.option_value_ids.exists'] = "Salah satu ID nilai opsi yang diberikan tidak ada";
?>