<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Permissions.!error.group_id.exists'] = "Kelompok yang diberikan izin tidak ada.";
$lang['Permissions.!error.alias.empty'] = "Izin harus memiliki sebuah alias.";
$lang['Permissions.!error.action.empty'] = "Izin harus memiliki tindakan.";
$lang['Permissions.!error.plugin_id.exists'] = "Plugin yang ditentukan untuk izin ini tidak ada.";
$lang['Permissions.!error.level.group_empty'] = "Tingkat harus 'staf' atau 'klien'.";
$lang['Permissions.!error.alias.group_empty'] = "Kelompok izin harus memiliki alias.";
$lang['Permissions.!error.plugin_id.group_exists'] = "Plugin yang ditentukan untuk grup izin ini tidak ada.";
$lang['Permissions.!error.name.empty'] = "Izin harus memiliki nama.";
$lang['Permissions.!error.name.group_empty'] = "Grup izin harus memiliki nama.";
?>