<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PluginManager.!error.dir.empty'] = "Silakan masuk ke direktori Plugin.";
$lang['PluginManager.!error.dir.length'] = "Panjang direktori Plugin tidak boleh melebihi 64 karakter.";
$lang['PluginManager.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['PluginManager.!error.name.empty'] = "Masukkan nama Plugin.";
$lang['PluginManager.!error.author.empty'] = "Silakan masukkan pembuat plugin.";
$lang['PluginManager.!error.version.empty'] = "Silakan masukkan versi plugin.";
$lang['PluginManager.!error.version.length'] = "Panjang versi plugin tidak boleh melebihi 16 karakter.";
$lang['PluginManager.!error.event.empty'] = "Silakan masukkan acara.";
$lang['PluginManager.!error.callback.empty'] = "Cukup masukkan callback.";
$lang['PluginManager.!error.event.exists'] = "Acara plugin tidak dapat ditemukan.";
$lang['PluginManager.!error.event.length'] = "Panjang acara tidak boleh melebihi 128 karakter.";
$lang['PluginManager.!error.level.valid'] = "Level harus diatur ke \"klien\" atau \"staf\".";
$lang['PluginManager.!error.callback.exists'] = "Panggilan balik kartu plugin tidak dapat ditemukan.";
$lang['PluginManager.!error.callback.unique'] = "Panggilan balik harus unik untuk kartu plugin ini.";
$lang['PluginManager.!error.callback_type.valid'] = "Jenis panggilan balik harus disetel ke \"nilai\" atau \"html\".";
$lang['PluginManager.!error.label.empty'] = "Tolong masukan label.";
$lang['PluginManager.!error.link.empty'] = "Masukkan tautan.";
$lang['PluginManager.!error.background.empty'] = "Harap masukkan warna latar belakang atau URL gambar.";
$lang['PluginManager.!error.background.valid'] = "Latar belakang harus berupa URL yang valid untuk sebuah gambar.";
$lang['PluginManager.!error.background_type.valid'] = "Jenis latar belakang harus disetel ke \"warna\" atau \"gambar\".";
$lang['PluginManager.!error.text_color.empty'] = "Harap masukkan warna teks.";
?>