<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Pricings.!error.term.format'] = "Periode harus berupa angka.";
$lang['Pricings.!error.term.length'] = "Panjang periode tidak boleh melebihi 5 karakter.";
$lang['Pricings.!error.term.valid'] = "Istilah harus lebih besar dari 0.";
$lang['Pricings.!error.period.format'] = "Jenis periode tidak valid.";
$lang['Pricings.!error.price.format'] = "Harga harus berupa angka.";
$lang['Pricings.!error.setup_fee.format'] = "Biaya setup harus berupa angka.";
$lang['Pricings.!error.cancel_fee.format'] = "Biaya pembataalan harus berupa angka.";
$lang['Pricings.!error.currency.format'] = "Kode mata uang harus 3 karakter.";
$lang['Pricings.getPeriods.day'] = "Hari";
$lang['Pricings.getPeriods.week'] = "Minggu";
$lang['Pricings.getPeriods.month'] = "Bulan";
$lang['Pricings.getPeriods.year'] = "Tahun";
$lang['Pricings.getPeriods.onetime'] = "Satu kali";
$lang['Pricings.getPeriods.day_plural'] = "hari";
$lang['Pricings.getPeriods.week_plural'] = "Mingguan";
$lang['Pricings.getPeriods.month_plural'] = "Bulan";
$lang['Pricings.getPeriods.year_plural'] = "Tahun";
$lang['Pricings.getPeriods.onetime_plural'] = "Satu kali";
$lang['Pricings.!error.price_renews.format'] = "Harga perpanjangan harus berupa angka.";
$lang['Pricings.!error.price_renews.valid'] = "Harga perpanjangan tidak dapat ditetapkan untuk satu periode waktu.";
$lang['Pricings.!error.price_transfer.format'] = "Harga perpanjangan harus berupa angka.";
?>