<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SystemRequirements.!error.php.minimum'] = "versi PHP %1\$s atau lebih diperlukan. versi milik anda %2\$s."; // %1$s is the minimum version of PHP (i.e. 5.1.3), %2$s is the current version
$lang['SystemRequirements.!warning.mcrypt.recommended'] = "Ekstensi mcrypt direkomendasikan untuk kinerja yang lebih baik.";
$lang['SystemRequirements.!warning.gmp.recommended'] = "gmp extension sangat dianjurkan untuk performa yang lebih baik.";
$lang['SystemRequirements.!warning.cache_writable.recommended'] = "Untuk kinerja yang lebih baik memastikan bahwa %1\$s adalah bisa ditulis oleh webserver."; // %1$s is the absolute path to the cache directory
$lang['SystemRequirements.!warning.imap.recommended'] = "imap extension diperlukan untuk mengirim dan menerima email melalui SMTP dan IMAP.";
$lang['SystemRequirements.!warning.zlib.recommended'] = "Ekstensi zlib sangat disarankan untuk kinerja yang lebih baik.";
$lang['SystemRequirements.!warning.mbstring.recommended'] = "Ekstensi mbstring diperlukan oleh beberapa fitur opsional.";
$lang['SystemRequirements.!warning.libxml.recommended'] = "Ekstensi libxml sangat disarankan karena mungkin diperlukan untuk berinteraksi dengan beberapa sistem.";
$lang['SystemRequirements.!warning.mailparse.recommended'] = "Ekstensi mailparse diperlukan untuk mengurai email masuk.";
$lang['SystemRequirements.!error.config_writable.minimum'] = "File konfigurasi (%1\$s) dan direktori (%2\$s) harus dapat ditulis oleh server web."; // %1$s is the absolute path to the config file, %2$s is the absolute path to the config directory
$lang['SystemRequirements.!warning.simplexml.recommended'] = "Ekstensi simplexml sangat disarankan karena mungkin diperlukan untuk berinteraksi dengan beberapa sistem.";
$lang['SystemRequirements.!warning.iconv.recommended'] = "Ekstensi iconv diperlukan untuk encoding dan decoding karakter khusus.";
$lang['SystemRequirements.!error.extension_version.minimum'] = "Ekstensi '%1\$s' diperlukan. Versi Anda: %2\$s."; // %1$s is the name of the extension required. %2$s is the current version
$lang['SystemRequirements.!info.ext-ioncube.minimum'] = "Pastikan untuk menerapkan file hotfix yang diperlukan dengan menimpa file Blesta Anda dengan file dari direktori %1\$s. Blesta tidak akan dapat diakses setelah instalasi sebaliknya."; // %1$s is the name of the hotfix directory
$lang['SystemRequirements.!error.extension.minimum'] = "Ekstensi '%1\$s' diperlukan."; // %1$s is the name of the extension required
$lang['SystemRequirements.!warning.gd.recommended'] = "Ekstensi gd direkomendasikan untuk dukungan gambar yang lebih baik selama pembuatan PDF dan pembuatan captcha internal.";
$lang['SystemRequirements.!warning.soap.recommended'] = "Perpanjangan sabun diperlukan untuk penanganan pajak PPN otomatis.";
?>