<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SystemEvents.!error.event.empty'] = "Harap masukkan nama acara.";
$lang['SystemEvents.!error.event.length'] = "Panjang acara tidak boleh melebihi %1\$s karakter."; // %1$s is the maximum number of characters allowed
$lang['SystemEvents.!error.observer.valid'] = "Harap berikan pengamat yang dapat dipanggil berdasarkan namespace atau jalur sistem file.";
?>