<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SoftaculousPlugin.name'] = "Penginstal Otomatis Lembut";
$lang['SoftaculousPlugin.library_error'] = "Tidak dapat memuat perpustakaan.";
$lang['SoftaculousPlugin.remote_error'] = "Tidak dapat masuk ke server jauh.";
$lang['SoftaculousPlugin.remote_error_message'] = "Tidak dapat masuk ke server jauh. Kesalahan: %1\$s"; // %1$s is the error
$lang['SoftaculousPlugin.remote_curl_error'] = "Tidak dapat masuk ke server jauh. Kesalahan cURL: %1\$s"; // %1$s is the curl error
$lang['SoftaculousPlugin.remote_firewall_error'] = "Tidak dapat menentukan lokasi Softaculous di server jauh. Mungkin ada firewall yang mencegah akses.";
$lang['SoftaculousPlugin.script_selected_error'] = "Tidak dapat menentukan skrip yang akan dipasang. Pastikan nama skrip sudah benar. Nama Skrip: %1\$s"; // %1$s is the script
$lang['SoftaculousPlugin.script_installed'] = "Skrip berhasil diinstal";
$lang['SoftaculousPlugin.script_no_installed'] = "Tidak dapat memasang skrip: %1\$s"; // %1$s is the script
$lang['SoftaculousPlugin.admin_fname'] = "Sistem";
$lang['SoftaculousPlugin.admin_lname'] = "Administrator";
$lang['SoftaculousPlugin.installation_success'] = "Skrip berhasil dipasang untuk layanan dengan ID %1\$s"; // %1$s is the script
$lang['SoftaculousPlugin.cron.script_installation_name'] = "Script Layanan Penyediaan";
$lang['SoftaculousPlugin.cron.script_installation_desc'] = "Menginstal skrip tertunda untuk layanan.";
?>