<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cart.index.header_cart'] = "Tinjau Pesanan";
$lang['Cart.index.table_description'] = "Deskripsi";
$lang['Cart.index.table_term'] = "Istilah";
$lang['Cart.index.table_qty'] = "Kuantitas";
$lang['Cart.index.table_price'] = "Harga";
$lang['Cart.index.checkout_btn'] = "Periksa";
$lang['Cart.index.order_more_btn'] = "Pesan Lebih Banyak Barang";
$lang['Cart.index.edit_item'] = "Sunting";
$lang['Cart.index.remove_item'] = "Menghapus";
$lang['Cart.index.empty_cart'] = "Keranjang Anda masih kosong. Mulai dengan <a href=\"%1\$s\">memilih paket »</a>"; // %1$s is the URI to the order home page
?>