<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Config.index.header_configuration'] = "Konfigurasi";
$lang['Config.index.header_configure_service'] = "Konfigurasikan %1\$s"; // %1$s is the service name to configure
$lang['Config.index.header_term'] = "Istilah dan Harga";
$lang['Config.index.header_module'] = "Opsi yang Dapat Dikonfigurasi"; // %1$s is the name of the module
$lang['Config.index.header_addons'] = "Add-On yang Tersedia";
$lang['Config.index.continue_btn'] = "Terus";
?>