<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Signup.index.header_login_or_signup'] = "Daftar atau Masuk";
$lang['Signup.index.link_resetpassword'] = "Setel ulang kata sandi saya";
$lang['Signup.index.header_login'] = "Gabung";
$lang['Signup.index.heading_contact'] = "Kontak informasi";
$lang['Signup.index.heading_billing'] = "Informasi tagihan";
$lang['Signup.index.heading_authentication'] = "Autentikasi";
$lang['Signup.index.heading_settings'] = "Pengaturan Tambahan";
?>