<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Whmsonic.name'] = "WHMSonic";
$lang['Whmsonic.module_row'] = "Server";
$lang['Whmsonic.module_row_plural'] = "Server";
$lang['Whmsonic.module_group'] = "Server Group";
$lang['Whmsonic.tab_stats'] = "Informasi Layanan";
$lang['Whmsonic.tab_client_actions'] = "Tindakan";
$lang['Whmsonic.submit'] = "Kirimkan";
$lang['Whmsonic.tab_stats.info_heading.field'] = "Bidang";
$lang['Whmsonic.tab_stats.info_heading.value'] = "Nilai";
$lang['Whmsonic.tab_stats.info.client_type'] = "Jenis Klien";
$lang['Whmsonic.tab_stats.info.bitrate'] = "Batas Kecepatan Bit";
$lang['Whmsonic.tab_stats.info.bandwidth'] = "Batas Bandwidth (Dalam MB)";
$lang['Whmsonic.tab_stats.info.hspace'] = "Ruang Hosting (Dalam MB)";
$lang['Whmsonic.tab_stats.info.listeners'] = "Batas Pendengar";
$lang['Whmsonic.tab_stats.info.autodj'] = "Akses AutoDJ";
$lang['Whmsonic.tab_stats.info.username'] = "Nama pengguna";
$lang['Whmsonic.tab_stats.info.password'] = "Kata sandi";
$lang['Whmsonic.tab_stats.info.whmsonic_ftp'] = "Akses FTP";
$lang['Whmsonic.tab_stats.info.whmsonic_radio_ip'] = "IP Radio";
$lang['Whmsonic.tab_stats.info.whmsonic_radio_password'] = "Kata Sandi Radio";
$lang['Whmsonic.tab_client_actions.change_password'] = "Ubah Kata Sandi";
$lang['Whmsonic.tab_client_actions.password'] = "Kata Sandi cPanel";
$lang['Whmsonic.tab_client_actions.radio_password'] = "Kata Sandi Radio";
$lang['Whmsonic.add_module_row'] = "Tambahkan server";
$lang['Whmsonic.add_module_group'] = "Tambahkan Grup Server";
$lang['Whmsonic.manage.module_rows_title'] = "Server";
$lang['Whmsonic.manage.module_groups_title'] = "Grup Server";
$lang['Whmsonic.manage.module_rows_heading.name'] = "Label Server";
$lang['Whmsonic.manage.module_rows_heading.ip_address'] = "Alamat IP";
$lang['Whmsonic.manage.module_rows_heading.options'] = "Pilihan";
$lang['Whmsonic.manage.module_groups_heading.name'] = "Nama grup";
$lang['Whmsonic.manage.module_groups_heading.servers'] = "Jumlah Server";
$lang['Whmsonic.manage.module_groups_heading.options'] = "Pilihan";
$lang['Whmsonic.manage.module_rows.edit'] = "Edit";
$lang['Whmsonic.manage.module_groups.edit'] = "Sunting";
$lang['Whmsonic.manage.module_rows.delete'] = "Hapus";
$lang['Whmsonic.manage.module_groups.delete'] = "Hapus";
$lang['Whmsonic.manage.module_rows.confirm_delete'] = "Anda yakin ingin menghapus server ini?";
$lang['Whmsonic.manage.module_groups.confirm_delete'] = "Anda yakin ingin menghapus grup server ini?";
$lang['Whmsonic.manage.module_rows_no_results'] = "Tidak ada server.";
$lang['Whmsonic.manage.module_groups_no_results'] = "Tidak ada grup server.";
$lang['Whmsonic.order_options.first'] = "Server tidak penuh pertama";
$lang['Whmsonic.add_row.box_title'] = "Tambahkan Server WHMSonic";
$lang['Whmsonic.add_row.basic_title'] = "Pengaturan dasar";
$lang['Whmsonic.add_row.add_btn'] = "Tambahkan server";
$lang['Whmsonic.edit_row.box_title'] = "Sunting Server WHMSonic";
$lang['Whmsonic.edit_row.basic_title'] = "Pengaturan dasar";
$lang['Whmsonic.edit_row.add_btn'] = "Sunting Server";
$lang['Whmsonic.row_meta.server_name'] = "Label Server";
$lang['Whmsonic.row_meta.ip_address'] = "Alamat IP";
$lang['Whmsonic.row_meta.password'] = "Kata sandi";
$lang['Whmsonic.row_meta.use_ssl'] = "Gunakan SSL saat menghubungkan ke API (disarankan)";
$lang['Whmsonic.package_fields.client_type'] = "Tipe Klien";
$lang['Whmsonic.package_fields.client_type.external'] = "Luar";
$lang['Whmsonic.package_fields.client_type.internal'] = "Intern";
$lang['Whmsonic.package_fields.bitrate'] = "Batas Kecepatan Bit";
$lang['Whmsonic.package_fields.hspace'] = "Ruang Hosting (Dalam MB)";
$lang['Whmsonic.package_fields.bandwidth'] = "Batas Bandwidth (Dalam MB)";
$lang['Whmsonic.package_fields.listeners'] = "Batas Pendengar";
$lang['Whmsonic.package_fields.autodj'] = "Akses AutoDJ";
$lang['Whmsonic.package_fields.autodj.yes'] = "Ya";
$lang['Whmsonic.package_fields.autodj.no'] = "Tidak";
$lang['Whmsonic.service_field.cpanel_username'] = "cPanel Username";
$lang['Whmsonic.service_field.username'] = "Nama Pengguna Radio";
$lang['Whmsonic.service_field.radio_password'] = "Kata Sandi Radio";
$lang['Whmsonic.service_field.password'] = "Kata Sandi cPanel";
$lang['Whmsonic.service_field.username.tooltip'] = "Nama pengguna hanya akan diperbarui secara lokal di dalam Blesta";
$lang['Whmsonic.service_field.password.tooltip'] = "Kata sandi hanya akan diperbarui secara lokal di dalam Blesta";
$lang['Whmsonic.service_info.ip_address'] = "Alamat IP";
$lang['Whmsonic.service_info.username'] = "Nama pengguna";
$lang['Whmsonic.service_info.password'] = "Kata Sandi";
$lang['Whmsonic.service_info.options'] = "Pilihan";
$lang['Whmsonic.service_info.option_login'] = "Gabung";
$lang['Whmsonic.!error.server_name_valid'] = "Anda harus memasukkan Label Server.";
$lang['Whmsonic.!error.ip_address_valid'] = "Alamat IP tampaknya tidak valid.";
$lang['Whmsonic.!error.password_valid'] = "Kredensial API tampaknya tidak valid.";
$lang['Whmsonic.!error.api.internal'] = "Terjadi kesalahan internal, atau server tidak menanggapi permintaan.";
$lang['Whmsonic.!error.module_row.missing'] = "Terjadi kesalahan internal. Baris modul tidak tersedia.";
$lang['Whmsonic.!error.meta[client_type].valid'] = "Harap pilih jenis klien yang valid.";
$lang['Whmsonic.!error.meta[bitrate].valid'] = "Silahkan pilih batas bitrate yang benar.";
$lang['Whmsonic.!error.meta[hspace].empty'] = "Silakan masukkan Ruang Hosting (Dalam MB), mis: 1000.";
$lang['Whmsonic.!error.meta[bandwidth].empty'] = "Silakan masukkan Batas Bandwidth (Dalam MB), mis . : 1000.";
$lang['Whmsonic.!error.meta[listeners].empty'] = "Harap masukkan Batas Pendengar.";
$lang['Whmsonic.!error.meta[autodj].valid'] = "Silakan pilih opsi Akses AutoDJ yang valid.";
$lang['Whmsonic.!error.user_name.empty'] = "Nama pengguna wajib diisi.";
$lang['Whmsonic.!error.user_password.valid'] = "Kata sandi harus minimal 8 karakter.";
$lang['Whmsonic.description'] = "Memungkinkan Anda untuk menawarkan shoutcast, icecast, hosting media streaming, AutoDJ, reseller radio dari server Dedicated atau VPS Anda.";
?>
