<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DefaultInvoice.name'] = "default";
$lang['DefaultInvoice.page_of'] = "Halaman %1\$s of %2\$s"; // %1$s is the current page number, %2$s is the total number of pages
$lang['DefaultInvoice.terms_heading'] = "Persyaratan";
$lang['DefaultInvoice.type_active'] = "FAKTUR";
$lang['DefaultInvoice.type_draft'] = "FAKTUR - DRAFT";
$lang['DefaultInvoice.type_void'] = "FAKTUR - BATAL";
$lang['DefaultInvoice.invoice_id_code'] = "Nomor faktur:";
$lang['DefaultInvoice.client_id_code'] = "Nomor pelanggan:";
$lang['DefaultInvoice.tax_id'] = "ID pajak :";
$lang['DefaultInvoice.date_billed'] = "Tanggal faktur:";
$lang['DefaultInvoice.date_due'] = "Batas tanggal terakhir:";
$lang['DefaultInvoice.notes_heading'] = "Catatan";
$lang['DefaultInvoice.subtotal_heading'] = "Subtotal";
$lang['DefaultInvoice.total_heading'] = "Total";
$lang['DefaultInvoice.lines_description'] = "Deskripsi";
$lang['DefaultInvoice.lines_quantity'] = "Kuantitas";
$lang['DefaultInvoice.lines_unit_price'] = "Harga per unit";
$lang['DefaultInvoice.lines_cost'] = "Biaya";
$lang['DefaultInvoice.watermark_paid'] = "DIBAYAR";
$lang['DefaultInvoice.client_tax_id'] = "ID Pajak Pelanggan /VATIN";
$lang['DefaultInvoice.type_proforma'] = "FAKTUR PRO FORMA ";
$lang['DefaultInvoice.payments_heading'] = "Pembayaran";
$lang['DefaultInvoice.payments_applied_date'] = "Tanggal Berlaku";
$lang['DefaultInvoice.payments_type_name'] = "Tipe";
$lang['DefaultInvoice.payments_transaction_id'] = "Nomor Transaksi";
$lang['DefaultInvoice.payments_applied_amount'] = "Jumlah Diterapkan";
$lang['DefaultInvoice.balance_heading'] = "Keseimbangan";
$lang['DefaultInvoice.proforma_id_code'] = "Nomor Pro Forma:";
$lang['DefaultInvoice.draft_id_code'] = "Nomor Draf:";
?>