<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['FeedReaderPlugin.!error.libxml_required'] = "extension libxml diperlukan untuk plugin ini.";
$lang['FeedReaderPlugin.!error.dom_required'] = "dom extension diperlukan untuk plugin ini.";
$lang['FeedReaderPlugin.name'] = "Feed Reader";
$lang['FeedReaderPlugin.description'] = "Lihat umpan RSS/Atom apa pun langsung di dasbor Anda.";
?>
