<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Main.index.heading'] = "Pilihan Paket";
$lang['Main.index.subheading'] = "Silakan pilih grup paket di bawah ini untuk melanjutkan.";
$lang['Main.index.group_heading'] = "Pilih paket di bawah ini.";
$lang['Main.index.field_pricing_id'] = "Pilih siklus penagihan Anda.";
$lang['Main.index.button_order'] = "Pesan sekarang";
$lang['Main.index.sold_out'] = "Kehabisan persediaan";
$lang['Main.index.field_currency'] = "Mata uang:";
$lang['Main.packages.subheading'] = "Pilih paket dan kemudian konfigurasikan di bawah.";
$lang['Main.packages.select_note'] = "Seret untuk memilih paket yang berbeda.";
$lang['Main.packages.price_start'] = "Mulai dari";
$lang['Main.packages.box_select'] = "Pilih";
$lang['Main.packages.box_selected'] = "Terpilih";
$lang['Main.packages.box_sold_out'] = "Kehabisan persediaan";
$lang['Main.index.client_limit'] = "Batas Tercapai";
$lang['Main.packages.box_client_limit'] = "Batas Tercapai";
?>