<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Summary.index.have_coupon'] = "Gunakan kode kupon";
$lang['Summary.index.coupon'] = "Kupon";
$lang['Summary.index.coupon_btn'] = "Redeem";
$lang['Summary.index.heading_summary'] = "Ringkasan Pesanan";
$lang['Summary.index.summary_note'] = "Pajak apa pun yang berlaku akan dihitung setelah Anda mendaftar atau masuk.";
$lang['Summary.index.table_description'] = "Deskripsi";
$lang['Summary.index.table_price'] = "Harga";
$lang['Summary.index.empty_cart'] = "Keranjang kosong";
$lang['Summary.index.heading_paymethods'] = "Metode pembayaran";
$lang['Summary.index.paymethods_note'] = "Silakan pilih metode pembayaran yang Anda inginkan.";
?>