<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Paystack.name'] = "Standar Tumpukan Gaji";
$lang['Paystack.secret_key'] = "Kunci Rahasia Paystack";
$lang['Paystack.tooltip.secret_key'] = "Untuk menggunakan mode uji, cukup masukkan kunci uji.";
$lang['Paystack.buildprocess.submit'] = "Bayar dengan Paystack";
$lang['Paystack.!error.secret_key.valid'] = "Kunci rahasia harus setidaknya 40 karakter.";
$lang['Paystack.description'] = "Paystack adalah cara tercepat dan termudah untuk mulai menerima pembayaran online di Nigeria.";
?>