<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['GoGetSSL.!error.api_username.empty'] = "Silakan masukkan nama pengguna API.";
$lang['GoGetSSL.!error.api_username.valid'] = "Sambungan ke server tidak dapat dibuat. Harap periksa untuk memastikan bahwa kredensial API sudah benar.";
$lang['GoGetSSL.!error.api_password.empty'] = "Silakan masukkan sandi API.";
$lang['GoGetSSL.!error.gogetssl_name.empty'] = "Masukkan nama pengecer.";
$lang['GoGetSSL.!error.gogetssl_validity.empty'] = "Harap masukkan masa berlaku.";
$lang['GoGetSSL.!error.gogetssl_approver_email.format'] = "Harap masukkan E-Mail pemberi persetujuan yang valid.";
$lang['GoGetSSL.!error.gogetssl_csr.format'] = "Silakan masukkan nilai CSR.";
$lang['GoGetSSL.!error.gogetssl_fqdn.format'] = "Masukkan Domain yang valid.";
$lang['GoGetSSL.!error.gogetssl_webserver_type.format'] = "Masukkan  Jenis Webserver yang valid.";
$lang['GoGetSSL.!error.meta[product].valid'] = "Silakan pilih produk.";
$lang['GoGetSSL.!error.meta[gogetssl_name].empty'] = "ID";
$lang['GoGetSSL.!error.api.internal'] = "Terjadi kesalahan internal, atau server tidak menanggapi permintaan.";
$lang['GoGetSSL.please_select'] = "-- Silakan Pilih --";
$lang['GoGetSSL.name'] = "GoGetSSL";
$lang['GoGetSSL.module_row'] = "GoGetSSL Reseller";
$lang['GoGetSSL.module_row_plural'] = "Reseller";
$lang['GoGetSSL.add_module_row'] = "Tambahkan Pengecer";
$lang['GoGetSSL.manage.module_rows_title'] = "Pengecer GoGetSSL";
$lang['GoGetSSL.manage.module_rows.edit'] = "Sunting";
$lang['GoGetSSL.manage.module_rows.delete'] = "Menghapus";
$lang['GoGetSSL.manage.module_rows.confirm_delete'] = "Yakin ingin menghapus pengecer ini?";
$lang['GoGetSSL.manage.module_rows_no_results'] = "Tidak ada reseller.";
$lang['GoGetSSL.manage.module_rows_heading.gogetssl_name'] = "Nama Reseller";
$lang['GoGetSSL.manage.module_rows_heading.options'] = "Pilihan";
$lang['GoGetSSL.row_meta.gogetssl_name'] = "Nama reseller";
$lang['GoGetSSL.row_meta.api_username'] = "Nama pengguna API";
$lang['GoGetSSL.row_meta.api_password'] = "kata sandi API";
$lang['GoGetSSL.row_meta.sandbox'] = "Sandbox";
$lang['GoGetSSL.add_row.box_title'] = "Tambahkan GoGetSSL Reseller";
$lang['GoGetSSL.add_row.basic_title'] = "Pengaturan Dasar";
$lang['GoGetSSL.add_row.add_btn'] = "Tambahkan Pengecer";
$lang['GoGetSSL.edit_row.box_title'] = "Edit Pengecer GoGetSSL";
$lang['GoGetSSL.edit_row.basic_title'] = "Pengaturan Dasar";
$lang['GoGetSSL.edit_row.add_btn'] = "Perbarui Pengecer";
$lang['GoGetSSL.package_fields.product'] = "Produk";
$lang['GoGetSSL.service_field.gogetssl_fqdn'] = "Host / Domain";
$lang['GoGetSSL.service_field.gogetssl_csr'] = "konten CSR";
$lang['GoGetSSL.service_field.gogetssl_webserver_type'] = "Jenis server web";
$lang['GoGetSSL.service_field.gogetssl_approver_email'] = "Approver E-Mail";
$lang['GoGetSSL.service_field.gogetssl_title'] = "Judul";
$lang['GoGetSSL.service_field.gogetssl_firstname'] = "Nama depan";
$lang['GoGetSSL.service_field.gogetssl_lastname'] = "Nama terakhir";
$lang['GoGetSSL.service_field.gogetssl_address1'] = "Alamat baris 1";
$lang['GoGetSSL.service_field.gogetssl_address2'] = "Alamat Baris 2";
$lang['GoGetSSL.service_field.gogetssl_city'] = "Kota";
$lang['GoGetSSL.service_field.gogetssl_zip'] = "ZIP";
$lang['GoGetSSL.service_field.gogetssl_state'] = "Negara";
$lang['GoGetSSL.service_field.gogetssl_country'] = "Negara";
$lang['GoGetSSL.service_field.gogetssl_email'] = "E-Mail";
$lang['GoGetSSL.service_field.gogetssl_number'] = "Nomor telepon (format internasional)";
$lang['GoGetSSL.service_field.gogetssl_organization'] = "Organisasi (isi NA jika tidak ada)";
$lang['GoGetSSL.service_field.gogetssl_organization_unit'] = "Unit organisasi (masukkan NA jika tidak berlaku)";
$lang['GoGetSSL.service_field.gogetssl_fax'] = "Nomor faks (format internasional)";
$lang['GoGetSSL.tab_reissue'] = "Penerbitan kembali / Reissue";
$lang['GoGetSSL.tab_reissue.heading_reissue'] = "Penerbitan ulang";
$lang['GoGetSSL.description'] = "GoGetSSL telah melayani sertifikat SSL sejak 2009.";
?>