<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PterodactylRule.!error.required'] = "Bidang %1\$s wajib diisi."; // %1$s is the name of the required field
$lang['PterodactylRule.!error.regex'] = "Bidang %1\$s harus cocok dengan regex %2\$s."; // %1$s is the name of the field, %2$s is the regex to match
$lang['PterodactylRule.!error.numeric'] = "Bidang %1\$s harus berisi angka."; // %1$s is the name of the field
$lang['PterodactylRule.!error.integer'] = "Bidang %1\$s harus berisi bilangan bulat."; // %1$s is the name of the field
$lang['PterodactylRule.!error.string'] = "Bidang %1\$s harus berisi string."; // %1$s is the name of the field
$lang['PterodactylRule.!error.alphaNum'] = "Bidang %1\$s hanya boleh berisi karakter berikut a-z, A-Z, atau 0-9."; // %1$s is the name of the field
$lang['PterodactylRule.!error.alphaDash'] = "Kolom %1\$s hanya boleh berisi karakter berikut a-z, A-Z, 0-9, -, atau _."; // %1$s is the name of the field
$lang['PterodactylRule.!error.url'] = "Bidang %1\$s harus berisi url yang valid (mis. www.domain.com)."; // %1$s is the name of the field
$lang['PterodactylRule.!error.min'] = "Kolom %1\$s harus berisi minimal %2\$s."; // %1$s is the name of the field, %2$s is the minimum value/length
$lang['PterodactylRule.!error.max'] = "Bidang %1\$s memiliki maksimum %2\$s."; // %1$s is the name of the field, %2$s is the maximum value/length
$lang['PterodactylRule.!error.between'] = "Bidang %1\$s harus berisi nilai antara %2\$s dan %3\$s."; // %1$s is the name of the field, %2$s is the minimum value/length, %3$s is the maximum value/length
$lang['PterodactylRule.!error.digitsBetween'] = "Bidang %1\$s harus berisi nilai antara %2\$s dan %3\$s digit."; // %1$s is the name of the field, %2$s is the minimum value/length, %3$s is the maximum value/length
?>