<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PterodactylService.!error.server_name.empty'] = "Harap tetapkan nama untuk server.";
$lang['PterodactylService.service_fields.server_name'] = "Nama server";
$lang['PterodactylService.service_fields.tooltip.server_name'] = "Nama servernya.";
$lang['PterodactylService.service_fields.server_description'] = "Deskripsi Server (Opsional)";
$lang['PterodactylService.service_fields.tooltip.server_description'] = "Deskripsi servernya.";
$lang['PterodactylService.service_fields.server_id'] = "ID Server (Opsional)";
$lang['PterodactylService.service_fields.tooltip.server_id'] = "ID server di panel Pterodactyl. Ini hanya boleh digunakan saat Anda menautkan layanan ini ke server yang sudah ada sebelumnya.";
$lang['PterodactylService.service_fields.optional'] = "%1\$s (Opsional)"; // %1$s is the name of the field
?>