<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.index.health_excellent'] = "Sistem ini dalam keadaan yang baik dan tampaknya beroperasi secara normal.";
$lang['AdminMain.index.health_good'] = "Secara keseluruhan sistem dalam kesehatan yang baik, tetapi ada beberapa item yang mungkin memerlukan perhatian Anda.";
$lang['AdminMain.index.health_fair'] = "Ada beberapa masalah yang mempengaruhi kemampuan sistem untuk beroperasi secara normal.";
$lang['AdminMain.index.health_poor'] = "Ada masalah serius yang mempengaruhi kemampuan sistem untuk beroperasi secara normal. Ini harus diselesaikan sesegera mungkin.";
$lang['AdminMain.index.boxtitle_feed'] = "Status sistem";
$lang['AdminMain.index.cron_serious'] = "Cron tidak pernah berjalan.";
$lang['AdminMain.index.cron_minor'] = "Cron belum berjalan dalam 24 jam terakhir.";
$lang['AdminMain.index.cron_configure'] = "Mengkonfigurasi?";
$lang['AdminMain.index.invoices_minor'] = "Faktur belum dibuat secara otomatis melalui cron dalam 24 jam terakhir.";
$lang['AdminMain.index.invoices_configure'] = "Konfigurasi?";
$lang['AdminMain.index.backup_minor'] = "Tidak ada backup telah dijalankan dalam 7 hari terakhir.";
$lang['AdminMain.index.cron_task_stalled_minor'] = "Ada satu atau lebih tugas cron yang telah mengeksekusi selama lebih dari %1\$s menit."; // %1$s is the number of minutes
$lang['AdminMain.index.cron_task_stalled_automation'] = "Lihat Tugas otomatis";
$lang['AdminMain.index.trial_minor'] = "Lisensi uji coba Anda berakhir pada %1\$s."; // %1$s is the date the trial license expires
$lang['AdminMain.index.trial_buy'] = "Beli sekarang?";
$lang['AdminMain.index.updates_forever'] = "Dukungan dan update yang baik selamanya.";
$lang['AdminMain.index.updates_minor'] = "Dukungan dan pembaruan Anda baik melalui %1\$s."; // %1$s is the date support expires
$lang['AdminMain.index.updates_serious'] = "Dukungan dan pembaruan Anda berakhir pada %1\$s."; // %1$s is the date support expired
$lang['AdminMain.index.updates_buy'] = "Tambahkan dukungan dan pembaruan?";
$lang['AdminMain.index.docroot_minor'] = "Jalur akar dokumen yang terdeteksi tidak cocok dengan pengaturan Direktori Web Root.";
$lang['AdminMain.index.docroot_setting'] = "Memperbarui?";
$lang['AdminMain.index.system_dir_writable_minor'] = "Direktori sistem tidak dapat ditulis.";
$lang['AdminMain.index.system_dir_writable_setting'] = "Memperbarui?";
$lang['AdminMain.index.log_files_owner_minor'] = "Ada beberapa file log yang tidak dimiliki oleh pengguna yang sama dengan server web. Ini biasanya disebabkan oleh cron yang berjalan sebagai pengguna yang berbeda dari server web.";
$lang['AdminMain.index.db_version_serious'] = "Versi database tidak cocok dengan versi sistem.";
$lang['AdminMain.index.db_version_upgrade'] = "Meningkatkan?";
$lang['AdminMain.index.php_version_serious'] = "Versi PHP tidak memenuhi persyaratan sistem minimum.";
$lang['AdminMain.index.php_version_requirements'] = "Lihat persyaratan minimum";
$lang['AdminMain.index.sql_mysql_version_serious'] = "Versi MySQL tidak memenuhi persyaratan sistem minimum.";
$lang['AdminMain.index.sql_mysql_version_requirements'] = "Lihat persyaratan minimum";
$lang['AdminMain.index.sql_mariadb_version_serious'] = "Versi MariaDB tidak memenuhi persyaratan sistem minimum.";
$lang['AdminMain.index.sql_mariadb_version_requirements'] = "Lihat persyaratan minimum";
?>