<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminSettings.!success.settings_updated'] = "Pengaturan afiliasi telah diperbarui.";
$lang['AdminSettings.settings.boxtitle_settings'] = "Pengaturan Umum";
$lang['AdminSettings.settings.field_cookie_tld'] = "Durasi Cookie (dalam Hari)";
$lang['AdminSettings.settings.tooltip_cookie_tld'] = "Hari-hari ketika cookie afiliasi tetap valid setelah tautan rujukan diikuti.";
$lang['AdminSettings.settings.field_commission_type'] = "Jenis Komisi";
$lang['AdminSettings.settings.tooltip_commission_type'] = "Metode perhitungan yang digunakan untuk menentukan komisi referral. Baik nilai tetap per pesanan atau persentase dari total pesanan.";
$lang['AdminSettings.settings.field_commission_amount'] = "Jumlah Komisi";
$lang['AdminSettings.settings.field_order_frequency'] = "Frekuensi Pemesanan";
$lang['AdminSettings.settings.tooltip_order_frequency'] = "Pertama untuk membayar rujukan hanya untuk pesanan pertama yang dibuat klien menggunakan tautan rujukan, atau Any untuk membayar rujukan untuk setiap pesanan yang dibuat klien menggunakan tautan rujukan.";
$lang['AdminSettings.settings.field_order_recurring'] = "Pesanan Berulang";
$lang['AdminSettings.settings.tooltip_order_recurring'] = "Apakah rujukan akan dibayar untuk layanan yang dipesan yang diperbarui.";
$lang['AdminSettings.settings.field_maturity_days'] = "Hari Kedewasaan";
$lang['AdminSettings.settings.tooltip_maturity_days'] = "Jumlah hari setelah pembayaran, rujukan jatuh tempo dan tersedia untuk pembayaran.";
$lang['AdminSettings.settings.field_min_withdrawal_amount'] = "Jumlah Penarikan Minimum";
$lang['AdminSettings.settings.field_max_withdrawal_amount'] = "Jumlah Penarikan Maksimum";
$lang['AdminSettings.settings.field_withdrawal_currency'] = "Mata Uang Penarikan";
$lang['AdminSettings.settings.field_signup_content'] = "Daftar Isi";
$lang['AdminSettings.settings.tooltip_signup_content'] = "Konten HTML yang akan ditampilkan kepada klien di halaman afiliasi jika mereka belum terdaftar.";
$lang['AdminSettings.settings.zero_amount'] = "Jumlah penarikan saat ini nol, artinya afiliasi tidak akan menerima dana dari referensi";
$lang['AdminSettings.settings.text_inheritance'] = "Pengaturan afiliasi perusahaan diwarisi oleh afiliasi yang baru dibuat, tetapi kemudian ditimpa oleh pengaturan afiliasi individu";
$lang['AdminSettings.settings.submit_settings'] = "Simpan Pengaturan";
$lang['AdminSettings.settings.submit_cancel'] = "Batal";
?>
