<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminCompanyEmails.templates.Order.received_name'] = "Pesanan Diterima";
$lang['AdminCompanyEmails.templates.Order.received_desc'] = "Pemberitahuan dikirim ketika pesanan diterima.";
$lang['AdminCompanyEmails.templates.Order.received_mobile_name'] = "Pesanan Diterima (Mobile)";
$lang['AdminCompanyEmails.templates.Order.received_mobile_desc'] = "Pemberitahuan dikirim saat pesanan diterima yang ditujukan untuk perangkat seluler.";
$lang['AdminCompanyEmails.templates.Order.affiliate_payout_request_name'] = "Permintaan Pembayaran Afiliasi";
$lang['AdminCompanyEmails.templates.Order.affiliate_payout_request_desc'] = "Pemberitahuan dikirim ke staf saat permintaan pembayaran diajukan.";
$lang['AdminCompanyEmails.templates.Order.affiliate_payout_request_received_name'] = "Pembayaran Afiliasi Diterima";
$lang['AdminCompanyEmails.templates.Order.affiliate_payout_request_received_desc'] = "Pemberitahuan dikirim ke klien saat permintaan pembayaran mereka diajukan.";
$lang['AdminCompanyEmails.templates.Order.affiliate_monthly_report_name'] = "Laporan Afiliasi (Bulanan)";
$lang['AdminCompanyEmails.templates.Order.affiliate_monthly_report_desc'] = "Laporkan pendaftaran daftar dan data terkait untuk bulan lalu.";
?>
