<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Checkout.!error.invalid_agree_tos'] = "Anda harus mengakui persetujuan Anda terhadap syarat dan ketentuan.";
$lang['Checkout.!error.no_payment_info'] = "Anda harus memilih metode pembayaran untuk melanjutkan.";
$lang['Checkout.index.description_invoice'] = "Faktur #%1\$s"; // %1$s is the invoice number
$lang['Checkout.setcontactview.text_none'] = "Tidak Satupun";
$lang['Checkout.getpaymentaccounts.paymentaccount_cc'] = "Akun Kartu Kredit";
$lang['Checkout.getpaymentaccounts.paymentaccount_ach'] = "Akun ACH";
$lang['Checkout.getpaymentaccounts.account_name'] = "%1\$s %2\$s - %3\$s x%4\$s"; // %1$s is the account first name, %2$s is the account last name, %3$s is the account type (card type or bank account type), %4$s is the last 4 of the account
$lang['Checkout.index.field_agree_tos'] = "Saya telah membaca dan setuju dengan <a href=\"%1\$s\" target=\"_blank\">Syarat dan Ketentuan </a>"; // %1$s is the URI to the terms and conditions
$lang['Checkout.index.totals.setup_fee'] = "Biaya Setup :";
$lang['Checkout.index.totals.discount'] = "Diskon";
$lang['Checkout.index.totals.subtotal'] = "Sub Total:";
$lang['Checkout.index.totals.tax'] = "%1\$s (%2\$s%%):"; // %1$s is the tax name, %2$s is the tax percentage
$lang['Checkout.index.totals.total'] = "Total Jatuh Tempo:";
$lang['Checkout.contact_info.field_first_name'] = "Nama depan";
$lang['Checkout.contact_info.field_last_name'] = "Nama Belakang";
$lang['Checkout.contact_info.field_address1'] = "Alamat 1";
$lang['Checkout.contact_info.field_address2'] = "alamat 2";
$lang['Checkout.contact_info.field_city'] = "Kota";
$lang['Checkout.contact_info.field_country'] = "Negara";
$lang['Checkout.contact_info.field_state'] = "Negara";
$lang['Checkout.contact_info.field_zip'] = "Kode Pos/Kode Pos";
$lang['Checkout.contact_info.field_email'] = "Email";
$lang['Checkout.cc_info.field_number'] = "Jumlah";
$lang['Checkout.cc_info.field_security'] = "Security Code";
$lang['Checkout.cc_info.field_expiration'] = "Tanggal habis tempo";
$lang['Checkout.cc_info.field_savedetails'] = "Simpan Rincian Pembayaran";
$lang['Checkout.cc_info.tooltip_savedetails'] = "Rincian pembayaran disimpan dapat digunakan untuk melakukan pembayaran di masa depan tanpa harus memasukkan rincian setiap kali.";
$lang['Checkout.cc_info.tooltip_code'] = "Kode keamanan 3 atau 4 digit, biasanya terdapat di bagian belakang kartu.";
$lang['Checkout.ach_info.field_type'] = "Jenis";
$lang['Checkout.ach_info.field_accountnum'] = "Nomor Rekening";
$lang['Checkout.ach_info.field_routingnum'] = "Nomor Perutean
";
$lang['Checkout.ach_info.field_savedetails'] = "Simpan Rincian Pembayaran";
$lang['Checkout.ach_info.tooltip_savedetails'] = "Rincian pembayaran disimpan dapat digunakan untuk melakukan pembayaran di masa depan tanpa harus memasukkan rincian setiap kali";
$lang['Checkout.complete.order_number'] = "Pesanan #%1\$s"; // %1$s is the order number
$lang['Checkout.complete.complete_description'] = "Terima kasih atas pesanan Anda! Pesanan Anda sekarang sudah selesai.";
$lang['Checkout.complete.almost_complete_description'] = "Pesanan Anda telah diterima, menunggu pembayaran Anda di bawah ini.";
$lang['Checkout.complete.table_description'] = "Deskripsi";
$lang['Checkout.complete.table_qty'] = "Kuantitas";
$lang['Checkout.complete.table_price'] = "Patokan harga";
$lang['Checkout.complete.quantity'] = "%1\$s @"; // %1\$s is the quantity value being ordered
$lang['Checkout.complete.totals.subtotal'] = "Subtotal:";
$lang['Checkout.complete.totals.tax'] = "%1\$s (%2\$s%%):"; // %1$s is the tax name, %2$s is the tax percentage
$lang['Checkout.complete.totals.total'] = "Total Jatuh Tempo:";
$lang['Checkout.complete.totals.total_paid'] = "Total Dibayar:";
$lang['Checkout.index.totals.credit'] = "Kredit:";
$lang['Checkout.index.totals.paid'] = "Dibayar:";
$lang['Checkout.!error.not_client_owner'] = "Anda harus login sebagai pemilik / client untuk melanjutkan.";
$lang['Checkout.!info.unverified_email'] = "Tautan telah dikirim ke alamat email yang Anda berikan. Silakan klik link di email untuk memverifikasi alamat email Anda sebelum melanjutkan untuk melakukan pembayaran.";
$lang['Checkout.!info.unverified_email_button'] = "Mengirim ulang email verifikasi";
?>
