<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Referrals.index.boxtitle_referrals'] = "Referrals";
$lang['Referrals.index.category_pending'] = "Tertunda";
$lang['Referrals.index.category_mature'] = "Dewasa";
$lang['Referrals.index.category_canceled'] = "Dibatalkan";
$lang['Referrals.index.no_results'] = "Saat ini tidak ada rujukan dengan status ini.";
$lang['Referrals.index.heading_order'] = "Memesan #";
$lang['Referrals.index.heading_name'] = "Nama";
$lang['Referrals.index.heading_amount'] = "Jumlah";
$lang['Referrals.index.heading_currency'] = "Mata uang";
$lang['Referrals.index.heading_commission'] = "Komisi";
$lang['Referrals.index.heading_date_added'] = "Tanggal Ditambahkan";
?>
