<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Signup.!error.captcha.invalid'] = "Captcha tidak cocok. Harap coba lagi.";
$lang['Signup.index.field_taxid'] = "NPWP";
$lang['Signup.index.field_firstname'] = "Nama Depan";
$lang['Signup.index.field_lastname'] = "Nama keluarga";
$lang['Signup.index.field_company'] = "Perusahaan/Organisasi";
$lang['Signup.index.field_address1'] = "Alamat 1";
$lang['Signup.index.field_address2'] = "Alamat 2";
$lang['Signup.index.field_city'] = "Kota";
$lang['Signup.index.field_state'] = "Negara Bagian/Provinsi";
$lang['Signup.index.field_zip'] = "Zip / Postal Code";
$lang['Signup.index.field_country'] = "Negara";
$lang['Signup.index.field_phone'] = "Telepon";
$lang['Signup.index.field_fax'] = "Fax";
$lang['Signup.index.field_email'] = "Email";
$lang['Signup.index.field_username_type_email'] = "Gunakan email sebagai username";
$lang['Signup.index.field_username_type_username'] = "Tentukan nama pengguna";
$lang['Signup.index.field_action_continue'] = "Lanjutkan sebagai %1\$s %2\$s"; // %1$s is the first name of the client, %2$s is the last name of the client
$lang['Signup.index.field_action_login'] = "Gabung";
$lang['Signup.index.field_action_signup'] = "Buat sebuah akun";
$lang['Signup.index.field_username'] = "Nama pengguna";
$lang['Signup.index.field_password'] = "Kata sandi";
$lang['Signup.index.field_newpassword'] = "Kata sandi";
$lang['Signup.index.field_confirmpassword'] = "konfirmasi sandi";
$lang['Signup.index.login_btn'] = "Gabung";
$lang['Signup.index.continue_btn'] = "Lanjutkan ke checkout";
$lang['Signup.index.signup_btn'] = "Buat Akun";
$lang['Signup.!error.not_client_owner'] = "Anda harus masuk sebagai pemilik klien untuk melanjutkan.";
$lang['Signup.index.field_title'] = "Judul";
$lang['Signup.index.field_receive_email_marketing'] = "Saya ingin menerima email tentang produk, layanan, dan penawaran baru.";
$lang['Signup.!notice.force_email_usernames'] = "Nama pengguna Anda akan sama dengan alamat email Anda.";
$lang['Signup.!notice.email_verification'] = "Sebuah pesan telah dikirim untuk memverifikasi alamat email Anda. Harap selesaikan verifikasi sesegera mungkin.";
?>
