<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMerchant.getsupportedfeatures.cc'] = "Kartu kredit";
$lang['AdminMerchant.getsupportedfeatures.cc_offsite'] = "Kartu Kredit Luar Kantor";
$lang['AdminMerchant.getsupportedfeatures.cc_form'] = "Formulir Kartu Kredit Kustom";
$lang['AdminMerchant.getsupportedfeatures.ach'] = "ACH";
$lang['AdminMerchant.getsupportedfeatures.ach_offsite'] = "ACH di luar lokasi";
$lang['AdminMerchant.getsupportedfeatures.tooltip_cc'] = "Pemrosesan kartu kredit menggunakan kredensial yang tidak disimpan atau yang disimpan di Server kami.";
$lang['AdminMerchant.getsupportedfeatures.tooltip_cc_offsite'] = "Pemrosesan kartu kredit menggunakan kredensial yang disimpan di luar lokasi oleh prosesor.";
$lang['AdminMerchant.getsupportedfeatures.tooltip_cc_form'] = "Ini memungkinkan gateway untuk menyediakan html khusus untuk formulir kartu kredit. Ini dimaksudkan untuk mendukung kartu kredit di luar kantor yang mungkin menggunakan iframe atau memerlukan bidang tambahan.";
$lang['AdminMerchant.getsupportedfeatures.tooltip_ach'] = "Pemrosesan clearing house otomatis menggunakan kredensial yang tidak disimpan atau yang disimpan di Blesta.";
$lang['AdminMerchant.getsupportedfeatures.tooltip_ach_offsite'] = "Pemrosesan clearing house otomatis menggunakan kredensial yang disimpan di luar lokasi oleh prosesor.";
$lang['AdminMerchant.index.page_title'] = "Generator Ekstensi"; // %1$s is the plugin name
$lang['AdminMerchant.index.boxtitle_extension_generator'] = "Generator Ekstensi - Gerbang Pedagang";
$lang['AdminMerchant.basic.heading_basic'] = "Informasi dasar";
$lang['AdminMerchant.basic.heading_authors'] = "Penulis";
$lang['AdminMerchant.basic.description'] = "Deskripsi";
$lang['AdminMerchant.basic.logo'] = "Logo";
$lang['AdminMerchant.basic.signup_url'] = "URL Pendaftaran";
$lang['AdminMerchant.basic.currencies'] = "Mata Uang";
$lang['AdminMerchant.basic.author_name'] = "Nama Penulis";
$lang['AdminMerchant.basic.author_url'] = "URL penulis";
$lang['AdminMerchant.basic.text_options'] = "Pilihan";
$lang['AdminMerchant.basic.author_row_add'] = "Tambahkan Penulis";
$lang['AdminMerchant.basic.text_remove'] = "Menghapus";
$lang['AdminMerchant.basic.tooltip_description'] = "Deskripsi yang ditampilkan dalam daftar plugin";
$lang['AdminMerchant.basic.tooltip_logo'] = "Logo ditampilkan dalam daftar plugin. Gambar tidak diubah ukurannya, jadi dimensi idealnya adalah 150x70";
$lang['AdminMerchant.basic.tooltip_signup_url'] = "URL ke halaman pendaftaran gateway";
$lang['AdminMerchant.basic.tooltip_currencies'] = "Daftar mata uang yang didukung yang dipisahkan koma (mis. USD,JPY,EUR)";
$lang['AdminMerchant.basic.placeholder_signup_url'] = "e.g. https://dashboard.stripe.com/register";
$lang['AdminMerchant.basic.placeholder_currencies'] = "contoh. USD,EUR,JPY";
$lang['AdminMerchant.basic.placeholder_author_name'] = "e.g. Blesta";
$lang['AdminMerchant.basic.placeholder_author_url'] = "e.g. https://blesta.com/";
$lang['AdminMerchant.basic.fields'] = "Berikutnya - Bidang Konfigurasi";
$lang['AdminMerchant.basic.features'] = "Berikutnya - Fitur yang Didukung";
$lang['AdminMerchant.fields.heading_fields'] = "Bidang Konfigurasi";
$lang['AdminMerchant.fields.name'] = "Nama";
$lang['AdminMerchant.fields.label'] = "Label";
$lang['AdminMerchant.fields.type'] = "Jenis";
$lang['AdminMerchant.fields.tooltip'] = "Teks Tooltip";
$lang['AdminMerchant.fields.encryptable'] = "Dapat dienkripsi";
$lang['AdminMerchant.fields.tooltip_name'] = "Nama bidang dalam basis kode";
$lang['AdminMerchant.fields.tooltip_label'] = "Nama tampilan bidang";
$lang['AdminMerchant.fields.tooltip_type'] = "Jenis bidang yang akan dibuat (kotak centang, teks, dll.)";
$lang['AdminMerchant.fields.tooltip_tooltip'] = "Teks tooltip untuk ditampilkan di sepanjang sisi bidang (biarkan kosong agar tidak ada tooltip)";
$lang['AdminMerchant.fields.tooltip_encryptable'] = "Apakah akan mengenkripsi bidang ini di database";
$lang['AdminMerchant.fields.placeholder_name'] = "e.g. configuration_field";
$lang['AdminMerchant.fields.placeholder_label'] = "misalnya Bidang Konfigurasi";
$lang['AdminMerchant.fields.field_row_add'] = "Tambahkan Bidang Konfigurasi";
$lang['AdminMerchant.fields.text_options'] = "Pilihan";
$lang['AdminMerchant.fields.text_remove'] = "Menghapus";
$lang['AdminMerchant.fields.features'] = "Berikutnya - Fitur yang Didukung";
$lang['AdminMerchant.features.heading_supported_features'] = "Fitur yang Didukung";
$lang['AdminMerchant.features.confirm'] = "Selanjutnya - Konfirmasi";
?>