<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminNonmerchant.index.page_title'] = "Generator Ekstensi - %1\$s"; // %1$s is the plugin name
$lang['AdminNonmerchant.index.boxtitle_extension_generator'] = "Generator Ekstensi - Gerbang Non-Pedagang";
$lang['AdminNonmerchant.basic.heading_basic'] = "Informasi dasar";
$lang['AdminNonmerchant.basic.heading_authors'] = "Penulis";
$lang['AdminNonmerchant.basic.description'] = "Deskripsi";
$lang['AdminNonmerchant.basic.logo'] = "Logo";
$lang['AdminNonmerchant.basic.signup_url'] = "URL Pendaftaran";
$lang['AdminNonmerchant.basic.currencies'] = "mata uang";
$lang['AdminNonmerchant.basic.author_name'] = "Nama Penulis";
$lang['AdminNonmerchant.basic.author_url'] = "URL penulis";
$lang['AdminNonmerchant.basic.text_options'] = "Pilihan";
$lang['AdminNonmerchant.basic.author_row_add'] = "Tambahkan Penulis";
$lang['AdminNonmerchant.basic.text_remove'] = "Hapus";
$lang['AdminNonmerchant.basic.tooltip_description'] = "Deskripsi yang ditampilkan dalam daftar plugin";
$lang['AdminNonmerchant.basic.tooltip_logo'] = "Logo ditampilkan dalam daftar plugin. Gambar tidak diubah ukurannya, jadi dimensi idealnya adalah 150x70";
$lang['AdminNonmerchant.basic.tooltip_signup_url'] = "URL ke halaman pendaftaran gateway";
$lang['AdminNonmerchant.basic.tooltip_currencies'] = "Daftar mata uang yang didukung yang dipisahkan koma (mis. USD,JPY,EUR)";
$lang['AdminNonmerchant.basic.placeholder_signup_url'] = "mis. https://dashboard.stripe.com/register";
$lang['AdminNonmerchant.basic.placeholder_currencies'] = "e.g. USD,EUR,JPY";
$lang['AdminNonmerchant.basic.placeholder_author_name'] = "e.g. Blesta";
$lang['AdminNonmerchant.basic.placeholder_author_url'] = "e.g. https://blesta.com/";
$lang['AdminNonmerchant.basic.fields'] = "Berikutnya - Bidang Konfigurasi";
$lang['AdminNonmerchant.basic.confirm'] = "Selanjutnya - Konfirmasi";
$lang['AdminNonmerchant.fields.heading_fields'] = "Bidang Konfigurasi";
$lang['AdminNonmerchant.fields.name'] = "Nama";
$lang['AdminNonmerchant.fields.label'] = "Label";
$lang['AdminNonmerchant.fields.type'] = "Tipe";
$lang['AdminNonmerchant.fields.tooltip'] = "Teks Tooltip";
$lang['AdminNonmerchant.fields.encryptable'] = "Dapat dienkripsi";
$lang['AdminNonmerchant.fields.tooltip_name'] = "Nama bidang dalam basis kode";
$lang['AdminNonmerchant.fields.tooltip_label'] = "Nama tampilan bidang";
$lang['AdminNonmerchant.fields.tooltip_type'] = "Jenis bidang yang akan dibuat (kotak centang, teks, dll.)";
$lang['AdminNonmerchant.fields.tooltip_tooltip'] = "Teks tooltip untuk ditampilkan di sepanjang sisi bidang (biarkan kosong agar tidak ada tooltip)";
$lang['AdminNonmerchant.fields.tooltip_encryptable'] = "Apakah akan mengenkripsi bidang ini di database";
$lang['AdminNonmerchant.fields.placeholder_name'] = "mis. configuration_field";
$lang['AdminNonmerchant.fields.placeholder_label'] = "misalnya Bidang Konfigurasi";
$lang['AdminNonmerchant.fields.field_row_add'] = "Tambahkan Bidang Konfigurasi";
$lang['AdminNonmerchant.fields.text_options'] = "Pilihan";
$lang['AdminNonmerchant.fields.text_remove'] = "Menghapus";
$lang['AdminNonmerchant.fields.features'] = "Berikutnya - Fitur Tambahan";
$lang['AdminNonmerchant.features.heading_optional_functions'] = "Fungsi Opsional";
$lang['AdminNonmerchant.features.confirm'] = "Selanjutnya - Konfirmasi";
?>