<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ExtensionGeneratorExtensions.!error.name.empty'] = "Harap masukkan nama ekstensi.";
$lang['ExtensionGeneratorExtensions.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['ExtensionGeneratorExtensions.!error.date_updated.format'] = "Format pembaruan tanggal tidak valid.";
$lang['ExtensionGeneratorExtensions.!error.type.valid'] = "Jenis ekstensi tidak valid.";
$lang['ExtensionGeneratorExtensions.!error.form_type.valid'] = "Jenis formulir tidak valid.";
$lang['ExtensionGeneratorExtensions.!error.code_examples.format'] = "Format opsi contoh kode tidak valid.";
$lang['ExtensionGeneratorExtensions.!error.id.exists'] = "ID ekstensi yang diberikan tidak valid.";
$lang['ExtensionGeneratorExtensions.gettypes.module'] = "Modul";
$lang['ExtensionGeneratorExtensions.gettypes.plugin'] = "Plugin";
$lang['ExtensionGeneratorExtensions.gettypes.merchant'] = "Gerbang Pedagang";
$lang['ExtensionGeneratorExtensions.gettypes.nonmerchant'] = "Gerbang Non-Pedagang";
$lang['ExtensionGeneratorExtensions.getformtypes.basic'] = "Dasar";
$lang['ExtensionGeneratorExtensions.getformtypes.advanced'] = "Maju";
?>