<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ExtensionGeneratorController.getnodes.general_settings'] = "Pengaturan Umum";
$lang['ExtensionGeneratorController.getnodes.basic_info'] = "Info dasar";
$lang['ExtensionGeneratorController.getnodes.plugin_database'] = "Informasi Basis Data";
$lang['ExtensionGeneratorController.getnodes.plugin_integrations'] = "Integrasi Inti";
$lang['ExtensionGeneratorController.getnodes.module_fields'] = "Bidang Modul";
$lang['ExtensionGeneratorController.getnodes.merchant_fields'] = "Bidang Konfigurasi";
$lang['ExtensionGeneratorController.getnodes.merchant_features'] = "Fitur yang Didukung";
$lang['ExtensionGeneratorController.getnodes.nonmerchant_fields'] = "Bidang Konfigurasi";
$lang['ExtensionGeneratorController.getnodes.additional_features'] = "Fitur tambahan";
$lang['ExtensionGeneratorController.getnodes.confirm'] = "Konfirmasi";
$lang['ExtensionGeneratorController.getfieldtypes.text'] = "Teks";
$lang['ExtensionGeneratorController.getfieldtypes.textarea'] = "Area teks";
$lang['ExtensionGeneratorController.getfieldtypes.checkbox'] = "kotak centang";
$lang['ExtensionGeneratorController.gettablevels.staff'] = "Staf";
$lang['ExtensionGeneratorController.gettablevels.client'] = "Klien";
$lang['ExtensionGeneratorController.gettasktypes.time'] = "Waktu";
$lang['ExtensionGeneratorController.gettasktypes.interval'] = "Selang";
?>