<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Ccavenue.name'] = "Pembayaran CCAvenue";
$lang['Ccavenue.buildprocess.submit'] = "Membayar melalui CCAvenue";
$lang['Ccavenue.!error.merchant_id.valid'] = "Cukup masukkan ID pedagang yang valid.";
$lang['Ccavenue.!error.pending.log'] = "Status pembayaran yang diterima tertunda dari gateway.";
$lang['Ccavenue.!error.delay.response'] = "Terima kasih telah berbelanja dengan kami. Kami akan terus mengabari Anda mengenai status pesanan Anda melalui email";
$lang['Ccavenue.!error.security.response'] = "Kesalahan keamanan. Akses ilegal terdeteksi.";
$lang['Ccavenue.!error.authentication.response'] = "Terima kasih telah berbelanja dengan kami. Namun, transaksi tersebut ditolak. Silahkan ulangi transaksinya.";
$lang['Ccavenue.!error.authentication.log'] = "Transaksi telah ditolak dari bank.";
$lang['Ccavenue.encryption_key'] = "Kunci enkripsi";
$lang['Ccavenue.encryption_key_note'] = "Ini dibuat di akun CCAvenue Anda di bawah Kunci API.";
$lang['Ccavenue.access_code'] = "Kode Akses";
$lang['Ccavenue.access_code_note'] = "Hal ini dapat ditemukan di akun CCAvenue Anda di bawah Keys API.";
$lang['Ccavenue.test_mode'] = "Modus Uji";
$lang['Ccavenue.test_mode_note'] = "Jika dicentang, gateway akan mengirimkan permintaan pembayaran ke URL test";
$lang['Ccavenue.!error.access_code.empty'] = "Silakan masukkan kode akses
";
$lang['Ccavenue.!error.encryption_key.valid'] = "Masukkan kunci enkripsi.";
$lang['Ccavenue.merchant_id'] = "ID Pedagang";
$lang['Ccavenue.merchant_id_note'] = "ID pedagang Anda tersedia di akun CCAvenue Anda di bawah Kunci API";
$lang['Ccavenue.description'] = "Dengan lebih dari 240 opsi pembayaran yang menghubungkan lebih dari 55 bank India secara real-time, CCAvenue adalah salah satu mesin debit langsung terbesar di India";
?>
