<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminPayouts.!success.payout_updated'] = "Pembayaran telah berhasil diperbarui.";
$lang['AdminPayouts.!success.payout_approved'] = "Pembayaran berhasil disetujui.";
$lang['AdminPayouts.!success.payout_declined'] = "Pembayaran berhasil ditolak.";
$lang['AdminPayouts.!error.insufficient_funds_payout_request'] = "Dana tidak cukup untuk memproses permintaan pembayaran.";
$lang['AdminPayouts.index.boxtitle_payouts'] = "Pembayaran Afiliasi";
$lang['AdminPayouts.index.category_approved'] = "Disetujui";
$lang['AdminPayouts.index.category_pending'] = "Tertunda";
$lang['AdminPayouts.index.category_declined'] = "ditolak";
$lang['AdminPayouts.index.heading_payout_id'] = "ID pembayaran";
$lang['AdminPayouts.index.heading_name'] = "Klien";
$lang['AdminPayouts.index.heading_code'] = "Kode";
$lang['AdminPayouts.index.heading_payment_method_id'] = "Metode Pembayaran";
$lang['AdminPayouts.index.heading_requested_amount'] = "Jumlah yang diminta";
$lang['AdminPayouts.index.heading_requested_currency'] = "Mata Uang yang Diminta";
$lang['AdminPayouts.index.heading_paid_amount'] = "Jumlah pembayaran";
$lang['AdminPayouts.index.heading_paid_currency'] = "Mata Uang Dibayar";
$lang['AdminPayouts.index.heading_date_requested'] = "Tanggal Diminta";
$lang['AdminPayouts.index.heading_options'] = "Pilihan";
$lang['AdminPayouts.index.option_edit'] = "Sunting";
$lang['AdminPayouts.index.option_approve'] = "Menyetujui";
$lang['AdminPayouts.index.option_decline'] = "Menurun";
$lang['AdminPayouts.index.confirm_approve'] = "Apakah Anda yakin ingin menyetujui pembayaran ini?";
$lang['AdminPayouts.index.confirm_decline'] = "Apakah Anda yakin ingin menolak pembayaran ini?";
$lang['AdminPayouts.index.no_results'] = "Tidak ada permintaan pembayaran saat ini.";
$lang['AdminPayouts.index.payment_method_na'] = "N/A";
$lang['AdminPayouts.edit.boxtitle_edit_payout'] = "Sunting Pembayaran";
$lang['AdminPayouts.edit.heading_payout_request'] = "Permintaan Pembayaran";
$lang['AdminPayouts.edit.field_payment_method_id'] = "Cara Pembayaran";
$lang['AdminPayouts.edit.field_requested_amount'] = "Jumlah yang diminta";
$lang['AdminPayouts.edit.field_requested_currency'] = "Mata Uang yang Diminta";
$lang['AdminPayouts.edit.field_status'] = "Status";
$lang['AdminPayouts.edit.modify_payout'] = "Ubah Pembayaran";
?>