<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.status_updated'] = "Order yang dipilih telah berhasil diperbarui.";
$lang['AdminMain.!success.settings_updated'] = "Pengaturan pemesanan Anda berhasi diperbarui.";
$lang['AdminMain.index.boxtitle_order'] = "Pesanan";
$lang['AdminMain.index.no_results'] = "Tidak ada pesanan dari jenis ini.";
$lang['AdminMain.index.category_accepted'] = "diterima";
$lang['AdminMain.index.category_fraud'] = "Penipuan";
$lang['AdminMain.index.heading_order_number'] = "Memesan #";
$lang['AdminMain.index.heading_client_id_code'] = "ID Klien";
$lang['AdminMain.index.heading_invoice_id_code'] = "Faktur #";
$lang['AdminMain.index.heading_total'] = "Total";
$lang['AdminMain.index.heading_paid'] = "Dibayar";
$lang['AdminMain.index.heading_date_added'] = "Tanggal pesan";
$lang['AdminMain.index.field_ordersubmit'] = "Perbarui Pesanan";
$lang['AdminMain.orderinfo.fraudreport_heading'] = "Laporan Penipuan ";
$lang['AdminMain.orderinfo.fraudreport_heading_key'] = "Key";
$lang['AdminMain.orderinfo.fraudreport_heading_value'] = "Nilai";
$lang['AdminMain.orderinfo.applied_heading'] = "Transaksi";
$lang['AdminMain.orderinfo.applied_heading_paymenttype'] = "Tipe pembayaran";
$lang['AdminMain.orderinfo.applied_heading_amount'] = "Jumlah";
$lang['AdminMain.orderinfo.applied_heading_applied'] = "Terapan";
$lang['AdminMain.orderinfo.applied_heading_appliedon'] = "Terapan Pada";
$lang['AdminMain.orderinfo.applied_heading_options'] = "Pilihan";
$lang['AdminMain.orderinfo.applied_option_edit'] = "Sunting";
$lang['AdminMain.orderinfo.applied_no_results'] = "Tidak ada transaksi diterapkan untuk pesanan ini";
$lang['AdminMain.orderinfo.services_heading'] = "Layanan";
$lang['AdminMain.orderinfo.services_heading_package'] = "Paket";
$lang['AdminMain.orderinfo.services_heading_label'] = "label";
$lang['AdminMain.orderinfo.services_heading_term'] = "Periode";
$lang['AdminMain.orderinfo.services_heading_dateadded'] = "Tanggal Ditambahkan";
$lang['AdminMain.orderinfo.services_heading_daterenews'] = "Pembaruan Tanggal";
$lang['AdminMain.orderinfo.services_heading_options'] = "Pilihan";
$lang['AdminMain.orderinfo.services_option_manage'] = "Mengelola";
$lang['AdminMain.orderinfo.services_text_never'] = "Tak pernah";
$lang['AdminMain.orderinfo.services_no_results'] = "Tidak ada layanan dalam urutan ini.";
$lang['AdminMain.settings.heading_notifications'] = "Pemberitahuan Order";
$lang['AdminMain.settings.field_email_notice'] = "Email";
$lang['AdminMain.settings.field_email_notice_never'] = "Jangan dikirim";
$lang['AdminMain.settings.field_email_notice_manual'] = "Hanya kirim jika diperlukan persetujuan manual";
$lang['AdminMain.settings.field_email_notice_always'] = "Selalu kirim";
$lang['AdminMain.settings.field_mobile_notice'] = "Seluler";
$lang['AdminMain.settings.field_mobile_notice_never'] = "Jangan dikirim";
$lang['AdminMain.settings.field_mobile_notice_manual'] = "Hanya mengirim jika persetujuan manual diperlukan";
$lang['AdminMain.settings.field_mobile_notice_always'] = "Selalu kirim";
$lang['AdminMain.settings.submit_settings'] = "Perbarui Pengaturan";
$lang['AdminMain.settings.submit_cancel'] = "Kembali ke daftar orderan";
$lang['AdminMain.index.category_canceled'] = "Dibatalkan";
$lang['AdminMain.index.field_markas'] = "Tandai sebagai:";
$lang['AdminMain.index.text_location'] = "Lokasi";
$lang['AdminMain.index.category_pending'] = "Dalam Ulasan";
$lang['AdminMain.search.page_title'] = "Hasil Pencarian untuk \"%1\$s\""; // %1$s is the search keywords
$lang['AdminMain.search.boxtitle_order'] = "Telusuri Pesanan untuk \"%1\$s\""; // %1$s is the search keywords
$lang['AdminMain.!success.affiliate_settings_updated'] = "Pengaturan afiliasi telah diperbarui.";
$lang['AdminMain.settings.heading_affiliate_notifications'] = "Pemberitahuan Afiliasi";
$lang['AdminMain.settings.field_payout_notice'] = "Pembayaran";
$lang['AdminMain.settings.field_payout_notice_never'] = "Tidak pernah";
$lang['AdminMain.settings.field_payout_notice_always'] = "Selalu";
$lang['AdminMain.affiliates.page_title'] = "Ikhtisar Afiliasi";
$lang['AdminMain.affiliates.boxtitle_affiliates'] = "Ikhtisar Afiliasi";
$lang['AdminMain.affiliates.inactive'] = "Afiliasi ini telah ditandai tidak aktif.";
$lang['AdminMain.affiliates.activate'] = "Klik di sini untuk mengaktifkan kembali";
$lang['AdminMain.affiliates.no_results'] = "Tidak ada afiliasi yang terkait dengan klien ini. Klik di sini untuk mendaftar.";
$lang['AdminMain.affiliates.title_details'] = "Detail";
$lang['AdminMain.affiliates.title_referral'] = "Tautan Rujukan";
$lang['AdminMain.affiliates.visits'] = "Klik";
$lang['AdminMain.affiliates.monthly_visits'] = "%1\$s/bln rata-rata"; // %1$s is the number of average monthly visits
$lang['AdminMain.affiliates.sales'] = "Total Penjualan";
$lang['AdminMain.affiliates.monthly_sales'] = "%1\$s/bln rata-rata"; // %1$s is the number of average monthly sales
$lang['AdminMain.affiliates.conversion_rate'] = "Tingkat konversi";
$lang['AdminMain.affiliates.conversion_fraction'] = "%1\$s/%2\$s rata-rata"; // %1$s 1 or 0 if there are no sales, %2$s is the average number of visits per sale
$lang['AdminMain.affiliates.commission_type'] = "Tingkat Pembayaran";
$lang['AdminMain.affiliates.min_withdrawal_amount'] = "Jumlah Pembayaran Minimum";
$lang['AdminMain.affiliates.maturity_days'] = "Hari untuk Dewasa";
$lang['AdminMain.affiliates.available_payout'] = "Tersedia untuk Pembayaran";
$lang['AdminMain.affiliates.field.commission_fixed'] = "%1\$s satu kali untuk setiap referral yang sudah matang"; // %1$s is the commission amount
$lang['AdminMain.affiliates.field.commission_percentage'] = "%1\$s dari setiap rujukan yang telah matang"; // %1$s is the commission percentage
$lang['AdminMain.affiliates.request_payout'] = "Minta Pembayaran";
$lang['AdminMain.affiliates.boxtitle_client'] = "Klien #%1\$s - %2\$s %3\$s";
$lang['AdminMain.affiliates.heading_affiliates'] = "Pengaturan Afiliasi";
$lang['AdminMain.affiliates.heading_referral_link'] = "Tautan Rujukan";
$lang['AdminMain.affiliates.field_commission_type'] = "Jenis Komisi";
$lang['AdminMain.affiliates.tooltip_commission_type'] = "Metode perhitungan yang digunakan untuk menentukan komisi referral. Baik nilai tetap per pesanan atau persentase dari total pesanan.";
$lang['AdminMain.affiliates.field_commission_amount'] = "Jumlah Komisi";
$lang['AdminMain.affiliates.field_order_frequency'] = "Frekuensi Pemesanan";
$lang['AdminMain.affiliates.tooltip_order_frequency'] = "Pertama untuk membayar rujukan hanya untuk pesanan pertama yang dibuat klien menggunakan tautan rujukan, atau Any untuk membayar rujukan untuk setiap pesanan yang dibuat klien menggunakan tautan rujukan.";
$lang['AdminMain.affiliates.field_order_recurring'] = "Pesanan Berulang";
$lang['AdminMain.affiliates.tooltip_order_recurring'] = "Apakah rujukan akan dibayar untuk layanan yang dipesan yang diperbarui.";
$lang['AdminMain.affiliates.field_maturity_days'] = "Hari Kedewasaan";
$lang['AdminMain.affiliates.tooltip_maturity_days'] = "Jumlah hari setelah pembayaran, rujukan jatuh tempo dan tersedia untuk pembayaran.";
$lang['AdminMain.affiliates.field_min_withdrawal_amount'] = "Jumlah Penarikan Minimum";
$lang['AdminMain.affiliates.field_max_withdrawal_amount'] = "Jumlah Penarikan Maksimum";
$lang['AdminMain.affiliates.field_withdrawal_currency'] = "Mata Uang Penarikan";
$lang['AdminMain.affiliates.text_code_order_form'] = "Anda juga dapat menautkan ke halaman formulir pemesanan tertentu sebagai afiliasi dengan menambahkan di akhir ?a=%1\$s ke tautan tanpa parameter kueri atau &a=%1\$s ke tautan dengan parameter kueri.";
$lang['AdminMain.affiliates.heading_statistics'] = "Statistik";
$lang['AdminMain.affiliates.graph_referrals'] = "Rujukan";
$lang['AdminMain.affiliates.graph_visits'] = "Kunjugan";
$lang['AdminMain.affiliates.graph_sales'] = "Penjualan";
$lang['AdminMain.affiliates.submit_settings'] = "Simpan Pengaturan";
$lang['AdminMain.affiliates.submit_cancel'] = "Membatalkan";
$lang['AdminMain.settings.field_messenger_notice'] = "Messengers";
$lang['AdminMain.settings.field_messenger_notice_never'] = "Jangan dikirim";
$lang['AdminMain.settings.field_messenger_notice_manual'] = "Hanya kirim jika diperlukan persetujuan manual";
$lang['AdminMain.settings.field_messenger_notice_always'] = "Selalu kirim";
?>