<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminForms.!success.settings_saved'] = "Pengaturan berhasil disimpan";
$lang['AdminForms.!success.form_added'] = " form telah ditambahkan.";
$lang['AdminForms.!success.form_delete'] = "Formulir telah dihapus";
$lang['AdminForms.!success.form_edited'] = "form berhasil diperbarui.";
$lang['AdminForms.index.page_title'] = "Sistem Pemesanan";
$lang['AdminForms.settings.page_title'] = "System Order";
$lang['AdminForms.add.page_title'] = "Sistem Pemesanan";
$lang['AdminForms.edit.page_title'] = "Sistem Pemesanan";
$lang['AdminForms.index.boxtitle_order'] = "Sistem Order";
$lang['AdminForms.index.tab_forms'] = "Form Pesanan";
$lang['AdminForms.index.tab_settings'] = "Pengaturan";
$lang['AdminForms.index.order_form_add'] = "Tambah Form Order";
$lang['AdminForms.index.order_forms_no_results'] = "Tidak ada formulir pemesanan saat ini.";
$lang['AdminForms.index.heading_name'] = "Nama";
$lang['AdminForms.index.heading_label'] = "Label";
$lang['AdminForms.index.heading_template'] = "Template";
$lang['AdminForms.index.heading_type'] = "Jenis";
$lang['AdminForms.index.heading_date_added'] = "Tanggal Ditambahkan";
$lang['AdminForms.index.heading_status'] = "Status";
$lang['AdminForms.index.heading_options'] = "Pilihan";
$lang['AdminForms.index.option_edit'] = "Edit";
$lang['AdminForms.index.option_delete'] = "Hapus";
$lang['AdminForms.index.text_confirm_delete'] = "Benar-benar menghapus order form ini?";
$lang['AdminForms.index.field_status_active'] = "Aktif";
$lang['AdminForms.index.field_status_inactive'] = "Non-aktif";
$lang['AdminForms.add.boxtitle_order'] = "Sistem Pesanan - Tambah Formulir";
$lang['AdminForms.add.field_name'] = "Nama";
$lang['AdminForms.add.field_label'] = "Label";
$lang['AdminForms.add.field_type'] = "Jenis";
$lang['AdminForms.add.field_allow_coupons'] = "Izinkan Kupon";
$lang['AdminForms.add.field_manual_review'] = "Membutuhkan Pedoman Ulasan dan Persetujuan Semua Pesanan";
$lang['AdminForms.add.field_require_ssl'] = "Paksa koneksi Aman (HTTPS)";
$lang['AdminForms.add.field_require_captcha'] = "Membutuhkan Tantangan Verifikasi Manusia / bukan bot untuk Semua Pendaftaran";
$lang['AdminForms.add.field_require_tos'] = "Memerlukan Perjanjian untuk Persyaratan Layanan";
$lang['AdminForms.add.field_tos_url'] = "URL Persyaratan Layanan";
$lang['AdminForms.add.field_status'] = "Status";
$lang['AdminForms.add.field_status_active'] = "Aktif";
$lang['AdminForms.add.field_status_inactive'] = "Tidak aktif";
$lang['AdminForms.add.field_template'] = "Template";
$lang['AdminForms.add.field_client_group_id'] = "Klien Grup standar";
$lang['AdminForms.add.tooltip_client_group'] = "Pendaftaran baru grup klien default dari formulir ini akan ditetapkan.";
$lang['AdminForms.add.field_addsubmit'] = "Tambahkan Form";
$lang['AdminForms.add.heading_basic'] = "Dasar";
$lang['AdminForms.edit.boxtitle_order'] = "Sistem Order - Form Edit";
$lang['AdminForms.edit.field_name'] = "Nama";
$lang['AdminForms.edit.field_label'] = "Label";
$lang['AdminForms.edit.field_type'] = "Jenis";
$lang['AdminForms.edit.field_allow_coupons'] = "Izinkan Kupon";
$lang['AdminForms.edit.field_manual_review'] = "Membutuhkan Tinjauan Manual dan Persetujuan Untuk Semua Pesanan";
$lang['AdminForms.edit.field_require_ssl'] = "Paksa Menggunakan Koneksi Aman (HTTPS)";
$lang['AdminForms.edit.field_require_tos'] = "Membutuhkan Kesediaan anda untuk menyetujui persyaratan Layanan";
$lang['AdminForms.edit.field_require_captcha'] = "Wajibkan Tantangan Verifikasi Manusia untuk Semua Pendaftaran";
$lang['AdminForms.edit.field_tos_url'] = "URL Ketentuan Layanan";
$lang['AdminForms.edit.field_status'] = "Status";
$lang['AdminForms.edit.field_status_active'] = "Aktif";
$lang['AdminForms.edit.field_status_inactive'] = "Tidak aktif";
$lang['AdminForms.edit.field_template'] = "Templat";
$lang['AdminForms.edit.field_client_group_id'] = "Klien Group Default";
$lang['AdminForms.edit.tooltip_client_group'] = "Kelompok default klien pendaftaran baru dari formulir ini akan ditugaskan untuk.";
$lang['AdminForms.edit.field_addsubmit'] = "Sunting Formulir";
$lang['AdminForms.edit.heading_basic'] = "Dasar";
$lang['AdminForms.meta.text_membergroups'] = "Ditugaskan Di Grup";
$lang['AdminForms.meta.text_availablegroups'] = "Grup yang Tersedia";
$lang['AdminForms.meta.heading_package_groups'] = "Grup Paket";
$lang['AdminForms.meta.heading_package_group'] = "Grup Paket";
$lang['AdminForms.meta.heading_currencies'] = "Mata Uang";
$lang['AdminForms.meta.heading_gateways'] = "Gateway";
$lang['AdminForms.settings.boxtitle_order'] = "Sistem Pemesanan";
$lang['AdminForms.settings.basic_heading'] = "Opsi Dasar";
$lang['AdminForms.settings.field_default_form'] = "Formulir Pemesanan Standar";
$lang['AdminForms.settings.antifraud_heading'] = "Anti-Fraud";
$lang['AdminForms.settings.field_antifraud'] = "Jenis";
$lang['AdminForms.settings.field_antifraud.none'] = "Tidak ada";
$lang['AdminForms.settings.field_save'] = "Simpan Pengaturan";
$lang['AdminForms.add.template_preview'] = "Preview";
$lang['AdminForms.edit.template_preview'] = "Pratinjau";
$lang['AdminForms.add.field_description'] = "Deskripsi";
$lang['AdminForms.add.field_visibility'] = "Visibilitas";
$lang['AdminForms.edit.field_description'] = "Deskripsi";
$lang['AdminForms.edit.field_visibility'] = "Visibilitas";
$lang['AdminForms.settings.default_form.none'] = "Tidak Ada - Tampilkan Daftar";
$lang['AdminForms.settings.field_antifraud_frequency'] = "Frekuensi Anti-Penipuan";
$lang['AdminForms.settings.field_antifraud_frequency.always'] = "Jalankan pemeriksaan penipuan untuk semua pesanan dan pendaftaran pelanggan";
$lang['AdminForms.settings.field_antifraud_frequency.new'] = "Jalankan pemeriksaan penipuan hanya untuk pendaftaran pelanggan";
$lang['AdminForms.meta.text_drag_and_drop'] = "Seret & Lepas Grup Di Sini";
$lang['AdminForms.meta.tooltip_text_membergroups'] = "Grup paket akan muncul di formulir pemesanan dalam urutan yang terlihat di sini.";
$lang['AdminForms.settings.embed_code_heading'] = "Sematkan Kode";
$lang['AdminForms.settings.field_tags'] = "Tags";
$lang['AdminForms.settings.field_embed_code'] = "Kode Sematkan Formulir Pemesanan";
$lang['AdminForms.settings.marketing_heading'] = "Pemasaran";
$lang['AdminForms.settings.field_marketing_default'] = "Pemasaran Email Klien";
$lang['AdminForms.settings.field_marketing_default.true'] = "Opsi untuk menerima pemasaran email akan dipilih secara default";
$lang['AdminForms.settings.field_marketing_default.false'] = "Opsi untuk menerima pemasaran email harus dipilih oleh klien";
$lang['AdminForms.settings.tooltip_marketing_default_true'] = "Opsi ini akan ditampilkan di halaman pendaftaran klien, dipilih untuk mengikutsertakan mereka dalam pemasaran email.";
$lang['AdminForms.settings.tooltip_marketing_default_false'] = "Opsi ini akan ditampilkan di halaman pendaftaran klien, tidak dipilih untuk menyisih dari pemasaran email.";
$lang['AdminForms.settings.field_antifraud_after_validate'] = "Verifikasi data input pendaftaran klien baru melewati validasi sebelum menggunakannya untuk pemeriksaan anti-penipuan.";
$lang['AdminForms.settings.registration_heading'] = "Penggantian Pendaftaran Baru";
$lang['AdminForms.settings.text_accepted_payment_types'] = "Saat seseorang mendaftar untuk akun klien baru, hanya jenis pembayaran yang dipilih yang akan tersedia untuk diproses melalui gateway atau untuk membuat akun pembayaran.";
$lang['AdminForms.settings.payments_allowed_cc'] = "Kartu kredit";
$lang['AdminForms.settings.payments_allowed_ach'] = "Lembaga Kliring Otomatis";
$lang['AdminForms.settings.email_verification_heading'] = "Verifikasi email";
$lang['AdminForms.settings.hold_unverified_orders'] = "Tahan Pesanan dari Klien yang Belum Terverifikasi";
?>