<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminAffiliates.!success.affiliate_added'] = "Afiliasi berhasil ditambahkan.";
$lang['AdminAffiliates.!success.settings_updated'] = "Pengaturan afiliasi telah diperbarui.";
$lang['AdminAffiliates.!success.affiliate_activated'] = "Afiliasi berhasil diaktifkan.";
$lang['AdminAffiliates.!success.affiliate_deactivated'] = "Afiliasi berhasil dinonaktifkan.";
$lang['AdminAffiliates.!success.affilates_enabled'] = "Sistem afiliasi berhasil diaktifkan.";
$lang['AdminAffiliates.leftnav.nav_affiliates'] = "Afiliasi";
$lang['AdminAffiliates.leftnav.nav_payouts'] = "Pembayaran";
$lang['AdminAffiliates.leftnav.nav_settings'] = "Pengaturan";
$lang['AdminAffiliates.leftnav.nav_settings_general'] = "Pengaturan Umum";
$lang['AdminAffiliates.leftnav.nav_settings_payment_methods'] = "Metode Pembayaran";
$lang['AdminAffiliates.index.page_title'] = "Ikhtisar Afiliasi";
$lang['AdminAffiliates.index.boxtitle_affiliates'] = "Afiliasi";
$lang['AdminAffiliates.index.category_active'] = "Aktif";
$lang['AdminAffiliates.index.category_inactive'] = "Tidak Aktif";
$lang['AdminAffiliates.index.order_affiliate_add'] = "Tambahkan Affiliate";
$lang['AdminAffiliates.index.no_results'] = "Tidak ada pesanan afiliasi saat ini.";
$lang['AdminAffiliates.index.disable_affiliates'] = "Untuk menonaktifkan halaman afiliasi dan menghapus link navigasi yang terkait dengan sistem afiliasi, gunakan tab tindakan halaman pengaturan plugin Order.";
$lang['AdminAffiliates.index.heading_name'] = "Klien";
$lang['AdminAffiliates.index.heading_code'] = "Kode";
$lang['AdminAffiliates.index.heading_visits'] = "Kunjungan";
$lang['AdminAffiliates.index.heading_sales'] = "Sales";
$lang['AdminAffiliates.index.heading_date_added'] = "Tanggal Ditambahkan";
$lang['AdminAffiliates.index.heading_date_updated'] = "Tanggal Diperbarui";
$lang['AdminAffiliates.index.heading_options'] = "Opsi / Pilihan";
$lang['AdminAffiliates.index.option_manage'] = "Kelola";
$lang['AdminAffiliates.index.option_deactivate'] = "Menonaktifkan";
$lang['AdminAffiliates.index.option_activate'] = "Aktif";
$lang['AdminAffiliates.index.confirm_deactivate'] = "Anda yakin ingin menonaktifkan afiliasi ini?";
$lang['AdminAffiliates.index.confirm_activate'] = "Anda yakin ingin mengaktifkan afiliasi ini?";
$lang['AdminAffiliates.index.text_enable'] = "Sistem afiliasi saat ini dinonaktifkan. Klik tombol aktifkan untuk mengaktifkan sistem afiliasi dan mengizinkan afiliasi untuk mulai mendaftar dan membuat referensi.";
$lang['AdminAffiliates.index.enable'] = "Aktifkan Sistem Afiliasi";
$lang['AdminAffiliates.add.boxtitle_order'] = "Pesan - Tambahkan Afiliasi";
$lang['AdminAffiliates.add.field_client'] = "Klien";
$lang['AdminAffiliates.add.client_placeholder'] = "ID atau Nama Klien";
$lang['AdminAffiliates.add.field_status'] = "Status";
$lang['AdminAffiliates.add.field_addsubmit'] = "Tambahkan Afiliasi";
$lang['AdminAffiliates.add.text_no_clients'] = "Klien tidak ditemukan. Coba cari lagi.";
$lang['AdminAffiliates.leftnav.nav_settings_excluded_packages'] = "Paket yang Dikecualikan";
?>