<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderAffiliateReferrals.!error.referral_id.exists'] = "ID rujukan tidak valid.";
$lang['OrderAffiliateReferrals.!error.affiliate_id.exists'] = "ID afiliasi tidak valid.";
$lang['OrderAffiliateReferrals.!error.order_id.exists'] = "ID pesanan tidak valid.";
$lang['OrderAffiliateReferrals.!error.name.length'] = "Nama rujukan harus kurang dari 255 karakter.";
$lang['OrderAffiliateReferrals.!error.status.valid'] = "Silakan pilih status rujukan yang valid.";
$lang['OrderAffiliateReferrals.!error.amount.format'] = "Jumlah rujukan harus berupa angka.";
$lang['OrderAffiliateReferrals.!error.currency.length'] = "Kode mata uang harus terdiri dari 3 karakter.";
$lang['OrderAffiliateReferrals.!error.commission.format'] = "Komisi rujukan harus berupa angka.";
$lang['OrderAffiliateReferrals.!error.date_added.format'] = "Tanggal yang ditambahkan dalam format tanggal yang tidak valid.";
$lang['OrderAffiliateReferrals.!error.date_updated.format'] = "Tanggal yang diperbarui dalam format tanggal yang tidak valid.";
$lang['OrderAffiliateReferrals.getStatuses.pending'] = "Tertunda";
$lang['OrderAffiliateReferrals.getStatuses.mature'] = "Dewasa";
$lang['OrderAffiliateReferrals.getStatuses.canceled'] = "Dibatalkan";
?>