<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Orders.!success.order_canceled'] = "Pesanan berhasil dibatalkan.";
$lang['Orders.index.boxtitle_orders'] = "Riwayat Pemesanan";
$lang['Orders.index.heading_order_number'] = "Order #";
$lang['Orders.index.heading_status'] = "Status";
$lang['Orders.index.heading_invoice_number'] = "Faktur #";
$lang['Orders.index.heading_total'] = "Total";
$lang['Orders.index.heading_paid'] = "Dibayar";
$lang['Orders.index.heading_date_ordered'] = "Tanggal Dipesan";
$lang['Orders.index.heading_options'] = "Pilihan";
$lang['Orders.index.option_view'] = "Melihat";
$lang['Orders.index.option_cancel'] = "Membatalkan";
$lang['Orders.index.no_results'] = "Anda tidak memiliki perintah.";
$lang['Orders.view.boxtitle_view_order'] = "Tampilan Pemesanan";
$lang['Orders.view.heading_invoices'] = "Faktur";
$lang['Orders.view.heading_services'] = "Jasa";
$lang['Orders.view.heading_transactions'] = "Transaksi";
$lang['Orders.view.heading_invoice_number'] = "Faktur #";
$lang['Orders.view.heading_amount'] = "Jumlah";
$lang['Orders.view.heading_paid'] = "Dibayar";
$lang['Orders.view.heading_date_billed'] = "Tanggal Ditagih";
$lang['Orders.view.heading_package'] = "Paket";
$lang['Orders.view.heading_label'] = "Label";
$lang['Orders.view.heading_term'] = "Istilah";
$lang['Orders.view.heading_date_created'] = "Tanggal Diciptakan";
$lang['Orders.view.heading_date_renews'] = "Pembaruan Tanggal";
$lang['Orders.view.heading_options'] = "Pilihan";
$lang['Orders.view.heading_type'] = "Tipe";
$lang['Orders.view.heading_applied'] = "Terapan";
$lang['Orders.view.heading_status'] = "Status";
$lang['Orders.view.heading_number'] = "Nomor";
$lang['Orders.view.heading_date'] = "Tanggal";
$lang['Orders.view.option_view'] = "Melihat";
$lang['Orders.view.option_manage'] = "Pengaturan";
$lang['Orders.view.field_back_order_history'] = "Kembali ke Riwayat Pesanan";
$lang['Orders.view.no_invoices'] = "Tidak ada faktur yang terkait dengan pesanan ini.";
$lang['Orders.view.no_services'] = "Tidak ada layanan yang terkait dengan pesanan ini.";
$lang['Orders.view.no_transactions'] = "Tidak ada transaksi yang terkait dengan pesanan ini.";
$lang['Orders.view.recurring_term'] = "%1\$s %2\$s @ %3\$s"; // %1$s is the service term length (number), %2$s is the service period, %3$s is the formatted service renewal price
?>