<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Summary.index.totals.discount'] = "Diskon:";
$lang['Summary.index.totals.subtotal'] = "Subtotal:";
$lang['Summary.index.totals.total'] = "Total Jatuh Tempo Hari Ini:";
$lang['Summary.index.price'] = "@ %1\$s"; // %1$s is the price per term
$lang['Summary.index.totals.tax'] = "%1\$s:"; // %1$s is the tax name
$lang['Summary.index.totals.total_recurring'] = "Total Saat Memperbarui:";
$lang['Summary.index.totals.total_recurring_amount'] = "%1\$s %2\$s @ %3\$s"; // %1$s is the term, %2$s is the period, %3$s is the amount
?>