<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Csv1_0.!error.csv_data.invalid'] = "Data CSV yang diberikan tidak valid.";
$lang['Csv1_0.!error.import'] = "Impor selesai tetapi terjadi kesalahan berikut:";
$lang['Csv1_0.!error.required_fields'] = "Bidang berikut harus diimpor: Nama Pengguna, Nama Depan, Nama Belakang, Email, Telepon";
$lang['Csv1_0.settings.csv_data'] = "CSV Data";
$lang['Csv1_0.settings.enable_debug'] = "Aktifkan Debug";
$lang['Csv1_0.configuration.local_field'] = "Lapangan Lokal";
$lang['Csv1_0.configuration.remote_field'] = "Lapangan Terpencil";
$lang['Csv1_0.configuration.no_import'] = "Tidak ada Impor";
$lang['Csv1_0.configuration.username'] = "Nama pengguna";
$lang['Csv1_0.configuration.first_name'] = "Nama depan";
$lang['Csv1_0.configuration.last_name'] = "Nama keluarga";
$lang['Csv1_0.configuration.email'] = "Email";
$lang['Csv1_0.configuration.address1'] = "Alamat 1";
$lang['Csv1_0.configuration.address2'] = "alamat 2";
$lang['Csv1_0.configuration.state'] = "Negara";
$lang['Csv1_0.configuration.zip'] = "Kode Pos";
$lang['Csv1_0.configuration.city'] = "Kota";
$lang['Csv1_0.configuration.country'] = "Negara";
$lang['Csv1_0.configuration.phone'] = "Telepon";
$lang['Csv1_0.configuration.company'] = "Perusahaan";
$lang['Csv1_0.configuration.title'] = "Judul";
?>