<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Gocardless.name'] = "GoCardless";
$lang['Gocardless.access_token'] = "Token Akses";
$lang['Gocardless.webhook_secret'] = "Rahasia Webhook";
$lang['Gocardless.pay_type'] = "Opsi pembayaran";
$lang['Gocardless.pay_type_onetime'] = "Hanya satu kali pembayaran";
$lang['Gocardless.pay_type_subscribe'] = "Pembayaran berlangganan saja";
$lang['Gocardless.pay_type_both'] = "Pembayaran satu kali dan berlangganan bila memungkinkan";
$lang['Gocardless.dev_mode'] = "Mode pengembang";
$lang['Gocardless.dev_mode_note'] = "Mengaktifkan opsi ini akan memposting transaksi ke lingkungan GoCardless Sandbox. Hanya aktifkan opsi ini jika Anda menguji dengan akun GoCardless Sandbox.";
$lang['Gocardless.buildprocess.submit'] = "Bayar dengan GoCardless";
$lang['Gocardless.buildprocess.subscription'] = "Berlangganan dengan GoCardless";
$lang['Gocardless.webhook'] = "GoCardless Webhook";
$lang['Gocardless.webhook_note'] = "Sebelum Anda mulai menggunakan gateway ini, Anda harus mengonfigurasi url berikut sebagai Webhook di akun GoCardless Anda. Rahasia Webhook harus setidaknya 40 karakter.";
$lang['Gocardless.!error.access_token.valid'] = "Anda harus memasukkan Token Akses yang valid.";
$lang['Gocardless.!error.webhook_secret.valid'] = "Anda harus memasukkan Rahasia Webhook yang valid setidaknya sepanjang 40 karakter.";
$lang['Gocardless.!error.dev_mode.valid'] = "Mode pengembang harus disetel ke \"benar\" jika diberikan.";
$lang['Gocardless.description'] = "Kumpulkan pembayaran berulang dari lebih dari 30 negara, dan bayarkan ke rekening bank Anda yang ada";
$lang['Gocardless.!tooltip.webhook_secret'] = "Rahasia Webhook harus setidaknya 40 karakter.";
?>