<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CWatch.name'] = "CWatch";
$lang['CWatch.module_row.name'] = "Akun API";
$lang['CWatch.module_row_plural.name'] = "Akun API";
$lang['CWatch.!success.sftp_test'] = "Koneksi SFTP berhasil!";
$lang['CWatch.!tooltip.initiateDns'] = "Apakah akan memulai pemindaian data DNS.";
$lang['CWatch.!tooltip.autoSsl'] = "Apakah akan menginstal Sertifikat SSL Gratis Comodo.";
$lang['CWatch.!error.cwatch_email.format'] = "Format email salah.";
$lang['CWatch.!error.cwatch_email.unique'] = "Pelanggan dengan email yang diberikan sudah ada.";
$lang['CWatch.!error.cwatch_firstname.empty'] = "Masukkan nama depan.";
$lang['CWatch.!error.cwatch_lastname.empty'] = "Masukkan nama belakang.";
$lang['CWatch.!error.cwatch_country.length'] = "Kabupaten tidak valid.";
$lang['CWatch.!error.limit_exceeded'] = "Jumlah lisensi yang saat ini ditetapkan ke domain melebihi batas yang dimasukkan. Harap bebaskan lisensi dengan menghapus domain sebelum mengurangi batas Anda.";
$lang['CWatch.!error.api.internal'] = "Terjadi kesalahan internal, atau server tidak menanggapi permintaan.";
$lang['CWatch.!error.sftp_test'] = "Sambungan SFTP gagal! Harap periksa setelan Anda dan coba lagi.";
$lang['CWatch.manage.boxtitle'] = "Kelola CWatch";
$lang['CWatch.manage.title'] = "Akun API";
$lang['CWatch.manage.add_module_row'] = "Tambahkan Akun API";
$lang['CWatch.manage.option_edit'] = "Sunting";
$lang['CWatch.manage.delete'] = "Menghapus";
$lang['CWatch.manage.confirm_delete'] = "Anda yakin ingin menghapus pengguna ini?";
$lang['CWatch.manage.no_results'] = "Tidak ada akun yang ditemukan";
$lang['CWatch.manage.heading_username'] = "Nama pengguna";
$lang['CWatch.manage.heading_options'] = "Pilihan";
$lang['CWatch.package_fields.package_type'] = "Jenis Paket";
$lang['CWatch.package_fields.tooltip.package_type'] = "Paket lisensi tunggal hanya menyediakan satu lisensi di cWatch dari jenis yang dipilih di sini oleh paket. Paket multi lisensi menggunakan Opsi yang Dapat Dikonfigurasi untuk memungkinkan pelanggan memesan sejumlah variabel dari berbagai jenis.";
$lang['CWatch.package_fields.license_type'] = "Tipe lisensi";
$lang['CWatch.package_fields.license_basic_detection'] = "Dasar";
$lang['CWatch.package_fields.license_pro'] = "Profesional";
$lang['CWatch.package_fields.license_pro_free'] = "Uji Coba Profesional";
$lang['CWatch.package_fields.license_pro_free_60d'] = "Uji Coba Profesional yang Diperpanjang";
$lang['CWatch.package_fields.license_premium'] = "Premium";
$lang['CWatch.package_fields.license_premium_free'] = "Uji Coba Premium";
$lang['CWatch.package_fields.license_premium_free_60d'] = "Perpanjangan Uji Coba Premium";
$lang['CWatch.packagetypes.single_license'] = "Lisensi Tunggal";
$lang['CWatch.packagetypes.multi_license'] = "Multi Lisensi";
$lang['Cwatch.service_field.domain'] = "Domain";
$lang['Cwatch.service_field.email'] = "Email";
$lang['Cwatch.service_field.firstname'] = "Nama depan";
$lang['Cwatch.service_field.lastname'] = "Nama Belakang";
$lang['Cwatch.service_field.country'] = "Negara";
$lang['CWatch.add_row.box_title'] = "Tambahkan Akun API";
$lang['CWatch.add_row.basic_title'] = "Pengaturan pengguna";
$lang['CWatch.add_row.field_username'] = "Nama pengguna";
$lang['CWatch.add_row.field_password'] = "Kata sandi";
$lang['CWatch.add_row.field_sandbox'] = "Aktifkan  SandBox";
$lang['CWatch.add_row.add_btn'] = "Menambahkan akun";
$lang['CWatch.edit_row.box_title'] = "Edit Akun API";
$lang['CWatch.edit_row.basic_title'] = "Pengaturan pengguna";
$lang['CWatch.edit_row.field_username'] = "Nama pengguna";
$lang['CWatch.edit_row.field_password'] = "Kata sandi";
$lang['CWatch.edit_row.field_sandbox'] = "Aktifkan SandBox";
$lang['CWatch.edit_row.add_btn'] = "Edit Kredensial";
$lang['CWatch.service_info.option_login'] = "Masuk ke cWatch";
$lang['CWatch.tab_licenses.licenses'] = "Kelola Lisensi";
$lang['CWatch.tab_licenses.add'] = "Tambahkan Situs Baru";
$lang['CWatch.tab_licenses.licenseKey'] = "Kunci lisensi";
$lang['CWatch.tab_licenses.type'] = "Jenis";
$lang['CWatch.tab_licenses.domain'] = "Domain";
$lang['CWatch.tab_licenses.status'] = "Status Domain";
$lang['CWatch.tab_licenses.malware_scanner'] = "Pemindai";
$lang['CWatch.tab_licenses.no_results'] = "Tidak ada lisensi yang disediakan untuk layanan ini.";
$lang['CWatch.tab_licenses.not_applicable'] = "N/A";
$lang['CWatch.tab_licenses.remove_site'] = "Hapus Situs";
$lang['CWatch.tab_licenses.add_site'] = "Tambahkan Situs";
$lang['CWatch.tab_licenses.confirm_delete'] = "Yakin ingin menghapus domain ini?";
$lang['CWatch.tab_licenses.initiateDns'] = "DNS awal";
$lang['CWatch.tab_licenses.autoSsl'] = "AutoSSL";
$lang['CWatch.tab_licenses.submit'] = "Kirim";
$lang['CWatch.tab_malware.malware'] = "Kontrol Perangkat Lunak Perusak";
$lang['CWatch.tab_malware.add_scanner'] = "Tambahkan Pemindai";
$lang['CWatch.tab_malware.test_credentials'] = "Uji Kredensial Ini";
$lang['CWatch.tab_malware.domainname'] = "Nama domain";
$lang['CWatch.tab_malware.ftppassword'] = "Kata Sandi FTP";
$lang['CWatch.tab_malware.ftpusername'] = "Nama Pengguna FTP";
$lang['CWatch.tab_malware.host'] = "Nama Host FTP";
$lang['CWatch.tab_malware.port'] = "FTP Port";
$lang['CWatch.tab_malware.path'] = "Direktori Situs";
$lang['CWatch.tab_malware.submit'] = "Submit";
$lang['CWatch.getsitestatuses.waiting'] = "Menunggu";
$lang['CWatch.getsitestatuses.site_inprogress'] = "Penyediaan Situs Sedang Berlangsung";
$lang['CWatch.getsitestatuses.site_retry'] = "Mencoba Kembali Penyediaan Situs";
$lang['CWatch.getsitestatuses.site_completed'] = "Situs Ditambahkan";
$lang['CWatch.getsitestatuses.site_failed'] = "Penyediaan Situs Gagal";
$lang['CWatch.getsitestatuses.dns_inprogress'] = "Pemindaian DNS sedang berlangsung";
$lang['CWatch.getsitestatuses.dns_retry'] = "Mencoba lagi Pemindaian DNS";
$lang['CWatch.getsitestatuses.dns_completed'] = "Pemindaian DNS Selesai";
$lang['CWatch.getsitestatuses.dns_failed'] = "Situs Ditambahkan, Pemindaian DNS Gagal";
$lang['CWatch.getsitestatuses.ssl_inprogress'] = "Instal SSL dalam Progress";
$lang['CWatch.getsitestatuses.ssl_retry'] = "Mencoba lagi Pemasangan SSL";
$lang['CWatch.getsitestatuses.ssl_completed'] = "Sertifikat SSL Ditambahkan";
$lang['CWatch.getsitestatuses.ssl_fail'] = "Situs Ditambahkan, Pemasangan SSL Gagal";
$lang['CWatch.!error.cwatch_domain.format'] = "Harap masukkan nama domain yang valid, mis. domain.com.";
$lang['CWatch.package_fields.license_starter'] = "Starter";
$lang['CWatch.!success.ftp_test'] = "Koneksi FTP berhasil!";
$lang['CWatch.!error.username.valid'] = "Harap masukkan nama pengguna.";
$lang['CWatch.!error.password.valid'] = "Masukkan Kata Sandi";
$lang['CWatch.!error.password.valid_connection'] = "Tidak dapat membuat sambungan menggunakan kredensial yang diberikan.";
$lang['CWatch.!error.cwatch_domain.unique'] = "Domain sudah terdaftar. Harap pilih domain yang berbeda.";
$lang['CWatch.!error.ftp_test'] = "Koneksi FTP gagal! Harap periksa setelan Anda dan coba lagi.";
$lang['CWatch.package_fields.available_terms'] = "Ketentuan yang Tersedia";
$lang['CWatch.package_fields.license_starter_paid_with_trial'] = "Pemula Dibayar dengan Percobaan";
$lang['CWatch.package_fields.license_waf_starter'] = "Waf Starter";
$lang['CWatch.package_fields.license_pro_paid_with_trial'] = "Profesional Dibayar dengan Percobaan";
$lang['CWatch.package_fields.license_premium_paid_with_trial'] = "Premium Dibayar dengan Uji Coba";
$lang['CWatch.tab_licenses.inactive_licenses'] = "Lisensi Tidak Aktif";
$lang['CWatch.tab_licenses.options'] = "Pilihan";
$lang['CWatch.tab_licenses.no_upgrade_options'] = "Tidak ada lisensi yang tersedia untuk peningkatan.";
$lang['CWatch.tab_licenses.upgrade_delay'] = "Pemutakhiran mungkin memerlukan beberapa waktu untuk disebarkan, sehingga jenis lisensi lama mungkin masih ditampilkan.";
$lang['CWatch.tab_licenses.deactivate_license'] = "Nonaktifkan Lisensi";
$lang['CWatch.tab_licenses.upgrade_site'] = "Tingkatkan Situs";
$lang['CWatch.tab_licenses.confirm_deactivate'] = "Apakah Anda yakin ingin menonaktifkan lisensi ini?";
$lang['CWatch.tab_licenses.cancel'] = "Batal";
$lang['CWatch.tab_licenses.current_license'] = "Lisensi saat ini";
$lang['CWatch.tab_licenses.license_name'] = "%1\$s (%2\$s)"; // %1$s is the license key, %2$s is the license type
$lang['CWatch.tab_malware.sftp'] = "Gunakan SFTP";
$lang['CWatch.description'] = "Alat perlindungan untuk situs web, server web, dan aplikasi web Anda dari ancaman peretas yang semakin canggih.";
?>