<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Upload.!error.max_file_size'] = "File melebihi ukuran file maksimum yang diizinkan.";
$lang['Upload.!error.mime_type'] = "Jenis file, %1\$s tidak diizinkan."; // %1$s is the MIME type that is not permitted
$lang['Upload.!error.file_exists'] = "Berkas sudah ada.";
$lang['Upload.!error.write_failed'] = "File tidak bisa ditulis.";
$lang['Upload.!error.path_created'] = "Tempat upload tidak dapat dibuat.";
?>