<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompose.index.page_title'] = "Mailer Massal > Tulis";
$lang['AdminCompose.!tooltip.log'] = "Jika dicentang, semua email yang dikirim akan masuk ke Blesta.";
$lang['AdminCompose.index.boxtitle'] = "Tulis Surat";
$lang['AdminCompose.index.form.from_name'] = "Dari nama";
$lang['AdminCompose.index.form.from_address'] = "Dari email";
$lang['AdminCompose.index.form.subject'] = "Subyek";
$lang['AdminCompose.index.form.html'] = "HTML";
$lang['AdminCompose.index.form.text'] = "Teks";
$lang['AdminCompose.index.form.log'] = "Surel Log";
$lang['AdminCompose.index.text.note'] = "Jika tidak ada versi Teks yang diatur, itu akan dibuat secara otomatis dari versi HTML.";
$lang['AdminCompose.index.heading_client_tags'] = "Tag Klien";
$lang['AdminCompose.index.heading_service_tags'] = "Tag Layanan";
$lang['AdminCompose.index.link_back'] = "Kembali";
$lang['AdminCompose.index.form.preview'] = "Pratinjau";
$lang['AdminCompose.preview.boxtitle'] = "Pratinjau Surat";
$lang['AdminCompose.preview.email_total'] = "Total kontak yang akan dikirimi email: %1\$s"; // %1$s is the total number of contacts
$lang['AdminCompose.preview.heading.email_sample'] = "Contoh Email";
$lang['AdminCompose.preview.text_name'] = "Dari: %1\$s %2\$s"; // %1$s is the email's from name, %2$s is the email's from address
$lang['AdminCompose.preview.text_subject'] = "Subyek: %1\$s"; // %1$s
$lang['AdminCompose.preview.link_back'] = "Kembali";
$lang['AdminCompose.preview.form.send'] = "Kirim";
$lang['AdminCompose.!error.parse_error'] = "Kesalahan penguraian template: %1\$s"; // %1$s is the parse error
?>