<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MassMailerController.!success.mail_job_added'] = "Pekerjaan pengiriman surat telah berhasil diantrekan. Email akan dikirim melalui cron.";
$lang['MassMailerController.!success.export_job_added'] = "Ekspor telah berhasil diantrekan. Itu akan tersedia di halaman daftar setelah diproses melalui cron.";
?>