<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MassMailerPlugin.name'] = "Mailer Massal";
$lang['MassMailerPlugin.nav_secondary_staff.admin_main'] = "Mailer Massal";
$lang['MassMailerPlugin.permission.admin_main'] = "Daftar Mailer Massal";
$lang['MassMailerPlugin.permission.admin_filter'] = "Filter Surat Massal";
$lang['MassMailerPlugin.permission.admin_compose'] = "Mass Mailer Tulis Email";
$lang['MassMailerPlugin.cron.export_name'] = "Bangun Ekspor Surat";
$lang['MassMailerPlugin.cron.export_desc'] = "Membuat file CSV untuk pekerjaan pengiriman massal yang menunggu ekspor.";
$lang['MassMailerPlugin.cron.mass_mail_name'] = "Kirim Email Massal";
$lang['MassMailerPlugin.cron.mass_mail_desc'] = "Mengirim email massal untuk pekerjaan pengiriman yang tertunda.";
$lang['MassMailerPlugin.description'] = "Mengirim email ke beberapa klien dalam sistem sekaligus.";
?>