<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['SoftaculousQueuedServices.errors.service_id.exists'] = "Layanan yang diberikan tidak ada.";
$lang['SoftaculousQueuedServices.errors.service_id.exists_softaculous'] = "Layanan yang diberikan tidak antri untuk instalasi.";
$lang['SoftaculousQueuedServices.errors.company_id.exists'] = "Perusahaan yang diberikan tidak ada.";
$lang['SoftaculousQueuedServices.errors.attempts.valid'] = "Harus Berupa angka positif";
?>
