<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminMain.!success.change_auto_renewal'] = "Perpanjangan otomatis Domain telah diperbarui!";
$lang['AdminMain.index.page_title'] = "Klien #%1\$s Domain"; // %1$s is the client ID number
$lang['AdminMain.index.boxtitle_domains'] = "Domain";
$lang['AdminMain.index.heading_addons'] = "Add-on";
$lang['AdminMain.index.heading_status'] = "Status";
$lang['AdminMain.index.heading_domain'] = "Domain";
$lang['AdminMain.index.heading_term'] = "Ketentuan";
$lang['AdminMain.index.heading_datecreated'] = "Tanggal Dibuat";
$lang['AdminMain.index.heading_daterenews'] = "Tanggal Perpanjangan";
$lang['AdminMain.index.heading_datesuspended'] = "Tanggal Ditangguhkan";
$lang['AdminMain.index.heading_datecanceled'] = "Tanggal Dibatalkan";
$lang['AdminMain.index.heading_options'] = "Pilihan";
$lang['AdminMain.index.category_active'] = "Aktif";
$lang['AdminMain.index.category_pending'] = "Tertunda";
$lang['AdminMain.index.category_suspended'] = "Ditangguhkan";
$lang['AdminMain.index.category_canceled'] = "Dibatalkan";
$lang['AdminMain.index.categorylink_newservice'] = "Domain Baru";
$lang['AdminMain.index.recurring_term'] = "%1\$s %2\$s @ %3\$s"; // %1$s is the service term length (number), %2$s is the service period, %3$s is the formatted service renewal price
$lang['AdminMain.index.option_manage'] = "Mengelola";
$lang['AdminMain.index.option_delete'] = "Hapus";
$lang['AdminMain.index.confirm_delete'] = "Anda yakin ingin menghapus layanan ini?";
$lang['AdminMain.index.no_results'] = "Tidak ada layanan dengan status ini.";
$lang['AdminMain.index.text_never'] = "Tidak pernah";
$lang['AdminMain.index.text_on'] = "Di";
$lang['AdminMain.index.text_off'] = "Mati";
$lang['AdminMain.index.change_auto_renewal'] = "Ubah Perpanjangan Otomatis";
$lang['AdminMain.index.field_actionsubmit'] = "Kirim";
$lang['AdminMain.getfilters.any'] = "Setiap";
$lang['AdminMain.getfilters.field_package_name'] = "TLD";
$lang['AdminMain.getfilters.field_service_meta'] = "Nama domain";
?>
