<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminCompanyEmails.templates.Domains.domain_renewal_1_name'] = "Pengingat Pembaruan Domain 1";
$lang['AdminCompanyEmails.templates.Domains.domain_renewal_1_desc'] = "Pemberitahuan pertama dikirim ke klien ketika domain mereka akan segera kedaluwarsa.";
$lang['AdminCompanyEmails.templates.Domains.domain_renewal_2_name'] = "Pengingat Pembaruan Domain 2";
$lang['AdminCompanyEmails.templates.Domains.domain_renewal_2_desc'] = "Pemberitahuan kedua dikirim ke klien ketika domain mereka akan segera kedaluwarsa.";
$lang['AdminCompanyEmails.templates.Domains.domain_expiration_name'] = "Pemberitahuan Kedaluwarsa Domain";
$lang['AdminCompanyEmails.templates.Domains.domain_expiration_desc'] = "Pemberitahuan dikirim ke klien segera setelah domain mereka kedaluwarsa.";
?>
