<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['DomainsTlds.!error.tld.empty'] = "Harap masukkan TLD.";
$lang['DomainsTlds.!error.tld.exists'] = "Domain TLD sudah ada di perusahaan.";
$lang['DomainsTlds.!error.tld.length'] = "Panjang TLD harus minimal 3 karakter.";
$lang['DomainsTlds.!error.package_id.exists'] = "ID paket tidak valid.";
$lang['DomainsTlds.!error.package_group_id.exists'] = "ID grup paket tidak valid.";
$lang['DomainsTlds.!error.module_id.exists'] = "ID modul tidak valid.";
$lang['DomainsTlds.!error.commpany_id.exists'] = "ID perusahaan tidak valid.";
$lang['DomainsTlds.!error.dns_management.valid'] = "Nilai untuk Manajemen DNS tidak valid, harus 0 atau 1.";
$lang['DomainsTlds.!error.email_forwarding.valid'] = "Nilai untuk Penerusan Email tidak valid, harus 0 atau 1.";
$lang['DomainsTlds.!error.id_protection.valid'] = "Nilai untuk Perlindungan ID tidak valid, harus 0 atau 1.";
$lang['DomainsTlds.!error.epp_code.valid'] = "Nilai untuk Kode EPP tidak valid, harus 0 atau 1.";
$lang['DomainsTlds.!error.package_pricing.count'] = "Penetapan harga tidak dapat dinonaktifkan, TLD harus memiliki setidaknya satu penetapan harga.";
$lang['DomainsTlds.!error.package_pricing.service'] = "Penetapan harga tidak dapat dinonaktifkan karena layanan sedang menggunakannya.";
$lang['DomainsTlds.!error.tld.supported'] = "TLD yang diberikan tidak didukung oleh modul registrar yang dipilih.";
$lang['DomainsTlds.!error.feature.unsupported'] = "Fitur %1\$s tidak didukung oleh modul registrar yang dipilih."; // %1$s is the feature name
$lang['DomainsTlds.getTldFields.group'] = "Grup";
?>
