<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerManagePlugin.!success.category_added'] = "Kategori ini telah berhasil dibuat.";
$lang['DownloadManagerManagePlugin.!success.category_updated'] = "Kategori telah berhasil diperbarui.";
$lang['DownloadManagerManagePlugin.!success.category_deleted'] = "Kategori telah berhasil dihapus.";
$lang['DownloadManagerManagePlugin.!success.file_added'] = "File telah berhasil ditambahkan.";
$lang['DownloadManagerManagePlugin.!success.file_updated'] = "File telah berhasil diperbarui.";
$lang['DownloadManagerManagePlugin.!success.file_deleted'] = "File telah berhasil dihapus.";
$lang['DownloadManagerManagePlugin.!tooltip.path_to_file'] = "Masukkan path absolut ke file pada sistem file.";
$lang['DownloadManagerManagePlugin.!text.open_parenthesis'] = "(";
$lang['DownloadManagerManagePlugin.!text.forward_slash'] = "/";
$lang['DownloadManagerManagePlugin.!text.closed_parenthesis'] = ")";
$lang['DownloadManagerManagePlugin.modal.delete_file'] = "Apakah Anda yakin ingin menghapus berkas ini?";
$lang['DownloadManagerManagePlugin.modal.delete_category'] = "Anda yakin ingin menghapus kategori ini? Semua subkategori dan file dalam kategori ini akan dipindahkan ke kategori induk.";
$lang['DownloadManagerManagePlugin.index.page_title'] = "Download Manager >Kelola";
$lang['DownloadManagerManagePlugin.index.boxtitle_downloadmanager'] = "Download Manager";
$lang['DownloadManagerManagePlugin.index.add_download'] = "Tambahkan Download Disini";
$lang['DownloadManagerManagePlugin.index.add_category'] = "Tambahkan Kategori disini";
$lang['DownloadManagerManagePlugin.index.go_back'] = "Naik ke tingkat atas";
$lang['DownloadManagerManagePlugin.index.edit'] = "Sunting";
$lang['DownloadManagerManagePlugin.index.delete'] = "Hapus";
$lang['DownloadManagerManagePlugin.index.no_downloads'] = "Tidak ada download di bagian ini.";
$lang['DownloadManagerManagePlugin.add.page_title'] = "Pengelola Unduhan > Tambah Unduh";
$lang['DownloadManagerManagePlugin.add.boxtitle_root'] = "Simpan unduhan di %1\$s"; // %1$s is the name of the root directory
$lang['DownloadManagerManagePlugin.add.boxtitle_add'] = "Tambahkan Unduhan ke Kategori [%1\$s]"; // %1$s is the name of the category the download is to be uploaded to
$lang['DownloadManagerManagePlugin.add.field_public'] = "Tersedia Untuk Publik";
$lang['DownloadManagerManagePlugin.add.field_logged_in'] = "Harus login";
$lang['DownloadManagerManagePlugin.add.field_name'] = "Nama";
$lang['DownloadManagerManagePlugin.add.field_available_to_client_groups'] = "Tersedia untuk Grup Klien";
$lang['DownloadManagerManagePlugin.add.field_available_to_packages'] = "Tersedia untuk Paket";
$lang['DownloadManagerManagePlugin.add.text_clientgroups'] = "Grup Klien yang Dipilih";
$lang['DownloadManagerManagePlugin.add.text_packagegroups'] = "Paket yang dipilih";
$lang['DownloadManagerManagePlugin.add.text_availableclientgroups'] = "Grup Klien yang Tersedia";
$lang['DownloadManagerManagePlugin.add.text_availablepackages'] = "Paket yang tersedia";
$lang['DownloadManagerManagePlugin.add.field_upload'] = "Unggah Berkas";
$lang['DownloadManagerManagePlugin.add.field_path'] = "Tentukan Jalur ke File";
$lang['DownloadManagerManagePlugin.add.field_file'] = "Berkas";
$lang['DownloadManagerManagePlugin.add.field_file_name'] = "Jalur ke file";
$lang['DownloadManagerManagePlugin.add.submit_add'] = "Tambahkan Unduh";
$lang['DownloadManagerManagePlugin.add.submit_cancel'] = "Membatalkan";
$lang['DownloadManagerManagePlugin.edit.page_title'] = "Pengelola Unduhan > Tambah Unduh";
$lang['DownloadManagerManagePlugin.edit.boxtitle_edit'] = "Perbarui Unduh";
$lang['DownloadManagerManagePlugin.edit.field_public'] = "Publik Tersedia";
$lang['DownloadManagerManagePlugin.edit.field_logged_in'] = "Harus login";
$lang['DownloadManagerManagePlugin.edit.field_name'] = "Nama";
$lang['DownloadManagerManagePlugin.edit.field_available_to_client_groups'] = "Tersedia untuk Kelompok Klien";
$lang['DownloadManagerManagePlugin.edit.field_available_to_packages'] = "Tersedia untuk Paket";
$lang['DownloadManagerManagePlugin.edit.text_clientgroups'] = "Grup Klien yang Dipilih";
$lang['DownloadManagerManagePlugin.edit.text_packagegroups'] = "Paket Terpilih";
$lang['DownloadManagerManagePlugin.edit.text_availableclientgroups'] = "Grup Klien yang Tersedia";
$lang['DownloadManagerManagePlugin.edit.text_availablepackages'] = "Paket yang tersedia";
$lang['DownloadManagerManagePlugin.edit.field_upload'] = "Unggah data";
$lang['DownloadManagerManagePlugin.edit.field_path'] = "Tentukan Jalur ke File";
$lang['DownloadManagerManagePlugin.edit.field_file'] = "Berkas";
$lang['DownloadManagerManagePlugin.edit.field_file_name'] = "Jalur ke File";
$lang['DownloadManagerManagePlugin.edit.submit_edit'] = "Perbarui Unduhan";
$lang['DownloadManagerManagePlugin.edit.submit_cancel'] = "Batal";
$lang['DownloadManagerManagePlugin.addcategory.page_title'] = "Pengelola Unduhan > Tambahkan Kategori";
$lang['DownloadManagerManagePlugin.addcategory.boxtitle_root'] = "Tambahkan Kategori ke %1\$s"; // %1$s is the name of the root directory
$lang['DownloadManagerManagePlugin.addcategory.boxtitle_addcategory'] = "Tambahkan kategori ke kategori [%1\$s]"; // %1$s is the name of the category that this category is to be nested under
$lang['DownloadManagerManagePlugin.addcategory.field_name'] = "Nama";
$lang['DownloadManagerManagePlugin.addcategory.field_description'] = "Deskripsi";
$lang['DownloadManagerManagePlugin.addcategory.submit_add'] = "Buat kategori";
$lang['DownloadManagerManagePlugin.addcategory.submit_cancel'] = "Membatalkan";
$lang['DownloadManagerManagePlugin.editcategory.page_title'] = "Pengelola Unduhan > Perbarui Kategori";
$lang['DownloadManagerManagePlugin.editcategory.boxtitle_editcategory'] = "Perbarui Kategori [%1\$s]"; // %1$s is the name of the category
$lang['DownloadManagerManagePlugin.editcategory.field_name'] = "Nama";
$lang['DownloadManagerManagePlugin.editcategory.field_description'] = "Deskripsi";
$lang['DownloadManagerManagePlugin.editcategory.submit_edit'] = "Update Kategori";
$lang['DownloadManagerManagePlugin.editcategory.submit_cancel'] = "Membatalkan";
$lang['DownloadManagerManagePlugin.!text.root_directory'] = "Home Directory";
$lang['DownloadManagerManagePlugin.package_name'] = "%1\$s (%2\$s)"; // %1$s is the package name, %2$s is the package status
?>