<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminStaff.!success.staff_added'] = "Anggota staf telah berhasil ditambahkan.";
$lang['AdminStaff.!success.staff_updated'] = "Anggota staf telah berhasil diperbarui.";
$lang['AdminStaff.!success.staff_deleted'] = "Anggota staf telah berhasil dihapus.";
$lang['AdminStaff.!tooltip.all_day'] = "Centang kotak ini untuk membuat anggota staf yang tersedia sepanjang hari.";
$lang['AdminStaff.!tooltip.ticket_emails'] = "Centang kotak dari setiap prioritas tiket yang harus diterima oleh staf melalui email tiket.";
$lang['AdminStaff.!tooltip.mobile_ticket_emails'] = "Centang kotak masing-masing prioritas tiket yang staf harus menerima email tiket secara mobile.";
$lang['AdminStaff.index.page_title'] = "Support Manager > Staff";
$lang['AdminStaff.add.page_title'] = "Support Manager > Tambah Staff";
$lang['AdminStaff.edit.page_title'] = "Manajer Dukungan > Edit Staf";
$lang['AdminStaff.index.categorylink_addstaff'] = "Tambahkan Staf";
$lang['AdminStaff.index.boxtitle_staff'] = "Staf";
$lang['AdminStaff.index.heading_first_name'] = "Nama";
$lang['AdminStaff.index.heading_email'] = "Email";
$lang['AdminStaff.index.heading_ticket_emails'] = "Terima Email Tiket";
$lang['AdminStaff.index.heading_mobile_ticket_emails'] = "Menerima Email Ponsel Tiket";
$lang['AdminStaff.index.heading_options'] = "Pilihan";
$lang['AdminStaff.index.option_edit'] = "Edit";
$lang['AdminStaff.index.option_delete'] = "Hapus";
$lang['AdminStaff.index.confirm_delete'] = "Menghapus anggota staf ini akan membatalkan penetapan semua tiket saat ini yang ditangani anggota staf ini. Apakah Anda yakin ingin menghapus anggota staf ini?";
$lang['AdminStaff.index.no_results'] = "Saat ini sedang tidak ada staff yang bertugas pada support system";
$lang['AdminStaff.add.boxtitle_addstaff'] = "Tambah Staf";
$lang['AdminStaff.add.heading_staff'] = "Staff";
$lang['AdminStaff.add.heading_schedule'] = "Jadwal";
$lang['AdminStaff.add.heading_settings'] = "Setting";
$lang['AdminStaff.add.heading_departments'] = "Departemen";
$lang['AdminStaff.add.field_staff_group_id'] = "Grup Staf";
$lang['AdminStaff.add.field_staff_id'] = "Anggota staff";
$lang['AdminStaff.add.heading_day'] = "Hari";
$lang['AdminStaff.add.heading_all_day'] = "Sepanjang Hari";
$lang['AdminStaff.add.heading_start_time'] = "Waktu mulai";
$lang['AdminStaff.add.heading_end_time'] = "Akhir Waktu";
$lang['AdminStaff.add.ticket_emails'] = "Terima Email Tiket";
$lang['AdminStaff.add.mobile_ticket_emails'] = "Terima Email Tiket Seluler";
$lang['AdminStaff.add.text_assigneddepartments'] = "Ditetapkan di departemen";
$lang['AdminStaff.add.text_availabledepartments'] = "Departemen yang Tersedia";
$lang['AdminStaff.add.field_addsubmit'] = "Tambah Staf";
$lang['AdminStaff.edit.boxtitle_editstaff'] = "Edit Staf %1\$s %2\$s"; // %1$s is the staff member's first name, %2$s is the staff member's last name
$lang['AdminStaff.edit.heading_schedule'] = "Jadual";
$lang['AdminStaff.edit.heading_settings'] = "Pengaturan";
$lang['AdminStaff.edit.heading_departments'] = "Departemen";
$lang['AdminStaff.edit.heading_day'] = "Hari";
$lang['AdminStaff.edit.heading_all_day'] = "Sepanjang hari";
$lang['AdminStaff.edit.heading_start_time'] = "Waktu mulai";
$lang['AdminStaff.edit.heading_end_time'] = "Selesai";
$lang['AdminStaff.edit.ticket_emails'] = "Terima Email Tiket";
$lang['AdminStaff.edit.mobile_ticket_emails'] = "Terima Email Tiket Seluler";
$lang['AdminStaff.edit.text_assigneddepartments'] = "Departemen yang Ditugaskan";
$lang['AdminStaff.edit.text_availabledepartments'] = "Departemen Yang Tersedia";
$lang['AdminStaff.edit.field_editsubmit'] = "Edit Staf";
$lang['AdminStaff.staff.name'] = "%1\$s %2\$s"; // %1$s is the staff member's first name, %2$s is the staff member's last name
$lang['AdminStaff.schedule_list.heading_schedule'] = "Rencana";
$lang['AdminStaff.schedule_list.heading_day'] = "Hari";
$lang['AdminStaff.schedule_list.heading_start_time'] = "Waktu Mulai";
$lang['AdminStaff.schedule_list.heading_end_time'] = "Akhir waktu";
$lang['AdminStaff.schedule_list.no_results'] = "Anggota staf ini tidak dijadwalkan untuk setiap hari.";
$lang['AdminStaff.schedule_list.heading_departments'] = "Departemen";
$lang['AdminStaff.schedule_list.heading_department'] = "Departemen";
$lang['AdminStaff.schedule_list.heading_description'] = "Deskripsi";
$lang['AdminStaff.schedule_list.no_department_results'] = "Anggota staf ini tidak ditugaskan ke departemen mana pun.";
$lang['AdminStaff.text.no_time'] = "--";
$lang['AdminStaff.!tooltip.title'] = "Memasukkan judul untuk anggota staf ini akan menimpa judul default: %1\$s"; // %1$s is the language for the default title
$lang['AdminStaff.!tooltip.signature'] = "Masukkan tanda tangan untuk membuatnya tersedia secara otomatis saat membalas tiket.";
$lang['AdminStaff.add.title'] = "Judul";
$lang['AdminStaff.add.signature'] = "Tanda tangan";
$lang['AdminStaff.edit.title'] = "Judul";
$lang['AdminStaff.edit.signature'] = "Tanda tangan";
$lang['AdminStaff.!tooltip.ticket_messenger_notifications'] = "Centang kotak dari setiap prioritas tiket yang harus menerima pemberitahuan pesan tiket oleh staf.";
$lang['AdminStaff.index.heading_ticket_messenger_notifications'] = "Terima Pemberitahuan Messenger Tiket";
$lang['AdminStaff.add.ticket_messenger_notifications'] = "Terima Pemberitahuan Messenger Tiket";
$lang['AdminStaff.edit.ticket_messenger_notifications'] = "Terima Pemberitahuan Messenger Tiket";
?>
