<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminResponses.!success.category_added'] = "Kategori %1\$s berhasil ditambahkan."; // %1$s is the name of the category
$lang['AdminResponses.!success.category_updated'] = "Kategori %1\$s berhasil diperbarui."; // %1$s is the name of the category
$lang['AdminResponses.!success.category_deleted'] = "Kategori %1\$s berhasil dihapus."; // %1$s is the name of the category
$lang['AdminResponses.!success.response_added'] = "Respon %1\$s berhasil ditambahkan."; // %1$s is the name of the predefined response
$lang['AdminResponses.!success.response_updated'] = "Tanggapan %1\$s Berhasil diperbaharui."; // %1$s is the name of the predefined response
$lang['AdminResponses.!success.response_deleted'] = "Tanggapan %1\$s berhasil dihapus."; // %1$s is the name of the predefined response
$lang['AdminResponses.index.page_title'] = "Dukungan Manajer> Tanggapan Predefined";
$lang['AdminResponses.add.page_title'] = "Manajer Dukungan > Tambahkan Respons Standar";
$lang['AdminResponses.edit.page_title'] = "Support Manager > Edit Predefined Response";
$lang['AdminResponses.addcategory.page_title'] = "Support Manager> Tambah Kategori";
$lang['AdminResponses.editcategory.page_title'] = "Manajer Dukungan > Edit Kategori";
$lang['AdminResponses.!text.open_parenthesis'] = "(";
$lang['AdminResponses.!text.forward_slash'] = "/";
$lang['AdminResponses.!text.closed_parenthesis'] = ")";
$lang['AdminResponses.index.boxtitle_responses'] = "Penetapan Respon";
$lang['AdminResponses.index.add_response'] = "Tambahkan Tanggapan Di Sini";
$lang['AdminResponses.index.add_category'] = "Tambahkan Kategori di sini";
$lang['AdminResponses.index.text_up_level'] = "Naik Level";
$lang['AdminResponses.index.edit'] = "Sunting";
$lang['AdminResponses.index.delete'] = "Hapus";
$lang['AdminResponses.index.no_responses'] = "Tidak ada tanggapan di bagian ini.";
$lang['AdminResponses.modal.delete_category'] = "Apakah Anda yakin ingin menghapus kategori ini? Semua subkategori dan tanggapan yang telah ditetapkan dalam kategori ini akan dipindahkan ke kategori induk.";
$lang['AdminResponses.modal.delete_response'] = "Apakah anda yakin menghapus respon yang telah ditentukan ini?";
$lang['AdminResponses.add.boxtitle_add'] = "Tambahkan Respons Standar ke Kategori [%1\$s]"; // %1$s is the name of the category
$lang['AdminResponses.add.field_name'] = "Nama";
$lang['AdminResponses.add.field_details'] = "Detil Respon";
$lang['AdminResponses.add.field_submit'] = "Buat Respon";
$lang['AdminResponses.edit.boxtitle_edit'] = "Mengedit Tanggapan Siap Pakai"; // %1$s is the name of the category
$lang['AdminResponses.edit.field_name'] = "Nama";
$lang['AdminResponses.edit.field_details'] = "Detail Response";
$lang['AdminResponses.edit.field_submit'] = "Perbarui Tanggapan";
$lang['AdminResponses.addcategory.boxtitle_root'] = "Tambahkan Kategori";
$lang['AdminResponses.addcategory.boxtitle_addcategory'] = "Tambahkan Kategori ke Kategori [%1\$s]"; // %1$s is the name of the parent category
$lang['AdminResponses.addcategory.field_name'] = "Nama";
$lang['AdminResponses.addcategory.field_submit'] = "Buat Kategori";
$lang['AdminResponses.editcategory.boxtitle_root'] = "Edit Kategori";
$lang['AdminResponses.editcategory.boxtitle_editcategory'] = "Kategori diPerbarui ";
$lang['AdminResponses.editcategory.field_name'] = "Nama";
$lang['AdminResponses.editcategory.field_submit'] = "Update Kategori";
?>
