<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['SupportManagerStaff.!error.staff_id.exists'] = "Anggota staf yang akan ditambahkan tidak ada.";
$lang['SupportManagerStaff.!error.staff_id.belongs'] = "Anggota staf bukan karyawan perusahaan yang sedang ditugaskan.";
$lang['SupportManagerStaff.!error.staff_id.duplicate'] = "Anggota staf yang dipilih sudah ada di support system.";
$lang['SupportManagerStaff.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['SupportManagerStaff.!error.departments.exists'] = "Setidaknya satu set departemen tidak ada.";
$lang['SupportManagerStaff.!error.schedules.minimum'] = "Silakan menetapkan jadwal waktu mulai dan akhir untuk setidaknya satu hari.";
$lang['SupportManagerStaff.!error.schedules.unique_days'] = "Setiap hari yang dijadwalkan harus unik.";
$lang['SupportManagerStaff.!error.schedules[][day].format'] = "Hari yang dijadwalkan tidak valid.";
$lang['SupportManagerStaff.!error.schedules[][start_time].format'] = "Silakan pilih waktu mulai untuk setiap hari yang telah dijadwalkan";
$lang['SupportManagerStaff.!error.schedules[][end_time].format'] = "Silakan pilih waktu akhir untuk setiap jadwal harian";
$lang['SupportManagerStaff.days.sun'] = "Minggu";
$lang['SupportManagerStaff.days.mon'] = "Senin";
$lang['SupportManagerStaff.days.tue'] = "Selasa";
$lang['SupportManagerStaff.days.wed'] = "Rabu";
$lang['SupportManagerStaff.days.thu'] = "Kamis";
$lang['SupportManagerStaff.days.fri'] = "Jumat";
$lang['SupportManagerStaff.days.sat'] = "Sabtu";
?>
