<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['SupportManagerPlugin.name'] = "Manajer Dukungan";
$lang['SupportManagerPlugin.cron.poll_tickets_name'] = "Unduh Tiket";
$lang['SupportManagerPlugin.cron.poll_tickets_desc'] = "Menghubungkan ke server POP3 / IMAP untuk men-download email dan mengubahnya menjadi tiket.";
$lang['SupportManagerPlugin.nav_primary_client.main'] = "Dukung";
$lang['SupportManagerPlugin.nav_primary_staff.main'] = "Support";
$lang['SupportManagerPlugin.nav_primary_staff.tickets'] = "Tiket";
$lang['SupportManagerPlugin.nav_primary_staff.departments'] = "Departemen";
$lang['SupportManagerPlugin.nav_primary_staff.responses'] = "Tanggapan";
$lang['SupportManagerPlugin.nav_primary_staff.staff'] = "Staf";
$lang['SupportManagerPlugin.widget_staff_client.tickets'] = "Tiket";
$lang['SupportManagerPlugin.action_staff_client.add'] = "Buka Tiket";
$lang['SupportManagerPlugin.event_getsearchoptions.tickets'] = "Pnecarian Tiket";
$lang['SupportManagerPlugin.permission.admin_main'] = "Support";
$lang['SupportManagerPlugin.permission.admin_tickets'] = "Tiket";
$lang['SupportManagerPlugin.permission.admin_tickets_client'] = "Widget Profil Klien";
$lang['SupportManagerPlugin.permission.admin_departments'] = "Departemen";
$lang['SupportManagerPlugin.permission.admin_responses'] = "Tanggapan";
$lang['SupportManagerPlugin.permission.admin_staff'] = "Staff";
$lang['SupportManagerPlugin.cron.close_tickets_name'] = "Tutup Tiket";
$lang['SupportManagerPlugin.cron.close_tickets_desc'] = "Otomatis menutup tiket terbuka sebagai sedang dikonfigurasi untuk departemen Support Manager.";
$lang['SupportManagerPlugin.nav_primary_client.tickets'] = "Tiket";
$lang['SupportManagerPlugin.nav_primary_client.knowledgebase'] = "Dasar pengetahuan";
$lang['SupportManagerPlugin.nav_primary_staff.knowledgebase'] = "Dasar pengetahuan";
$lang['SupportManagerPlugin.permission.admin_knowledgebase'] = "Dasar pengetahuan";
$lang['SupportManagerPlugin.cron.delete_tickets_name'] = "Hapus Tiket Sampah";
$lang['SupportManagerPlugin.cron.delete_tickets_desc'] = "Hapus tiket sampah secara otomatis sebagaimana dikonfigurasi untuk departemen di Manajer Dukungan.";
$lang['SupportManagerPlugin.permission.admin_tickets_delete'] = "Hapus Tiket Secara Permanen";
$lang['SupportManagerPlugin.description'] = "Memungkinkan pengguna dan staf untuk membuka dan mengelola tiket dukungan.";
$lang['SupportManagerPlugin.card_client.tickets'] = "Tiket";
$lang['SupportManagerPlugin.cron.send_reminders_name'] = "Kirim Pengingat";
$lang['SupportManagerPlugin.cron.send_reminders_desc'] = "Secara otomatis mengirimkan pengingat untuk tiket dengan status tertentu setelah jangka waktu tertentu.";
$lang['SupportManagerPlugin.nav_primary_staff.reminders'] = "Pengingat";
$lang['SupportManagerPlugin.permission.admin_reminders'] = "Pengingat";
?>
