<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminManagePlugin.!success.settings_saved'] = "Pengaturan telah disimpan.";
$lang['AdminManagePlugin.index.page_title'] = "Pembatalan Otomatis";
$lang['AdminManagePlugin.index.boxtitle_auto_cancel'] = "Pembatalan Otomatis";
$lang['AdminManagePlugin.index.heading_settings'] = "Pengaturan";
$lang['AdminManagePlugin.index.field.schedule_days'] = "Jadwalkan Hari Pembatalan Setelah Ditangguhkan";
$lang['AdminManagePlugin.index.field.cancel_days'] = "Batalkan Layanan Beberapa Hari Setelah Ditangguhkan";
$lang['AdminManagePlugin.index.field.submit'] = "Menyimpan";
$lang['AdminManagePlugin.getDays.never'] = "Tidak pernah";
$lang['AdminManagePlugin.getDays.text_day'] = "%1\$s Hari";
$lang['AdminManagePlugin.getDays.text_days'] = "%1\$s Hari"; // %1$s is the number of days
?>
