<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AutoCancelPlugin.getCronTasks.schedule_cancellation_name'] = "Jadwal Pembatalan Otomatis";
$lang['AutoCancelPlugin.getCronTasks.schedule_cancellation_desc'] = "Secara otomatis menjadwalkan layanan yang ditangguhkan untuk pembatalan.";
$lang['AutoCancelPlugin.name'] = "Batal Otomatis";
$lang['AutoCancelPlugin.description'] = "Secara otomatis menjadwalkan layanan untuk pembatalan.";
?>
