<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['ClientDocumentsPlugin.nav_primary_client.main'] = "Dokumen";
$lang['ClientDocumentsPlugin.action_staff_client.index'] = "Dokumen";
$lang['ClientDocumentsPlugin.name'] = "Dokumen Klien";
$lang['ClientDocumentsPlugin.description'] = "Unggah file untuk diunduh oleh klien tertentu.";
?>
