<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['ClientMain.index.page_title'] = "Dokumen";
$lang['ClientMain.index.boxtitle_documents'] = "Dokumen";
$lang['ClientMain.index.no_results'] = "Tidak ada dokumen yang tersedia untuk di-download.";
$lang['ClientMain.index.heading_name'] = "Nama";
$lang['ClientMain.index.heading_description'] = "Deskripsi";
$lang['ClientMain.index.heading_date_added'] = "Tanggal Ditambahkan";
$lang['ClientMain.index.heading_options'] = "Pilihan";
$lang['ClientMain.index.option_download'] = "Download";
?>
