<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['FormRules.general.name.format'] = "Nama ekstensi hanya boleh berisi karakter alfa_numerik, garis bawah, dan spasi.";
$lang['FormRules.modulebasic.module_row.empty'] = "Harap masukkan nama baris modul.";
$lang['FormRules.modulebasic.module_row_plural.empty'] = "Harap tambahkan nama baris modul jamak.";
$lang['FormRules.modulebasic.module_group.empty'] = "Harap masukkan label grup modul.";
$lang['FormRules.modulebasic.authors[][name].empty'] = "Silakan masukkan nama untuk setiap penulis.";
$lang['FormRules.modulefields.module_rows[][name].format'] = "Harap masukkan nama untuk setiap bidang baris modul dalam format snake_case_name.";
$lang['FormRules.modulefields.module_rows[][label].empty'] = "Harap masukkan label untuk setiap bidang baris modul.";
$lang['FormRules.modulefields.module_rows[][type].valid'] = "Satu atau beberapa baris modul memiliki tipe yang tidak valid.";
$lang['FormRules.modulefields.module_rows[][name_key].valid'] = "Apakah akan menyetel bidang baris modul sebagai kunci nama harus disetel ke benar atau salah.";
$lang['FormRules.modulefields.service_fields[][name].format'] = "Harap masukkan nama untuk setiap bidang layanan dalam format snake_case_name.";
$lang['FormRules.modulefields.service_fields[][label].empty'] = "Harap masukkan label untuk setiap bidang layanan.";
$lang['FormRules.modulefields.service_fields[][type].valid'] = "Satu atau beberapa bidang layanan memiliki jenis yang tidak valid.";
$lang['FormRules.modulefields.service_fields[][name_key].valid'] = "Apakah akan menyetel bidang layanan sebagai kunci nama harus disetel ke benar atau salah.";
$lang['FormRules.modulefields.package_fields[][name].format'] = "Harap masukkan nama untuk setiap bidang paket dalam format snake_case_name.";
$lang['FormRules.modulefields.package_fields[][label].empty'] = "Harap masukkan label untuk setiap bidang paket.";
$lang['FormRules.modulefields.package_fields[][type].valid'] = "Satu atau beberapa bidang paket memiliki jenis yang tidak valid.";
$lang['FormRules.modulefields.package_fields[][name_key].valid'] = "Apakah akan menyetel bidang paket sebagai kunci nama harus disetel ke benar atau salah.";
$lang['FormRules.modulefeatures.service_tabs[][method_name].format'] = "Harap masukkan nama metode untuk setiap tab layanan dalam format camelCaseName.";
$lang['FormRules.modulefeatures.service_tabs[][label].empty'] = "Harap masukkan label untuk setiap tab layanan.";
$lang['FormRules.modulefeatures.service_tabs[][level].valid'] = "Satu atau beberapa tab layanan memiliki tingkat yang tidak valid.";
$lang['FormRules.modulefeatures.cron_tasks[][name].format'] = "Harap masukkan nama metode untuk setiap tugas cron dalam format snake_case_name.";
$lang['FormRules.modulefeatures.cron_tasks[][label].empty'] = "Harap masukkan label untuk setiap tugas cron.";
$lang['FormRules.modulefeatures.cron_tasks[][type].valid'] = "Satu atau beberapa tugas cron memiliki tipe yang tidak valid.";
$lang['FormRules.modulefeatures.cron_tasks[][time].format'] = "Harap masukkan waktu dalam format 00:00 atau interval numerik.";
$lang['FormRules.pluginbasic.authors[][name].empty'] = "Silakan masukkan nama untuk setiap penulis.";
$lang['FormRules.plugindatabase.tables[][name].format'] = "Harap masukkan nama metode untuk setiap tabel dalam format snake_case_name.";
$lang['FormRules.plugindatabase.tables[][columns][][name].format'] = "Harap masukkan nama metode untuk setiap kolom dalam format snake_case_name.";
$lang['FormRules.plugindatabase.tables[][columns][][type].valid'] = "Satu atau beberapa kolom memiliki jenis yang tidak valid.";
$lang['FormRules.plugindatabase.tables[][columns][][length].empty'] = "Panjangnya harus dalam format 'a','b','c' untuk kolom enum, kosong untuk kolom teks dan waktu, dan numerik untuk yang lainnya.";
$lang['FormRules.plugindatabase.tables[][columns][][nullable].valid'] = "Nullable harus disetel ke true atau false untuk setiap kolom.";
$lang['FormRules.plugindatabase.tables[][columns][][primary].valid'] = "Utama harus disetel ke benar atau salah untuk setiap kolom.";
$lang['FormRules.pluginintegrations.actions[][controller].format'] = "Masukkan pengontrol untuk setiap tindakan dalam format snake_case_name.";
$lang['FormRules.pluginintegrations.actions[][action].format'] = "Harap masukkan tindakan untuk setiap tindakan dalam semua huruf kecil.";
$lang['FormRules.pluginintegrations.actions[][name].empty'] = "Harap masukkan nama untuk setiap tindakan.";
$lang['FormRules.pluginintegrations.events[][event].empty'] = "Harap masukkan nama acara untuk setiap acara.";
$lang['FormRules.pluginintegrations.events[][callback].format'] = "Harap masukkan metode panggilan balik untuk setiap peristiwa dalam format camelCaseName.";
$lang['FormRules.pluginintegrations.cards[][level].valid'] = "Satu atau lebih kartu memiliki level yang tidak valid.";
$lang['FormRules.pluginintegrations.cards[][callback].format'] = "Harap masukkan metode panggilan balik untuk setiap kartu dalam format camelCaseName.";
$lang['FormRules.pluginintegrations.cards[][label].empty'] = "Harap masukkan label untuk setiap kartu.";
$lang['FormRules.merchantbasic.authors[][name].empty'] = "Silakan masukkan nama untuk setiap penulis.";
$lang['FormRules.merchantbasic.currencies.format'] = "Harap masukkan mata uang dalam format tiga karakter yang dipisahkan dengan koma (mis. USD,EUR,JPY).";
$lang['FormRules.merchantfields.fields[][name].format'] = "Harap masukkan nama untuk setiap bidang dalam format snake_case_name.";
$lang['FormRules.merchantfields.fields[][label].empty'] = "Harap masukkan label untuk setiap bidang.";
$lang['FormRules.merchantfields.fields[][type].valid'] = "Satu atau beberapa bidang memiliki jenis yang tidak valid.";
$lang['FormRules.nonmerchantbasic.authors[][name].empty'] = "Silakan masukkan nama untuk setiap penulis.";
$lang['FormRules.nonmerchantbasic.currencies.format'] = "Harap masukkan mata uang dalam format tiga karakter yang dipisahkan dengan koma (mis. USD,EUR,JPY).";
$lang['FormRules.nonmerchantfields.fields[][name].format'] = "Harap masukkan nama untuk setiap bidang dalam format snake_case_name.";
$lang['FormRules.nonmerchantfields.fields[][label].empty'] = "Harap masukkan label untuk setiap bidang.";
$lang['FormRules.nonmerchantfields.fields[][type].valid'] = "Satu atau beberapa bidang memiliki jenis yang tidak valid.";
$lang['FormRules.pluginintegrations.actions[][location].valid'] = "Harap masukkan lokasi tindakan yang valid.";
?>
