<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TaxLiability.name'] = "Kewajiban pajak";
$lang['TaxLiability.options.field_start_date'] = "Mulai Tanggal";
$lang['TaxLiability.options.field_end_date'] = "Tanggal Akhir";
$lang['TaxLiability.options.field_cascade_true'] = "Ya";
$lang['TaxLiability.options.field_cascade_false'] = "Tidak";
$lang['TaxLiability.heading.id_code'] = "Faktur #";
$lang['TaxLiability.heading.client_id_code'] = "Klien #";
$lang['TaxLiability.heading.subtotal'] = "Subtotal";
$lang['TaxLiability.heading.taxable_amount'] = "Jumlah Kena Pajak";
$lang['TaxLiability.heading.level1_tax_rate'] = "Level 1 Tarif Pajak (%)";
$lang['TaxLiability.heading.level1_tax_amount'] = "Jumlah Pajak Tingkat 1";
$lang['TaxLiability.heading.level2_tax_rate'] = "Level 2 Prosentase Pajak (%)";
$lang['TaxLiability.heading.level2_tax_amount'] = "Jumlah Pajak Tingkat 2";
$lang['TaxLiability.heading.cascade'] = "Pajak Kaskade";
$lang['TaxLiability.heading.currency'] = "Mata Uang";
$lang['TaxLiability.heading.date_closed'] = "Tanggal Ditutup";
$lang['TaxLiability.heading.level1_tax_country'] = "Tingkat 1 Negara";
$lang['TaxLiability.heading.level1_tax_state'] = "Tingkat 1 Negara Bagian/Provinsi";
$lang['TaxLiability.heading.level2_tax_country'] = "Tingkat 2 Negara";
$lang['TaxLiability.heading.level2_tax_state'] = "Tingkat 2 Negara Bagian/Provinsi";
?>