<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Cart.index.header_cart'] = "Ringkasan Pesanan";
$lang['Cart.index.header_note'] = "Pajak apa pun yang berlaku akan dihitung setelah Anda mendaftar atau masuk.";
$lang['Cart.index.table_description'] = "Deskripsi";
$lang['Cart.index.table_term'] = "Istilah";
$lang['Cart.index.table_qty'] = "Kuantitas";
$lang['Cart.index.table_price'] = "Harga";
$lang['Cart.index.edit_item'] = "Ubah";
$lang['Cart.index.remove_item'] = "Hapus";
$lang['Cart.index.have_coupon'] = "Gunakan kode kupon";
$lang['Cart.index.coupon'] = "Kupon";
$lang['Cart.index.order_more_btn'] = "Klik untuk memesan lebih banyak item";
$lang['Cart.index.order_more_note'] = "Atau daftar/login dan lanjutkan melakukan pembayaran.";
?>
