<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['DirectAdmin.!error.server_name.empty'] = "Anda harus memasukkan Label Server.";
$lang['DirectAdmin.!error.host_name.format'] = "Host Name tampaknya tidak valid.";
$lang['DirectAdmin.!error.user_name.empty'] = "Anda harus memasukkan User Name.";
$lang['DirectAdmin.!error.password.format'] = "Anda harus memasukkan Password.";
$lang['DirectAdmin.!error.use_ssl.format'] = "Gunakan SSL harus benar atau salah.";
$lang['DirectAdmin.!error.account_limit.valid'] = "Batas akun harus dibiarkan kosong (untuk akun unlimited) atau mengatur untuk beberapa nilai integer.";
$lang['DirectAdmin.!error.name_servers.valid'] = "Satu atau beberapa server nama yang dimasukkan tidak valid.";
$lang['DirectAdmin.!error.name_servers.count'] = "Anda harus menentukan setidaknya 2 server nama.";
$lang['DirectAdmin.!error.api.internal'] = "Terjadi kesalahan internal, atau server tidak menanggapi permintaan.";
$lang['DirectAdmin.!error.meta[type].format'] = "Jenis akun harus pengguna atau reseller.";
$lang['DirectAdmin.!error.meta[package].empty'] = "Sebuah paket DirectAdmin diperlukan.";
$lang['DirectAdmin.!error.meta[ip].empty'] = "Alamat IP diperlukan.";
$lang['DirectAdmin.!error.direct_admin_domain.format'] = "Silakan masukkan nama domain yang valid dari formulir: domain.com";
$lang['DirectAdmin.!error.direct_admin_username.format'] = "Nama pengguna hanya boleh berisi karakter alfanumerik.";
$lang['DirectAdmin.!error.direct_admin_username.length'] = "Username harus antara 4 dan 8 karakter.";
$lang['DirectAdmin.!error.direct_admin_password.format'] = "Pastikan kata sandi berisi hal berikut: Setidaknya 12 karakter, setidaknya 1 karakter huruf besar AZ, setidaknya 1 karakter huruf kecil az, setidaknya 1 angka 0-9, dan setidaknya 1 karakter khusus dari himpunan: ! \"#\$%&'()*+,-./:;<=>?@[]^_` {|}";
$lang['DirectAdmin.!error.direct_admin_email.format'] = "Silakan isi alamat email.";
$lang['DirectAdmin.!error.change_package.type'] = "Modul tidak mendukung perubahan antara paket pengguna dan pengecer.";
$lang['DirectAdmin.name'] = "DirectAdmin";
$lang['DirectAdmin.module_row'] = "Server";
$lang['DirectAdmin.module_row_plural'] = "Server";
$lang['DirectAdmin.module_group'] = "Kelompok Server";
$lang['DirectAdmin.tab_stats'] = "Statistik";
$lang['DirectAdmin.servers.no_results'] = "Tidak ada server.";
$lang['DirectAdmin.server_groups.no_results'] = "Tidak ada kelompok server";
$lang['DirectAdmin.service_field.domain'] = "Domain";
$lang['DirectAdmin.service_field.username'] = "Nama Pengguna";
$lang['DirectAdmin.service_field.password'] = "Kata sandi";
$lang['DirectAdmin.service_field.email'] = "Email";
$lang['DirectAdmin.service_info.username'] = "Nama pengguna";
$lang['DirectAdmin.service_info.password'] = "Kata sandi";
$lang['DirectAdmin.service_info.server'] = "Server";
$lang['DirectAdmin.service_info.options'] = "Pilihan";
$lang['DirectAdmin.service_info.option_login'] = "Masuk";
$lang['DirectAdmin.package_fields.type'] = "Jenis akun";
$lang['DirectAdmin.package_fields.type_user'] = "User";
$lang['DirectAdmin.package_fields.type_reseller'] = "Reseller";
$lang['DirectAdmin.package_fields.package'] = "Paket DirectAdmin";
$lang['DirectAdmin.package_fields.ip'] = "Alamat IP";
$lang['DirectAdmin.package_fields.ip_shared'] = "Bersama";
$lang['DirectAdmin.package_fields.ip_assign'] = "Menetapkan";
$lang['DirectAdmin.add_module_row'] = "Tambahkan Server";
$lang['DirectAdmin.add_module_group'] = "Tambahkan Kelompok Server";
$lang['DirectAdmin.manage.module_rows_title'] = "Server";
$lang['DirectAdmin.manage.module_groups_title'] = "Grup Server";
$lang['DirectAdmin.manage.module_rows_heading.name'] = "Label Server";
$lang['DirectAdmin.manage.module_rows_heading.host_name'] = "Host Name";
$lang['DirectAdmin.manage.module_rows_heading.accounts'] = "Akun";
$lang['DirectAdmin.manage.module_rows_heading.options'] = "Pilihan";
$lang['DirectAdmin.manage.module_groups_heading.name'] = "Nama kelompok";
$lang['DirectAdmin.manage.module_groups_heading.servers'] = "Hitungan Server ";
$lang['DirectAdmin.manage.module_groups_heading.options'] = "Pilihan";
$lang['DirectAdmin.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['DirectAdmin.manage.module_rows.edit'] = "Mengedit";
$lang['DirectAdmin.manage.module_groups.edit'] = "Sunting";
$lang['DirectAdmin.manage.module_rows.delete'] = "Hapus";
$lang['DirectAdmin.manage.module_groups.delete'] = "Hapus";
$lang['DirectAdmin.manage.module_rows.confirm_delete'] = "Anda yakin ingin menghapus server ini?";
$lang['DirectAdmin.manage.module_groups.confirm_delete'] = "Apakah Anda yakin ingin menghapus kelompok server ini?";
$lang['DirectAdmin.row_meta.server_name'] = "Server Label";
$lang['DirectAdmin.row_meta.host_name'] = "Nama host";
$lang['DirectAdmin.row_meta.user_name'] = "Nama User";
$lang['DirectAdmin.row_meta.password'] = "Sandi";
$lang['DirectAdmin.row_meta.use_ssl'] = "Gunakan SSL saat menghubungkan ke API (dianjurkan)";
$lang['DirectAdmin.row_meta.account_limit'] = "Batas akun";
$lang['DirectAdmin.row_meta.name_server'] = "Nama server %1\$s"; // %1$s is the name server number (e.g. 2)
$lang['DirectAdmin.add_row.box_title'] = "Tambahkan DirectAdmin Server";
$lang['DirectAdmin.add_row.basic_title'] = "Pengaturan Dasar";
$lang['DirectAdmin.add_row.name_servers_title'] = "Nama Server";
$lang['DirectAdmin.add_row.name_server_btn'] = "Tambahkan Server Nama Tambahan";
$lang['DirectAdmin.add_row.name_server_col'] = "Nama Server";
$lang['DirectAdmin.add_row.name_server_host_col'] = "Hostname";
$lang['DirectAdmin.add_row.remove_name_server'] = "Hapus";
$lang['DirectAdmin.add_row.notes_title'] = "Catatan";
$lang['DirectAdmin.add_row.add_btn'] = "Tambahkan Server";
$lang['DirectAdmin.edit_row.box_title'] = "Sunting DirectAdmin Server";
$lang['DirectAdmin.edit_row.basic_title'] = "Pengaturan dasar";
$lang['DirectAdmin.edit_row.name_servers_title'] = "Nama Server";
$lang['DirectAdmin.edit_row.name_server_btn'] = "Tambahkan Nameserver Tambahan";
$lang['DirectAdmin.edit_row.name_server_col'] = "Nama Server";
$lang['DirectAdmin.edit_row.name_server_host_col'] = "Hostname";
$lang['DirectAdmin.edit_row.remove_name_server'] = "hapus";
$lang['DirectAdmin.edit_row.notes_title'] = "Catatan";
$lang['DirectAdmin.edit_row.add_btn'] = "Edit Server";
$lang['DirectAdmin.tab_client_stats'] = "Statistik";
$lang['DirectAdmin.tab_client_stats.info_title'] = "Informasi";
$lang['DirectAdmin.tab_client_stats.info_heading.field'] = "Bidang";
$lang['DirectAdmin.tab_client_stats.info_heading.value'] = "Nilai";
$lang['DirectAdmin.tab_client_stats.no_results'] = "Informasi statistik saat ini tidak tersedia.";
$lang['DirectAdmin.order_options.roundrobin'] = "Distribusikan Secara Merata Antar Server";
$lang['DirectAdmin.!error.direct_admin_password.matches'] = "Kata Sandi dan Konfirmasi Kata Sandi tidak cocok.";
$lang['DirectAdmin.tab_client_actions'] = "tindakan";
$lang['DirectAdmin.order_options.first'] = "Server Tidak Penuh Pertama";
$lang['DirectAdmin.tab_client_actions.change_password'] = "Ganti kata sandi";
$lang['DirectAdmin.tab_client_actions.field_direct_admin_password'] = "Kata sandi";
$lang['DirectAdmin.tab_client_actions.field_direct_admin_confirm_password'] = "konfirmasi sandi";
$lang['DirectAdmin.tab_client_actions.field_password_submit'] = "Ubah Password";
$lang['DirectAdmin.!error.port.format'] = "Port harus berupa angka.";
$lang['DirectAdmin.service_field.text_generate_password'] = "Buat Kata Sandi";
$lang['DirectAdmin.row_meta.port'] = "Port";
$lang['DirectAdmin.row_meta.default_port'] = "2222";
$lang['DirectAdmin.tab_client_actions.text_generate_password'] = "Buat Kata Sandi";
$lang['DirectAdmin.description'] = "DirectAdmin adalah panel kontrol hosting web berbasis web grafis yang dirancang untuk mempermudah administrasi situs web.";
?>
