<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Offline.name'] = "Pembayaran Offline";
$lang['Offline.instructions'] = "Instruksi";
$lang['Offline.!error.instructions.valid'] = "Anda harus memasukkan beberapa petunjuk.";
$lang['Offline.description'] = "Memungkinkan Anda menampilkan instruksi khusus untuk melakukan pembayaran secara offline";
?>