<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminMain.!success.options_updated'] = "Opsi Sekilas Penagihan berhasil diperbarui!";
$lang['AdminMain.index.boxtitle_overview'] = "Sekilas tentang Penagihan";
$lang['AdminMain.index.statistic.revenue_today'] = "Pendapatan Hari Ini";
$lang['AdminMain.index.statistic.revenue_month'] = "Pendapatan Bulan ini";
$lang['AdminMain.index.statistic.invoiced_today'] = "Ditagih Hari Ini";
$lang['AdminMain.index.statistic.invoiced_month'] = "Tagihan Bulan ini";
$lang['AdminMain.index.statistic.balance_outstanding'] = "Saldo luar biasa";
$lang['AdminMain.index.statistic.balance_overdue'] = "Saldo terlambat";
$lang['AdminMain.index.statistic.scheduled_cancelation'] = "Pembatalan terjadwal";
$lang['AdminMain.index.statistic.services_active'] = "Layanan Aktif";
$lang['AdminMain.index.statistic.services_added_today'] = "Layanan Ditambahkan Hari ini";
$lang['AdminMain.index.statistic.services_canceled_today'] = "Layanan Dibatalkan Hari ini";
$lang['AdminMain.settings.text_options'] = "Periksa pilihan yang akan muncul pada Ikhtisar Penagihan.";
$lang['AdminMain.settings.heading_statistics'] = "Statistik";
$lang['AdminMain.settings.heading_graphs'] = "Grafik";
$lang['AdminMain.settings.heading_graph_settings'] = "Pengaturan Grafik";
$lang['AdminMain.settings.revenue_today'] = "Pendapatan Hari Ini";
$lang['AdminMain.settings.revenue_month'] = "Pendapatan Bulan ini";
$lang['AdminMain.settings.invoiced_today'] = "Ditagih Hari Ini";
$lang['AdminMain.settings.invoiced_month'] = "Tagihan Bulan ini";
$lang['AdminMain.settings.balance_outstanding'] = "Saldo luar biasa";
$lang['AdminMain.settings.balance_overdue'] = "Saldo Terlambat";
$lang['AdminMain.settings.scheduled_cancelation'] = "Pembatalan terjadwal";
$lang['AdminMain.settings.services_active'] = "Layanan Aktif";
$lang['AdminMain.settings.services_added_today'] = "Layanan Ditambahkan Hari ini";
$lang['AdminMain.settings.services_canceled_today'] = "Layanan Batal hari ini";
$lang['AdminMain.settings.text_graphs'] = "Periksa grafik mana yang akan muncul di Ikhtisar Penagihan.";
$lang['AdminMain.settings.graph_invoiced'] = "Grafik Jumlah tagihan";
$lang['AdminMain.settings.text_graph_settings'] = "Kelola setelan grafik untuk grafik yang akan muncul di Ikhtisar Penagihan.";
$lang['AdminMain.settings.show_legend'] = "Tampilkan Legend di Grafik";
$lang['AdminMain.settings.date_range'] = "Rentang Tanggal Grafik";
$lang['AdminMain.settings.submit_settings'] = "Perbarui Pengaturan";
$lang['AdminMain.settings.submit_cancel'] = "Kembali ke Ikhtisar";
$lang['AdminMain.date_range.days'] = "hari-hari";
$lang['AdminMain.graph_name.graph_invoiced'] = "Jumlah Faktur";
$lang['AdminMain.graph_line_name.total'] = "Total";
$lang['AdminMain.graph_line_name.credit'] = "Kartu Kredit";
$lang['AdminMain.graph_line_name.ach'] = "ACH";
$lang['AdminMain.graph_line_name.other'] = "Lain";
$lang['AdminMain.index.statistic.revenue_year'] = "Pendapatan Tahun ini";
$lang['AdminMain.settings.revenue_year'] = "Pendapatan Tahun ini";
$lang['AdminMain.settings.graph_revenue_year'] = "Grafik Pendapatan (Tahun ke Tanggal)";
$lang['AdminMain.graph_name.graph_revenue_year'] = "Pendapatan (Tahun ke Tanggal)";
$lang['AdminMain.settings.graph_revenue'] = "Grafik Pendapatan (Range)";
$lang['AdminMain.graph_name.graph_revenue'] = "Pendapatan (Rentang)";
$lang['AdminMain.index.statistic.credits_today'] = "Kredit Hari Ini";
$lang['AdminMain.index.statistic.credits_month'] = "Kredit Bulan ini";
$lang['AdminMain.index.statistic.credits_year'] = "Kredit Tahun ini";
$lang['AdminMain.settings.credits_today'] = "Kredit Hari Ini";
$lang['AdminMain.settings.credits_month'] = "Kredit Bulan ini";
$lang['AdminMain.settings.credits_year'] = "Kredit Tahun ini";
$lang['AdminMain.graph_line_name.credits'] = "Kredit";
$lang['AdminMain.index.statistic.invoiced_today_proforma'] = "Ditagih Hari Ini (Proforma)";
$lang['AdminMain.index.statistic.invoiced_month_proforma'] = "Ditagih Bulan ini (Proforma)";
$lang['AdminMain.settings.invoiced_today_proforma'] = "Ditagih Hari Ini (Proforma)";
$lang['AdminMain.settings.invoiced_month_proforma'] = "Ditagih Bulan ini (Proforma)";
?>
