<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['BillingOverviewSettings.!error.staff_id.exists'] = "ID staf tidak valid.";
$lang['BillingOverviewSettings.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['BillingOverviewSettings.!error.settings[][key].empty'] = "Tidak ada tombol pengaturan, mungkin kosong.";
$lang['BillingOverviewSettings.!error.settings[][value].length'] = "Setiap panjang nilai pengaturan individu tidak boleh melebihi 255 karakter.";
?>
