<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['InvoiceDelivery.!error.libxml_required'] = "extensi libxml dan simplexml diperlukan untuk pengiriman Faktur";
$lang['InvoiceDelivery.deliverinvoices.interfax_subject'] = "Faktur #%1\$s"; // %1$s is the invoice number (or the first invoice number in a group of several)
$lang['InvoiceDelivery.deliverinvoices.postalmethods_description'] = "Faktur #%1\$s"; // %1$s is the invoice number (or the first invoice number in a group of several);
?>