<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AgingInvoices.name'] = "Aging Invoices";
$lang['AgingInvoices.options.field_status'] = "Status";
$lang['AgingInvoices.option.any'] = "Apa saja";
$lang['AgingInvoices.heading.id_code'] = "Faktur #";
$lang['AgingInvoices.heading.client_id_code'] = "Klien #";
$lang['AgingInvoices.heading.subtotal'] = "Subtotal";
$lang['AgingInvoices.heading.total'] = "Total";
$lang['AgingInvoices.heading.paid'] = "Dibayar";
$lang['AgingInvoices.heading.currency'] = "Mata uang";
$lang['AgingInvoices.heading.status'] = "Status";
$lang['AgingInvoices.heading.date_billed'] = "Tanggal Ditagih";
$lang['AgingInvoices.heading.date_due'] = "Tanggal jatuh tempo";
$lang['AgingInvoices.heading.past30'] = "30";
$lang['AgingInvoices.heading.past60'] = "60";
$lang['AgingInvoices.heading.past90'] = "90+";
$lang['AgingInvoices.heading.client_first_name'] = "Nama Depan Klien";
$lang['AgingInvoices.heading.client_last_name'] = "Nama Belakang Klien";
$lang['AgingInvoices.heading.client_email'] = "Email Klien";
$lang['AgingInvoices.heading.client_numbers'] = "Nomor Telepon Klien";
?>
