<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Actions.!error.location.valid'] = "lokasi tidak valid";
$lang['Actions.!error.location.unique'] = "Lokasi dan url harus unik untuk company ini";
$lang['Actions.!error.url.empty'] = "Masukkan urlnya";
$lang['Actions.!error.name.action_empty'] = "masukkan nama aksi";
$lang['Actions.!error.plugin_id.valid'] = "sediakan ID plugin yang valid";
$lang['Actions.!error.company_id.valid'] = "ID Company tidak benar";
$lang['Actions.!error.editable.valid'] = "Piihan Edit harus di set 1 atau 0";
$lang['Actions.!error.enabled.valid'] = "Pilihan harus di set 1 atau 0";
$lang['Actions.getLocations.nav_staff'] = "Menu Navigasi Staf";
$lang['Actions.getLocations.nav_client'] = "Menu Navigasi Klien";
$lang['Actions.getLocations.nav_public'] = "Menu Navigasi Publik";
$lang['Actions.getLocations.widget_client_home'] = "Widget Dasbor Klien";
$lang['Actions.getLocations.widget_staff_home'] = "Widget Dasbor Staf";
$lang['Actions.getLocations.widget_staff_client'] = "Widget Profil Klien Staf";
$lang['Actions.getLocations.widget_staff_billing'] = "Widget Penagihan Staf";
$lang['Actions.getLocations.action_staff_client'] = "Tautan \"Tindakan Akun\" Klien";
$lang['Actions.getLocationDescriptions.nav_staff'] = "Buat link tersedia di interface admin";
$lang['Actions.getLocationDescriptions.nav_client'] = "Buat link tersedia di navigasi client";
$lang['Actions.getLocationDescriptions.nav_public'] = "Buat link menjadi tersedia di interface umum";
$lang['Actions.getLocationDescriptions.widget_client_home'] = "Membuat widget di dasbor klien.";
$lang['Actions.getLocationDescriptions.widget_staff_home'] = "Membuat widget di dasbor staf.";
$lang['Actions.getLocationDescriptions.widget_staff_client'] = "Membuat widget di halaman profil klien staf.";
$lang['Actions.getLocationDescriptions.widget_staff_billing'] = "Membuat widget di halaman penagihan staf.";
$lang['Actions.getLocationDescriptions.action_staff_client'] = "-";
?>
