<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminCompanyClientOptions.!success.field_updated'] = "Bidang kustom klien telah berhasil diperbarui.";
$lang['AdminCompanyClientOptions.!success.field_created'] = "Bidang khusus klien telah berhasil dibuat.";
$lang['AdminCompanyClientOptions.!success.field_deleted'] = "Bidang kustom klien telah berhasil dihapus.";
$lang['AdminCompanyClientOptions.!success.requiredfields_updated'] = "Bidang wajib telah berhasil diperbarui.";
$lang['AdminCompanyClientoptions.customfields.page_title'] = "Pengaturan > Perusahaan > Opsi Klien > Bidang Kustom Klien > Telusuri";
$lang['AdminCompanyClientOptions.customfields.boxtitle_browse'] = "Jelajahi Bidang Kustom Klien";
$lang['AdminCompanyClientOptions.customfields.categorylink_addfield'] = "Buat Bidang";
$lang['AdminCompanyClientOptions.customfields.text_name'] = "Nama";
$lang['AdminCompanyClientOptions.customfields.text_type'] = "Tipe";
$lang['AdminCompanyClientOptions.customfields.text_required'] = "Yg dibutuhkan";
$lang['AdminCompanyClientOptions.customfields.text_visible'] = "Terlihat oleh Klien";
$lang['AdminCompanyClientOptions.customfields.text_read_only'] = "Baca Saja untuk Klien";
$lang['AdminCompanyClientOptions.customfields.text_options'] = "Pilihan";
$lang['AdminCompanyClientOptions.customfields.option_edit'] = "Sunting";
$lang['AdminCompanyClientOptions.customfields.option_delete'] = "Menghapus";
$lang['AdminCompanyClientOptions.customfields.confirm_delete'] = "Menghapus bidang khusus ini akan menghapus semua dan semua data yang disimpan untuknya untuk setiap klien dalam grup ini. Anda yakin ingin menghapus bidang khusus ini?";
$lang['AdminCompanyClientOptions.customfields.no_results'] = "Tidak ada bidang khusus.";
$lang['AdminCompanyClientoptions.addcustomfield.page_title'] = "Pengaturan> Perusahaan> Opsi Klien> Bidang Kustom Klien> Tambahkan Bidang Kustom";
$lang['AdminCompanyClientOptions.addcustomfield.boxtitle_add'] = "Tambahkan Bidang Kustom";
$lang['AdminCompanyClientOptions.addcustomfield.categorylink_select'] = "Tambahkan Opsi Tambahan";
$lang['AdminCompanyClientOptions.addcustomfield.heading_select_value'] = "Nilai";
$lang['AdminCompanyClientOptions.addcustomfield.heading_select_option'] = "Nama Opsi";
$lang['AdminCompanyClientOptions.addcustomfield.text_remove'] = "Menghapus";
$lang['AdminCompanyClientoptions.editcustomfield.page_title'] = "Pengaturan > Perusahaan > Opsi Klien > Bidang Kustom Klien > Edit Bidang Kustom";
$lang['AdminCompanyClientOptions.editcustomfield.boxtitle_edit'] = "Edit Bidang Kustom";
$lang['AdminCompanyClientOptions.editcustomfield.categorylink_select'] = "Tambahkan Opsi Tambahan";
$lang['AdminCompanyClientOptions.editcustomfield.heading_select_value'] = "Nilai";
$lang['AdminCompanyClientOptions.editcustomfield.heading_select_option'] = "Nama Opsi";
$lang['AdminCompanyClientOptions.editcustomfield.text_remove'] = "Menghapus";
$lang['AdminCompanyClientOptions.getRequired.no'] = "Tidak";
$lang['AdminCompanyClientOptions.getRequired.yes'] = "ya";
$lang['AdminCompanyClientOptions.getRequired.regex'] = "Regex Kustom";
$lang['AdminCompanyClientoptions.requiredfields.page_title'] = "Pengaturan > Perusahaan > Opsi Klien > Bidang Kustom Klien > Bidang Klien yang Diperlukan";
$lang['AdminCompanyClientOptions.requiredfields.boxtitle'] = "Bidang Klien yang Diperlukan";
$lang['AdminCompanyClientOptions.requiredfields.description'] = "Periksa bidang yang harus diperlukan saat membuat atau memperbarui klien atau kontak.";
$lang['AdminCompanyClientOptions.requiredfields.field_company'] = "Perusahaan / Org.";
$lang['AdminCompanyClientOptions.requiredfields.field_title'] = "Judul";
$lang['AdminCompanyClientOptions.requiredfields.field_address1'] = "Alamat 1";
$lang['AdminCompanyClientOptions.requiredfields.field_address2'] = "alamat 2";
$lang['AdminCompanyClientOptions.requiredfields.field_city'] = "Kota";
$lang['AdminCompanyClientOptions.requiredfields.field_country'] = "Negara";
$lang['AdminCompanyClientOptions.requiredfields.field_state'] = "Negara Bagian/Provinsi";
$lang['AdminCompanyClientOptions.requiredfields.field_zip'] = "Kode Pos/Kode Pos";
$lang['AdminCompanyClientOptions.requiredfields.field_email'] = "Email";
$lang['AdminCompanyClientOptions.requiredfields.text_submit'] = "Perbarui Pengaturan";
$lang['AdminCompanyClientOptions.requiredfields.field_first_name'] = "Nama depan";
$lang['AdminCompanyClientOptions.requiredfields.field_last_name'] = "Nama keluarga";
$lang['AdminCompanyClientOptions.!notice.group_settings'] = "CATATAN: Pengaturan ini hanya berlaku untuk Grup Klien yang mewarisi pengaturannya dari Perusahaan.";
$lang['AdminCompanyClientOptions.!tooltip.state'] = "Berhati-hatilah saat membutuhkan Negara Bagian/Provinsi untuk dipilih. Beberapa negara tidak memiliki negara bagian. Klien di negara-negara tersebut tidak akan dapat menyimpan detail kontak mereka. Kami menyarankan untuk tidak memerlukan bidang ini.";
$lang['AdminCompanyClientOptions.!success.general_updated'] = "Pengaturan umum telah berhasil diperbarui.";
$lang['AdminCompanyClientOptions.!tooltip.unique_contact_emails'] = "Membatasi alamat email untuk kontak. Kontak Utama berarti tidak ada dua kontak utama (yaitu klien) yang dapat memiliki alamat email yang sama. Semua Kontak berarti tidak ada kontak jenis apa pun yang dapat memiliki alamat email yang sama dengan kontak lain.";
$lang['AdminCompanyClientoptions.general.page_title'] = "Pengaturan > Perusahaan > Opsi Klien > Umum";
$lang['AdminCompanyClientOptions.general.boxtitle'] = "Pengaturan Klien Umum";
$lang['AdminCompanyClientOptions.general.field_unique_contact_emails'] = "Terapkan Alamat Email Kontak Unik";
$lang['AdminCompanyClientOptions.general.field_unique_contact_emails_none'] = "-- Tidak ada --";
$lang['AdminCompanyClientOptions.general.field_unique_contact_emails_primary'] = "Kontak Utama";
$lang['AdminCompanyClientOptions.general.field_unique_contact_emails_all'] = "Semua kontak";
$lang['AdminCompanyClientOptions.general.text_submit'] = "Kirim";
$lang['AdminCompanyClientOptions.addcustomfield.configuration_warning'] = "Memerlukan bidang ini sementara tidak membuatnya terlihat oleh klien akan mengakibatkan klien tidak dapat mendaftar atau memperbarui informasi akun mereka.";
$lang['AdminCompanyClientOptions.!tooltip.client_group_id'] = "Bidang kustom hanya akan berlaku untuk anggota grup klien yang dipilih.";
$lang['AdminCompanyClientOptions.!tooltip.name'] = "Ini adalah nama tampilan untuk bidang ini. Ini mungkin definisi bahasa.";
$lang['AdminCompanyClientOptions.!tooltip.is_lang'] = "Hanya centang kotak ini jika Anda telah menambahkan definisi bahasa untuk bidang kustom ini dalam file bahasa kustom.";
$lang['AdminCompanyClientOptions.!tooltip.type'] = "Bidang kustom akan muncul sebagai jenis formulir yang dipilih.";
$lang['AdminCompanyClientOptions.!tooltip.show_client'] = "Centang untuk mengizinkan klien melihat dan memperbarui bidang ini.";
$lang['AdminCompanyClientOptions.!tooltip.read_only'] = "Mencentang kotak ini akan membuat bidang khusus ini tidak dapat diubah oleh klien. Bidang baca-saja akan disetel secara otomatis ke nilai default yang ditetapkan.";
$lang['AdminCompanyClientOptions.!tooltip.required'] = "Pilih \"Ya\" untuk memastikan bahwa nilai diberikan untuk bidang ini, untuk jenis Drop Down opsi harus muncul dalam daftar opsi. Pilih \"Tidak\" untuk menerima nilai apa pun untuk bidang ini. Pilih \"Custom Regex\" untuk menggunakan ekspresi reguler khusus untuk memvalidasi bidang ini.";
$lang['AdminCompanyClientOptions.!tooltip.regex'] = "Opsi ini akan muncul jika \"Diperlukan\" diatur ke \"Regex Khusus\". Masukkan ekspresi reguler khusus untuk memvalidasi bidang ini di sini.";
$lang['AdminCompanyClientOptions.!tooltip.encrypted'] = "Centang kotak ini untuk menyimpan nilai yang dienkripsi. Ini sangat dianjurkan jika menyimpan informasi sensitif atau identitas pribadi.";
$lang['AdminCompanyClientOptions.!tooltip.checkbox_value'] = "Nilai yang dikirimkan saat kotak centang dicentang.";
$lang['AdminCompanyClientOptions.!tooltip.default_text'] = "Teks yang dimasukkan di sini akan menjadi nilai default yang ditetapkan untuk opsi ini ketika bidang khusus ini ditambahkan untuk klien.";
$lang['AdminCompanyClientOptions.!tooltip.default_checkbox'] = "Jika dicentang, kotak centang ini akan dicentang secara default saat bidang khusus ini ditambahkan untuk klien.";
$lang['AdminCompanyClientOptions.!tooltip.select_default'] = "Nilai opsi yang dicentang akan menjadi nilai default yang dipilih saat opsi ini ditambahkan untuk klien.";
$lang['AdminCompanyClientOptions.addcustomfield.field.client_group_id'] = "Grup Klien";
$lang['AdminCompanyClientOptions.addcustomfield.field.name'] = "Nama";
$lang['AdminCompanyClientOptions.addcustomfield.field.is_lang'] = "Nama adalah definisi bahasa";
$lang['AdminCompanyClientOptions.addcustomfield.field.type'] = "Jenis";
$lang['AdminCompanyClientOptions.addcustomfield.field.show_client'] = "Terlihat oleh Klien";
$lang['AdminCompanyClientOptions.addcustomfield.field.read_only'] = "Baca Saja untuk Klien";
$lang['AdminCompanyClientOptions.addcustomfield.field.required'] = "Yg dibutuhkan";
$lang['AdminCompanyClientOptions.addcustomfield.field.regex'] = "Regex Khusus";
$lang['AdminCompanyClientOptions.addcustomfield.field.encrypted'] = "Enkripsi Nilai";
$lang['AdminCompanyClientOptions.addcustomfield.field.addsubmit'] = "Tambahkan Bidang Kustom";
$lang['AdminCompanyClientOptions.addcustomfield.field.checkbox_value'] = "Nilai";
$lang['AdminCompanyClientOptions.addcustomfield.field.default_checkbox'] = "Nilai Default Diperiksa";
$lang['AdminCompanyClientOptions.addcustomfield.field.default_text'] = "Nilai Teks Default";
$lang['AdminCompanyClientOptions.addcustomfield.heading_select_default'] = "Bawaan";
$lang['AdminCompanyClientOptions.editcustomfield.field.name'] = "Nama";
$lang['AdminCompanyClientOptions.editcustomfield.field.is_lang'] = "Nama adalah definisi bahasa";
$lang['AdminCompanyClientOptions.editcustomfield.field.type'] = "Tipe";
$lang['AdminCompanyClientOptions.editcustomfield.field.show_client'] = "Terlihat oleh Klien";
$lang['AdminCompanyClientOptions.editcustomfield.field.read_only'] = "Baca Saja untuk Klien";
$lang['AdminCompanyClientOptions.editcustomfield.field.required'] = "Yg dibutuhkan";
$lang['AdminCompanyClientOptions.editcustomfield.field.regex'] = "Regex Khusus";
$lang['AdminCompanyClientOptions.editcustomfield.field.encrypted'] = "Enkripsi Nilai";
$lang['AdminCompanyClientOptions.editcustomfield.field.editsubmit'] = "Edit Bidang Kustom";
$lang['AdminCompanyClientOptions.editcustomfield.field.checkbox_value'] = "Nilai";
$lang['AdminCompanyClientOptions.editcustomfield.field.default_checkbox'] = "Nilai Default Diperiksa";
$lang['AdminCompanyClientOptions.editcustomfield.field.default_text'] = "Nilai Teks Default";
$lang['AdminCompanyClientOptions.editcustomfield.heading_select_default'] = "Bawaan";
$lang['AdminCompanyClientOptions.!tooltip.force_email_usernames'] = "Klien harus menggunakan alamat email mereka sebagai nama pengguna mereka daripada menentukan nama mereka sendiri. Klien yang ada masih dapat login dengan nama pengguna mereka saat ini.";
$lang['AdminCompanyClientOptions.general.field_force_email_usernames'] = "Paksa Nama Pengguna Email";
$lang['AdminCompanyClientOptions.!tooltip.email_verification'] = "Centang untuk mengirim email verifikasi email saat login baru dibuat atau klien mengubah alamat email mereka. Pemberitahuan akan muncul di profil klien sampai mereka diverifikasi.";
$lang['AdminCompanyClientOptions.general.field_email_verification'] = "Aktifkan Verifikasi Email";
$lang['AdminCompanyClientOptions.general.prevent_unverified_payments'] = "Cegah Pembayaran dari Klien yang Belum Diverifikasi";
?>
