<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminMyinfo.!success.updated'] = "Setting akun anda berhasil diupdate";
$lang['AdminMyinfo.!success.notices_updated'] = "Pengaturan pemberitahuan Anda berhasil diperbarui.";
$lang['AdminMyinfo.gettabnames.text_index'] = "Akun";
$lang['AdminMyinfo.gettabnames.text_notices'] = "Pemberitahuan";
$lang['AdminMyinfo.index.page_title'] = "Informasi saya";
$lang['AdminMyinfo.index.boxtitle_myinfo'] = "Informasi saya";
$lang['AdminMyinfo.index.field_username'] = "Nama pengguna";
$lang['AdminMyinfo.index.field_firstname'] = "Nama depan";
$lang['AdminMyinfo.index.field_lastname'] = "Nama terakhir";
$lang['AdminMyinfo.index.field_email'] = "E-mail";
$lang['AdminMyinfo.index.field_mobileemail'] = "E-Mail Mobile";
$lang['AdminMyinfo.index.field_newpass'] = "kata sandi baru";
$lang['AdminMyinfo.index.field_confirmpass'] = "Konfirmasi Sandi";
$lang['AdminMyinfo.index.field_twofactormode'] = "Dua Faktor Otentikasi";
$lang['AdminMyinfo.index.field_twofactorkey'] = "Key / kunci Dua Faktor";
$lang['AdminMyinfo.index.field_twofactorpin'] = "Dua Faktor Pin";
$lang['AdminMyinfo.index.field_groups'] = "Grup Staf";
$lang['AdminMyinfo.index.field_currentpass'] = "Password terkini";
$lang['AdminMyinfo.index.field_infosubmit'] = "Perbarui Akun";
$lang['AdminMyinfo.notices.heading_notices'] = "Email Pemberitahuan BCC";
$lang['AdminMyinfo.notices.field_noticesubmit'] = "Update Pemberitahuan";
$lang['AdminMyinfo.notices.no_bcc_results'] = "Tidak ada catatan email BCC yang tersedia pada kelompok staff anda";
$lang['AdminMyinfo.index.field_otp'] = "Kata Sandi Sekali Pakai";
$lang['AdminMyinfo.index.note_otp'] = "Untuk mengkonfirmasi otentikasi dua arah Anda, konfigurasikan dengan benar, masukkan password yang dihasilkan satu waktu (one-time password.)";
$lang['AdminMyinfo.notices.page_title'] = "Informasi saya > Pemberitahuan";
$lang['AdminMyinfo.notices.heading_subscription_notices'] = "Pemberitahuan Berlangganan Email";
$lang['AdminMyinfo.notices.no_subscription_results'] = "Tidak ada pemberitahuan berlangganan yang tersedia untuk grup staf Anda.";
$lang['AdminMyinfo.index.field_language'] = "Bahasa";
$lang['AdminMyinfo.index.field_mobilenumber'] = "Nomor handphone";
?>
