<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminSystemStaff.!success.staff_added'] = "Anggota staf itu telah berhasil ditambahkan!";
$lang['AdminSystemStaff.!success.staff_updated'] = "Anggota staf itu telah berhasil diperbarui!";
$lang['AdminSystemStaff.!success.group_added'] = "Staff group, \"%1\$s\", Berhasil dibuat!"; // %1$s is the name of the staff group
$lang['AdminSystemStaff.!success.group_updated'] = "Grup staf, \"%1\$s\", telah berhasil diperbarui!"; // %1$s is the name of the staff group
$lang['AdminSystemStaff.!success.group_deleted'] = "Grup staf, \"%1\$s\", telah berhasil dihapus!"; // %1$s is the name of the staff group
$lang['AdminSystemStaff.manage.boxtitle_manage'] = "Kelola Staff";
$lang['AdminSystemStaff.manage.category_active'] = "Aktif";
$lang['AdminSystemStaff.manage.category_inactive'] = "Non-aktif";
$lang['AdminSystemStaff.manage.categorylink_addstaff'] = "Tambahkan Staf";
$lang['AdminSystemStaff.manage.heading_name'] = "Nama";
$lang['AdminSystemStaff.manage.heading_email'] = "E-mail";
$lang['AdminSystemStaff.manage.heading_options'] = "Pilihan";
$lang['AdminSystemStaff.manage.no_results'] = "Tidak ada anggota staf dengan status ini.";
$lang['AdminSystemStaff.manage.confirm_deactivate'] = "Benar-benar menonaktifkan anggota staf ini?";
$lang['AdminSystemStaff.manage.confirm_reactivate'] = "Benar-benar mengaktifkan kembali anggota staff ini?";
$lang['AdminSystemStaff.manage.option_edit'] = "Edit";
$lang['AdminSystemStaff.manage.option_deactivate'] = "Menonaktifkan";
$lang['AdminSystemStaff.manage.option_reactivate'] = "Mengaktifkan kembali";
$lang['AdminSystemStaff.groups.option_delete'] = "Hapus";
$lang['AdminSystemStaff.add.boxtitle_addstaff'] = "Tambahkan Staf";
$lang['AdminSystemStaff.add.heading_contact'] = "Info kontak";
$lang['AdminSystemStaff.add.heading_authentication'] = "Otentikasi";
$lang['AdminSystemStaff.add.heading_groups'] = "Grup";
$lang['AdminSystemStaff.add.field_firstname'] = "Nama Depan";
$lang['AdminSystemStaff.add.field_lastname'] = "Nama keluarga";
$lang['AdminSystemStaff.add.field_email'] = "E-mail";
$lang['AdminSystemStaff.add.field_username'] = "Nama pengguna";
$lang['AdminSystemStaff.add.field_username_username'] = "Masukkan username";
$lang['AdminSystemStaff.add.field_username_email'] = "Gunakan alamat email sebagai username";
$lang['AdminSystemStaff.add.field_password'] = "Kata sandi";
$lang['AdminSystemStaff.add.field_confirmpass'] = "Konfirmasi Password";
$lang['AdminSystemStaff.add.field_twofactormode'] = "Otentikas iDua Faktor";
$lang['AdminSystemStaff.add.field_twofactorkey'] = "Kunci Dua Faktor";
$lang['AdminSystemStaff.add.field_twofactorpin'] = "Dua Faktor Pin";
$lang['AdminSystemStaff.add.text_membergroups'] = "Anggota Grup";
$lang['AdminSystemStaff.add.text_availablegroups'] = "Group yang tersedia";
$lang['AdminSystemStaff.edit.boxtitle_editstaff'] = "Edit Staff";
$lang['AdminSystemStaff.edit.heading_contact'] = "Info kontak";
$lang['AdminSystemStaff.edit.heading_authentication'] = "Autentikasi";
$lang['AdminSystemStaff.edit.heading_groups'] = "Grup";
$lang['AdminSystemStaff.edit.field_firstname'] = "Nama";
$lang['AdminSystemStaff.edit.field_lastname'] = "Nama Belakang";
$lang['AdminSystemStaff.edit.field_username'] = "Nama Pengguna";
$lang['AdminSystemStaff.edit.field_email'] = "E-mail";
$lang['AdminSystemStaff.edit.field_password'] = "kata sandi baru";
$lang['AdminSystemStaff.edit.field_confirmpass'] = "Konfirmasi Kata Sandi";
$lang['AdminSystemStaff.edit.field_twofactormode'] = "Two Factor Authentication";
$lang['AdminSystemStaff.edit.field_twofactorkey'] = "Kunci Dua Faktor";
$lang['AdminSystemStaff.edit.field_twofactorpin'] = "Dua Faktor Pin";
$lang['AdminSystemStaff.edit.text_membergroups'] = "Anggota Grup";
$lang['AdminSystemStaff.edit.text_availablegroups'] = "Grup yang tersedia";
$lang['AdminSystemStaff.groups.boxtitle_groups'] = "Staf Grup";
$lang['AdminSystemStaff.groups.categorylink_addgroup'] = "Buat Grup";
$lang['AdminSystemStaff.groups.heading_name'] = "Nama";
$lang['AdminSystemStaff.groups.heading_company_name'] = "Nama Perusahaan";
$lang['AdminSystemStaff.groups.heading_staff'] = "Jumlah staf";
$lang['AdminSystemStaff.groups.heading_options'] = "Pilihan";
$lang['AdminSystemStaff.groups.no_results'] = "Tidak ada kelompok staf.";
$lang['AdminSystemStaff.groups.option_edit'] = "Edit";
$lang['AdminSystemStaff.groups.modal_delete'] = "Apakah Anda yakin ingin menghapus kelompok staf ini?";
$lang['AdminSystemStaff.addgroup.boxtitle_addgroup'] = "Buat Grup";
$lang['AdminSystemStaff.addgroup.field_name'] = "Nama";
$lang['AdminSystemStaff.addgroup.field_company'] = "Perusahaan";
$lang['AdminSystemStaff.addgroup.field_groupsubmit'] = "Buat Grup";
$lang['AdminSystemStaff.addgroup.heading_general'] = "Umum";
$lang['AdminSystemStaff.addgroup.heading_permissions'] = "Access Control List";
$lang['AdminSystemStaff.editgroup.boxtitle_editgroup'] = "Edit Grup";
$lang['AdminSystemStaff.editgroup.field_name'] = "Nama";
$lang['AdminSystemStaff.editgroup.field_company'] = "Perusahaan";
$lang['AdminSystemStaff.editgroup.field_groupsubmit'] = "edit Grup";
$lang['AdminSystemStaff.editgroup.heading_general'] = "Umum";
$lang['AdminSystemStaff.editgroup.heading_permissions'] = "Daftar Kontrol Akses";
$lang['AdminSystemStaff.editgroup.dialog_confirm_edit_assigned'] = "Anda sedang ditugaskan untuk kelompok staf ini. Setiap perubahan yang Anda buat akan segera berlaku dan Anda mungkin tidak dapat mengakses daerah ini lagi. Apakah Anda yakin ingin membuat perubahan ini?";
$lang['AdminSystemStaff.manage.page_title'] = "Pengaturan > Sistem> Staf> Kelola Staf";
$lang['AdminSystemStaff.add.page_title'] = "Settings> System> Staf> Tambah Staf";
$lang['AdminSystemStaff.edit.page_title'] = "Pengaturan > Sistem > Staf > Edit Staf";
$lang['AdminSystemStaff.groups.page_title'] = "Pengaturan > Sistem > Staf > Staf Grup";
$lang['AdminSystemStaff.!groups.text_separator'] = "/";
$lang['AdminSystemStaff.!groups.text_group_start'] = "(";
$lang['AdminSystemStaff.!groups.text_group_end'] = ")";
$lang['AdminSystemStaff.addgroup.page_title'] = "Pengaturan > Sistem > Staf > Buat Grup";
$lang['AdminSystemStaff.addgroup.heading_email_notices'] = "Email Pemberitahuan BCC";
$lang['AdminSystemStaff.addgroup.text_check_all'] = "Centang Semua";
$lang['AdminSystemStaff.addgroup.text_uncheck_all'] = "Hapus tanda centang Semua";
$lang['AdminSystemStaff.editgroup.page_title'] = "Pengaturan > Sistem > Staf > Edit Grup";
$lang['AdminSystemStaff.editgroup.heading_email_notices'] = "Email Pemberitahuan BCC";
$lang['AdminSystemStaff.add.field_addsubmit'] = "Buat Staf";
$lang['AdminSystemStaff.edit.field_editsubmit'] = "Edit Staff";
$lang['AdminSystemStaff.addgroup.heading_subscription_email_notices'] = "Pemberitahuan Email Berlangganan";
$lang['AdminSystemStaff.editgroup.heading_subscription_email_notices'] = "Pemberitahuan Email Berlangganan";
$lang['AdminSystemStaff.addgroup.field_session_lock'] = "Log Out Pada Perubahan Alamat IP";
$lang['AdminSystemStaff.editgroup.field_session_lock'] = "Log Out Pada Perubahan Alamat IP";
$lang['AdminSystemStaff.add.field_numbermobile'] = "Nomor handphone";
$lang['AdminSystemStaff.edit.field_numbermobile'] = "Nomor handphone";
?>
