<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminCompanyGateways.!success.manage_updated'] = "Gateway telah berhasil diperbaharui";
$lang['AdminCompanyGateways.!success.upgraded'] = "Gateway berhasil ditingkatkan";
$lang['AdminCompanyGateways.!success.uninstalled'] = "Gerbang berhasil dicopot pemasangannya.";
$lang['AdminCompanyGateways.!success.installed'] = "Gateway berhasil diinstal.";
$lang['AdminCompanyGateways.available.heading_merchant'] = "Merchant";
$lang['AdminCompanyGateways.available.heading_nonmerchant'] = "Non-Merchant";
$lang['AdminCompanyGateways.available.text_author'] = "Penulis:";
$lang['AdminCompanyGateways.available.text_author_url'] = "URL penulis";
$lang['AdminCompanyGateways.available.text_supports'] = "Supports:";
$lang['AdminCompanyGateways.available.text_merchantach'] = "ACH";
$lang['AdminCompanyGateways.available.text_merchantachoffsite'] = "ACH offsite";
$lang['AdminCompanyGateways.available.text_merchantcc'] = "Kartu kredit";
$lang['AdminCompanyGateways.available.text_merchantccoffsite'] = "Kartu Kredit offsite";
$lang['AdminCompanyGateways.available.text_merchant_none'] = "Tidak ada gateway pedagang yang tersedia.";
$lang['AdminCompanyGateways.available.text_nonmerchant_none'] = "Tidak ada gateway non-pedagang yang tersedia.";
$lang['AdminCompanyGateways.available.btn_install'] = "Install";
$lang['AdminCompanyGateways.installed.heading_merchant'] = "Merchant/Pedagang";
$lang['AdminCompanyGateways.installed.heading_nonmerchant'] = "Non-Merchant";
$lang['AdminCompanyGateways.installed.text_author'] = "Penulis:";
$lang['AdminCompanyGateways.installed.text_author_url'] = "URL Penulis";
$lang['AdminCompanyGateways.installed.text_supports'] = "Supports:";
$lang['AdminCompanyGateways.installed.text_merchantach'] = "ACH";
$lang['AdminCompanyGateways.installed.text_merchantachoffsite'] = "ACH offsite";
$lang['AdminCompanyGateways.installed.text_merchantcc'] = "Kartu kredit";
$lang['AdminCompanyGateways.installed.text_merchantccoffsite'] = "Kartu Kredit offsite";
$lang['AdminCompanyGateways.installed.text_merchant_none'] = "Tidak ada gateway pedagang yang terpasang.";
$lang['AdminCompanyGateways.installed.text_nonmerchant_none'] = "Tidak ada gateway non-merchant.yang diinstal ";
$lang['AdminCompanyGateways.installed.btn_uninstall'] = "Uninstall";
$lang['AdminCompanyGateways.installed.btn_manage'] = "Mengelola";
$lang['AdminCompanyGateways.installed.btn_upgrade'] = "Meningkatkan";
$lang['AdminCompanyGateways.installed.confirm_uninstall'] = "Anda yakin ingin mencopot pemasangan gerbang ini?";
$lang['AdminCompanyGateways.manage.boxtitle_manage'] = "Kelola %1\$s"; // %1$s is the name of the gateway
$lang['AdminCompanyGateways.manage.heading_gateway'] = "Pilihan Gateway";
$lang['AdminCompanyGateways.manage.heading_currencies'] = "Mata Uang Yang Diterima";
$lang['AdminCompanyGateways.manage.text_addcurrency'] = "menambahkan mata uang";
$lang['AdminCompanyGateways.manage.update_settings'] = "Pembaruan Pengaturan ";
$lang['AdminCompanyGateways.available.page_title'] = "Pengaturan> Perusahaan> Gateways> Tersedia";
$lang['AdminCompanyGateways.available.signup_url'] = "Daftar";
$lang['AdminCompanyGateways.installed.page_title'] = "Pengaturan> Perusahaan> Gateway> Terpasang";
$lang['AdminCompanyGateways.installed.signup_url'] = "Daftar";
$lang['AdminCompanyGateways.manage.page_title'] = "Pengaturan> Perusahaan> Gateways> Kelola %1\$s"; // %1$s is the name of the gateway
$lang['AdminCompanyGateways.available.text_version'] = "(ver %1\$s)"; // %1$s is the version number of this gateway
$lang['AdminCompanyGateways.installed.text_version'] = "(ver %1\$s)"; // %1$s is the version number of this gateway
$lang['AdminCompanyGateways.manage.text_in_use_by'] = "digunakan oleh";
$lang['AdminCompanyGateways.!tab.installed'] = "Terpasang";
$lang['AdminCompanyGateways.!tab.available'] = "Tersedia";
$lang['AdminCompanyGateways.available.boxtitle_gateway'] = "Gateways";
$lang['AdminCompanyGateways.installed.boxtitle_gateway'] = "Gateway";
$lang['AdminCompanyGateways.available.text_merchantccform'] = "Formulir khusus Kartu Kredit";
$lang['AdminCompanyGateways.installed.text_merchantccform'] = "Formulir khusus Kartu Kredit";
?>
