<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminDialog.confirm.text_yes'] = "Iya";
$lang['AdminDialog.confirm.text_no'] = "Tidak";
$lang['AdminDialog.password.field_modal_password'] = "Kata sandi";
$lang['AdminDialog.password.field_modal_password_copied'] = "Saya telah menyalin kata sandi ini ke tempat yang aman";
$lang['AdminDialog.password.btn_generate'] = "Menghasilkan";
$lang['AdminDialog.password.btn_modal_password'] = "Kata sandi";
$lang['AdminDialog.password.btn_cancel'] = "Batal";
$lang['AdminDialog.password.btn_use_password'] = "Gunakan Kata Sandi";
?>
