<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminSystemApi.!notice.api_not_restrictive'] = "PERINGATAN! Perusahaan adalah perusahaan tempat pengguna mengautentikasi saat menghubungkan. Akses ke data perusahaan lain tidak dibatasi oleh permintaan API yang mendukung akses tersebut.";
$lang['AdminSystemApi.!success.key_added'] = "API Pengguna telah ditambahkan.";
$lang['AdminSystemApi.!success.key_deleted'] = "Pengguna API berhasil dihapus.";
$lang['AdminSystemApi.!success.key_updated'] = "API user berhasil diperbarui.";
$lang['AdminSystemApi.index.boxtitle_api'] = "API Access";
$lang['AdminSystemApi.index.categorylink_keyadd'] = "Tambahkan Pengguna API";
$lang['AdminSystemApi.index.heading_user'] = "Pengguna";
$lang['AdminSystemApi.index.heading_key'] = "Kunci";
$lang['AdminSystemApi.index.heading_company'] = "Perusahaan";
$lang['AdminSystemApi.index.heading_date'] = "Tanggal Diciptakan";
$lang['AdminSystemApi.index.heading_options'] = "Pilihan";
$lang['AdminSystemApi.index.option_edit'] = "Edit";
$lang['AdminSystemApi.index.option_delete'] = "Hapus";
$lang['AdminSystemApi.index.no_results'] = "Tidak ada API pengguna";
$lang['AdminSystemApi.index.confirm_delete'] = "Benar-benar menghapus pengguna API ini?";
$lang['AdminSystemApi.add.boxtitle_add'] = "Tambah Pengguna API";
$lang['AdminSystemApi.add.field_company'] = "Perusahaan";
$lang['AdminSystemApi.add.field_user'] = "Pengguna";
$lang['AdminSystemApi.add.field_notes'] = "Catatan";
$lang['AdminSystemApi.add.field_apisubmit'] = "Tambahkan Pengguna";
$lang['AdminSystemApi.edit.boxtitle_edit'] = "Edit API User";
$lang['AdminSystemApi.edit.field_company'] = "Perusahaan";
$lang['AdminSystemApi.edit.field_user'] = "User";
$lang['AdminSystemApi.edit.field_notes'] = "Catatan";
$lang['AdminSystemApi.edit.field_apisubmit'] = "Perbarui Pengguna";
$lang['AdminSystemApi.index.page_title'] = "Pengaturan > Sistem > Akses API";
?>
