<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminSystemUpgrade.index.boxtitle_upgrade'] = "Opsi Peningkatan";
$lang['AdminSystemUpgrade.index.field_upgradesubmit'] = "Perbarui Pengaturan";
$lang['AdminSystemUpgrade.index.page_title'] = "Pengaturan > Sistem > Opsi Peningkatan";
$lang['AdminSystemUpgrade.index.no_results'] = "Pilihan upgrade tidak tersedia saat ini.";
?>
