<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminMain.index.heading_quicklinks'] = "tautan langsung";
$lang['AdminMain.index.no_quicklinks'] = "Tidak ada Tautan Cepat yang disetel.";
$lang['AdminMain.index.manage_widgets'] = "Kelola Widget";
$lang['AdminMain.index.customize_dashboard'] = "Sesuaikan Dashboard";
$lang['AdminMain.managewidgets.text_version'] = "ver %1\$s"; // %1$s is the version number of the plugin
$lang['AdminMain.managewidgets.text_author'] = "Penulis:";
$lang['AdminMain.updatedashboard.text_layout'] = "Pilih tata letak di bawah ini untuk menyesuaikan dasbor Anda.";
$lang['AdminMain.!error.delete_event.staff_id'] = "Hanya pembuat acara yang dapat menghapus acara ini.";
$lang['AdminMain.!error.event_editable'] = "Hanya pembuat acara memungkinlan menghapus acara itu.";
$lang['AdminMain.!success.event_added'] = "Acara ini telah berhasil ditambahkan!";
$lang['AdminMain.!success.event_edited'] = "Acara telah berhasil diperbarui!";
$lang['AdminMain.!success.event_deleted'] = "Acara telah berhasil dihapus!";
$lang['AdminMain.index.page_title'] = "Dasbor";
$lang['AdminMain.managewidgets.text_widgets'] = "Seret widget dari kanan ke kiri untuk menambahkannya ke dasbor Anda, atau dari kiri ke kanan untuk menghapusnya.";
$lang['AdminMain.calendar.page_title'] = "Kalender";
$lang['AdminMain.calendar.boxtitle_calendar'] = "Kalender";
$lang['AdminMain.calendar.categorylink_addevent'] = "Membuat acara";
$lang['AdminMain.calendar.category_month'] = "Bulan";
$lang['AdminMain.calendar.category_week'] = "Minggu";
$lang['AdminMain.calendar.category_day'] = "Hari";
$lang['AdminMain.getEvents.shared_event_title'] = "%2\$s %3\$s: %1\$s"; // %1$s is the event title, %2$s is the staff's first name, %3$s is the staff's last name
$lang['AdminMain.addevent.boxtitle_addevent'] = "Buat Acara";
$lang['AdminMain.addevent.field_title'] = "Judul";
$lang['AdminMain.addevent.field_start_date'] = "Mulai tanggal";
$lang['AdminMain.addevent.field_end_date'] = "Tanggal Akhir";
$lang['AdminMain.addevent.field_shared'] = "Buat acara ini bisa dilihat oleh staf lain";
$lang['AdminMain.addevent.field_all_day'] = "Sepanjang hari";
$lang['AdminMain.addevent.field_addeventsubmit'] = "Buat Acara";
$lang['AdminMain.editevent.boxtitle_editevent'] = "edit Acara";
$lang['AdminMain.editevent.field_title'] = "Judul";
$lang['AdminMain.editevent.field_start_date'] = "tanggal Mulai ";
$lang['AdminMain.editevent.field_end_date'] = "Tanggal akhir";
$lang['AdminMain.editevent.field_shared'] = "Buat acara ini supaya dapat dilihat oleh staf lainnya";
$lang['AdminMain.editevent.field_all_day'] = "Sepanjang hari";
$lang['AdminMain.editevent.field_editeventsubmit'] = "Perbarui Acara";
$lang['AdminMain.editevent.field_deleteeventsubmit'] = "Hapus Acara";
$lang['AdminMain.editevent.confirm_delete'] = "Benar-benar menghapus acara ini?";
?>
