<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AdminSystemMarketplace.index.boxtitle_marketplace'] = "pasar";
$lang['AdminSystemMarketplace.index.text_unavailable'] = "Marketplace saat ini tidak tersedia.";
$lang['AdminSystemMarketplace.index.page_title'] = "Pengaturan > Sistem > Pasar";
$lang['AdminSystem.marketplace.category_all'] = "Semua";
$lang['AdminSystemMarketplace.listing.boxtitle_listing'] = "Ekstensi %1\$s"; // %1$s is the name of the extension
?>
