<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['ApiKeys.!error.key.generate'] = "Kuncinya gagal dihasilkan.";
$lang['ApiKeys.!error.company_id.exists'] = "Perusahaan yang diberikan tidak ada.";
$lang['ApiKeys.!error.user.valid'] = "Pengguna API atau kunci tampaknya tidak valid.";
$lang['ApiKeys.!error.user.unique'] = "Pengguna API sudah ada untuk perusahaan tertentu.";
$lang['ApiKeys.!error.user.format'] = "Masukkan API pengguna dengan panjang antara 3 dan 64 karakter.";
?>
