<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['AppController.lang.dir'] = "ltr";
$lang['AppController.!error.unauthorized_access'] = "Anda tidak diizinkan untuk mengakses sumber daya itu";
$lang['AppController.modal.text_close'] = "Tutup";
$lang['AppController.tooltip.text'] = "?";
$lang['AppController.structure.text_myinfo'] = "Info saya";
$lang['AppController.structure.text_settings'] = "Pengaturan";
$lang['AppController.structure.text_logout'] = "Keluar";
$lang['AppController.!error.invalid_csrf'] = "Bentuk token tidak valid.";
$lang['AppController.message.close'] = "×";
$lang['AppController.structure.text_maintenance'] = "Maintenance Mode saat diaktifkan dan klien mungkin tidak bisa masuk. Klik di sini untuk merubah.";
$lang['AppController.structure.text_search_placeholder'] = "%1\$s..."; // %1$s is the search type
$lang['AppController.client_structure.default_title'] = "Akun saya";
$lang['AppController.client_structure.text_return_to_portal'] = "Kembali ke Portal";
$lang['AppController.client_structure.text_logout'] = "Keluar";
$lang['AppController.dates.day_sun'] = "Minggu";
$lang['AppController.dates.day_mon'] = "Senin";
$lang['AppController.dates.day_tue'] = "Selasa";
$lang['AppController.dates.day_wed'] = "Rabu";
$lang['AppController.dates.day_thu'] = "Kamis";
$lang['AppController.dates.day_fri'] = "Jumat";
$lang['AppController.dates.day_sat'] = "Sabtu";
$lang['AppController.dates.dayabbr_sun'] = "Ming";
$lang['AppController.dates.dayabbr_mon'] = "Senin";
$lang['AppController.dates.dayabbr_tue'] = "Selasa";
$lang['AppController.dates.dayabbr_wed'] = "Rabu";
$lang['AppController.dates.dayabbr_thur'] = "Kamis";
$lang['AppController.dates.dayabbr_fri'] = "Jum";
$lang['AppController.dates.dayabbr_sat'] = "Sab";
$lang['AppController.dates.month_jan'] = "Januari";
$lang['AppController.dates.month_feb'] = "Februari";
$lang['AppController.dates.month_mar'] = "Maret";
$lang['AppController.dates.month_apr'] = "April";
$lang['AppController.dates.month_may'] = "Mei";
$lang['AppController.dates.month_jun'] = "Juni";
$lang['AppController.dates.month_jul'] = "Juli";
$lang['AppController.dates.month_aug'] = "Agustus";
$lang['AppController.dates.month_sep'] = "Bulan September";
$lang['AppController.dates.month_oct'] = "Bulan Oktober";
$lang['AppController.dates.month_nov'] = "November";
$lang['AppController.dates.month_dec'] = "Desember";
$lang['AppController.dates.monthabbr_jan'] = "Januari";
$lang['AppController.dates.monthabbr_feb'] = "Feb";
$lang['AppController.dates.monthabbr_mar'] = "Mar";
$lang['AppController.dates.monthabbr_apr'] = "April";
$lang['AppController.dates.monthabbr_may'] = "Mei";
$lang['AppController.dates.monthabbr_jun'] = "Juni";
$lang['AppController.dates.monthabbr_jul'] = "Jul";
$lang['AppController.dates.monthabbr_aug'] = "Agt";
$lang['AppController.dates.monthabbr_sep'] = "Sep";
$lang['AppController.dates.monthabbr_oct'] = "Okt";
$lang['AppController.dates.monthabbr_nov'] = "Nop";
$lang['AppController.dates.monthabbr_dec'] = "Desember";
$lang['AppController.!success.license_updated'] = "Lisensi Anda berhasil divalidasi ulang. Silakan login.";
$lang['AppController.!success.license_key_updated'] = "Kunci lisensi Anda telah berhasil diperbarui. Silakan login.";
$lang['AppController.select.please'] = "-- Mohon pilih --";
$lang['AppController.modal.text_confirm'] = "Mohon Konfirmasi";
$lang['AppController.client_structure.text_update_account'] = "Kelola Akun";
$lang['AppController.sreader.dropdown'] = "Toggle Dropdown";
$lang['AppController.sreader.navigation'] = "PIndah Navigasi";
$lang['AppController.client_structure.staff_as_client_note'] = "Kembali ke Portal Staf";
$lang['AppController.client_structure.text_login'] = "Gabung";
$lang['AppController.graphs.control_label.stacked'] = "Ditumpuk";
$lang['AppController.graphs.control_label.stream'] = "Aliran";
$lang['AppController.graphs.control_label.expanded'] = "Diperluas";
$lang['AppController.graphs.control_label.grouped'] = "Dikelompokkan";
$lang['AppController.graphs.label.total'] = "Total";
$lang['AppController.client_structure.text_emails'] = "Riwayat Email";
$lang['AppController.client_structure.text_accounts'] = "Akun Pembayaran";
$lang['AppController.client_structure.text_contacts'] = "Kontak";
?>
