<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['CalendarEvents.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['CalendarEvents.!error.staff_id.exists'] = "Staf ID tidak cocok";
$lang['CalendarEvents.!error.staff_id.valid'] = "Hanya pembuat acara yang dapat memperbarui acara ini.";
$lang['CalendarEvents.!error.shared.format'] = "Apakah acara dibagikan atau tidak harus berupa angka.";
$lang['CalendarEvents.!error.shared.length'] = "Panjang bersama tidak boleh melebihi 1 digit.";
$lang['CalendarEvents.!error.title.empty'] = "Silahkan masukkan judul.";
$lang['CalendarEvents.!error.start_date.format'] = "Format tanggal mulai tidak valid";
$lang['CalendarEvents.!error.start_date.order'] = "Tanggal mulai harus sebelum tanggal akhir.";
$lang['CalendarEvents.!error.end_date.format'] = "Tanggal akhir dalam format tanggal yang tidak valid.";
$lang['CalendarEvents.!error.all_day.format'] = "Apakah acara berlangsung sepanjang hari atau tidak harus berupa angka.";
$lang['CalendarEvents.!error.all_day.length'] = "Panjang all_day tidak boleh melebihi 1 digit.";
?>
