<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['ClientVerify.!success.email_verified'] = "Alamat email Anda telah berhasil diverifikasi.";
$lang['ClientVerify.!success.email_sent'] = "Email verifikasi telah dikirim ke %1\$s."; // %1$s is the email address to be verified
$lang['ClientVerify.!error.invalid_token'] = "Token yang diberikan tidak valid atau telah kedaluwarsa.";
?>
