<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['ClientEmails.index.page_title'] = "Klien #%1\$s Riwayat Email"; // %1$s is the client ID number
$lang['ClientEmails.index.boxtitle_emails'] = "Riwayat Email";
$lang['ClientEmails.index.heading_date'] = "Tanggal";
$lang['ClientEmails.index.heading_subject'] = "Subyek";
$lang['ClientEmails.index.heading_summary'] = "Ringkasan";
$lang['ClientEmails.index.text_to'] = "Kepada";
$lang['ClientEmails.index.text_cc'] = "CC";
$lang['ClientEmails.index.text_from'] = "Dari";
$lang['ClientEmails.index.no_results'] = "Anda tidak memiliki riwayat email.";
?>
