<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Clients.!error.client_group_id.exists'] = "ID kelompok klien yang tidak valid.";
$lang['Clients.!error.client_id.exists'] = "ID pelanggan tidak valid";
$lang['Clients.!error.account_id.exists'] = "ID akun tidak valid.";
$lang['Clients.!error.type.exists'] = "Jenis tidak valid.";
$lang['Clients.!error.id_format.empty'] = "Tidak ada format ID yang ditetapkan untuk klien.";
$lang['Clients.!error.id_format.length'] = "Format ID untuk klien tidak boleh melebihi 64 karakter.";
$lang['Clients.!error.id_value.valid'] = "Tidak dapat menentukan nilai ID klien.";
$lang['Clients.!error.user_id.exists'] = "ID pengguna tidak valid.";
$lang['Clients.!error.user_id.unique'] = "ID pengguna klien %1\$s telah terdaftar"; // %1$s is the client user ID number
$lang['Clients.!error.status.format'] = "Status tidak valid.";
$lang['Clients.!error.name.empty'] = "Masukkan nama.";
$lang['Clients.!error.is_lang.format'] = "is_lang harus berupa angka.";
$lang['Clients.!error.type.format'] = "Jenis tidak valid.";
$lang['Clients.!error.show_client.format'] = "Tampilkan client harus berupa angka.";
$lang['Clients.!error.encrypted.format'] = "Enskripsi harus berupa angka.";
$lang['Clients.!error.staff_id.exists'] = "ID staf tidak valid.";
$lang['Clients.!error.title.empty'] = "Harap masukkan judul.";
$lang['Clients.!error.note_id.exists'] = "Catatan ID salah";
$lang['Clients.!error.stickied.format'] = "Sticky harus berupa angka";
$lang['Clients.!error.stickied.length'] = "Panjang tempel tidak boleh lebih dari 1 karakter.";
$lang['Clients.getCustomFieldTypes.textbox'] = "Kolom tulisan";
$lang['Clients.getCustomFieldTypes.checkbox'] = "Kotak Centang";
$lang['Clients.getCustomFieldTypes.dropdown'] = "Drop Down";
$lang['Clients.getCustomFieldTypes.textarea'] = "Area teks";
$lang['Clients.getStatusTypes.active'] = "Aktif";
$lang['Clients.getStatusTypes.inactive'] = "Tidak aktif";
$lang['Clients.getStatusTypes.fraud'] = "Penipuan";
$lang['Clients.customfield.cf2'] = "Custom Field";
$lang['Clients.!error.autodebit.format'] = "Nilai autodebet keliru";
$lang['Clients.!error.inv_address_to.exists'] = "Harap tentukan kontak yang valid untuk menangani faktur.";
$lang['Clients.!error.default_currency.valid'] = "Mata uang yang tidak valid.";
$lang['Clients.!error.default_currency.editable'] = "Mata uang mungkin tidak diperbarui.";
$lang['Clients.!error.inv_method.valid'] = "Metode pengiriman tagihan tidak valid.";
$lang['Clients.!error.inv_method.editable'] = "Metode pengiriman faktur tidak dapat diperbarui.";
$lang['Clients.!error.language.valid'] = "Bahasa tidak valid.";
$lang['Clients.!error.language.editable'] = "Bahasa mungkin tidak diperbarui.";
$lang['Clients.!error.values.format'] = "Nilai dalam format yang tidak valid.";
$lang['Clients.!error.client_field_id.exists'] = "ID bidang khusus tidak valid.";
$lang['Clients.!error.client_field_id.matches'] = "Bidang khusus tidak valid";
$lang['Clients.!error.package_ids.exists'] = "Setidaknya salah satu paket yang disediakan tidak ada.";
$lang['Clients.!error.client_id.deleteable'] = "Klien tidak boleh dihapus saat ada faktur terbuka, ada faktur berulang, atau ada layanan aktif/ditangguhkan. Harap batalkan semua faktur terbuka, hapus semua faktur berulang, dan batalkan semua layanan yang aktif/ditangguhkan sebelum melanjutkan.";
$lang['Clients.!error.regex.valid'] = "Ekspresi reguler tidak valid.";
$lang['Clients.!error.read_only.format'] = "Hanya baca, harus berupa angka.";
$lang['Clients.!error.read_only.length'] = "Read only panjangnya tidak boleh melebihi 1 karakter.";
$lang['Clients.!error.value.required'] = "%1\$s dalam format yang tidak valid."; // %1$s is the name of the custom field
$lang['Clients.!error.value.valid'] = "%1\$s diatur ke nilai yang tidak valid."; // %1$s is the name of the custom field
$lang['Clients.!error.is_lang.length'] = "is_lang Tidak boleh memiliki karakter yang panjang";
$lang['Clients.!error.show_client.length'] = "Tampilkan klien tidak boleh melebihi 1 karakter.";
$lang['Clients.!error.encrypted.length'] = "Dienkripsi tidak boleh melebihi 1 karakter.";
$lang['Clients.setDebitAccountFailure.note_title'] = "Debit otomatis dinonaktifkan untuk rekening pembayaran.";
$lang['Clients.setDebitAccountFailure.note_body'] = "Akun pembayaran %1\$s yang diakhiri dengan x%2\$s dinonaktifkan karena melebihi jumlah maksimum upaya penolakan."; // %1$s is the payment account type, %2$s is the last four of the payment account
$lang['Clients.!error.receive_email_marketing.valid'] = "Nilai pemasaran email tidak valid.";
$lang['Clients.!error.default.valid'] = "Nilai default tidak valid.";
$lang['Clients.!error.title.length'] = "Panjang judul tidak boleh melebihi 255 karakter.";
$lang['Clients.!error.settings[tax_id].valid'] = "Harap tentukan ID Pajak/PPN yang valid.";
?>
