<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Coupons.getAmountTypes.amount'] = "Jumlah";
$lang['Coupons.getAmountTypes.percent'] = "Persen";
$lang['Coupons.!error.code.empty'] = "Harap masukkan kode kupon.";
$lang['Coupons.!error.code.length'] = "Panjang kode kupon tidak boleh melebihi 64 karakter.";
$lang['Coupons.!error.package_group_id.length'] = "ID grup paket tidak boleh lebih dari 10 karakter.";
$lang['Coupons.!error.used_qty.format'] = "Kuantitas yang digunakan harus berupa angka.";
$lang['Coupons.!error.used_qty.length'] = "Panjang kuantitas tidak boleh melebihi 10 karakter.";
$lang['Coupons.!error.max_qty.format'] = "Kuantitas Max. harus berupa angka.";
$lang['Coupons.!error.max_qty.length'] = "Panjang kuantitas maksimal tidak boleh melebihi 10 karakter.";
$lang['Coupons.!error.start_date.format'] = "Format tanggal mulai tidak valid.";
$lang['Coupons.!error.end_date.format'] = "Format tanggal akhir tidak valid.";
$lang['Coupons.!error.status.format'] = "Status tidak valid.";
$lang['Coupons.!error.recurring.format'] = "Berulang harus berupa angka.";
$lang['Coupons.!error.recurring.length'] = "Panjang (berulang) tidak boleh melebihi 1 karakter.";
$lang['Coupons.!error.coupon_id.exists'] = "ID kupon tidak valid.";
$lang['Coupons.!error.packages[].exists'] = "Setidaknya salah satu paket yang Anda berikan kupon ini tidak valid.";
$lang['Coupons.!error.amounts.exists'] = "Hanya satu mata uang yang berlaku sebagai diskon untuk kupon ini.";
$lang['Coupons.!error.amounts[][currency].length'] = "Kode mata uang harus 3 karakter.";
$lang['Coupons.!error.amounts[][amount].format'] = "Setiap nilai diskon harus berupa angka.";
$lang['Coupons.!error.amounts[][type].format'] = "Jenis jumlah yang tidak valid.";
$lang['Coupons.!error.company_id.exists'] = "ID perusahaan yang diberikan tidak valid.";
$lang['Coupons.!error.max_qty.exceeded'] = "Jumlah yang digunakan tidak boleh melebihi jumlah maksimal.";
$lang['Coupons.!error.limit_recurring.format'] = "Batas Berulang harus berupa angka.";
$lang['Coupons.!error.limit_recurring.length'] = "Batas Panjang berulang tidak boleh melebihi 1 karakter.";
$lang['Coupons.!error.apply_package_options.format'] = "Apakah kupon berlaku untuk opsi yang dapat dikonfigurasi harus disetel ke 1 atau 0.";
$lang['Coupons.!error.code.unique'] = "Kode kupon saat ini ditetapkan pada kupon yang berbeda dan tidak dapat digunakan kembali.";
$lang['Coupons.!error.internal_use_only.format'] = "Apakah kupon hanya untuk penggunaan internal harus disetel ke 1 atau 0.";
$lang['Coupons.!error.amounts[][amount].positive'] = "Setiap nilai diskon harus positif.";
?>
