<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['CronTasks.!error.key.unique'] = "Kunci tugas cron yang disediakan sudah diambil.";
$lang['CronTasks.!error.key.length'] = "Panjang kunci tugas cron tidak boleh melebihi 64 karakter.";
$lang['CronTasks.!error.run_id.exists'] = "ID menjalankan tugas cron tidak valid.";
$lang['CronTasks.!error.id.exists'] = "ID tugas cron tidak valid.";
$lang['CronTasks.!error.name.empty'] = "Harap masukkan nama.";
$lang['CronTasks.!error.is_lang.format'] = "is_lang harus berupa angka.";
$lang['CronTasks.!error.is_lang.length'] = "panjang is_lang tidak boleh melebihi 1 karakter.";
$lang['CronTasks.!error.enabled.format'] = "diaktifkan harus berupa angka.";
$lang['CronTasks.!error.enabled.length'] = "Panjang diaktifkan tidak boleh melebihi 1 karakter.";
$lang['CronTasks.!error.interval.format'] = "Interval harus angka, yang mewakili menit.";
$lang['CronTasks.!error.time.format'] = "Format penulisan waktu salah.";
$lang['CronTasks.!error.type.format'] = "Jenis tugas cron tidak valid. Harus berupa waktu atau interval.
";
$lang['CronTasks.crontask.name.create_invoice'] = "Buat Faktur";
$lang['CronTasks.crontask.name.autodebit'] = "Auto Debit";
$lang['CronTasks.crontask.description.autodebit'] = "Rekening pembayaran karena adanya auto debet akan dijalankan untuk melunasi faktur yang terbuka setiap hari pada waktu yang ditentukan.";
$lang['CronTasks.crontask.name.payment_reminders'] = "Peringatan Pembayaran";
$lang['CronTasks.crontask.description.payment_reminders'] = "Pengingat pembayaran dan pemberitahuan terlambat dikirim setiap hari pada waktu yang ditentukan.";
$lang['CronTasks.crontask.name.apply_payments'] = "Terapkan Pembayaran untuk Membuka Faktur";
$lang['CronTasks.crontask.description.apply_payments'] = "Kredit longgar yang diterapkan untuk membuka faktur secara otomatis pada interval yang dipilih.";
$lang['CronTasks.crontask.name.provision_pending_services'] = "Penyediaan Layanan Tertunda Berbayar";
$lang['CronTasks.crontask.description.provision_pending_services'] = "Layanan tertunda berbayar diaktifkan pada interval yang dipilih.";
$lang['CronTasks.crontask.name.cancel_scheduled_services'] = "Batalkan Layanan Terjadwal";
$lang['CronTasks.crontask.description.cancel_scheduled_services'] = "Layanan dengan tanggal pembatalan terjadwal pada interval yang dipilih.";
$lang['CronTasks.crontask.name.card_expiration_reminders'] = "Pengingat Kartu Kedaluwarsa Tanggal 15 tiap Bulan";
$lang['CronTasks.crontask.description.card_expiration_reminders'] = "Sebuah pengingat akan dikirim pada tanggal 1a5 tiap bulan untuk kartu kredit yang berakhir pada bulan itu, pada waktu yang ditentukan.";
$lang['CronTasks.crontask.name.deliver_invoices'] = "Kirim Faktur";
$lang['CronTasks.crontask.description.deliver_invoices'] = "Faktur yang dijadwalkan untuk pengiriman akan dikirim pada interval yang dipilih.";
$lang['CronTasks.crontask.name.suspend_services'] = "Menangguhkan Layanan";
$lang['CronTasks.crontask.description.suspend_services'] = "Layanan jatuh tempo akan ditangguhkan setiap hari pada waktu yang ditentukan.";
$lang['CronTasks.crontask.name.exchange_rates'] = "Pembaruan Nilai Tukar";
$lang['CronTasks.crontask.description.exchange_rates'] = "Nilai tukar akan diperbarui pada interval tertentu. Hal ini tidak dianjurkan untuk menjalankan ini lebih dari dua kali sehari karena risiko diblokir.";
$lang['CronTasks.crontask.name.deliver_reports'] = "Memberi Laporan";
$lang['CronTasks.crontask.description.deliver_reports'] = "A / R, Faktur Generation, Kewajiban Pajak, dan laporan lainnya akan dikirimkan setiap hari pada waktu yang ditentukan.";
$lang['CronTasks.crontask.name.cleanup_logs'] = "Bersihkan Log";
$lang['CronTasks.crontask.name.process_renewing_services'] = "Proses Perpanjangan Layanan";
$lang['CronTasks.crontask.description.process_renewing_services'] = "memperbaharui Layanan yang melekat pada modul, dan diperbarui pada interval yang dipilih.";
$lang['CronTasks.crontask.name.backups_amazons3'] = "Cadangan Amazon S33";
$lang['CronTasks.crontask.description.backups_amazons3'] = "Amazon S3 Backup dijadwalkan di bawah Pengaaturan Sistem> Backup> Amazon S3.";
$lang['CronTasks.crontask.name.unsuspend_services'] = "Batalkan Penangguhan Layanan";
$lang['CronTasks.crontask.description.unsuspend_services'] = "Layanan yang ditangguhkan yang telah dibayar akan dibatalkan penangguhannya pada interval yang dipilih.";
$lang['CronTasks.crontask.name.license_validation'] = "Validasi Lisensi";
$lang['CronTasks.crontask.description.create_invoice'] = "Faktur berulang dan memperbaharui jasa dijadwalkan melalui tugas ini, yang berjalan sekali sehari pada waktu yang ditentukan.";
$lang['CronTasks.crontask.description.cleanup_logs'] = "gateway lama, modul, dan log lain akan dirotasi setiap hari tergantung pada pengaturan retensinya pada waktu yang ditentukan.";
$lang['CronTasks.crontask.name.backups_sftp'] = "SFTP Backup";
$lang['CronTasks.crontask.description.backups_sftp'] = "Pencadangan SFTP dijadwalkan di bawah Pengaturan Sistem > Cadangan > FTP Aman.";
$lang['CronTasks.crontask.name.process_service_changes'] = "Proses Perubahan Layanan";
$lang['CronTasks.crontask.description.process_service_changes'] = "Antrian perubahan layanan berbayar (mis upgrade) akan diproses pada interval yang dipilih.";
$lang['CronTasks.!error.task_type.format'] = "Jenis tugas tidak valid. Harus modul, plugin, atau sistem.";
$lang['CronTasks.!error.dir.length'] = "Panjang direktori tidak boleh melebihi 64 karakter.";
$lang['CronTasks.task_type.system'] = "Sistim";
$lang['CronTasks.task_type.plugin'] = "Plugin";
$lang['CronTasks.task_type.module'] = "Modul";
$lang['CronTasks.crontask.name.apply_invoice_late_fees'] = "Terapkan Biaya Keterlambatan Faktur";
$lang['CronTasks.crontask.description.apply_invoice_late_fees'] = "Berlaku biaya keterlambatan untuk membuka faktur jumlah hari yang dikonfigurasi setelah jatuh tempo.";
?>
