<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Cron.index.attempt_all'] = "Mencoba menjalankan semua tugas untuk %1\$s."; // %1$s is the company name
$lang['Cron.index.completed_all'] = "Semua tugas telah selesai.";
$lang['Cron.index.attempt_all_system'] = "Mencoba untuk menjalankan semua tugas sistem.";
$lang['Cron.index.completed_all_system'] = "Semua tugas sistem telah selesai.";
$lang['Cron.applycredits.attempt'] = "Mencoba menerapkan kredit untuk membuka faktur.";
$lang['Cron.applycredits.completed'] = "Tugas menerapkan kredit telah selesai.";
$lang['Cron.applycredits.apply_none'] = "Tidak ada faktur yang kreditnya dapat diterapkan.";
$lang['Cron.autodebitinvoices.attempt'] = "Mencoba mendebit faktur terbuka secara otomatis.";
$lang['Cron.autodebitinvoices.completed'] = "Tugas faktur debit otomatis telah selesai.";
$lang['Cron.autodebitinvoices.charge_attempt'] = "Mencoba mendebit otomatis klien #%1\$s untuk semua faktur terbuka dalam jumlah %2\$s."; // %1$s is the client ID, %2$s is the amount due
$lang['Cron.autodebitinvoices.charge_failed'] = "Tidak dapat memproses pembayaran.";
$lang['Cron.autodebitinvoices.charge_success'] = "Berhasil memproses pembayaran.";
$lang['Cron.cardexpirationreminders.attempt'] = "Mencoba untuk mengirim pengingat tentang masa kedaluwarsa kartu";
$lang['Cron.cardexpirationreminders.completed'] = "Tugas pengingat kedaluwarsa kartu telah selesai.";
$lang['Cron.cardexpirationreminders.failed'] = "Berakhirnya pengingat untuk kontak %1\$s %2\$s  dari klien #%3\$s tidak dapat dikirim.
"; // %1$s is the contact's first name, %2$s is the contact's last name, %3$s is the client ID
$lang['Cron.cardexpirationreminders.success'] = "Berhasil mengirimkan pengingat kedaluwarsa untuk kontak %1\$s %2\$s dari klien # %3\$s."; // %1$s is the contact's first name, %2$s is the contact's last name, %3$s is the client ID
$lang['Cron.suspendservices.attempt'] = "Mencoba untuk menangguhkan layanan karena jatuh tempo";
$lang['Cron.suspendservices.completed'] = "Tugas layanan penangguhan telah selesai.";
$lang['Cron.suspendservices.suspend_error'] = "Layanan #%1\$s dari klien %2\$s tidak dapat ditangguhkan."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.suspendservices.suspend_success'] = "Layanan #%1\$s dari klien  %2\$s  telah ditangguhkan."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.unsuspendservices.attempt'] = "Mencoba untuk unsuspend layanan ditangguhkan yang sudah dibayar.";
$lang['Cron.unsuspendservices.completed'] = "Tugas membatalkan penangguhan layanan telah selesai.";
$lang['Cron.unsuspendservices.unsuspend_error'] = "Layanan  #%1\$s dari klien %2\$s tidak bisa tidak ditangguhkan."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.unsuspendservices.unsuspend_success'] = "Layanan #%1\$s dari klien %2\$s telah diunsuspend"; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.cancelscheduledservices.attempt'] = "Mencoba membatalkan layanan terjadwal.";
$lang['Cron.cancelscheduledservices.completed'] = "Pembatalan layanan selesai dijadwalkan.";
$lang['Cron.cancelscheduledservices.cancel_error'] = "Layanan #%1\$s dari klien #%2\$s tidak bisa dibatalkan."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.cancelscheduledservices.cancel_success'] = "Layanan #%1\$s dari klien #%2\$s telah dibatalkan."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.addpaidpendingservices.attempt'] = "Mencoba untuk penyediaan bayar layanan yang tertunda.";
$lang['Cron.addpaidpendingservices.completed'] = "Tugas layanan tertunda berbayar telah selesai.";
$lang['Cron.addpaidpendingservices.service_error'] = "Layanan  tertunda  #%1\$s dari klien #%2\$s  tidak bisa diaktifkan"; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.addpaidpendingservices.service_success'] = "Layanan tertunda #%1\$s dari klien #%2\$s sekarang aktif."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.!error.cron.failed'] = "Cron gagal masuk.";
$lang['Cron.!error.task_execution.failed'] = "Error: %1\$s %2\$s"; // %1$s is the error message that occurred, %2$s is the stack trace
$lang['Cron.applycredits.apply_failed'] = "Tidak dapat menerapkan kredit tertunda untuk klien #%1\$s."; // %1$s is the client ID
$lang['Cron.applycredits.apply_success'] = "Berhasil diterapkan kredit tertunda dari transaksi %1\$s untuk klien #%2\$s untuk faktur #%3\$s dalam jumlah %4\$s."; // %1$s is the transaction number, %2$s is the client ID, %3$s is the invoice ID, and %4$s is the amount applied
$lang['Cron.suspendservices.suspension_reason'] = "Non-Pembayaran";
?>
