<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['EmailVerifications.!error.contact_id.exists'] = "ID kontak tidak valid.";
$lang['EmailVerifications.!error.email.valid'] = "Silakan isi alamat email.";
$lang['EmailVerifications.!error.token.format'] = "Harap masukkan token yang valid.";
$lang['EmailVerifications.!error.verified.valid'] = "Bidang terverifikasi harus \"1\" atau \"0\".";
$lang['EmailVerifications.!error.redirect_url.valid'] = "Harap masukkan URL yang valid.";
?>
