<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Encryption.!error.current_passphrase.empty'] = "Harap masukkan frasa sandi kunci pribadi saat ini.";
$lang['Encryption.!error.current_passphrase.matches'] = "Frase sandi kunci pribadi saat ini tidak valid.";
$lang['Encryption.!error.private_key_passphrase.empty'] = "Masukkan private key passphrase baru";
$lang['Encryption.!error.confirm_new_passphrase.matches'] = "Passphrase baru tidak cocok.";
$lang['Encryption.!error.agree.empty'] = "Anda harus setuju bahwa Anda telah menyimpan frasa sandi ini ke lokasi yang aman.";
?>
