<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['MessageGroups.!error.action.empty'] = "Harap masukkan tindakan.";
$lang['MessageGroups.!error.type.valid'] = "Jenis grup pesan harus disetel ke \"klien\", \"staf\", atau \"bersama\".";
$lang['MessageGroups.!error.plugin_dir.empty'] = "Silakan masuk ke direktori plugin.";
$lang['MessageGroups.!error.tags.empty'] = "Silakan masukkan tag.";
?>
