<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Navigation.getprimary.nav_home'] = "Home";
$lang['Navigation.getprimary.nav_clients'] = "Klien";
$lang['Navigation.getprimary.nav_billing'] = "Penagihan";
$lang['Navigation.getprimary.nav_billing_overview'] = "Gambaran";
$lang['Navigation.getprimary.nav_billing_invoices'] = "Faktur";
$lang['Navigation.getprimary.nav_billing_transactions'] = "Transaksi";
$lang['Navigation.getprimary.nav_billing_services'] = "Jasa";
$lang['Navigation.getprimary.nav_billing_reports'] = "Laporan";
$lang['Navigation.getprimary.nav_packages'] = "Paket";
$lang['Navigation.getprimary.nav_tools'] = "Alat";
$lang['Navigation.getprimary.nav_tools_logs'] = "Log";
$lang['Navigation.getprimary.nav_tools_currency'] = "Konversi Mata Uang";
$lang['Navigation.getprimary.nav_settings_company'] = "Perusahaan";
$lang['Navigation.getprimary.nav_settings_system'] = "Sistem";
$lang['Navigation.getcompany.nav_general'] = "Umum";
$lang['Navigation.getcompany.nav_general_localization'] = "Lokalisasi";
$lang['Navigation.getcompany.nav_general_international'] = "Penginternasionalan";
$lang['Navigation.getcompany.nav_general_encryption'] = "Enkripsi";
$lang['Navigation.getcompany.nav_general_contacttypes'] = "Jenis kontak";
$lang['Navigation.getcompany.nav_automation'] = "Otomatisasi";
$lang['Navigation.getcompany.nav_billing'] = "Penagihan/Pembayaran";
$lang['Navigation.getcompany.nav_billing_invoices'] = "Pilihan Faktur dan Biaya ";
$lang['Navigation.getcompany.nav_billing_custominvoice'] = "Kustomisasi Faktur";
$lang['Navigation.getcompany.nav_billing_deliverymethods'] = "Pengiriman Tagihan";
$lang['Navigation.getcompany.nav_billing_coupons'] = "Kupon";
$lang['Navigation.getcompany.nav_billing_acceptedtypes'] = "Jenis Pembayaraan Yang Diterima";
$lang['Navigation.getcompany.nav_modules'] = "Modul";
$lang['Navigation.getcompany.nav_gateways'] = "Gerbang Pembayaran";
$lang['Navigation.getcompany.nav_taxes'] = "Pajak";
$lang['Navigation.getcompany.nav_taxes_basictax'] = "Pengaturan Pajak dasar";
$lang['Navigation.getcompany.nav_taxes_taxrules'] = "Peraturan Pajak";
$lang['Navigation.getcompany.nav_emails'] = "Email";
$lang['Navigation.getcompany.nav_emails_mail'] = "Pengaturan Mail";
$lang['Navigation.getcompany.nav_emails_templates'] = "Email Template";
$lang['Navigation.getcompany.nav_emails_signatures'] = "Signature";
$lang['Navigation.getcompany.nav_currencies'] = "mata uang";
$lang['Navigation.getcompany.nav_currency_currencysetup'] = "Pengaturan Mata Uang";
$lang['Navigation.getcompany.nav_currency_active'] = "Mata Uang Aktif";
$lang['Navigation.getcompany.nav_plugins'] = "Plugin";
$lang['Navigation.getcompany.nav_groups'] = "Grup Klien";
$lang['Navigation.getsystem.nav_general'] = "Umum";
$lang['Navigation.getsystem.nav_general_basic'] = "Setting Dasar";
$lang['Navigation.getsystem.nav_general_geoip'] = "Pengaturan GeoIP";
$lang['Navigation.getsystem.nav_general_maintenance'] = "Pemeliharaan";
$lang['Navigation.getsystem.nav_general_license'] = "lisensi Key";
$lang['Navigation.getsystem.nav_general_paymenttypes'] = "jenis pembayaran";
$lang['Navigation.getsystem.nav_automation'] = "Otomatisasi";
$lang['Navigation.getsystem.nav_companies'] = "Perusahaan";
$lang['Navigation.getsystem.nav_backup'] = "Salinan";
$lang['Navigation.getsystem.nav_backup_ftp'] = "FTP Mode Aman";
$lang['Navigation.getsystem.nav_backup_index'] = "On Demand";
$lang['Navigation.getsystem.nav_backup_amazon'] = "Amazon S3";
$lang['Navigation.getsystem.nav_staff'] = "Staf";
$lang['Navigation.getsystem.nav_staff_manage'] = "Mengelola Staf";
$lang['Navigation.getsystem.nav_staff_groups'] = "Staf Grup";
$lang['Navigation.getsystem.nav_api'] = "API Access";
$lang['Navigation.getsystem.nav_upgrade'] = "Pilihan Upgrade";
$lang['Navigation.getsystem.nav_help'] = "Tolong";
$lang['Navigation.getsystem.nav_help_notes'] = "Catatan Rilis";
$lang['Navigation.getsystem.nav_help_about'] = "Tentang Blesta";
$lang['Navigation.getsystem.nav_marketplace'] = "pasar";
$lang['Navigation.getprimary.nav_home_dashboard'] = "Dasbor";
$lang['Navigation.getprimary.nav_billing_printqueue'] = "Antrian Cetak";
$lang['Navigation.getprimary.nav_billing_batch'] = "Batch";
$lang['Navigation.getprimaryclient.nav_dashboard'] = "Dasbor";
$lang['Navigation.getprimaryclient.nav_paymentaccounts'] = "Account Pembayaran";
$lang['Navigation.getprimaryclient.nav_contacts'] = "Kontak";
$lang['Navigation.getsystem.nav_help_index'] = "Sumber daya";
$lang['Navigation.getsearchoptions.smart'] = "Smart Search";
$lang['Navigation.getsearchoptions.clients'] = "Cari Klien";
$lang['Navigation.getsearchoptions.invoices'] = "Pencarian Faktur";
$lang['Navigation.getsearchoptions.transactions'] = "Pencarian Transaksi";
$lang['Navigation.getsearchoptions.services'] = "Pencarian Layanan";
$lang['Navigation.getsearchoptions.packages'] = "Pencarian Paket";
$lang['Navigation.getprimaryclient.nav_paymentaccounts_add'] = "Masukkan Akun Pembayaran";
$lang['Navigation.getprimaryclient.nav_contacts_add'] = "Tambahkan kontak";
$lang['Navigation.getprimaryclient.nav_return'] = "Kembali ke Dasbor";
$lang['Navigation.getcompany.nav_lookandfeel'] = "Tampilan";
$lang['Navigation.getcompany.nav_lookandfeel_themes'] = "Tema";
$lang['Navigation.getcompany.nav_lookandfeel_template'] = "Templat";
$lang['Navigation.getcompany.nav_lookandfeel_customize'] = "Menyesuaikan";
$lang['Navigation.getprimarypublic.nav_dashboard'] = "Home";
$lang['Navigation.getprimary.nav_clients_browse'] = "Jelajahi Klien";
$lang['Navigation.getprimary.nav_packages_browse'] = "Jelajahi Paket";
$lang['Navigation.getprimary.nav_packages_groups'] = "Grup Paket";
$lang['Navigation.getprimary.nav_package_options'] = "Opsi yang Dapat Dikonfigurasi";
$lang['Navigation.getcompany.nav_clientoptions'] = "Opsi Klien";
$lang['Navigation.getcompany.nav_clientoptions_customfields'] = "Bidang Kustom Klien";
$lang['Navigation.getcompany.nav_clientoptions_requiredfields'] = "Bidang Klien yang Diperlukan";
$lang['Navigation.getcompany.nav_general_marketing'] = "Pemasaran";
$lang['Navigation.getcompany.nav_clientoptions_general'] = "Pengaturan Klien Umum";
$lang['Navigation.getcompany.nav_billing_notices'] = "Pemberitahuan";
$lang['Navigation.getcompany.nav_general_smart_search'] = "Pencarian cerdas";
$lang['Navigation.getcompany.nav_general_humanverification'] = "Verifikasi Manusia";
$lang['Navigation.getcompany.nav_billing_latefees'] = "Biaya Keterlambatan";
$lang['Navigation.getcompany.nav_lookandfeel_layout'] = "Tata Letak";
$lang['Navigation.getcompany.nav_messengers'] = "Messenger";
$lang['Navigation.getcompany.nav_messengers_messengers'] = "Messenger";
$lang['Navigation.getcompany.nav_messengers_configuration'] = "Konfigurasi Messenger";
$lang['Navigation.getcompany.nav_messengers_templates'] = "Template Pesan";
$lang['Navigation.!error.action_id.valid'] = "ID tindakan tidak valid";
$lang['Navigation.!error.order.valid'] = "Indeks pesanan harus berupa nilai numerik";
$lang['Navigation.!error.parent_id.valid'] = "ID item navigasi orang tua tidak valid";
$lang['Navigation.getprimary.nav_tools_utilities'] = "Keperluan";
$lang['Navigation.getcompany.nav_lookandfeel_navigation'] = "Navigasi";
$lang['Navigation.getcompany.nav_lookandfeel_actions'] = "tindakan";
$lang['Navigation.getprimaryclient.nav_services'] = "Jasa";
?>
