<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['PackageOptions.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['PackageOptions.!error.label.empty'] = "Masukkan label.";
$lang['PackageOptions.!error.label.length'] = "Label tidak boleh melebihi 128 karakter.";
$lang['PackageOptions.!error.name.empty'] = "Harap masukkan nama untuk opsi ini.";
$lang['PackageOptions.!error.name.length'] = "Nama tidak boleh melebihi 128 karakter.";
$lang['PackageOptions.!error.values.count'] = "Mungkin hanya ada satu entri nilai opsi untuk kotak centang, jumlah, teks, area teks, atau jenis kata sandi.";
$lang['PackageOptions.!error.values[][step].valid'] = "Nilai langkah hanya dapat ditetapkan untuk jenis kuantitas, dan harus bernilai 1 atau lebih besar.";
$lang['PackageOptions.!error.values[][min].valid'] = "Nilai batas minimum hanya dapat ditetapkan untuk jenis kuantitas, dan harus menjadi nilai 0 atau lebih besar.";
$lang['PackageOptions.!error.values[][max].valid'] = "Nilai batas maksimum hanya dapat ditetapkan untuk jenis kuantitas, dan harus bernilai 1 atau lebih besar.";
$lang['PackageOptions.!error.values[][name].empty'] = "Silakan masukkan nama untuk nilai pilihan.";
$lang['PackageOptions.!error.values[][name].length'] = "Nama nilai opsi tidak boleh melebihi 128 karakter.";
$lang['PackageOptions.!error.values[][value].length'] = "Nilai opsi tidak boleh melebihi 255 karakter.";
$lang['PackageOptions.!error.groups.exists'] = "Setidaknya satu dari ID grup opsi paket yang diberikan tidak ada atau bukan milik perusahaan yang sama.";
$lang['PackageOptions.!error.option_id.exists'] = "ID pilihan paket yang tidak valid.";
$lang['PackageOptions.!error.values[][pricing][][term].format'] = "Istilah harus berupa angka.";
$lang['PackageOptions.!error.values[][pricing][][term].length'] = "Panjang periode tidak boleh melebihi 5 karakter.";
$lang['PackageOptions.!error.values[][pricing][][term].valid'] = "Istilah harus lebih besar dari 0.";
$lang['PackageOptions.!error.values[][pricing][][period].format'] = "Jenis periode tidak valid.";
$lang['PackageOptions.!error.values[][pricing][][price].format'] = "Harga harus berupa angka.";
$lang['PackageOptions.!error.values[][pricing][][setup_fee].format'] = "Biaya pemasangan harus berupa angka.";
$lang['PackageOptions.!error.values[][pricing][][currency].format'] = "Kode mata uang harus 3 karakter.";
$lang['PackageOptions.gettypes.checkbox'] = "Checkbox";
$lang['PackageOptions.gettypes.select'] = "Drop-down";
$lang['PackageOptions.gettypes.quantity'] = "Jumlah";
$lang['PackageOptions.gettypes.radio'] = "Radio";
$lang['PackageOptions.getfields.label_quantity'] = "x %1\$s %2\$s"; // %1$s is the option value, %2$s is the option price
$lang['PackageOptions.getfields.label_quantity_setup'] = "x %1\$s %2\$s + %3\$s setup"; // %1$s is the option value, %2$s is the option price, %3$s is the setup fee
$lang['PackageOptions.getfields.label_radio'] = "%1\$s (%2\$s)"; // %1$s is the option value, %2$s is the option price
$lang['PackageOptions.getfields.label_radio_setup'] = "%1\$s (%2\$s + %3\$s setup)"; // %1$s is the option value, %2$s is the option price, %3$s is the setup fee
$lang['PackageOptions.getfields.label_select'] = "%1\$s (%2\$s)"; // %1$s is the option value, %2$s is the option price
$lang['PackageOptions.getfields.label_select_setup'] = "%1\$s (%2\$s + %3\$s setup)"; // %1$s is the option value, %2$s is the option price, %3$s is the setup fee
$lang['PackageOptions.getfields.label_checkbox'] = "%1\$s (%2\$s)"; // %1$s is the option value, %2$s is the option price
$lang['PackageOptions.getfields.label_checkbox_setup'] = "%1\$s (%2\$s + %3\$s setup)"; // %1$s is the option value, %2$s is the option price, %3$s is the setup fee
$lang['PackageOptions.!error.type.valid'] = "Silakan pilih jenis opsi.";
$lang['PackageOptions.!error.values[][id].exists'] = "ID nilai opsi paket tidak valid.";
$lang['PackageOptions.!error.values[][pricing][][id].exists'] = "ID harga opsi paket tidak valid.";
$lang['PackageOptions.!error.values.select_value'] = "Setidaknya satu nilai opsi berisi karakter khusus yang tidak valid.";
$lang['PackageOptions.gettypes.text'] = "Teks";
$lang['PackageOptions.gettypes.textarea'] = "Area teks";
$lang['PackageOptions.gettypes.password'] = "Kata sandi";
$lang['PackageOptions.getfields.label_text'] = "%1\$s"; // %1$s is the option price
$lang['PackageOptions.getfields.label_text_setup'] = "Penyiapan %1\$s + %2\$s"; // %1$s is the option price, %2$s is the setup fee
$lang['PackageOptions.getfields.label_password'] = "%1\$s"; // %1$s is the option price
$lang['PackageOptions.getfields.label_password_setup'] = "Penyiapan %1\$s + %2\$s"; // %1$s is the option price, %2$s is the setup fee
$lang['PackageOptions.getfields.label_textarea'] = "%1\$s"; // %1$s is the option price
$lang['PackageOptions.getfields.label_textarea_setup'] = "Penyiapan %1\$s + %2\$s"; // %1$s is the option price, %2$s is the setup fee
$lang['PackageOptions.!error.values.active_status'] = "Setidaknya satu nilai opsi harus aktif.";
$lang['PackageOptions.!error.values.single_default_value'] = "Hanya satu nilai yang dapat dipilih sebagai nilai default.
";
$lang['PackageOptions.!error.values[][value].edit_in_use'] = "Nilai opsi tidak dapat diubah karena sedang digunakan oleh layanan.";
$lang['PackageOptions.!error.values[][value].delete_in_use'] = "Nilai opsi tidak dapat dihapus karena sedang digunakan oleh layanan.";
$lang['PackageOptions.!error.values[][status].valid'] = "Harap pilih status nilai opsi yang valid.";
$lang['PackageOptions.!error.values[][default].inactive'] = "Nilai opsi yang tidak aktif mungkin tidak ditetapkan sebagai nilai default.";
$lang['PackageOptions.!error.values[][default].qty_valid'] = "Kuantitas nilai default yang dipilih tidak valid untuk min, maks, dan langkah yang dikonfigurasi.";
$lang['PackageOptions.!error.values[][pricing][][id].delete_in_use'] = "Penetapan harga nilai opsi tidak dapat dihapus karena sedang digunakan oleh suatu layanan.";
$lang['PackageOptions.!error.values[][pricing][][price_renews].format'] = "Harga perpanjangan harus berupa angka.";
$lang['PackageOptions.!error.values[][pricing][][price_renews].valid'] = "Harga perpanjangan tidak dapat ditetapkan untuk satu periode waktu.";
$lang['PackageOptions.getvaluestatuses.active'] = "Aktif";
$lang['PackageOptions.getvaluestatuses.inactive'] = "Tidak aktif";
$lang['PackageOptions.getfields.label_quantity_recurring'] = "x %1\$s %2\$s (memperbarui @ %3\$s)"; // %1$s is the option value, %2$s is the option initial price, %3$is is the option renewal price
$lang['PackageOptions.getfields.label_quantity_setup_recurring'] = "x penyiapan %1\$s %2\$s + %3\$s (perbarui @ %4\$s)"; // %1$s is the option value, %2$s is the option initial price, %3$s is the setup fee, %4$s is the option renewal price
$lang['PackageOptions.getfields.label_radio_recurring'] = "%1\$s (%2\$s, memperbarui @ %3\$s)"; // %1$s is the option value, %2$s is the option initial price, %3$s is the option renewal price
$lang['PackageOptions.getfields.label_radio_setup_recurring'] = "%1\$s (penyiapan %2\$s + %3\$s, memperbarui @ %4\$s)"; // %1$s is the option value, %2$s is the option initial price, %3$s is the setup fee, %$4s is the option renewal price
$lang['PackageOptions.getfields.label_select_recurring'] = "%1\$s (%2\$s, memperbarui @ %3\$s)"; // %1$s is the option value, %2$s is the option initial price, %3$s is the option renewal price
$lang['PackageOptions.getfields.label_select_setup_recurring'] = "%1\$s (penyiapan %2\$s + %3\$s, memperbarui @ %4\$s)"; // %1$s is the option value, %2$s is the option initial price, %3$s is the setup fee, %4$s is the option renewal price
$lang['PackageOptions.getfields.label_checkbox_recurring'] = "%1\$s (%2\$s, memperbarui @ %3\$s)"; // %1$s is the option value, %2$s is the option initial price, %3$s is the option renewal price
$lang['PackageOptions.getfields.label_checkbox_setup_recurring'] = "%1\$s (penyiapan %2\$s + %3\$s, perbarui @ %4\$s)"; // %1$s is the option value, %2$s is the option initial price, %3$s is the setup fee, %4$s is the option renewal price
$lang['PackageOptions.getfields.label_text_recurring'] = "%1\$s (memperbarui @ %2\$s)"; // %1$s is the option initial price, %2$s is the option renewal price
$lang['PackageOptions.getfields.label_text_setup_recurring'] = "Penyiapan %1\$s + %2\$s (perbarui @ %3\$s)"; // %1$s is the option initial price, %2$s is the setup fee, %3$s is the option renewal price
$lang['PackageOptions.getfields.label_password_recurring'] = "%1\$s (memperbarui @ %2\$s)"; // %1$s is the option initial price, %2$s is the option renewal price
$lang['PackageOptions.getfields.label_password_setup_recurring'] = "Penyiapan %1\$s + %2\$s (perbarui @ %3\$s)"; // %1$s is the option initial price, %2$s is the setup fee, %3$s is the option renewal price
$lang['PackageOptions.getfields.label_textarea_recurring'] = "%1\$s (memperbarui @ %2\$s)"; // %1$s is the option initial price, %2$s is the option renewal price
$lang['PackageOptions.getfields.label_textarea_setup_recurring'] = "Pengaturan %1\$s + %2\$s (renews @ %3\$s)"; // %1$s is the option initial price, %2$s is the setup fee, %3$s is the option renewal price
$lang['PackageOptions.!error.values.unique'] = "Nilai opsi harus unik.";
$lang['PackageOptions.!error.values[][default].format'] = "Standarnya harus berupa angka.";
?>
