<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Packages.!error.package_id.exists'] = "Paket tidak dapat dihapus karena layanan sedang menggunakannya.";
$lang['Packages.!error.qty.format'] = "Kuantitas harus berupa angka.";
$lang['Packages.!error.taxable.format'] = "Kena Pajak harus berupa angka.";
$lang['Packages.!error.taxable.length'] = "Panjang kena pajak tidak boleh melebihi 1 karakter.";
$lang['Packages.!error.status.format'] = "Status tidak valid.";
$lang['Packages.!error.email_content[][lang].empty'] = "Harap masukkan bahasa.";
$lang['Packages.!error.email_content[][lang].length'] = "Panjang bahasa tidak boleh lebih dari 5 karakter.";
$lang['Packages.!error.groups[].exists'] = "ID grup paket tidak valid.";
$lang['Packages.!error.groups[].valid'] = "Kelompok paket yang dipilih bukan milik perusahaan yang diberikan.";
$lang['Packages.getPricingPeriods.day'] = "Hari";
$lang['Packages.getPricingPeriods.week'] = "Minggu";
$lang['Packages.getPricingPeriods.month'] = "Bulan";
$lang['Packages.getPricingPeriods.year'] = "Tahun";
$lang['Packages.getPricingPeriods.onetime'] = "Satu kali";
$lang['Packages.getStatusTypes.active'] = "Aktif";
$lang['Packages.getStatusTypes.inactive'] = "Non-aktif";
$lang['Packages.getStatusTypes.restricted'] = "Terbatas";
$lang['Packages.!error.pricing[][term].format'] = "Term harus berupa angka.";
$lang['Packages.!error.pricing[][term].length'] = "Panjang periode tidak boleh melebihi 5 karakter.";
$lang['Packages.!error.pricing[][period].format'] = "Jenis periode tidak valid.";
$lang['Packages.!error.pricing[][price].format'] = "Harga harus berupa angka.";
$lang['Packages.!error.pricing[][setup_fee].format'] = "Biaya pemasangan harus berupa angka.";
$lang['Packages.!error.pricing[][cancel_fee].format'] = "Fee pembatalan harus berupa angka.";
$lang['Packages.!error.pricing[][currency].format'] = "Kode mata uang harus 3 karakter";
$lang['Packages.!error.pricing[][id].format'] = "ID harga paket tidak valid.";
$lang['Packages.getPricingPeriods.day_plural'] = "Hari";
$lang['Packages.getPricingPeriods.week_plural'] = "Minggu";
$lang['Packages.getPricingPeriods.month_plural'] = "Bulan";
$lang['Packages.getPricingPeriods.year_plural'] = "Tahun";
$lang['Packages.getPricingPeriods.onetime_plural'] = "Satu kali";
$lang['Packages.!error.company_id.exists'] = "Perusahaan yang diberikan tidak valid";
$lang['Packages.!error.module_id.exists'] = "Modul tidak valid";
$lang['Packages.!error.module_row.format'] = "Baris modul yang diberikan tidak valid.";
$lang['Packages.!error.pricing[][term].valid'] = "Istilah harus lebih besar dari 0.";
$lang['Packages.!error.module_group.format'] = "Grup modul yang diberikan tidak valid.";
$lang['Packages.!error.option_groups[].valid'] = "Kelompok pilihan paket yang dikonfigurasi tidak valid";
$lang['Packages.!error.single_term.valid'] = "Istilah tunggal harus 1 atau 0.";
$lang['Packages.!error.prorata_day.format'] = "Hari pro rata harus antara 1 dan 28.";
$lang['Packages.!error.prorata_cutoff.format'] = " pro rata cutoff day harus antara 1 dan 28";
$lang['Packages.!error.email_content.parse'] = "Kesalahan penguraian template: %1\$s"; // %1$s is the parse error generated
$lang['Packages.!error.module_id.changed'] = "Modul tidak dapat diubah karena ada satu atau lebih layanan yang sudah menggunakan paket ini.";
$lang['Packages.!error.plugins[].valid'] = "Plugin yang diberikan tidak valid.";
$lang['Packages.!error.names.format'] = "Nama paket dalam format yang tidak valid.";
$lang['Packages.!error.names.empty_name'] = "Harap tentukan nama paket untuk setiap bahasa.";
$lang['Packages.!error.names.empty_lang'] = "Harap tentukan kode bahasa paket untuk setiap nama.";
$lang['Packages.!error.descriptions.format'] = "Deskripsi paket dalam format yang tidak valid.";
$lang['Packages.!error.descriptions.empty_lang'] = "Harap tentukan kode bahasa paket untuk setiap deskripsi.";
$lang['Packages.!error.upgrades_use_renewal.valid'] = "Gunakan harga perpanjangan untuk peningkatan harus 1 atau 0.";
$lang['Packages.!error.pricing[][price_renews].format'] = "Harga perpanjangan harus berupa angka.";
$lang['Packages.!error.pricing[][price_renews].valid'] = "Harga perpanjangan tidak dapat ditetapkan untuk satu periode waktu.";
$lang['Packages.!error.client_qty.format'] = "Batas klien harus berupa angka.";
$lang['Packages.!error.package_id.has_children'] = "Paket tidak dapat dihapus karena layanan memiliki layanan anak.";
$lang['Packages.!error.pricing[][price_transfer].format'] = "Harga transfer harus berupa angka.";
$lang['Packages.!error.hidden.format'] = "Apakah grup ini harus disembunyikan di antarmuka harus disetel ke 1 atau 0.";
?>
