<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['ServiceChanges.!error.id.exists'] = "ID perubahan layanan tidak valid.";
$lang['ServiceChanges.!error.service_id.exists'] = "ID layanan tidak valid.";
$lang['ServiceChanges.!error.invoice_id.exists'] = "ID faktur tidak valid.";
$lang['ServiceChanges.!error.invoice_id.unique'] = "ID faktur sudah disetel untuk perubahan layanan dan mungkin tidak disetel lagi.";
$lang['ServiceChanges.!error.status.valid'] = "Silakan pilih status yang sah.";
$lang['ServiceChanges.status.pending'] = "Pending";
$lang['ServiceChanges.status.completed'] = "Selesai";
$lang['ServiceChanges.status.error'] = "Kesalahan";
$lang['ServiceChanges.status.canceled'] = "Dibatalkan";
?>
