<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Taxes.!error.company_id.exists'] = "ID perusahaan tidak valid";
$lang['Taxes.!error.level.format'] = "Tingkat pajak harus berupa angka.";
$lang['Taxes.!error.level.length'] = "Panjang tingkat pajak tidak boleh melebihi 2 karakter.";
$lang['Taxes.!error.name.length'] = "Panjang nama pajak tidak boleh melebihi 64 karakter.";
$lang['Taxes.!error.amount.format'] = "Jumlah harus berupa angka.";
$lang['Taxes.!error.type.format'] = "Jenis pajak tidak valid.";
$lang['Taxes.!error.status.format'] = "Status tidak valid.";
$lang['Taxes.!error.tax_id.exists'] = "NPWP tidak valid.";
$lang['Taxes.getTaxStatus.active'] = "Aktif";
$lang['Taxes.getTaxStatus.inactive'] = "Non-aktif";
$lang['Taxes.getTaxTypes.inclusive'] = "Inklusif (Aditif)";
$lang['Taxes.getTaxTypes.exclusive'] = "Eksklusif";
$lang['Taxes.!error.country.valid'] = "Negara tidak valid ISO 3166-1 kode negara.";
$lang['Taxes.!error.state.valid'] = "Negara tidak valid kode ISO 3166-2  subdivisi.";
$lang['Taxes.!error.amount.positive'] = "Jumlahnya harus positif.";
$lang['Taxes.getTaxTypes.inclusive_calculated'] = "Inklusif";
?>
