<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Themes.!error.id.exists'] = "Tema yang Anda pilih tidak ada.";
$lang['Themes.!error.company_id.exists'] = "ID perusahaan tidak valid.";
$lang['Themes.!error.company_id.isset'] = "Hanya tema khusus perusahaan yang dapat dihapus.";
$lang['Themes.!error.company_id.set'] = "Hanya tema khusus perusahaan yang dapat diperbarui.";
$lang['Themes.!error.name.empty'] = "Masukkan nama tema.";
$lang['Themes.!error.name.length'] = "Nama tema tidak boleh melebihi 64 karakter.";
$lang['Themes.!error.colors.exist'] = "Harap masukkan kode hex 6 karakter yang valid untuk setiap warna.";
$lang['Themes.!error.type.format'] = "Jenis tema yang diberikan tidak valid.";
$lang['Themes.type.admin'] = "Staf";
$lang['Themes.type.client'] = "Klien";
?>
