<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Transactions.!error.client_id.exists'] = "ID klien yang tidak valid.";
$lang['Transactions.!error.amount.format'] = "Jumlah harus berupa angka.";
$lang['Transactions.!error.currency.length'] = "Mata uang harus 3 karakter.";
$lang['Transactions.!error.type.format'] = "Jenis transaksi yang tidak valid.";
$lang['Transactions.!error.transaction_type_id.exists'] = "ID jenis transaksi tidak valid.";
$lang['Transactions.!error.gateway_id.exists'] = "ID gatewayaa tidak sah";
$lang['Transactions.!error.status.format'] = "Status transaksi tidak valid.";
$lang['Transactions.!error.transaction_id.exists'] = "ID transaksi tidak valid.";
$lang['Transactions.!error.date_added.format'] = "Tanggal transaksi tidak boleh tanggal yang akan datang.";
$lang['Transactions.!error.invoice_id.exists'] = "ID faktur tidak valid.";
$lang['Transactions.!error.date.format'] = "Tanggal yang diterapkan tidak valid.";
$lang['Transactions.!error.name.empty'] = "Harap masukkan nama.";
$lang['Transactions.!error.name.length'] = "Panjang nama tidak boleh melebihi 32 karakter.";
$lang['Transactions.!error.is_lang.format'] = "is_lang haruslah angka.";
$lang['Transactions.!error.is_lang.length'] = "panjang is_lang tidak boleh melebihi 1 karakter.";
$lang['Transactions.!error.type_id.exists'] = "jenis ID  transaksi tidak valid.";
$lang['Transactions.types.cc'] = "Kartu kredit";
$lang['Transactions.types.ach'] = "ACH";
$lang['Transactions.types.other'] = "Yang Lainnya";
$lang['Transactions.status.approved'] = "Disetujui";
$lang['Transactions.status.declined'] = "Ditolak";
$lang['Transactions.status.void'] = "Batal";
$lang['Transactions.status.error'] = "Kesalahan";
$lang['Transactions.status.pending'] = "Tertunda";
$lang['Transactions.status.returned'] = "Kembali";
$lang['Transactions.!error.amounts.positive'] = "Satu atau lebih nilai Jumlah yang Harus Dibayar adalah negatif. Pastikan bahwa setiap nilai Jumlah yang Harus Dibayar adalah nol atau lebih.";
$lang['Transactions.status.refunded'] = "Dikembalikan";
$lang['Transactions.!error.currency.missing'] = "Silakan set mata uang.";
$lang['Transactions.!error.currency.mismatch'] = "Mata uang yang diberikan tidak sesuai dengan salah satu tagihan yang terkait";
$lang['Transactions.!error.amounts.overage'] = "Satu atau lebih nilai Jumlah yang Harus Dibayar tidak dapat diterapkan ke faktur yang ditentukan. Pastikan Jumlah yang Harus Dibayar tidak melebihi Jumlah yang Harus Dibayar pada faktur, bahwa faktur terbuka, dan jumlah nilai Jumlah yang Harus Dibayar tidak melebihi Jumlah Pembayaran atau Kredit.";
$lang['Transactions.!error.transaction_id.currency_matches'] = "Jumlah faktur tidak dapat diterapkan karena tidak sesuai dengan mata uang transaksi.";
$lang['Transactions.!error.type.valid'] = "Pilih jenis yang valid.";
$lang['Transactions.debit_types.debit'] = "Debet";
$lang['Transactions.debit_types.credit'] = "Kredit";
?>
