<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Users.!error.username.empty'] = "Harap masukkan nama pengguna.";
$lang['Users.!error.username.unique'] = "Nama pengguna itu sudah diambil.";
$lang['Users.!error.current_password.matches'] = "Kata sandi tidak valid.";
$lang['Users.!error.new_password.format'] = "Harap masukkan kata sandi dengan panjang minimal 6 karakter.";
$lang['Users.!error.new_password.matches'] = "Password tidak cocok.";
$lang['Users.!error.two_factor_mode.format'] = "Mode dua faktor yang tidak valid.";
$lang['Users.!error.username.auth'] = "Tidak ditemukan kecocokan untuk kombinasi pengguna/sandi tersebut.";
$lang['Users.!error.otp.auth'] = "Kata sandi satu kali yang dimasukkan tidak valid. Panjang maksimal 16 karakter";
$lang['Users.!error.user_id.exists'] = "ID pengguna yang tidak valid.";
$lang['Users.!error.username.attempts'] = "Terdeteksi !! terlalu banyak upaya login gagal ";
$lang['Users.!error.clients.exist'] = "Pengguna tidak dapat dihapus dikarenakan terdapat setidaknya satu klien yang ditempatkan pada pengguna.";
$lang['Users.!error.two_factor_key.format'] = "Kunci dua faktor yang tidak valid.";
$lang['Users.!error.username.company'] = "Anda tidak diizinkan untuk masuk di lokasi ini.";
?>
