<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TheSSLStorePlugin.name'] = "TheSSLStore Plugin";
$lang['TheSSLStorePlugin.getCronTasks.tss_expiration_reminder_name'] = "Pengingat Kedaluwarsa Sertifikat SSL";
$lang['TheSSLStorePlugin.getCronTasks.tss_expiration_reminder_desc'] = "Pengingat akan dikirim 30 hari sebelum tanggal kedaluwarsa sertifikat.";
?>