<?php
/**
* Language definitions. Generated by the Blesta Translator
*
* @package blesta
* @version 5.5.2
* @copyright Copyright (c) 2022, Phillips Data, Inc.
* @license http://www.blesta.com/license/ The Blesta License Agreement
* @link http://www.blesta.com/ Blesta
*/
$lang['Eway.!error.customer_id.empty'] = "Masukkan ID Eway Anda.";
$lang['Eway.!error.customer_id.length'] = "ID Pelanggan tidak boleh melebihi 8 karakter.";
$lang['Eway.!error.developer_mode.valid'] = "Mode pengembang harus disetel ke \"benar\" jika diberikan.";
$lang['Eway.!error.test_mode.valid'] = "Mode uji harus diatur ke \"true\" jika diberikan.";
$lang['Eway.!error.refund_password.empty'] = "Sandi pengembalian dana harus ditetapkan untuk memproses pengembalian dana melalui eWAY.";
$lang['Eway.!error.libxml_required'] = "Ekstensi libxml dan simplexml diperlukan untuk gateway ini.";
$lang['Eway.!error.invalid_xml'] = "Gateway menanggapi dengan XML tidak valid.";
$lang['Eway.name'] = "eWAY";
$lang['Eway.customer_id'] = "ID Pelanggan";
$lang['Eway.refund_password'] = "Pengembalian Kata Sandi";
$lang['Eway.developer_mode'] = "Modus pengembang";
$lang['Eway.test_mode'] = "Test Mode";
$lang['Eway.tooltip_refund_password'] = "Masukkan Kata Sandi Pengembalian Dana yang telah Anda tetapkan di akun eWAY Anda. Ini bukan kata sandi akun eWAY Anda. Sandi pengembalian dana harus ditetapkan untuk memproses pengembalian dana melalui eWAY.";
$lang['Eway.tooltip_developer_mode'] = "Mengaktifkan opsi ini akan memposting transaksi ke lingkungan kotak pasir eWAY. Anda harus memiliki akun pengujian kotak pasir untuk menggunakan lingkungan ini.";
$lang['Eway.tooltip_test_mode'] = "Mode uji akan menggunakan akun uji eWAY dengan nomor kartu kredit uji apa pun yang Anda masukkan. Untuk informasi lebih lanjut tentang mode uji di eWAY, silakan baca manual.";
$lang['Eway.description'] = "eWAY adalah 25% dari pasar online Australia dan berdagang di 5 negara. Memproses pembayaran miliaran dolar setiap tahun di seluruh dunia untuk puluhan ribu bisnis";
?>
