<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Perfectmoney.name'] = "Perfect Money";
$lang['Perfectmoney.payee_account'] = "Payee Account";
$lang['Perfectmoney.passphrase'] = "Frasa Sandi Alternatif";
$lang['Perfectmoney.passphrase_note'] = "Frasa sandi alternatif digunakan untuk penghitungan hash MD5 untuk memvalidasi pembayaran.";
$lang['Perfectmoney.buildprocess.submit'] = "Bayar dengan Perfect Money";
$lang['Perfectmoney.!error.payee_account.valid'] = "Anda harus memasukkan akun yang valid.";
$lang['Perfectmoney.!error.passphrase.valid'] = "Anda harus memasukkan frasa sandi yang valid.";
?>