<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DomainsPlugin.name'] = "Manajer Domain";
$lang['DomainsPlugin.description'] = "Digunakan untuk menangani berbagai aspek manajemen domain dan penjualan. Plugin ini sedang dalam tahap beta.";
$lang['DomainsPlugin.!error.module_id.exists'] = "ID modul tidak valid.";
$lang['DomainsPlugin.getCronTasks.domain_synchronization'] = "Sinkronisasi Domain";
$lang['DomainsPlugin.getCronTasks.domain_synchronization_description'] = "Sinkronkan layanan domain dengan tanggal kedaluwarsa dari modul registrar mereka";
$lang['DomainsPlugin.getCronTasks.domain_term_change'] = "Ubah Istilah Domain";
$lang['DomainsPlugin.getCronTasks.domain_term_change_description'] = "Ubah layanan dengan jangka waktu lebih dari satu tahun menjadi jangka waktu tahunan";
$lang['DomainsPlugin.getCronTasks.domain_renewal_reminders'] = "Kirim Pengingat Pembaruan";
$lang['DomainsPlugin.getCronTasks.domain_renewal_reminders_description'] = "Kirim email pengingat untuk domain yang hampir mendekati tanggal perpanjangannya";
$lang['DomainsPlugin.nav_secondary_staff.domain_options'] = "Opsi Domain";
$lang['DomainsPlugin.nav_secondary_staff.domains'] = "Domain";
$lang['DomainsPlugin.card_client.getDomainCount'] = "Domain";
$lang['DomainsPlugin.permission.admin_domains'] = "Domain";
$lang['DomainsPlugin.permission.admin_domains.browse'] = "Domain";
$lang['DomainsPlugin.permission.admin_domains.tlds'] = "Harga TLD";
$lang['DomainsPlugin.permission.admin_domains.registrars'] = "Pendaftar";
$lang['DomainsPlugin.permission.admin_domains.whois'] = "Whois";
$lang['DomainsPlugin.permission.admin_domains.configuration'] = "Konfigurasi";
$lang['DomainsPlugin.tld_package_group.name'] = "Harga Paket TLD";
$lang['DomainsPlugin.tld_package_group.description'] = "Grup paket untuk menyembunyikan dan mengelola semua paket harga TLD";
$lang['DomainsPlugin.email_forwarding.name'] = "Penerusan Email";
$lang['DomainsPlugin.email_forwarding.description'] = "Penerusan Email";
$lang['DomainsPlugin.dns_management.name'] = "Manajemen DNS";
$lang['DomainsPlugin.dns_management.description'] = "Manajemen DNS";
$lang['DomainsPlugin.id_protection.name'] = "Perlindungan ID";
$lang['DomainsPlugin.id_protection.description'] = "Perlindungan ID";
$lang['DomainsPlugin.enabled'] = "Diaktifkan";
$lang['DomainsPlugin.nav_client.services'] = "Jasa";
$lang['DomainsPlugin.nav_client.domains'] = "Domain";
$lang['DomainsPlugin.widget_staff_home.main'] = "Domain";
$lang['DomainsPlugin.widget_client_home.main'] = "Domain";
?>