<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 5.5.2
 * @copyright Copyright (c) 2022, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientDocumentsFiles.!error.client_id.exists'] = "Klien tidak ada.";
$lang['ClientDocumentsFiles.!error.name.valid'] = "Nama dokumen wajib diisi.";
$lang['ClientDocumentsFiles.!error.date_added.valid'] = "Sebuah tanggal yang valid diperlukan.";
?>